import type { TopicTestPool, TopicTestQuestion } from "../../types";

/**
 * Topic-test pool — Year 12 Mathematics Advanced · Applications of Differentiation
 * (NESA MA-C3). Legacy/canonical course, routed
 * /course/year-12-advanced/ma-c3-applications-of-differentiation/<lesson>.
 *
 * MA-C3 in the legacy data merges an older 5-lesson set with a newer, more
 * granular 6-lesson set (the duplicate `optimisation` slug is the seam). This pool
 * uses the NEWER/canonical set — the one newCourseCatalog.ts references with
 * stableSkillIds — all verified route-reachable. `optimisation` resolves to the
 * live "Optimisation Problems" lesson.
 *
 * Status: subtopic 1 "Second Derivative, Concavity and Points of Inflection" —
 * D4 + D5, authored and audited. Remaining subtopics to follow; not yet registered.
 */

const href = (lesson: string) =>
  `/course/year-12-advanced/ma-c3-applications-of-differentiation/${lesson}`;

// ── Subtopic 1: Second Derivative, Concavity and Points of Inflection ────────
const concD4: TopicTestQuestion[] = [
  { id: "y12a-c3-conc-d4-1", prompt: "For f(x) = x³, find f''(2).", latex: "f(x) = x^3", marks: 2, difficulty: 4,
    answer: "12", explanation: "f'(x) = 3x², f''(x) = 6x; f''(2) = 12." },
  { id: "y12a-c3-conc-d4-2", prompt: "For f(x) = x³ − 3x², find f''(0).", latex: "f(x) = x^3 - 3x^2", marks: 2, difficulty: 4,
    answer: "-6", acceptedAnswers: ["−6"], explanation: "f'(x) = 3x² − 6x, f''(x) = 6x − 6; f''(0) = −6." },
  { id: "y12a-c3-conc-d4-3", prompt: "For f(x) = 2x² + 3x, find f''(x).", latex: "f(x) = 2x^2 + 3x", marks: 2, difficulty: 4,
    answer: "4", explanation: "f'(x) = 4x + 3, f''(x) = 4 (constant)." },
  { id: "y12a-c3-conc-d4-4", prompt: "For f(x) = x³ + x, is the curve concave up or down at x = −1? Answer 'up' or 'down'.", latex: "f(x) = x^3 + x", marks: 2, difficulty: 4,
    answer: "down", acceptedAnswers: ["concave down", "concave-down", "downwards"], explanation: "f''(x) = 6x; f''(−1) = −6 < 0, so the curve is concave down at x = −1." },
  { id: "y12a-c3-conc-d4-5", prompt: "For f(x) = x³, is the curve concave up or concave down at x = 2?", latex: "f(x) = x^3", marks: 2, difficulty: 4,
    choices: [ { label: "A", text: "Concave up" }, { label: "B", text: "Concave down" }, { label: "C", text: "Neither" }, { label: "D", text: "A straight line" } ],
    answer: "A", explanation: "f''(2) = 12 > 0, so the curve is concave up at x = 2." },
  { id: "y12a-c3-conc-d4-6", prompt: "Find the x-coordinate of the point of inflection of y = x³.", latex: "y = x^3", marks: 3, difficulty: 4,
    answer: "0", explanation: "f''(x) = 6x = 0 at x = 0, and f'' changes sign there, so x = 0 is a point of inflection." },
  { id: "y12a-c3-conc-d4-7", prompt: "Find the x-coordinate of the point of inflection of y = x³ − 6x².", latex: "y = x^3 - 6x^2", marks: 3, difficulty: 4,
    answer: "2", explanation: "f''(x) = 6x − 12 = 0 ⇒ x = 2 (with a sign change)." },
  { id: "y12a-c3-conc-d4-8", prompt: "If f''(x) = 2x − 4, the curve is concave up for x > k. Find k.", latex: "f''(x) = 2x - 4", marks: 3, difficulty: 4,
    answer: "2", explanation: "Concave up ⇒ f''(x) > 0 ⇒ 2x − 4 > 0 ⇒ x > 2." },
  { id: "y12a-c3-conc-d4-9", prompt: "Classify the stationary point of y = x² − 4x using the second derivative.", latex: "y = x^2 - 4x", marks: 3, difficulty: 4,
    choices: [ { label: "A", text: "Minimum" }, { label: "B", text: "Maximum" }, { label: "C", text: "Point of inflection" }, { label: "D", text: "Cannot tell" } ],
    answer: "A", explanation: "f''(x) = 2 > 0, so the stationary point is a minimum." },
  { id: "y12a-c3-conc-d4-10", prompt: "If f''(x) = 6x, the curve is concave down for x < k. Find k.", latex: "f''(x) = 6x", marks: 3, difficulty: 4,
    answer: "0", explanation: "Concave down ⇒ f''(x) < 0 ⇒ 6x < 0 ⇒ x < 0." },
];
const concD5: TopicTestQuestion[] = [
  { id: "y12a-c3-conc-d5-1", prompt: "Find the positive x-coordinate of a point of inflection of y = x⁴ − 6x².", latex: "y = x^4 - 6x^2", marks: 4, difficulty: 5,
    answer: "1", explanation: "f''(x) = 12x² − 12 = 0 ⇒ x² = 1 ⇒ x = ±1; positive is 1." },
  { id: "y12a-c3-conc-d5-2", prompt: "y = x⁴ − 4x³ has two points of inflection. Find the larger x-coordinate.", latex: "y = x^4 - 4x^3", marks: 4, difficulty: 5,
    answer: "2", explanation: "f''(x) = 12x² − 24x = 12x(x − 2) = 0 ⇒ x = 0 or 2 (both with sign changes); the larger is 2." },
  { id: "y12a-c3-conc-d5-3", prompt: "y = x³ + ax² has a point of inflection at x = 1. Find a.", latex: "y = x^3 + ax^2", marks: 4, difficulty: 5,
    answer: "-3", acceptedAnswers: ["−3"], explanation: "f''(x) = 6x + 2a = 0 at x = 1 ⇒ 6 + 2a = 0 ⇒ a = −3." },
  { id: "y12a-c3-conc-d5-4", prompt: "Find the y-coordinate of the point of inflection of y = x³ − 6x² + 5.", latex: "y = x^3 - 6x^2 + 5", marks: 4, difficulty: 5,
    answer: "-11", acceptedAnswers: ["−11"], explanation: "Inflection at x = 2 (f''=6x−12=0); y(2) = 8 − 24 + 5 = −11." },
  { id: "y12a-c3-conc-d5-5", prompt: "For y = x³ − 6x² + 9x, find d²y/dx² at the stationary point x = 3.", latex: "y = x^3 - 6x^2 + 9x", marks: 4, difficulty: 5,
    answer: "6", explanation: "f''(x) = 6x − 12; f''(3) = 6 (> 0, so x = 3 is a minimum)." },
  { id: "y12a-c3-conc-d5-6", prompt: "Classify the stationary point of y = x³ − 12x at x = 2 using the second derivative.", latex: "y = x^3 - 12x", marks: 4, difficulty: 5,
    answer: "minimum", acceptedAnswers: ["min"], explanation: "f''(x) = 6x; f''(2) = 12 > 0, so x = 2 is a minimum." },
  { id: "y12a-c3-conc-d5-7", prompt: "Find the x-coordinate of the point of inflection of y = 2x³ − 9x² + 12x (exact fraction).", latex: "y = 2x^3 - 9x^2 + 12x", marks: 4, difficulty: 5,
    answer: "3/2", acceptedAnswers: ["1.5"], explanation: "f''(x) = 12x − 18 = 0 ⇒ x = 3/2." },
  { id: "y12a-c3-conc-d5-8", prompt: "Is x = 0 a point of inflection of y = x⁴? Answer 'yes' or 'no'.", latex: "y = x^4", marks: 4, difficulty: 5,
    answer: "no", acceptedAnswers: ["it is a minimum", "no it is a minimum"], explanation: "f''(x) = 12x² ≥ 0 with no sign change at x = 0, so it is not a point of inflection (it is a minimum)." },
  { id: "y12a-c3-conc-d5-9", prompt: "The curve y = x³ − 3x² is concave up for x > k. Find k.", latex: "y = x^3 - 3x^2", marks: 4, difficulty: 5,
    answer: "1", explanation: "f''(x) = 6x − 6 > 0 ⇒ x > 1." },
  { id: "y12a-c3-conc-d5-10", prompt: "y = x³ − kx² has a point of inflection at x = 2. Find k.", latex: "y = x^3 - kx^2", marks: 4, difficulty: 5,
    answer: "6", explanation: "f''(x) = 6x − 2k = 0 at x = 2 ⇒ 12 − 2k = 0 ⇒ k = 6." },
];

// ── Subtopic 2: Stationary Point Classification ──────────────────────────────
const sptD4: TopicTestQuestion[] = [
  { id: "y12a-c3-spt-d4-1", prompt: "Find the x-coordinate of the stationary point of y = x² − 6x.", latex: "y = x^2 - 6x", marks: 2, difficulty: 4,
    answer: "3", explanation: "dy/dx = 2x − 6 = 0 ⇒ x = 3." },
  { id: "y12a-c3-spt-d4-2", prompt: "Classify the stationary point of y = x² − 6x.", latex: "y = x^2 - 6x", marks: 2, difficulty: 4,
    choices: [ { label: "A", text: "Minimum" }, { label: "B", text: "Maximum" }, { label: "C", text: "Horizontal inflection" }, { label: "D", text: "None" } ],
    answer: "A", explanation: "Upward parabola (f''(x) = 2 > 0), so a minimum." },
  { id: "y12a-c3-spt-d4-3", prompt: "Classify the stationary point of y = −x² + 4x (minimum or maximum).", latex: "y = -x^2 + 4x", marks: 2, difficulty: 4,
    answer: "maximum", acceptedAnswers: ["max"], explanation: "Downward parabola (f''(x) = −2 < 0), so a maximum." },
  { id: "y12a-c3-spt-d4-4", prompt: "Find the x-coordinate of the local maximum of y = x³ − 3x.", latex: "y = x^3 - 3x", marks: 3, difficulty: 4,
    answer: "-1", acceptedAnswers: ["−1"], explanation: "dy/dx = 3x² − 3 = 0 ⇒ x = ±1; the maximum is at x = −1 (f''(−1) < 0)." },
  { id: "y12a-c3-spt-d4-5", prompt: "Find the x-coordinate of the local minimum of y = x³ − 3x.", latex: "y = x^3 - 3x", marks: 3, difficulty: 4,
    answer: "1", explanation: "The minimum is at x = 1 (f''(1) > 0)." },
  { id: "y12a-c3-spt-d4-6", prompt: "Classify the stationary point of y = x³ at x = 0.", latex: "y = x^3", marks: 3, difficulty: 4,
    choices: [ { label: "A", text: "Horizontal point of inflection" }, { label: "B", text: "Local minimum" }, { label: "C", text: "Local maximum" }, { label: "D", text: "Discontinuity" } ],
    answer: "A", explanation: "dy/dx = 3x² does not change sign at x = 0, so it is a horizontal point of inflection — neither a max nor a min." },
  { id: "y12a-c3-spt-d4-7", prompt: "y = x³ − 6x² + 9x has two stationary points. Find the larger x-coordinate.", latex: "y = x^3 - 6x^2 + 9x", marks: 3, difficulty: 4,
    answer: "3", explanation: "dy/dx = 3x² − 12x + 9 = 3(x − 1)(x − 3) = 0 ⇒ x = 1 or 3; the larger is 3." },
  { id: "y12a-c3-spt-d4-8", prompt: "Find the positive stationary-point x-value of y = 2x³ − 6x.", latex: "y = 2x^3 - 6x", marks: 3, difficulty: 4,
    answer: "1", explanation: "dy/dx = 6x² − 6 = 0 ⇒ x = ±1; positive is 1." },
  { id: "y12a-c3-spt-d4-9", prompt: "Find the x-coordinate of the local minimum of y = x³ − 3x².", latex: "y = x^3 - 3x^2", marks: 3, difficulty: 4,
    answer: "2", explanation: "dy/dx = 3x² − 6x = 3x(x − 2) = 0 ⇒ x = 0 or 2; the minimum is at x = 2." },
  { id: "y12a-c3-spt-d4-10", prompt: "How many stationary points does y = x⁴ − 2x² have?", latex: "y = x^4 - 2x^2", marks: 3, difficulty: 4,
    answer: "3", explanation: "dy/dx = 4x³ − 4x = 4x(x² − 1) = 0 ⇒ x = 0, 1, −1: three stationary points." },
];
const sptD5: TopicTestQuestion[] = [
  { id: "y12a-c3-spt-d5-1", prompt: "Classify the stationary point of y = x³ − 6x² + 9x at x = 1 (minimum or maximum).", latex: "y = x^3 - 6x^2 + 9x", marks: 4, difficulty: 5,
    answer: "maximum", acceptedAnswers: ["max"], explanation: "dy/dx = 3(x − 1)(x − 3); at x = 1, dy/dx goes + to −, so a local maximum." },
  { id: "y12a-c3-spt-d5-2", prompt: "Find the local minimum value of y = x³ − 6x² + 9x.", latex: "y = x^3 - 6x^2 + 9x", marks: 4, difficulty: 5,
    answer: "0", explanation: "The minimum is at x = 3; y(3) = 27 − 54 + 27 = 0." },
  { id: "y12a-c3-spt-d5-3", prompt: "y = x³ + ax has a stationary point at x = 2. Find a.", latex: "y = x^3 + ax", marks: 4, difficulty: 5,
    answer: "-12", acceptedAnswers: ["−12"], explanation: "dy/dx = 3x² + a = 0 at x = 2 ⇒ 12 + a = 0 ⇒ a = −12." },
  { id: "y12a-c3-spt-d5-4", prompt: "Classify the stationary point of y = x⁴ − 2x² at x = 0 (minimum or maximum).", latex: "y = x^4 - 2x^2", marks: 4, difficulty: 5,
    answer: "maximum", acceptedAnswers: ["max"], explanation: "dy/dx = 4x³ − 4x = 4x(x−1)(x+1); at x = 0 it goes + to −, so a local maximum (between the two minima)." },
  { id: "y12a-c3-spt-d5-5", prompt: "Find the local maximum value of y = x³ − 12x.", latex: "y = x^3 - 12x", marks: 4, difficulty: 5,
    answer: "16", explanation: "Maximum at x = −2; y(−2) = −8 + 24 = 16." },
  { id: "y12a-c3-spt-d5-6", prompt: "Find the local minimum value of y = x³ − 3x.", latex: "y = x^3 - 3x", marks: 4, difficulty: 5,
    answer: "-2", acceptedAnswers: ["−2"], explanation: "Minimum at x = 1; y(1) = 1 − 3 = −2." },
  { id: "y12a-c3-spt-d5-7", prompt: "Find the x-coordinate of the stationary point of y = x² + 16/x (x > 0).", latex: "y = x^2 + \\tfrac{16}{x}", marks: 4, difficulty: 5,
    answer: "2", explanation: "dy/dx = 2x − 16/x² = 0 ⇒ 2x³ = 16 ⇒ x³ = 8 ⇒ x = 2." },
  { id: "y12a-c3-spt-d5-8", prompt: "Classify the stationary point of y = 2x³ − 3x² − 12x at x = 2 (minimum or maximum).", latex: "y = 2x^3 - 3x^2 - 12x", marks: 4, difficulty: 5,
    answer: "minimum", acceptedAnswers: ["min"], explanation: "dy/dx = 6x² − 6x − 12 = 6(x − 2)(x + 1); at x = 2 it goes − to +, so a local minimum." },
  { id: "y12a-c3-spt-d5-9", prompt: "y = x³ − px² has a stationary point at x = 4 (other than x = 0). Find p.", latex: "y = x^3 - px^2", marks: 4, difficulty: 5,
    answer: "6", explanation: "dy/dx = 3x² − 2px = x(3x − 2p) = 0; the non-zero root is x = 2p/3 = 4 ⇒ p = 6." },
  { id: "y12a-c3-spt-d5-10", prompt: "Find the difference between the local maximum and local minimum values of y = x³ − 3x² + 1.", latex: "y = x^3 - 3x^2 + 1", marks: 4, difficulty: 5,
    answer: "4", explanation: "Max at x = 0: y = 1. Min at x = 2: y = 8 − 12 + 1 = −3. Difference = 1 − (−3) = 4." },
];

// ── Subtopic 3: Curve Sketching with Calculus ────────────────────────────────
const csD4: TopicTestQuestion[] = [
  { id: "y12a-c3-cs-d4-1", prompt: "Find the larger x-intercept of y = x² − 5x + 6.", latex: "y = x^2 - 5x + 6", marks: 2, difficulty: 4,
    answer: "3", explanation: "(x − 2)(x − 3) = 0 ⇒ x = 2 or 3; the larger is 3." },
  { id: "y12a-c3-cs-d4-2", prompt: "Find the y-intercept of y = x² − 4x + 3.", latex: "y = x^2 - 4x + 3", marks: 2, difficulty: 4,
    answer: "3", explanation: "At x = 0, y = 3." },
  { id: "y12a-c3-cs-d4-3", prompt: "Find the sum of the x-intercepts of y = (x − 1)(x − 2)(x − 3).", latex: "y = (x-1)(x-2)(x-3)", marks: 2, difficulty: 4,
    answer: "6", explanation: "Roots are x = 1, 2, 3, so the sum is 6." },
  { id: "y12a-c3-cs-d4-4", prompt: "How many stationary points does y = x³ − 3x have?", latex: "y = x^3 - 3x", marks: 2, difficulty: 4,
    answer: "2", explanation: "dy/dx = 3x² − 3 = 0 has two solutions x = ±1." },
  { id: "y12a-c3-cs-d4-5", prompt: "How many x-intercepts does y = x² + 1 have?", latex: "y = x^2 + 1", marks: 2, difficulty: 4,
    choices: [ { label: "A", text: "$0$" }, { label: "B", text: "$1$" }, { label: "C", text: "$2$" }, { label: "D", text: "$-1$" } ],
    answer: "A", explanation: "x² + 1 = 0 has no real solutions, so the curve never crosses the x-axis." },
  { id: "y12a-c3-cs-d4-6", prompt: "Find the x-intercept of y = (x + 2)².", latex: "y = (x+2)^2", marks: 2, difficulty: 4,
    answer: "-2", acceptedAnswers: ["−2"], explanation: "(x + 2)² = 0 ⇒ x = −2 (a double root — the curve touches the axis)." },
  { id: "y12a-c3-cs-d4-7", prompt: "As x → +∞, what happens to y = −x³?", latex: "y = -x^3", marks: 2, difficulty: 4,
    choices: [ { label: "A", text: "$y \\to -\\infty$" }, { label: "B", text: "$y \\to +\\infty$" }, { label: "C", text: "$y \\to 0$" }, { label: "D", text: "$y \\to -1$" } ],
    answer: "A", explanation: "Negative leading coefficient on an odd power: as x → +∞, y → −∞." },
  { id: "y12a-c3-cs-d4-8", prompt: "How many x-intercepts does y = x³ − 12x have?", latex: "y = x^3 - 12x", marks: 3, difficulty: 4,
    answer: "3", explanation: "x(x² − 12) = 0 ⇒ x = 0, ±√12: three x-intercepts." },
  { id: "y12a-c3-cs-d4-9", prompt: "Find the y-coordinate of the minimum turning point of y = x² − 6x.", latex: "y = x^2 - 6x", marks: 3, difficulty: 4,
    answer: "-9", acceptedAnswers: ["−9"], explanation: "Minimum at x = 3; y(3) = 9 − 18 = −9." },
  { id: "y12a-c3-cs-d4-10", prompt: "How many points of inflection does y = x³ have?", latex: "y = x^3", marks: 2, difficulty: 4,
    answer: "1", explanation: "f''(x) = 6x changes sign at x = 0: one point of inflection." },
];
const csD5: TopicTestQuestion[] = [
  { id: "y12a-c3-cs-d5-1", prompt: "Find the y-coordinate of the local maximum of y = x³ − 3x.", latex: "y = x^3 - 3x", marks: 4, difficulty: 5,
    answer: "2", explanation: "Local max at x = −1; y(−1) = −1 + 3 = 2." },
  { id: "y12a-c3-cs-d5-2", prompt: "How many distinct x-intercepts does y = x³ − 6x² + 9x have?", latex: "y = x^3 - 6x^2 + 9x", marks: 4, difficulty: 5,
    answer: "2", explanation: "x(x − 3)² = 0 ⇒ x = 0 and x = 3 (double): two distinct x-intercepts." },
  { id: "y12a-c3-cs-d5-3", prompt: "How many distinct x-intercepts does y = x⁴ − 4x² have?", latex: "y = x^4 - 4x^2", marks: 4, difficulty: 5,
    answer: "3", explanation: "x²(x² − 4) = 0 ⇒ x = 0, ±2: three distinct x-intercepts." },
  { id: "y12a-c3-cs-d5-4", prompt: "Find the y-coordinate of the minimum turning point of y = x³ − 3x².", latex: "y = x^3 - 3x^2", marks: 4, difficulty: 5,
    answer: "-4", acceptedAnswers: ["−4"], explanation: "Minimum at x = 2; y(2) = 8 − 12 = −4." },
  { id: "y12a-c3-cs-d5-5", prompt: "How many stationary points does y = x²(x − 3) have?", latex: "y = x^2(x-3)", marks: 4, difficulty: 5,
    answer: "2", explanation: "y = x³ − 3x², dy/dx = 3x² − 6x = 3x(x − 2): two stationary points." },
  { id: "y12a-c3-cs-d5-6", prompt: "Find the y-intercept of y = (x − 1)²(x + 2).", latex: "y = (x-1)^2(x+2)", marks: 3, difficulty: 5,
    answer: "2", explanation: "At x = 0: (−1)²(2) = 2." },
  { id: "y12a-c3-cs-d5-7", prompt: "The turning points of y = x³ − 12x are at x = −2 and x = 2. Find the distance between their x-values.", latex: "y = x^3 - 12x", marks: 4, difficulty: 5,
    answer: "4", explanation: "From x = −2 to x = 2 the distance is 4." },
  { id: "y12a-c3-cs-d5-8", prompt: "Find the x-coordinate of the local maximum of y = x³ + 3x² − 9x.", latex: "y = x^3 + 3x^2 - 9x", marks: 4, difficulty: 5,
    answer: "-3", acceptedAnswers: ["−3"], explanation: "dy/dx = 3(x + 3)(x − 1) = 0 ⇒ x = −3 (max) or 1 (min); the max is at x = −3." },
  { id: "y12a-c3-cs-d5-9", prompt: "Find the sum of the x-intercepts of y = x³ − x.", latex: "y = x^3 - x", marks: 4, difficulty: 5,
    answer: "0", explanation: "x(x − 1)(x + 1) = 0 ⇒ roots −1, 0, 1; sum = 0." },
  { id: "y12a-c3-cs-d5-10", prompt: "y = x³ − 3x + 2 has a repeated root. Find it.", latex: "y = x^3 - 3x + 2", marks: 4, difficulty: 5,
    answer: "1", explanation: "x³ − 3x + 2 = (x − 1)²(x + 2), so the repeated root is x = 1." },
];

// ── Subtopic 4: Optimisation Problems ────────────────────────────────────────
const optD4: TopicTestQuestion[] = [
  { id: "y12a-c3-opt-d4-1", prompt: "Two numbers have a sum of 10. Find the value of each number that maximises their product.", latex: "x + y = 10", marks: 3, difficulty: 4,
    answer: "5", explanation: "P = x(10 − x); P' = 10 − 2x = 0 ⇒ x = 5 (so both numbers are 5)." },
  { id: "y12a-c3-opt-d4-2", prompt: "A rectangle has a perimeter of 40 m. Find its maximum area (m²).", latex: "P = 40", marks: 3, difficulty: 4,
    choices: [ { label: "A", text: "$100$" }, { label: "B", text: "$400$" }, { label: "C", text: "$1600$" }, { label: "D", text: "$40$" } ],
    answer: "A", explanation: "Sides sum to 20, so A = x(20 − x) is max at x = 10: a 10×10 square, area 100. B/C square the perimeter incorrectly." },
  { id: "y12a-c3-opt-d4-3", prompt: "Find the value of x that minimises x² − 6x.", latex: "f(x) = x^2 - 6x", marks: 2, difficulty: 4,
    answer: "3", explanation: "f'(x) = 2x − 6 = 0 ⇒ x = 3." },
  { id: "y12a-c3-opt-d4-4", prompt: "Find the maximum value of 12x − x².", latex: "f(x) = 12x - x^2", marks: 3, difficulty: 4,
    answer: "36", explanation: "f'(x) = 12 − 2x = 0 ⇒ x = 6; f(6) = 72 − 36 = 36." },
  { id: "y12a-c3-opt-d4-5", prompt: "A farmer has 100 m of fencing for a rectangular pen. Find the maximum area (m²).", latex: "2(x+y) = 100", marks: 3, difficulty: 4,
    answer: "625", explanation: "x + y = 50, A = x(50 − x) max at x = 25: 25 × 25 = 625." },
  { id: "y12a-c3-opt-d4-6", prompt: "Two numbers have a sum of 8. Find the minimum value of the sum of their squares.", latex: "x + y = 8", marks: 3, difficulty: 4,
    answer: "32", explanation: "x² + (8 − x)² is least at x = 4: 16 + 16 = 32." },
  { id: "y12a-c3-opt-d4-7", prompt: "A rectangular area against a wall has area A = x(20 − 2x). Find the x that maximises A.", latex: "A = x(20 - 2x)", marks: 3, difficulty: 4,
    answer: "5", explanation: "A' = 20 − 4x = 0 ⇒ x = 5." },
  { id: "y12a-c3-opt-d4-8", prompt: "For x > 0, find the minimum value of C = x + 16/x.", latex: "C = x + \\tfrac{16}{x}", marks: 3, difficulty: 4,
    choices: [ { label: "A", text: "$8$" }, { label: "B", text: "$16$" }, { label: "C", text: "$4$" }, { label: "D", text: "$32$" } ],
    answer: "A", explanation: "C' = 1 − 16/x² = 0 ⇒ x = 4; C(4) = 4 + 4 = 8. B is the product; C is the optimal x." },
  { id: "y12a-c3-opt-d4-9", prompt: "Two positive numbers have a product of 36. Find the smaller number when their sum is least.", latex: "xy = 36", marks: 3, difficulty: 4,
    answer: "6", explanation: "S = x + 36/x is least at x = 6 (then y = 6), so both are 6." },
  { id: "y12a-c3-opt-d4-10", prompt: "Find the value of x that maximises A = x(16 − x).", latex: "A = x(16 - x)", marks: 2, difficulty: 4,
    answer: "8", explanation: "A' = 16 − 2x = 0 ⇒ x = 8." },
];
const optD5: TopicTestQuestion[] = [
  { id: "y12a-c3-opt-d5-1", prompt: "An open-top box with a square base of side x and height h has volume 32 cm³. Find the base side x (cm) that minimises its surface area.", latex: "x^2 h = 32, \\ SA = x^2 + 4xh", marks: 4, difficulty: 5,
    answer: "4", explanation: "h = 32/x², SA = x² + 128/x; SA' = 2x − 128/x² = 0 ⇒ x³ = 64 ⇒ x = 4." },
  { id: "y12a-c3-opt-d5-2", prompt: "For the open box above (volume 32, x = 4), find the minimum surface area (cm²).", latex: "SA = x^2 + \\tfrac{128}{x}", marks: 4, difficulty: 5,
    answer: "48", explanation: "SA(4) = 16 + 128/4 = 16 + 32 = 48." },
  { id: "y12a-c3-opt-d5-3", prompt: "A rectangular field beside a straight river (no fence on the river side) uses 200 m of fencing. Find the maximum area (m²).", latex: "x + 2y = 200", marks: 4, difficulty: 5,
    answer: "5000", explanation: "x = 200 − 2y, A = (200 − 2y)y max at y = 50: x = 100, A = 5000." },
  { id: "y12a-c3-opt-d5-4", prompt: "For that field (200 m, against a river), find the width y (the side perpendicular to the river) at maximum area.", latex: "A = (200 - 2y)y", marks: 4, difficulty: 5,
    answer: "50", explanation: "A' = 200 − 4y = 0 ⇒ y = 50." },
  { id: "y12a-c3-opt-d5-5", prompt: "Two positive numbers satisfy x + y = 12. Find the value of x that maximises x²y.", latex: "x + y = 12", marks: 4, difficulty: 5,
    answer: "8", explanation: "x²(12 − x); derivative 24x − 3x² = 3x(8 − x) = 0 ⇒ x = 8." },
  { id: "y12a-c3-opt-d5-6", prompt: "For x + y = 12, find the maximum value of x²y.", latex: "x + y = 12", marks: 4, difficulty: 5,
    answer: "256", explanation: "At x = 8, y = 4: x²y = 64 × 4 = 256." },
  { id: "y12a-c3-opt-d5-7", prompt: "A 24 cm wire is cut into two pieces, each bent into a square. Find the minimum total area (cm²).", latex: "\\text{two squares, perimeters sum to } 24", marks: 4, difficulty: 5,
    answer: "18", explanation: "Side lengths a, b with a + b = 6; total area a² + b² is least at a = b = 3: 9 + 9 = 18." },
  { id: "y12a-c3-opt-d5-8", prompt: "Find the value of x in (0, 6) that maximises V = x²(6 − x).", latex: "V = x^2(6 - x)", marks: 4, difficulty: 5,
    answer: "4", explanation: "V' = 12x − 3x² = 3x(4 − x) = 0 ⇒ x = 4." },
  { id: "y12a-c3-opt-d5-9", prompt: "Two positive numbers satisfy x + y = 9. Find the value of y that maximises xy².", latex: "x + y = 9", marks: 4, difficulty: 5,
    answer: "6", explanation: "xy² = (9 − y)y²; derivative 18y − 3y² = 3y(6 − y) = 0 ⇒ y = 6." },
  { id: "y12a-c3-opt-d5-10", prompt: "A rectangle has area 100 m². Find its minimum possible perimeter (m).", latex: "xy = 100", marks: 4, difficulty: 5,
    answer: "40", explanation: "P = 2x + 200/x; P' = 2 − 200/x² = 0 ⇒ x = 10 (a 10×10 square), P = 40." },
];

// ── Subtopic 5: Kinematics and Rates of Change ───────────────────────────────
const kinD4: TopicTestQuestion[] = [
  { id: "y12a-c3-kin-d4-1", prompt: "A particle has displacement s = t² − 4t. Find its velocity at t = 3.", latex: "s = t^2 - 4t", marks: 2, difficulty: 4,
    answer: "2", explanation: "v = ds/dt = 2t − 4; v(3) = 2." },
  { id: "y12a-c3-kin-d4-2", prompt: "A particle has displacement s = t³ − 3t². Find its acceleration at t = 2.", latex: "s = t^3 - 3t^2", marks: 2, difficulty: 4,
    answer: "6", explanation: "a = d²s/dt² = 6t − 6; a(2) = 6." },
  { id: "y12a-c3-kin-d4-3", prompt: "A particle has displacement s = t² − 6t. Find the time when it is at rest.", latex: "s = t^2 - 6t", marks: 2, difficulty: 4,
    choices: [ { label: "A", text: "$t = 3$" }, { label: "B", text: "$t = 0$" }, { label: "C", text: "$t = 6$" }, { label: "D", text: "$t = -6$" } ],
    answer: "A", explanation: "At rest ⇒ v = 2t − 6 = 0 ⇒ t = 3. B and C come from setting displacement (not velocity) to zero." },
  { id: "y12a-c3-kin-d4-4", prompt: "A particle has displacement s = t³ − 12t. Find its velocity at t = 0.", latex: "s = t^3 - 12t", marks: 2, difficulty: 4,
    answer: "-12", acceptedAnswers: ["−12"], explanation: "v = 3t² − 12; v(0) = −12." },
  { id: "y12a-c3-kin-d4-5", prompt: "A particle has displacement s = 5t − t². Find its acceleration.", latex: "s = 5t - t^2", marks: 2, difficulty: 4,
    answer: "-2", acceptedAnswers: ["−2"], explanation: "v = 5 − 2t, a = −2 (constant)." },
  { id: "y12a-c3-kin-d4-6", prompt: "A particle has displacement s = t² − 4t + 3. Find its initial velocity.", latex: "s = t^2 - 4t + 3", marks: 2, difficulty: 4,
    choices: [ { label: "A", text: "$-4$" }, { label: "B", text: "$3$" }, { label: "C", text: "$0$" }, { label: "D", text: "$-1$" } ],
    answer: "A", explanation: "v = 2t − 4; initial velocity v(0) = −4. B is the initial position s(0) = 3, not the velocity." },
  { id: "y12a-c3-kin-d4-7", prompt: "A particle has displacement s = t³ − 6t² + 9t. Find the earliest time it is at rest.", latex: "s = t^3 - 6t^2 + 9t", marks: 3, difficulty: 4,
    answer: "1", explanation: "v = 3t² − 12t + 9 = 3(t − 1)(t − 3) = 0 ⇒ t = 1 or 3; earliest is 1." },
  { id: "y12a-c3-kin-d4-8", prompt: "A particle has velocity v = 3t² − 12. Find its acceleration at t = 2.", latex: "v = 3t^2 - 12", marks: 2, difficulty: 4,
    answer: "12", explanation: "a = dv/dt = 6t; a(2) = 12." },
  { id: "y12a-c3-kin-d4-9", prompt: "A particle has displacement s = 2t² − 8t. Find its minimum displacement.", latex: "s = 2t^2 - 8t", marks: 3, difficulty: 4,
    answer: "-8", acceptedAnswers: ["−8"], explanation: "At rest at t = 2; s(2) = 8 − 16 = −8." },
  { id: "y12a-c3-kin-d4-10", prompt: "A sphere has volume V = (4/3)πr³. Find dV/dr when r = 3 (exact form).", latex: "V = \\tfrac{4}{3}\\pi r^3", marks: 3, difficulty: 4,
    answer: "36pi", acceptedAnswers: ["36π", "113.1", "113.10"], explanation: "dV/dr = 4πr²; at r = 3, dV/dr = 4π(9) = 36π." },
];
const kinD5: TopicTestQuestion[] = [
  { id: "y12a-c3-kin-d5-1", prompt: "A particle has displacement s = t³ − 6t² + 9t. Find its minimum velocity.", latex: "s = t^3 - 6t^2 + 9t", marks: 4, difficulty: 5,
    answer: "-3", acceptedAnswers: ["−3"], explanation: "v = 3t² − 12t + 9 is least at its vertex t = 2; v(2) = 12 − 24 + 9 = −3." },
  { id: "y12a-c3-kin-d5-2", prompt: "A particle has displacement s = t³ − 3t². Find its acceleration at the instant it is next at rest after t = 0.", latex: "s = t^3 - 3t^2", marks: 4, difficulty: 5,
    answer: "6", explanation: "v = 3t² − 6t = 3t(t − 2); next at rest at t = 2. a = 6t − 6; a(2) = 6." },
  { id: "y12a-c3-kin-d5-3", prompt: "A particle has displacement s = t² − 4t. Find the total distance travelled in the first 3 seconds.", latex: "s = t^2 - 4t, \\ 0 \\le t \\le 3", marks: 4, difficulty: 5,
    answer: "5", explanation: "At rest at t = 2. |s(2) − s(0)| + |s(3) − s(2)| = |−4| + |1| = 4 + 1 = 5." },
  { id: "y12a-c3-kin-d5-4", prompt: "A particle has displacement s = t³ − 12t (t ≥ 0). Find its minimum velocity.", latex: "s = t^3 - 12t", marks: 4, difficulty: 5,
    answer: "-12", acceptedAnswers: ["−12"], explanation: "v = 3t² − 12 is least at t = 0; v(0) = −12." },
  { id: "y12a-c3-kin-d5-5", prompt: "A particle has velocity v = t² − 6t + 8. Find its acceleration at the first time it is at rest.", latex: "v = t^2 - 6t + 8", marks: 4, difficulty: 5,
    answer: "-2", acceptedAnswers: ["−2"], explanation: "v = (t − 2)(t − 4) = 0 ⇒ t = 2 (first); a = 2t − 6; a(2) = −2." },
  { id: "y12a-c3-kin-d5-6", prompt: "A particle has displacement s = t³ − 9t² + 24t. Find its displacement at the first time it is at rest.", latex: "s = t^3 - 9t^2 + 24t", marks: 4, difficulty: 5,
    answer: "20", explanation: "v = 3t² − 18t + 24 = 3(t − 2)(t − 4); first at rest at t = 2; s(2) = 8 − 36 + 48 = 20." },
  { id: "y12a-c3-kin-d5-7", prompt: "A particle has velocity v = 12t − 3t². Find its maximum velocity.", latex: "v = 12t - 3t^2", marks: 4, difficulty: 5,
    answer: "12", explanation: "dv/dt = 12 − 6t = 0 ⇒ t = 2; v(2) = 24 − 12 = 12." },
  { id: "y12a-c3-kin-d5-8", prompt: "A particle has displacement s = t³ − 3t² − 9t. Find the time (t > 0) when it is at rest.", latex: "s = t^3 - 3t^2 - 9t", marks: 4, difficulty: 5,
    answer: "3", explanation: "v = 3t² − 6t − 9 = 3(t − 3)(t + 1) = 0 ⇒ t = 3 (t > 0)." },
  { id: "y12a-c3-kin-d5-9", prompt: "A particle has acceleration a = 6t − 4 and velocity v = 1 when t = 0. Find its velocity at t = 2.", latex: "a = 6t - 4, \\ v(0) = 1", marks: 4, difficulty: 5,
    answer: "5", explanation: "v = ∫a dt = 3t² − 4t + C; v(0) = C = 1; v(2) = 12 − 8 + 1 = 5." },
  { id: "y12a-c3-kin-d5-10", prompt: "A particle has displacement s = t³ − 6t². Find its acceleration at the time (t > 0) when it is at rest.", latex: "s = t^3 - 6t^2", marks: 4, difficulty: 5,
    answer: "12", explanation: "v = 3t² − 12t = 3t(t − 4); at rest (t > 0) at t = 4; a = 6t − 12; a(4) = 12." },
];

// ── Subtopic 6: Applications of Differentiation Exam Practice — D6 ────────────
// Multi-part Section II-style, each combining ≥2 strands (stationary points,
// classification, inflection, curve sketching, optimisation, kinematics).
const examD6: TopicTestQuestion[] = [
  { id: "y12a-c3-ex-d6-1", prompt: "Consider the curve y = x³ − 3x² − 9x + 5.", latex: "y = x^3 - 3x^2 - 9x + 5", marks: 6, difficulty: 6,
    explanation: "Stationary points, classification, and the point of inflection.",
    parts: [
      { key: "a", label: "(a)", prompt: "Find the larger x-coordinate of the two stationary points.", marks: 2, answer: "3", explanation: "dy/dx = 3(x − 3)(x + 1) = 0 ⇒ x = −1 or 3; larger is 3." },
      { key: "b", label: "(b)", prompt: "Classify the stationary point at x = −1 (minimum or maximum).", marks: 2, answer: "maximum", acceptedAnswers: ["max"], explanation: "f''(x) = 6x − 6; f''(−1) = −12 < 0, so a maximum." },
      { key: "c", label: "(c)", prompt: "Find the x-coordinate of the point of inflection.", marks: 2, answer: "1", explanation: "f''(x) = 6x − 6 = 0 ⇒ x = 1." },
    ] },
  { id: "y12a-c3-ex-d6-2", prompt: "A rectangle has a perimeter of 24 m; its width is x.", latex: "P = 24, \\text{ width } x", marks: 6, difficulty: 6,
    explanation: "Set up the area, optimise, and evaluate.",
    parts: [
      { key: "a", label: "(a)", prompt: "Find the length when x = 4.", marks: 1, answer: "8", explanation: "Length = 12 − x = 8." },
      { key: "b", label: "(b)", prompt: "Find the width x that maximises the area.", marks: 2, answer: "6", explanation: "A = x(12 − x); A' = 12 − 2x = 0 ⇒ x = 6." },
      { key: "c", label: "(c)", prompt: "Find the maximum area (m²).", marks: 2, answer: "36", explanation: "A(6) = 6 × 6 = 36." },
      { key: "d", label: "(d)", prompt: "Find the area when x = 4 (m²).", marks: 1, answer: "32", explanation: "A(4) = 4 × 8 = 32." },
    ] },
  { id: "y12a-c3-ex-d6-3", prompt: "A particle has displacement s = t³ − 6t² + 9t (t ≥ 0).", latex: "s = t^3 - 6t^2 + 9t", marks: 6, difficulty: 6,
    explanation: "Velocity, at-rest times, acceleration, and displacement.",
    parts: [
      { key: "a", label: "(a)", prompt: "Find the initial velocity (at t = 0).", marks: 1, answer: "9", explanation: "v = 3t² − 12t + 9; v(0) = 9." },
      { key: "b", label: "(b)", prompt: "Find the earliest time the particle is at rest.", marks: 2, answer: "1", explanation: "v = 3(t − 1)(t − 3) = 0 ⇒ t = 1 or 3; earliest is 1." },
      { key: "c", label: "(c)", prompt: "Find the acceleration at t = 3.", marks: 1, answer: "6", explanation: "a = 6t − 12; a(3) = 6." },
      { key: "d", label: "(d)", prompt: "Find the displacement at the first time it is at rest.", marks: 2, answer: "4", explanation: "s(1) = 1 − 6 + 9 = 4." },
    ] },
  { id: "y12a-c3-ex-d6-4", prompt: "Consider the curve y = x³ − 12x.", latex: "y = x^3 - 12x", marks: 6, difficulty: 6,
    explanation: "Intercepts, the local maximum, and inflection — a full sketch analysis.",
    parts: [
      { key: "a", label: "(a)", prompt: "How many x-intercepts does the curve have?", marks: 1, answer: "3", explanation: "x(x² − 12) = 0 ⇒ x = 0, ±√12: three." },
      { key: "b", label: "(b)", prompt: "Find the x-coordinate of the local maximum.", marks: 2, answer: "-2", acceptedAnswers: ["−2"], explanation: "dy/dx = 3x² − 12 = 0 ⇒ x = ±2; the maximum is at x = −2." },
      { key: "c", label: "(c)", prompt: "Find the local maximum value.", marks: 2, answer: "16", explanation: "y(−2) = −8 + 24 = 16." },
      { key: "d", label: "(d)", prompt: "How many points of inflection does the curve have?", marks: 1, answer: "1", explanation: "f''(x) = 6x = 0 at x = 0 (one)." },
    ] },
  { id: "y12a-c3-ex-d6-5", prompt: "An open-top box has a square base of side x and height h, with volume 500 cm³.", latex: "x^2 h = 500, \\ S = x^2 + 4xh", marks: 6, difficulty: 6,
    explanation: "Eliminate h, minimise surface area, and evaluate.",
    parts: [
      { key: "a", label: "(a)", prompt: "Find h when x = 10.", marks: 1, answer: "5", explanation: "h = 500/x² = 500/100 = 5." },
      { key: "b", label: "(b)", prompt: "Find the base side x that minimises the surface area S = x² + 2000/x.", marks: 3, answer: "10", explanation: "S' = 2x − 2000/x² = 0 ⇒ x³ = 1000 ⇒ x = 10." },
      { key: "c", label: "(c)", prompt: "Find the minimum surface area (cm²).", marks: 2, answer: "300", explanation: "S(10) = 100 + 2000/10 = 100 + 200 = 300." },
    ] },
];

export const applicationsDifferentiationPool: TopicTestPool = {
  courseSlug: "year-12-advanced",
  courseTitle: "Year 12 Mathematics Advanced",
  topicSlug: "ma-c3-applications-of-differentiation",
  topicTitle: "Applications of Differentiation",
  subtopics: [
    {
      subtopicSlug: "second-derivative-concavity",
      subtopicTitle: "Second Derivative, Concavity and Points of Inflection",
      remediationHref: href("second-derivative-concavity"),
      d4: concD4,
      d5: concD5,
    },
    {
      subtopicSlug: "stationary-point-classification",
      subtopicTitle: "Stationary Point Classification",
      remediationHref: href("stationary-point-classification"),
      d4: sptD4,
      d5: sptD5,
    },
    {
      subtopicSlug: "curve-sketching-calculus",
      subtopicTitle: "Curve Sketching with Calculus",
      remediationHref: href("curve-sketching-calculus"),
      d4: csD4,
      d5: csD5,
    },
    {
      subtopicSlug: "optimisation",
      subtopicTitle: "Optimisation Problems",
      remediationHref: href("optimisation"),
      d4: optD4,
      d5: optD5,
    },
    {
      subtopicSlug: "kinematics-rates-change",
      subtopicTitle: "Kinematics and Rates of Change",
      remediationHref: href("kinematics-rates-change"),
      d4: kinD4,
      d5: kinD5,
    },
    {
      subtopicSlug: "applications-differentiation-exam-practice",
      subtopicTitle: "Applications of Differentiation Exam Practice",
      remediationHref: href("applications-differentiation-exam-practice"),
      d4: [],
      d5: [],
      d6: examD6,
    },
  ],
};
