import type { TopicTestPool, TopicTestQuestion } from "../../types";

/**
 * Topic-test pool — Year 12 Mathematics Advanced · Differential Calculus
 * (NESA MA-C2). Legacy/canonical course, routed
 * /course/year-12-advanced/ma-c2-differential-calculus/<lesson>.
 *
 * Four skill subtopics (D4 + D5) plus a D6 exam-practice band, all auto-markable.
 * Status: subtopic 1 "Standard Derivatives" — D4 + D5. Remaining subtopics to
 * follow; not yet registered.
 */

const href = (lesson: string) =>
  `/course/year-12-advanced/ma-c2-differential-calculus/${lesson}`;

// ── Subtopic 1: Standard Derivatives (trig, exponential, logarithmic) ────────
const stdD4: TopicTestQuestion[] = [
  { id: "y12a-c2-std-d4-1", prompt: "For f(x) = sin x, find f'(π/3) (exact fraction).", latex: "f(x) = \\sin x", marks: 2, difficulty: 4,
    answer: "1/2", acceptedAnswers: ["0.5"], explanation: "f'(x) = cos x; f'(π/3) = cos(π/3) = 1/2." },
  { id: "y12a-c2-std-d4-2", prompt: "For f(x) = eˣ, find f'(2) (exact form).", latex: "f(x) = e^x", marks: 2, difficulty: 4,
    choices: [ { label: "A", text: "$e^2$" }, { label: "B", text: "$2e$" }, { label: "C", text: "$e$" }, { label: "D", text: "$2e^2$" } ],
    answer: "A", explanation: "f'(x) = eˣ, so f'(2) = e². B applies the power rule incorrectly." },
  { id: "y12a-c2-std-d4-3", prompt: "For f(x) = ln x, find f'(4) (exact fraction).", latex: "f(x) = \\ln x", marks: 2, difficulty: 4,
    answer: "1/4", acceptedAnswers: ["0.25"], explanation: "f'(x) = 1/x, so f'(4) = 1/4." },
  { id: "y12a-c2-std-d4-4", prompt: "For f(x) = cos x, find f'(π/2).", latex: "f(x) = \\cos x", marks: 2, difficulty: 4,
    choices: [ { label: "A", text: "$-1$" }, { label: "B", text: "$1$" }, { label: "C", text: "$0$" }, { label: "D", text: "$\\tfrac{\\pi}{2}$" } ],
    answer: "A", explanation: "f'(x) = −sin x, so f'(π/2) = −1. B drops the sign." },
  { id: "y12a-c2-std-d4-5", prompt: "For f(x) = 4 sin x, find f'(0).", latex: "f(x) = 4\\sin x", marks: 2, difficulty: 4,
    answer: "4", explanation: "f'(x) = 4 cos x, so f'(0) = 4." },
  { id: "y12a-c2-std-d4-6", prompt: "For f(x) = eˣ, find f'(1) (exact form).", latex: "f(x) = e^x", marks: 2, difficulty: 4,
    answer: "e", acceptedAnswers: ["2.718", "2.7183"], explanation: "f'(x) = eˣ, so f'(1) = e." },
  { id: "y12a-c2-std-d4-7", prompt: "For f(x) = 2 ln x, find f'(2).", latex: "f(x) = 2\\ln x", marks: 2, difficulty: 4,
    answer: "1", explanation: "f'(x) = 2/x, so f'(2) = 1." },
  { id: "y12a-c2-std-d4-8", prompt: "For f(x) = sin x + cos x, find f'(0).", latex: "f(x) = \\sin x + \\cos x", marks: 2, difficulty: 4,
    answer: "1", explanation: "f'(x) = cos x − sin x, so f'(0) = 1 − 0 = 1." },
  { id: "y12a-c2-std-d4-9", prompt: "For f(x) = eˣ, find f'(ln 3).", latex: "f(x) = e^x", marks: 3, difficulty: 4,
    answer: "3", explanation: "f'(x) = eˣ, so f'(ln 3) = e^{ln 3} = 3." },
  { id: "y12a-c2-std-d4-10", prompt: "For f(x) = 2cos x, find f'(π/6).", latex: "f(x) = 2\\cos x", marks: 2, difficulty: 4,
    answer: "-1", acceptedAnswers: ["−1"], explanation: "f'(x) = −2sin x; f'(π/6) = −2(1/2) = −1." },
];
const stdD5: TopicTestQuestion[] = [
  { id: "y12a-c2-std-d5-1", prompt: "For f(x) = sin x, find the first positive x where f'(x) = 1/2 (exact form).", latex: "f(x) = \\sin x", marks: 4, difficulty: 5,
    answer: "pi/3", acceptedAnswers: ["π/3", "1.047", "1.0472"], explanation: "f'(x) = cos x = 1/2 ⇒ x = π/3." },
  { id: "y12a-c2-std-d5-2", prompt: "For f(x) = sin x, find f''(π/2) (the second derivative at π/2).", latex: "f(x) = \\sin x", marks: 3, difficulty: 5,
    answer: "-1", acceptedAnswers: ["−1"], explanation: "f'(x) = cos x, f''(x) = −sin x; f''(π/2) = −1." },
  { id: "y12a-c2-std-d5-3", prompt: "For f(x) = eˣ, find x where f'(x) = e².", latex: "f(x) = e^x", marks: 3, difficulty: 5,
    answer: "2", explanation: "f'(x) = eˣ = e² ⇒ x = 2." },
  { id: "y12a-c2-std-d5-4", prompt: "For f(x) = ln x, find x where f'(x) = 1/3.", latex: "f(x) = \\ln x", marks: 3, difficulty: 5,
    answer: "3", explanation: "f'(x) = 1/x = 1/3 ⇒ x = 3." },
  { id: "y12a-c2-std-d5-5", prompt: "For f(x) = eˣ, find f''(0).", latex: "f(x) = e^x", marks: 3, difficulty: 5,
    answer: "1", explanation: "All derivatives of eˣ are eˣ; f''(0) = 1." },
  { id: "y12a-c2-std-d5-6", prompt: "For f(x) = cos x, find the first positive x where f'(x) = −1 (exact form).", latex: "f(x) = \\cos x", marks: 4, difficulty: 5,
    answer: "pi/2", acceptedAnswers: ["π/2", "1.571", "1.5708"], explanation: "f'(x) = −sin x = −1 ⇒ sin x = 1 ⇒ x = π/2." },
  { id: "y12a-c2-std-d5-7", prompt: "For f(x) = 2 sin x + 3 cos x, find f'(0).", latex: "f(x) = 2\\sin x + 3\\cos x", marks: 4, difficulty: 5,
    answer: "2", explanation: "f'(x) = 2 cos x − 3 sin x; f'(0) = 2 − 0 = 2." },
  { id: "y12a-c2-std-d5-8", prompt: "For f(x) = cos x, find f''(π/3) (exact fraction).", latex: "f(x) = \\cos x", marks: 3, difficulty: 5,
    answer: "-1/2", acceptedAnswers: ["−1/2", "-0.5"], explanation: "f'(x) = −sin x, f''(x) = −cos x; f''(π/3) = −cos(π/3) = −1/2." },
  { id: "y12a-c2-std-d5-9", prompt: "For f(x) = eˣ, find f'(ln 2).", latex: "f(x) = e^x", marks: 4, difficulty: 5,
    answer: "2", explanation: "f'(x) = eˣ, so f'(ln 2) = e^{ln 2} = 2." },
  { id: "y12a-c2-std-d5-10", prompt: "For f(x) = eˣ − x, find f'(0).", latex: "f(x) = e^x - x", marks: 3, difficulty: 5,
    answer: "0", explanation: "f'(x) = eˣ − 1; f'(0) = 1 − 1 = 0." },
];

// ── Subtopic 2: The Chain Rule ───────────────────────────────────────────────
const chainD4: TopicTestQuestion[] = [
  { id: "y12a-c2-chain-d4-1", prompt: "For f(x) = (x² + 1)³, find f'(1).", latex: "f(x) = (x^2+1)^3", marks: 3, difficulty: 4,
    answer: "24", explanation: "f'(x) = 3(x²+1)²·2x; f'(1) = 3(4)(2) = 24." },
  { id: "y12a-c2-chain-d4-2", prompt: "For f(x) = sin(2x), find f'(0).", latex: "f(x) = \\sin(2x)", marks: 2, difficulty: 4,
    choices: [ { label: "A", text: "$2$" }, { label: "B", text: "$1$" }, { label: "C", text: "$0$" }, { label: "D", text: "$2x$" } ],
    answer: "A", explanation: "f'(x) = 2cos(2x); f'(0) = 2. B forgets the chain factor of 2." },
  { id: "y12a-c2-chain-d4-3", prompt: "For f(x) = e^{3x}, find f'(0).", latex: "f(x) = e^{3x}", marks: 2, difficulty: 4,
    choices: [ { label: "A", text: "$3$" }, { label: "B", text: "$1$" }, { label: "C", text: "$e^3$" }, { label: "D", text: "$3x$" } ],
    answer: "A", explanation: "f'(x) = 3e^{3x}; f'(0) = 3. B forgets the chain factor." },
  { id: "y12a-c2-chain-d4-4", prompt: "For f(x) = (2x + 1)⁴, find f'(0).", latex: "f(x) = (2x+1)^4", marks: 3, difficulty: 4,
    answer: "8", explanation: "f'(x) = 4(2x+1)³·2 = 8(2x+1)³; f'(0) = 8." },
  { id: "y12a-c2-chain-d4-5", prompt: "For f(x) = ln(x²), find f'(1).", latex: "f(x) = \\ln(x^2)", marks: 3, difficulty: 4,
    answer: "2", explanation: "f'(x) = (1/x²)·2x = 2/x; f'(1) = 2." },
  { id: "y12a-c2-chain-d4-6", prompt: "For f(x) = cos(3x), find f'(0).", latex: "f(x) = \\cos(3x)", marks: 2, difficulty: 4,
    answer: "0", explanation: "f'(x) = −3sin(3x); f'(0) = 0." },
  { id: "y12a-c2-chain-d4-7", prompt: "For f(x) = √(x² + 9), find f'(4) (exact fraction).", latex: "f(x) = \\sqrt{x^2+9}", marks: 3, difficulty: 4,
    answer: "4/5", acceptedAnswers: ["0.8"], explanation: "f'(x) = x/√(x²+9); f'(4) = 4/5." },
  { id: "y12a-c2-chain-d4-8", prompt: "For f(x) = (3x − 1)², find f'(1).", latex: "f(x) = (3x-1)^2", marks: 2, difficulty: 4,
    answer: "12", explanation: "f'(x) = 2(3x−1)·3; f'(1) = 6(2) = 12." },
  { id: "y12a-c2-chain-d4-9", prompt: "For f(x) = e^{x²}, find f'(1) (exact form).", latex: "f(x) = e^{x^2}", marks: 3, difficulty: 4,
    answer: "2e", acceptedAnswers: ["2*e", "5.437", "5.4366"], explanation: "f'(x) = 2x e^{x²}; f'(1) = 2e." },
  { id: "y12a-c2-chain-d4-10", prompt: "For f(x) = (x³ + 1)², find f'(1).", latex: "f(x) = (x^3+1)^2", marks: 3, difficulty: 4,
    answer: "12", explanation: "f'(x) = 2(x³+1)·3x²; f'(1) = 2(2)(3) = 12." },
];
const chainD5: TopicTestQuestion[] = [
  { id: "y12a-c2-chain-d5-1", prompt: "For f(x) = sin(2x), find the first positive x where f'(x) = 0 (exact form).", latex: "f(x) = \\sin(2x)", marks: 4, difficulty: 5,
    answer: "pi/4", acceptedAnswers: ["π/4", "0.785", "0.7854"], explanation: "f'(x) = 2cos(2x) = 0 ⇒ 2x = π/2 ⇒ x = π/4." },
  { id: "y12a-c2-chain-d5-2", prompt: "For f(x) = (x² − 4)³, find f'(2).", latex: "f(x) = (x^2-4)^3", marks: 4, difficulty: 5,
    answer: "0", explanation: "f'(x) = 3(x²−4)²·2x; at x = 2 the factor (x²−4) = 0, so f'(2) = 0." },
  { id: "y12a-c2-chain-d5-3", prompt: "For f(x) = e^{2x}, find x where f'(x) = 2.", latex: "f(x) = e^{2x}", marks: 4, difficulty: 5,
    answer: "0", explanation: "f'(x) = 2e^{2x} = 2 ⇒ e^{2x} = 1 ⇒ x = 0." },
  { id: "y12a-c2-chain-d5-4", prompt: "For f(x) = ln(2x + 1), find f'(0).", latex: "f(x) = \\ln(2x+1)", marks: 3, difficulty: 5,
    answer: "2", explanation: "f'(x) = 2/(2x+1); f'(0) = 2." },
  { id: "y12a-c2-chain-d5-5", prompt: "For f(x) = √(2x + 1), find f'(4) (exact fraction).", latex: "f(x) = \\sqrt{2x+1}", marks: 4, difficulty: 5,
    answer: "1/3", acceptedAnswers: ["0.333", "0.3333"], explanation: "f'(x) = 1/√(2x+1); f'(4) = 1/3." },
  { id: "y12a-c2-chain-d5-6", prompt: "For f(x) = sin²x, find f'(π/4).", latex: "f(x) = \\sin^2 x", marks: 4, difficulty: 5,
    answer: "1", explanation: "f'(x) = 2 sin x cos x = sin 2x; f'(π/4) = sin(π/2) = 1." },
  { id: "y12a-c2-chain-d5-7", prompt: "For f(x) = e^{−x}, find f'(0).", latex: "f(x) = e^{-x}", marks: 3, difficulty: 5,
    answer: "-1", acceptedAnswers: ["−1"], explanation: "f'(x) = −e^{−x}; f'(0) = −1." },
  { id: "y12a-c2-chain-d5-8", prompt: "For f(x) = e^{2x}, find f''(0).", latex: "f(x) = e^{2x}", marks: 4, difficulty: 5,
    answer: "4", explanation: "f'(x) = 2e^{2x}, f''(x) = 4e^{2x}; f''(0) = 4." },
  { id: "y12a-c2-chain-d5-9", prompt: "For f(x) = cos(2x), find f'(π/4).", latex: "f(x) = \\cos(2x)", marks: 4, difficulty: 5,
    answer: "-2", acceptedAnswers: ["−2"], explanation: "f'(x) = −2sin(2x); f'(π/4) = −2sin(π/2) = −2." },
  { id: "y12a-c2-chain-d5-10", prompt: "For f(x) = (2x + 1)³, find f'(0).", latex: "f(x) = (2x+1)^3", marks: 3, difficulty: 5,
    answer: "6", explanation: "f'(x) = 3(2x+1)²·2 = 6(2x+1)²; f'(0) = 6." },
];

// ── Subtopic 3: Product and Quotient Rules ───────────────────────────────────
const pqD4: TopicTestQuestion[] = [
  { id: "y12a-c2-pq-d4-1", prompt: "For f(x) = x·eˣ, find f'(0).", latex: "f(x) = xe^x", marks: 3, difficulty: 4,
    choices: [ { label: "A", text: "$1$" }, { label: "B", text: "$0$" }, { label: "C", text: "$e$" }, { label: "D", text: "$2$" } ],
    answer: "A", explanation: "f'(x) = eˣ + xeˣ = (1+x)eˣ; f'(0) = 1. B uses only one term of the product rule." },
  { id: "y12a-c2-pq-d4-2", prompt: "For f(x) = (2x)(x + 3), find f'(0).", latex: "f(x) = (2x)(x+3)", marks: 2, difficulty: 4,
    answer: "6", explanation: "f'(x) = 2(x+3) + 2x = 4x + 6; f'(0) = 6." },
  { id: "y12a-c2-pq-d4-3", prompt: "For f(x) = x ln x, find f'(1).", latex: "f(x) = x\\ln x", marks: 2, difficulty: 4,
    answer: "1", explanation: "f'(x) = ln x + 1; f'(1) = 1." },
  { id: "y12a-c2-pq-d4-4", prompt: "For f(x) = x/(x + 1), find f'(1) (exact fraction).", latex: "f(x) = \\tfrac{x}{x+1}", marks: 3, difficulty: 4,
    answer: "1/4", acceptedAnswers: ["0.25"], explanation: "f'(x) = 1/(x+1)²; f'(1) = 1/4." },
  { id: "y12a-c2-pq-d4-5", prompt: "For f(x) = (x + 1)/(x − 1), find f'(0).", latex: "f(x) = \\tfrac{x+1}{x-1}", marks: 3, difficulty: 4,
    choices: [ { label: "A", text: "$-2$" }, { label: "B", text: "$2$" }, { label: "C", text: "$-1$" }, { label: "D", text: "$1$" } ],
    answer: "A", explanation: "f'(x) = ((x−1) − (x+1))/(x−1)² = −2/(x−1)²; f'(0) = −2. B drops the sign." },
  { id: "y12a-c2-pq-d4-6", prompt: "For f(x) = x²eˣ, find f'(1) (exact form).", latex: "f(x) = x^2 e^x", marks: 3, difficulty: 4,
    answer: "3e", acceptedAnswers: ["3*e", "8.155", "8.1548"], explanation: "f'(x) = (2x + x²)eˣ; f'(1) = 3e." },
  { id: "y12a-c2-pq-d4-7", prompt: "For f(x) = x cos x, find f'(π/2) (exact form).", latex: "f(x) = x\\cos x", marks: 3, difficulty: 4,
    answer: "-pi/2", acceptedAnswers: ["−π/2", "-1.571", "-1.5708"], explanation: "f'(x) = cos x − x sin x; f'(π/2) = 0 − (π/2)(1) = −π/2." },
  { id: "y12a-c2-pq-d4-8", prompt: "For f(x) = (x²)(x³), find f'(1).", latex: "f(x) = (x^2)(x^3)", marks: 2, difficulty: 4,
    answer: "5", explanation: "f(x) = x⁵, f'(x) = 5x⁴; f'(1) = 5." },
  { id: "y12a-c2-pq-d4-9", prompt: "For f(x) = 1/(x² + 1), find f'(1) (exact fraction).", latex: "f(x) = \\tfrac{1}{x^2+1}", marks: 3, difficulty: 4,
    answer: "-1/2", acceptedAnswers: ["−1/2", "-0.5"], explanation: "f'(x) = −2x/(x²+1)²; f'(1) = −2/4 = −1/2." },
  { id: "y12a-c2-pq-d4-10", prompt: "For f(x) = x e^{−x}, find f'(0).", latex: "f(x) = xe^{-x}", marks: 3, difficulty: 4,
    answer: "1", explanation: "f'(x) = (1 − x)e^{−x}; f'(0) = 1." },
];
const pqD5: TopicTestQuestion[] = [
  { id: "y12a-c2-pq-d5-1", prompt: "For f(x) = x² sin x, find f'(π/2) (exact form).", latex: "f(x) = x^2 \\sin x", marks: 4, difficulty: 5,
    answer: "pi", acceptedAnswers: ["π", "3.142", "3.1416"], explanation: "f'(x) = 2x sin x + x² cos x; f'(π/2) = 2(π/2)(1) + (π/2)²(0) = π." },
  { id: "y12a-c2-pq-d5-2", prompt: "For f(x) = x² e^{−x}, find f'(1) (exact form).", latex: "f(x) = x^2 e^{-x}", marks: 4, difficulty: 5,
    answer: "1/e", acceptedAnswers: ["e^(-1)", "0.368", "0.3679"], explanation: "f'(x) = (2x − x²)e^{−x}; f'(1) = (2 − 1)e^{−1} = 1/e." },
  { id: "y12a-c2-pq-d5-3", prompt: "For f(x) = (x + 1)(x − 2), find f'(0).", latex: "f(x) = (x+1)(x-2)", marks: 3, difficulty: 5,
    answer: "-1", acceptedAnswers: ["−1"], explanation: "f'(x) = (x−2) + (x+1) = 2x − 1; f'(0) = −1." },
  { id: "y12a-c2-pq-d5-4", prompt: "For f(x) = (ln x)/x, find f'(1).", latex: "f(x) = \\tfrac{\\ln x}{x}", marks: 4, difficulty: 5,
    answer: "1", explanation: "f'(x) = (1 − ln x)/x²; f'(1) = 1." },
  { id: "y12a-c2-pq-d5-5", prompt: "For f(x) = x ln x, find f'(e).", latex: "f(x) = x\\ln x", marks: 3, difficulty: 5,
    answer: "2", explanation: "f'(x) = ln x + 1; f'(e) = 1 + 1 = 2." },
  { id: "y12a-c2-pq-d5-6", prompt: "For f(x) = eˣ/x, find f'(1).", latex: "f(x) = \\tfrac{e^x}{x}", marks: 4, difficulty: 5,
    answer: "0", explanation: "f'(x) = eˣ(x − 1)/x²; f'(1) = 0." },
  { id: "y12a-c2-pq-d5-7", prompt: "For f(x) = (x² + 1)/x, find f'(2) (exact fraction).", latex: "f(x) = \\tfrac{x^2+1}{x}", marks: 4, difficulty: 5,
    answer: "3/4", acceptedAnswers: ["0.75"], explanation: "f(x) = x + 1/x, f'(x) = 1 − 1/x²; f'(2) = 1 − 1/4 = 3/4." },
  { id: "y12a-c2-pq-d5-8", prompt: "For f(x) = x sin x, find f'(π) (exact form).", latex: "f(x) = x\\sin x", marks: 4, difficulty: 5,
    answer: "-pi", acceptedAnswers: ["−π", "-3.142", "-3.1416"], explanation: "f'(x) = sin x + x cos x; f'(π) = 0 + π(−1) = −π." },
  { id: "y12a-c2-pq-d5-9", prompt: "For f(x) = x²/(x + 1), find f'(2) (exact fraction).", latex: "f(x) = \\tfrac{x^2}{x+1}", marks: 4, difficulty: 5,
    answer: "8/9", acceptedAnswers: ["0.889", "0.8889"], explanation: "f'(x) = (x² + 2x)/(x+1)²; f'(2) = 8/9." },
  { id: "y12a-c2-pq-d5-10", prompt: "For f(x) = x√x, find f'(4).", latex: "f(x) = x\\sqrt{x}", marks: 3, difficulty: 5,
    answer: "3", explanation: "f(x) = x^{3/2}, f'(x) = (3/2)x^{1/2}; f'(4) = (3/2)(2) = 3." },
];

// ── Subtopic 4: Applications with Extended Differentiation ────────────────────
const appD4: TopicTestQuestion[] = [
  { id: "y12a-c2-app-d4-1", prompt: "Find the gradient of the tangent to y = ln x at x = 2 (exact fraction).", latex: "y = \\ln x", marks: 2, difficulty: 4,
    answer: "1/2", acceptedAnswers: ["0.5"], explanation: "dy/dx = 1/x; at x = 2 the gradient is 1/2." },
  { id: "y12a-c2-app-d4-2", prompt: "Find the gradient of the tangent to y = eˣ at x = 1 (exact form).", latex: "y = e^x", marks: 2, difficulty: 4,
    answer: "e", acceptedAnswers: ["2.718", "2.7183"], explanation: "dy/dx = eˣ; at x = 1 the gradient is e." },
  { id: "y12a-c2-app-d4-3", prompt: "Find the gradient of the tangent to y = sin x at x = π/3 (exact fraction).", latex: "y = \\sin x", marks: 3, difficulty: 4,
    answer: "1/2", acceptedAnswers: ["0.5"], explanation: "dy/dx = cos x; cos(π/3) = 1/2." },
  { id: "y12a-c2-app-d4-4", prompt: "Find the gradient of the tangent to y = e^{2x} at x = 0.", latex: "y = e^{2x}", marks: 2, difficulty: 4,
    answer: "2", explanation: "dy/dx = 2e^{2x}; at x = 0 the gradient is 2." },
  { id: "y12a-c2-app-d4-5", prompt: "A particle has position s = sin t. Find its velocity at t = 0.", latex: "s = \\sin t", marks: 2, difficulty: 4,
    answer: "1", explanation: "v = ds/dt = cos t; v(0) = 1." },
  { id: "y12a-c2-app-d4-6", prompt: "Find the x-coordinate of the stationary point of y = x eˣ.", latex: "y = xe^x", marks: 3, difficulty: 4,
    choices: [ { label: "A", text: "$-1$" }, { label: "B", text: "$0$" }, { label: "C", text: "$1$" }, { label: "D", text: "$e$" } ],
    answer: "A", explanation: "dy/dx = (1 + x)eˣ = 0 ⇒ x = −1 (eˣ ≠ 0). B sets only eˣ = 0." },
  { id: "y12a-c2-app-d4-7", prompt: "Find the x-coordinate of the stationary point of y = ln x − x (x > 0).", latex: "y = \\ln x - x", marks: 3, difficulty: 4,
    answer: "1", explanation: "dy/dx = 1/x − 1 = 0 ⇒ x = 1." },
  { id: "y12a-c2-app-d4-8", prompt: "A population is N = e^{0.5t}. Find dN/dt at t = 0.", latex: "N = e^{0.5t}", marks: 2, difficulty: 4,
    answer: "0.5", acceptedAnswers: ["1/2"], explanation: "dN/dt = 0.5e^{0.5t}; at t = 0 it is 0.5." },
  { id: "y12a-c2-app-d4-9", prompt: "For y = eˣ, find d²y/dx² at x = 0.", latex: "y = e^x", marks: 2, difficulty: 4,
    answer: "1", explanation: "All derivatives of eˣ are eˣ; at x = 0 it is 1." },
  { id: "y12a-c2-app-d4-10", prompt: "Find the gradient of the tangent to y = cos x at x = π/2.", latex: "y = \\cos x", marks: 2, difficulty: 4,
    answer: "-1", acceptedAnswers: ["−1"], explanation: "dy/dx = −sin x; at x = π/2 the gradient is −1." },
];
const appD5: TopicTestQuestion[] = [
  { id: "y12a-c2-app-d5-1", prompt: "Find the y-value at the stationary point of y = x eˣ (exact form).", latex: "y = xe^x", marks: 4, difficulty: 5,
    answer: "-1/e", acceptedAnswers: ["−1/e", "-e^(-1)", "-0.368", "-0.3679"], explanation: "Stationary at x = −1; y(−1) = −e^{−1} = −1/e." },
  { id: "y12a-c2-app-d5-2", prompt: "Find the maximum value of y = ln x − x (x > 0).", latex: "y = \\ln x - x", marks: 4, difficulty: 5,
    answer: "-1", acceptedAnswers: ["−1"], explanation: "Max at x = 1; y(1) = 0 − 1 = −1." },
  { id: "y12a-c2-app-d5-3", prompt: "Find the maximum value of y = e^{−x²}.", latex: "y = e^{-x^2}", marks: 4, difficulty: 5,
    answer: "1", explanation: "The exponent −x² is greatest (0) at x = 0, giving y = e⁰ = 1." },
  { id: "y12a-c2-app-d5-4", prompt: "The tangent to y = eˣ at x = 0 is y = x + 1. Find its y-intercept.", latex: "y = e^x \\text{ at } x=0", marks: 3, difficulty: 5,
    answer: "1", explanation: "y = x + 1 meets the y-axis at y = 1." },
  { id: "y12a-c2-app-d5-5", prompt: "Find the x-coordinate of the stationary point of y = x − ln x (x > 0).", latex: "y = x - \\ln x", marks: 4, difficulty: 5,
    answer: "1", explanation: "dy/dx = 1 − 1/x = 0 ⇒ x = 1." },
  { id: "y12a-c2-app-d5-6", prompt: "A particle has velocity v = t e^{−t}. Find the time t > 0 at which v is greatest.", latex: "v = te^{-t}", marks: 4, difficulty: 5,
    answer: "1", explanation: "dv/dt = (1 − t)e^{−t} = 0 ⇒ t = 1." },
  { id: "y12a-c2-app-d5-7", prompt: "Find the first positive x where y = sin x + cos x has a stationary point (exact form).", latex: "y = \\sin x + \\cos x", marks: 4, difficulty: 5,
    answer: "pi/4", acceptedAnswers: ["π/4", "0.785", "0.7854"], explanation: "dy/dx = cos x − sin x = 0 ⇒ tan x = 1 ⇒ x = π/4." },
  { id: "y12a-c2-app-d5-8", prompt: "Find the non-zero x-coordinate of a stationary point of y = x² eˣ.", latex: "y = x^2 e^x", marks: 4, difficulty: 5,
    answer: "-2", acceptedAnswers: ["−2"], explanation: "dy/dx = (2x + x²)eˣ = x(2 + x)eˣ = 0 ⇒ x = 0 or −2; non-zero is −2." },
  { id: "y12a-c2-app-d5-9", prompt: "The tangent to y = ln x at x = 1 is y = x − 1. Find its x-intercept.", latex: "y = \\ln x \\text{ at } x=1", marks: 3, difficulty: 5,
    answer: "1", explanation: "0 = x − 1 ⇒ x = 1." },
  { id: "y12a-c2-app-d5-10", prompt: "Find the x-coordinate of the stationary point of y = eˣ/x (x > 0).", latex: "y = \\tfrac{e^x}{x}", marks: 4, difficulty: 5,
    answer: "1", explanation: "dy/dx = eˣ(x − 1)/x² = 0 ⇒ x = 1." },
];

// ── Subtopic 5: Differentiation Techniques Exam Practice — D6 ─────────────────
const examD6: TopicTestQuestion[] = [
  { id: "y12a-c2-ex-d6-1", prompt: "Consider y = x eˣ.", latex: "y = xe^x", marks: 6, difficulty: 6,
    explanation: "Product-rule derivative, stationary point, classification, and exact value.",
    parts: [
      { key: "a", label: "(a)", prompt: "Find dy/dx at x = 0.", marks: 1, answer: "1", explanation: "dy/dx = (1 + x)eˣ; at 0, 1." },
      { key: "b", label: "(b)", prompt: "Find the x-coordinate of the stationary point.", marks: 2, answer: "-1", acceptedAnswers: ["−1"], explanation: "(1 + x)eˣ = 0 ⇒ x = −1." },
      { key: "c", label: "(c)", prompt: "Classify it (minimum or maximum).", marks: 2, answer: "minimum", acceptedAnswers: ["min"], explanation: "dy/dx goes − to + at x = −1, so a local minimum." },
      { key: "d", label: "(d)", prompt: "Find the y-value there (exact form).", marks: 1, answer: "-1/e", acceptedAnswers: ["−1/e", "-e^(-1)", "-0.368"], explanation: "y(−1) = −e^{−1} = −1/e." },
    ] },
  { id: "y12a-c2-ex-d6-2", prompt: "Consider y = x² − 2 ln x (x > 0).", latex: "y = x^2 - 2\\ln x", marks: 6, difficulty: 6,
    explanation: "Derivative, stationary point, value, and classification.",
    parts: [
      { key: "a", label: "(a)", prompt: "Find dy/dx at x = 2.", marks: 2, answer: "3", explanation: "dy/dx = 2x − 2/x; at 2, 4 − 1 = 3." },
      { key: "b", label: "(b)", prompt: "Find the stationary point's x-coordinate (x > 0).", marks: 2, answer: "1", explanation: "2x − 2/x = 0 ⇒ x² = 1 ⇒ x = 1." },
      { key: "c", label: "(c)", prompt: "Find the y-value there.", marks: 1, answer: "1", explanation: "y(1) = 1 − 2 ln 1 = 1." },
      { key: "d", label: "(d)", prompt: "Classify it (minimum or maximum).", marks: 1, answer: "minimum", acceptedAnswers: ["min"], explanation: "y'' = 2 + 2/x² > 0, so a minimum." },
    ] },
  { id: "y12a-c2-ex-d6-3", prompt: "Consider y = x e^{−x}.", latex: "y = xe^{-x}", marks: 6, difficulty: 6,
    explanation: "Product/chain derivative, stationary point, max value, and a further derivative.",
    parts: [
      { key: "a", label: "(a)", prompt: "Find dy/dx at x = 0.", marks: 1, answer: "1", explanation: "dy/dx = (1 − x)e^{−x}; at 0, 1." },
      { key: "b", label: "(b)", prompt: "Find the stationary point's x-coordinate.", marks: 2, answer: "1", explanation: "(1 − x)e^{−x} = 0 ⇒ x = 1." },
      { key: "c", label: "(c)", prompt: "Find the maximum value (exact form).", marks: 2, answer: "1/e", acceptedAnswers: ["e^(-1)", "0.368", "0.3679"], explanation: "y(1) = e^{−1} = 1/e." },
      { key: "d", label: "(d)", prompt: "Find dy/dx at x = 2 (exact form).", marks: 1, answer: "-1/e^2", acceptedAnswers: ["−1/e²", "-e^(-2)", "-0.135"], explanation: "(1 − 2)e^{−2} = −e^{−2} = −1/e²." },
    ] },
  { id: "y12a-c2-ex-d6-4", prompt: "Consider y = (ln x)/x (x > 0).", latex: "y = \\tfrac{\\ln x}{x}", marks: 6, difficulty: 6,
    explanation: "Quotient-rule derivative, stationary point, max value, and a further derivative.",
    parts: [
      { key: "a", label: "(a)", prompt: "Find dy/dx at x = 1.", marks: 1, answer: "1", explanation: "dy/dx = (1 − ln x)/x²; at 1, 1." },
      { key: "b", label: "(b)", prompt: "Find the stationary point's x-coordinate (exact form).", marks: 2, answer: "e", acceptedAnswers: ["2.718", "2.7183"], explanation: "1 − ln x = 0 ⇒ x = e." },
      { key: "c", label: "(c)", prompt: "Find the maximum value (exact form).", marks: 2, answer: "1/e", acceptedAnswers: ["e^(-1)", "0.368", "0.3679"], explanation: "y(e) = (ln e)/e = 1/e." },
      { key: "d", label: "(d)", prompt: "Find dy/dx at x = e² (exact form).", marks: 1, answer: "-1/e^4", acceptedAnswers: ["−1/e⁴", "-e^(-4)", "-0.018"], explanation: "(1 − 2)/(e²)² = −1/e⁴." },
    ] },
];

export const differentialCalculusPool: TopicTestPool = {
  courseSlug: "year-12-advanced",
  courseTitle: "Year 12 Mathematics Advanced",
  topicSlug: "ma-c2-differential-calculus",
  topicTitle: "Differential Calculus",
  subtopics: [
    {
      subtopicSlug: "standard-derivatives",
      subtopicTitle: "Standard Derivatives: Trig, Exponential and Logarithmic Functions",
      remediationHref: href("standard-derivatives"),
      d4: stdD4,
      d5: stdD5,
    },
    {
      subtopicSlug: "chain-rule",
      subtopicTitle: "The Chain Rule",
      remediationHref: href("chain-rule"),
      d4: chainD4,
      d5: chainD5,
    },
    {
      subtopicSlug: "product-quotient-rules",
      subtopicTitle: "Product and Quotient Rules",
      remediationHref: href("product-quotient-rules"),
      d4: pqD4,
      d5: pqD5,
    },
    {
      subtopicSlug: "applications-extended-differentiation",
      subtopicTitle: "Applications with Extended Differentiation",
      remediationHref: href("applications-extended-differentiation"),
      d4: appD4,
      d5: appD5,
    },
    {
      subtopicSlug: "differentiation-techniques-exam-practice",
      subtopicTitle: "Differentiation Techniques Exam Practice",
      remediationHref: href("differentiation-techniques-exam-practice"),
      d4: [],
      d5: [],
      d6: examD6,
    },
  ],
};
