import type { TopicTestPool, TopicTestQuestion } from "../../types";

/**
 * Topic-test pool — Year 12 Mathematics Advanced · Introduction to Differentiation
 * (NESA MA-C1). This is the legacy/canonical Y12 Advanced course (routed under
 * /course/year-12-advanced/<unit>/<lesson>, outside the new catalog).
 *
 * Seven skill subtopics (D4 + D5), all auto-markable per
 * docs/QUESTION_AUTHORING_STANDARD.md. No exam-practice lesson in this unit; a D6
 * synoptic band is attached to the final subtopic (precedent: inverse-trig).
 *
 * Status: subtopic 1 "The Derivative as Rate of Change" — D4 + D5. Remaining
 * subtopics to follow. Not yet registered in index.ts (register once complete).
 */

const href = (lesson: string) =>
  `/course/year-12-advanced/ma-c1-introduction-to-differentiation/${lesson}`;

// ── Subtopic 1: The Derivative as Rate of Change ─────────────────────────────
// Average vs instantaneous rate, evaluating f'(x), interpreting the sign.
const rocD4: TopicTestQuestion[] = [
  {
    id: "y12a-c1-roc-d4-1",
    prompt: "Find the average rate of change of f(x) = x² from x = 1 to x = 3.",
    latex: "f(x) = x^2",
    marks: 2,
    difficulty: 4,
    choices: [
      { label: "A", text: "$4$" },
      { label: "B", text: "$2$" },
      { label: "C", text: "$8$" },
      { label: "D", text: "$5$" },
    ],
    answer: "A",
    explanation:
      "(f(3) − f(1))/(3 − 1) = (9 − 1)/2 = 4. C forgets to divide by the change in x.",
  },
  {
    id: "y12a-c1-roc-d4-2",
    prompt: "For f(x) = x², find the instantaneous rate of change at x = 3.",
    latex: "f(x) = x^2",
    marks: 2,
    difficulty: 4,
    choices: [
      { label: "A", text: "$6$" },
      { label: "B", text: "$9$" },
      { label: "C", text: "$4$" },
      { label: "D", text: "$3$" },
    ],
    answer: "A",
    explanation: "f'(x) = 2x, so f'(3) = 6. B gives f(3) instead of f'(3).",
  },
  {
    id: "y12a-c1-roc-d4-3",
    prompt: "For f(x) = x² − 4x, find the instantaneous rate of change at x = 5.",
    latex: "f(x) = x^2 - 4x",
    marks: 2,
    difficulty: 4,
    answer: "6",
    explanation: "f'(x) = 2x − 4, so f'(5) = 6.",
  },
  {
    id: "y12a-c1-roc-d4-4",
    prompt: "Find the average rate of change of f(x) = x³ from x = 0 to x = 2.",
    latex: "f(x) = x^3",
    marks: 2,
    difficulty: 4,
    answer: "4",
    explanation: "(8 − 0)/(2 − 0) = 4.",
  },
  {
    id: "y12a-c1-roc-d4-5",
    prompt: "For f(x) = 3x² + 2x, find f'(1).",
    latex: "f(x) = 3x^2 + 2x",
    marks: 2,
    difficulty: 4,
    answer: "8",
    explanation: "f'(x) = 6x + 2, so f'(1) = 8.",
  },
  {
    id: "y12a-c1-roc-d4-6",
    prompt:
      "For f(x) with f'(x) = 2x − 6, is the sign of the rate of change at x = 2 positive or negative?",
    latex: "f'(x) = 2x - 6",
    marks: 2,
    difficulty: 4,
    answer: "negative",
    acceptedAnswers: ["-ve", "neg"],
    explanation: "f'(2) = 2(2) − 6 = −2 < 0, so the rate is negative (f is decreasing there).",
  },
  {
    id: "y12a-c1-roc-d4-7",
    prompt: "For f(x) = x² − 6x, find the value of x where the instantaneous rate of change is 0.",
    latex: "f(x) = x^2 - 6x",
    marks: 3,
    difficulty: 4,
    answer: "3",
    explanation: "f'(x) = 2x − 6 = 0 ⇒ x = 3.",
  },
  {
    id: "y12a-c1-roc-d4-8",
    prompt: "Find the average rate of change of f(x) = 2x² + 1 from x = 1 to x = 4.",
    latex: "f(x) = 2x^2 + 1",
    marks: 3,
    difficulty: 4,
    answer: "10",
    explanation: "(f(4) − f(1))/(4 − 1) = (33 − 3)/3 = 10.",
  },
  {
    id: "y12a-c1-roc-d4-9",
    prompt: "Find the gradient of the tangent to y = x² at x = 4.",
    latex: "y = x^2",
    marks: 2,
    difficulty: 4,
    answer: "8",
    explanation: "dy/dx = 2x, so at x = 4 the gradient is 8.",
  },
  {
    id: "y12a-c1-roc-d4-10",
    prompt: "If f'(4) = −2, is f increasing or decreasing at x = 4? Answer 'increasing' or 'decreasing'.",
    latex: "f'(4) = -2",
    marks: 2,
    difficulty: 4,
    answer: "decreasing",
    acceptedAnswers: ["it is decreasing", "decreasing at x=4"],
    explanation: "A negative derivative means the function is decreasing at that point.",
  },
];

// D5: difference quotient / first principles, solving rate conditions, recovering
// a coefficient from a rate, and an MVT-style comparison.
const rocD5: TopicTestQuestion[] = [
  {
    id: "y12a-c1-roc-d5-1",
    prompt:
      "For f(x) = x², the average rate of change from x = 2 to x = 2 + h simplifies to 4 + h. Find it when h = 0.5.",
    latex: "\\tfrac{f(2+h) - f(2)}{h} = 4 + h",
    marks: 4,
    difficulty: 5,
    answer: "4.5",
    acceptedAnswers: ["9/2"],
    explanation: "((2.5)² − 4)/0.5 = (6.25 − 4)/0.5 = 4.5 = 4 + 0.5.",
  },
  {
    id: "y12a-c1-roc-d5-2",
    prompt:
      "Evaluate lim(h→0) [f(2+h) − f(2)]/h for f(x) = x² (the derivative at x = 2).",
    latex: "\\lim_{h\\to 0} \\tfrac{f(2+h)-f(2)}{h}",
    marks: 4,
    difficulty: 5,
    answer: "4",
    explanation: "The limit is f'(2) = 2(2) = 4 (the difference quotient 4 + h → 4).",
  },
  {
    id: "y12a-c1-roc-d5-3",
    prompt: "For f(x) = x³ − 12x, find the positive x at which the instantaneous rate of change is 0.",
    latex: "f(x) = x^3 - 12x",
    marks: 4,
    difficulty: 5,
    answer: "2",
    explanation: "f'(x) = 3x² − 12 = 0 ⇒ x² = 4 ⇒ x = 2 (positive).",
  },
  {
    id: "y12a-c1-roc-d5-4",
    prompt: "The average rate of change of f(x) = x² over [a, a + 2] equals 10. Find a.",
    latex: "\\tfrac{f(a+2) - f(a)}{2} = 10",
    marks: 4,
    difficulty: 5,
    answer: "4",
    explanation: "((a+2)² − a²)/2 = (4a + 4)/2 = 2a + 2 = 10 ⇒ a = 4.",
  },
  {
    id: "y12a-c1-roc-d5-5",
    prompt: "A particle has position s(t) = t² − 4t. Find the time when its velocity (instantaneous rate) is 0.",
    latex: "s(t) = t^2 - 4t",
    marks: 3,
    difficulty: 5,
    answer: "2",
    explanation: "s'(t) = 2t − 4 = 0 ⇒ t = 2.",
  },
  {
    id: "y12a-c1-roc-d5-6",
    prompt:
      "For f(x) = x² on [1, 3], find the value c where the instantaneous rate equals the average rate over [1, 3].",
    latex: "f'(c) = \\tfrac{f(3)-f(1)}{2}",
    marks: 4,
    difficulty: 5,
    answer: "2",
    explanation: "Average rate = 4; f'(c) = 2c = 4 ⇒ c = 2.",
  },
  {
    id: "y12a-c1-roc-d5-7",
    prompt: "For f(x) = x² + bx, the instantaneous rate of change at x = 2 is 7. Find b.",
    latex: "f(x) = x^2 + bx, \\ f'(2) = 7",
    marks: 4,
    difficulty: 5,
    answer: "3",
    explanation: "f'(x) = 2x + b, so f'(2) = 4 + b = 7 ⇒ b = 3.",
  },
  {
    id: "y12a-c1-roc-d5-8",
    prompt: "For f(x) = ax², the instantaneous rate of change at x = 3 is 12. Find a.",
    latex: "f(x) = ax^2, \\ f'(3) = 12",
    marks: 3,
    difficulty: 5,
    answer: "2",
    explanation: "f'(x) = 2ax, so f'(3) = 6a = 12 ⇒ a = 2.",
  },
  {
    id: "y12a-c1-roc-d5-9",
    prompt:
      "For f(x) = x³, how many times larger is the instantaneous rate of change at x = 2 than at x = 1?",
    latex: "f(x) = x^3",
    marks: 4,
    difficulty: 5,
    answer: "4",
    explanation: "f'(x) = 3x²; f'(2)/f'(1) = 12/3 = 4.",
  },
  {
    id: "y12a-c1-roc-d5-10",
    prompt: "Find the average rate of change of f(x) = √x from x = 1 to x = 4 (exact fraction).",
    latex: "f(x) = \\sqrt{x}",
    marks: 4,
    difficulty: 5,
    answer: "1/3",
    acceptedAnswers: ["0.333", "0.3333"],
    explanation: "(√4 − √1)/(4 − 1) = (2 − 1)/3 = 1/3.",
  },
];

// ── Subtopic 2: Differentiating Polynomial Terms ─────────────────────────────
// Power rule on single terms, incl. negative/fractional powers and constants.
const termsD4: TopicTestQuestion[] = [
  { id: "y12a-c1-terms-d4-1", prompt: "For f(x) = x⁵, find f'(1).", latex: "f(x) = x^5", marks: 2, difficulty: 4,
    answer: "5", explanation: "f'(x) = 5x⁴, so f'(1) = 5." },
  { id: "y12a-c1-terms-d4-2", prompt: "For f(x) = 3x⁴, find f'(1).", latex: "f(x) = 3x^4", marks: 2, difficulty: 4,
    answer: "12", explanation: "f'(x) = 12x³, so f'(1) = 12." },
  { id: "y12a-c1-terms-d4-3", prompt: "For f(x) = x⁵, find f'(2).", latex: "f(x) = x^5", marks: 2, difficulty: 4,
    answer: "80", explanation: "f'(x) = 5x⁴, so f'(2) = 5(16) = 80." },
  { id: "y12a-c1-terms-d4-4", prompt: "For f(x) = 7x, find f'(x).", latex: "f(x) = 7x", marks: 2, difficulty: 4,
    choices: [ { label: "A", text: "$7$" }, { label: "B", text: "$7x$" }, { label: "C", text: "$0$" }, { label: "D", text: "$1$" } ],
    answer: "A", explanation: "The derivative of 7x is the constant 7. B fails to differentiate." },
  { id: "y12a-c1-terms-d4-5", prompt: "For f(x) = −2x³, find f'(1).", latex: "f(x) = -2x^3", marks: 2, difficulty: 4,
    answer: "-6", acceptedAnswers: ["−6"], explanation: "f'(x) = −6x², so f'(1) = −6." },
  { id: "y12a-c1-terms-d4-6", prompt: "For f(x) = x⁻², find f'(1).", latex: "f(x) = x^{-2}", marks: 3, difficulty: 4,
    answer: "-2", acceptedAnswers: ["−2"], explanation: "f'(x) = −2x⁻³, so f'(1) = −2." },
  { id: "y12a-c1-terms-d4-7", prompt: "For f(x) = √x, find f'(4) (exact fraction).", latex: "f(x) = \\sqrt{x}", marks: 3, difficulty: 4,
    answer: "1/4", acceptedAnswers: ["0.25"], explanation: "f(x) = x^{1/2}, f'(x) = ½x^{-1/2} = 1/(2√x); f'(4) = 1/4." },
  { id: "y12a-c1-terms-d4-8", prompt: "For f(x) = 4x², find f'(3).", latex: "f(x) = 4x^2", marks: 2, difficulty: 4,
    answer: "24", explanation: "f'(x) = 8x, so f'(3) = 24." },
  { id: "y12a-c1-terms-d4-9", prompt: "For f(x) = 6x^{1/3}, find f'(8) (exact fraction).", latex: "f(x) = 6x^{1/3}", marks: 3, difficulty: 4,
    answer: "1/2", acceptedAnswers: ["0.5"], explanation: "f'(x) = 2x^{-2/3}; f'(8) = 2/8^{2/3} = 2/4 = 1/2." },
  { id: "y12a-c1-terms-d4-10", prompt: "For f(x) = 5, find f'(x).", latex: "f(x) = 5", marks: 2, difficulty: 4,
    choices: [ { label: "A", text: "$0$" }, { label: "B", text: "$5$" }, { label: "C", text: "$5x$" }, { label: "D", text: "$1$" } ],
    answer: "A", explanation: "The derivative of a constant is 0. B leaves it unchanged." },
];
const termsD5: TopicTestQuestion[] = [
  { id: "y12a-c1-terms-d5-1", prompt: "For f(x) = 1/x, find f'(2) (exact fraction).", latex: "f(x) = \\tfrac{1}{x}", marks: 3, difficulty: 5,
    answer: "-1/4", acceptedAnswers: ["−1/4", "-0.25"], explanation: "f(x) = x⁻¹, f'(x) = −x⁻² = −1/x²; f'(2) = −1/4." },
  { id: "y12a-c1-terms-d5-2", prompt: "For f(x) = 1/x³, find f'(1).", latex: "f(x) = \\tfrac{1}{x^3}", marks: 3, difficulty: 5,
    answer: "-3", acceptedAnswers: ["−3"], explanation: "f(x) = x⁻³, f'(x) = −3x⁻⁴; f'(1) = −3." },
  { id: "y12a-c1-terms-d5-3", prompt: "For f(x) = xⁿ, f'(1) = 6. Find n.", latex: "f(x) = x^n, \\ f'(1) = 6", marks: 4, difficulty: 5,
    answer: "6", explanation: "f'(x) = nx^{n-1}, so f'(1) = n = 6." },
  { id: "y12a-c1-terms-d5-4", prompt: "For f(x) = ax³, f'(2) = 36. Find a.", latex: "f(x) = ax^3, \\ f'(2) = 36", marks: 4, difficulty: 5,
    answer: "3", explanation: "f'(x) = 3ax²; f'(2) = 12a = 36 ⇒ a = 3." },
  { id: "y12a-c1-terms-d5-5", prompt: "Rewrite f(x) = x²√x as a power and find f'(4).", latex: "f(x) = x^2\\sqrt{x}", marks: 4, difficulty: 5,
    answer: "20", explanation: "f(x) = x^{5/2}, f'(x) = (5/2)x^{3/2}; f'(4) = (5/2)(8) = 20." },
  { id: "y12a-c1-terms-d5-6", prompt: "For f(x) = x⁴, find f''(1) (the second derivative at x = 1).", latex: "f(x) = x^4", marks: 4, difficulty: 5,
    answer: "12", explanation: "f'(x) = 4x³, f''(x) = 12x²; f''(1) = 12." },
  { id: "y12a-c1-terms-d5-7", prompt: "For f(x) = 2/√x, find f'(4) (exact fraction).", latex: "f(x) = \\tfrac{2}{\\sqrt{x}}", marks: 4, difficulty: 5,
    answer: "-1/8", acceptedAnswers: ["−1/8", "-0.125"], explanation: "f(x) = 2x^{-1/2}, f'(x) = −x^{-3/2}; f'(4) = −1/8." },
  { id: "y12a-c1-terms-d5-8", prompt: "For f(x) = x³/3, find f'(3).", latex: "f(x) = \\tfrac{x^3}{3}", marks: 3, difficulty: 5,
    answer: "9", explanation: "f'(x) = x²; f'(3) = 9." },
  { id: "y12a-c1-terms-d5-9", prompt: "Find the positive x where d/dx[x²] = d/dx[2x³].", latex: "\\tfrac{d}{dx}x^2 = \\tfrac{d}{dx}2x^3", marks: 4, difficulty: 5,
    answer: "1/3", acceptedAnswers: ["0.333", "0.3333"], explanation: "2x = 6x² ⇒ 6x² − 2x = 0 ⇒ 2x(3x − 1) = 0 ⇒ x = 1/3." },
  { id: "y12a-c1-terms-d5-10", prompt: "For f(x) = x^{3/2}, find f'(9) (exact fraction).", latex: "f(x) = x^{3/2}", marks: 3, difficulty: 5,
    answer: "9/2", acceptedAnswers: ["4.5"], explanation: "f'(x) = (3/2)x^{1/2}; f'(9) = (3/2)(3) = 9/2." },
];

// ── Subtopic 3: Differentiating Polynomial Functions ─────────────────────────
const polyD4: TopicTestQuestion[] = [
  { id: "y12a-c1-poly-d4-1", prompt: "For f(x) = x² + 3x, find f'(1).", latex: "f(x) = x^2 + 3x", marks: 2, difficulty: 4,
    answer: "5", explanation: "f'(x) = 2x + 3; f'(1) = 5." },
  { id: "y12a-c1-poly-d4-2", prompt: "For f(x) = x³ − 2x² + x, find f'(1).", latex: "f(x) = x^3 - 2x^2 + x", marks: 3, difficulty: 4,
    answer: "0", explanation: "f'(x) = 3x² − 4x + 1; f'(1) = 3 − 4 + 1 = 0." },
  { id: "y12a-c1-poly-d4-3", prompt: "For f(x) = 2x³ + x, find f'(2).", latex: "f(x) = 2x^3 + x", marks: 2, difficulty: 4,
    answer: "25", explanation: "f'(x) = 6x² + 1; f'(2) = 24 + 1 = 25." },
  { id: "y12a-c1-poly-d4-4", prompt: "For f(x) = x² − 5x + 6, find f'(0).", latex: "f(x) = x^2 - 5x + 6", marks: 2, difficulty: 4,
    choices: [ { label: "A", text: "$-5$" }, { label: "B", text: "$6$" }, { label: "C", text: "$1$" }, { label: "D", text: "$0$" } ],
    answer: "A", explanation: "f'(x) = 2x − 5; f'(0) = −5. B differentiates the constant wrongly." },
  { id: "y12a-c1-poly-d4-5", prompt: "For f(x) = 4x² − 3x, find f'(1).", latex: "f(x) = 4x^2 - 3x", marks: 2, difficulty: 4,
    answer: "5", explanation: "f'(x) = 8x − 3; f'(1) = 5." },
  { id: "y12a-c1-poly-d4-6", prompt: "For f(x) = x⁴, find f'(1).", latex: "f(x) = x^4", marks: 2, difficulty: 4,
    answer: "4", explanation: "f'(x) = 4x³; f'(1) = 4." },
  { id: "y12a-c1-poly-d4-7", prompt: "For f(x) = x³ + x² + x + 1, find f'(1).", latex: "f(x) = x^3 + x^2 + x + 1", marks: 3, difficulty: 4,
    answer: "6", explanation: "f'(x) = 3x² + 2x + 1; f'(1) = 6." },
  { id: "y12a-c1-poly-d4-8", prompt: "For f(x) = 5x² + 2x − 7, find f'(2).", latex: "f(x) = 5x^2 + 2x - 7", marks: 2, difficulty: 4,
    answer: "22", explanation: "f'(x) = 10x + 2; f'(2) = 22." },
  { id: "y12a-c1-poly-d4-9", prompt: "For f(x) = (x + 1)(x + 2), find f'(0).", latex: "f(x) = (x+1)(x+2)", marks: 3, difficulty: 4,
    choices: [ { label: "A", text: "$3$" }, { label: "B", text: "$2$" }, { label: "C", text: "$0$" }, { label: "D", text: "$5$" } ],
    answer: "A", explanation: "Expand: x² + 3x + 2, f'(x) = 2x + 3; f'(0) = 3. B differentiates only one factor." },
  { id: "y12a-c1-poly-d4-10", prompt: "For f(x) = x³ − 3x, find f'(2).", latex: "f(x) = x^3 - 3x", marks: 2, difficulty: 4,
    answer: "9", explanation: "f'(x) = 3x² − 3; f'(2) = 12 − 3 = 9." },
];
const polyD5: TopicTestQuestion[] = [
  { id: "y12a-c1-poly-d5-1", prompt: "Find x where d/dx[x² − 6x + 5] = 0.", latex: "f(x) = x^2 - 6x + 5", marks: 3, difficulty: 5,
    answer: "3", explanation: "f'(x) = 2x − 6 = 0 ⇒ x = 3." },
  { id: "y12a-c1-poly-d5-2", prompt: "Find the positive x where d/dx[x³ − 3x²] = 0.", latex: "f(x) = x^3 - 3x^2", marks: 4, difficulty: 5,
    answer: "2", explanation: "f'(x) = 3x² − 6x = 3x(x − 2) = 0 ⇒ x = 0 or 2; positive is 2." },
  { id: "y12a-c1-poly-d5-3", prompt: "For f(x) = x³ + ax, f'(1) = 5. Find a.", latex: "f(x) = x^3 + ax, \\ f'(1) = 5", marks: 4, difficulty: 5,
    answer: "2", explanation: "f'(x) = 3x² + a; f'(1) = 3 + a = 5 ⇒ a = 2." },
  { id: "y12a-c1-poly-d5-4", prompt: "For f(x) = x⁴ − 2x³, find f''(1).", latex: "f(x) = x^4 - 2x^3", marks: 4, difficulty: 5,
    answer: "0", explanation: "f'(x) = 4x³ − 6x², f''(x) = 12x² − 12x; f''(1) = 0." },
  { id: "y12a-c1-poly-d5-5", prompt: "For f(x) = (2x − 1)², find f'(1).", latex: "f(x) = (2x-1)^2", marks: 4, difficulty: 5,
    answer: "4", explanation: "Expand: 4x² − 4x + 1, f'(x) = 8x − 4; f'(1) = 4." },
  { id: "y12a-c1-poly-d5-6", prompt: "For f(x) = x³, find the positive x where f'(x) = 27.", latex: "f(x) = x^3, \\ f'(x) = 27", marks: 4, difficulty: 5,
    answer: "3", explanation: "f'(x) = 3x² = 27 ⇒ x² = 9 ⇒ x = 3." },
  { id: "y12a-c1-poly-d5-7", prompt: "Find the smaller x where d/dx[x³ − 6x² + 9x] = 0.", latex: "f(x) = x^3 - 6x^2 + 9x", marks: 4, difficulty: 5,
    answer: "1", explanation: "f'(x) = 3x² − 12x + 9 = 3(x − 1)(x − 3) = 0 ⇒ x = 1 or 3; smaller is 1." },
  { id: "y12a-c1-poly-d5-8", prompt: "For f(x) = x³/3 − x²/2, find f'(2).", latex: "f(x) = \\tfrac{x^3}{3} - \\tfrac{x^2}{2}", marks: 4, difficulty: 5,
    answer: "2", explanation: "f'(x) = x² − x; f'(2) = 4 − 2 = 2." },
  { id: "y12a-c1-poly-d5-9", prompt: "For f(x) = ax² + bx, f'(0) = 3 and f'(1) = 7. Find a.", latex: "f(x) = ax^2 + bx", marks: 4, difficulty: 5,
    answer: "2", explanation: "f'(x) = 2ax + b; f'(0) = b = 3; f'(1) = 2a + 3 = 7 ⇒ a = 2." },
  { id: "y12a-c1-poly-d5-10", prompt: "For f(x) = (x² + 1)(x − 1), find f'(1).", latex: "f(x) = (x^2+1)(x-1)", marks: 4, difficulty: 5,
    answer: "2", explanation: "Expand: x³ − x² + x − 1, f'(x) = 3x² − 2x + 1; f'(1) = 2." },
];

// ── Subtopic 4: Tangents and Normals ─────────────────────────────────────────
const tanNormD4: TopicTestQuestion[] = [
  { id: "y12a-c1-tan-d4-1", prompt: "Find the gradient of the tangent to y = x² at x = 2.", latex: "y = x^2", marks: 2, difficulty: 4,
    answer: "4", explanation: "dy/dx = 2x; at x = 2 the gradient is 4." },
  { id: "y12a-c1-tan-d4-2", prompt: "Find the y-coordinate of the point on y = x² where x = 3.", latex: "y = x^2", marks: 2, difficulty: 4,
    answer: "9", explanation: "y = 3² = 9." },
  { id: "y12a-c1-tan-d4-3", prompt: "The tangent to y = x² at x = 1 is y = 2x − 1. Find its y-intercept.", latex: "y = x^2 \\text{ at } x=1", marks: 3, difficulty: 4,
    answer: "-1", acceptedAnswers: ["−1"], explanation: "y = 2x − 1 meets the y-axis at y = −1." },
  { id: "y12a-c1-tan-d4-4", prompt: "The tangent to y = x² at x = 2 has gradient 4. Find the gradient of the normal there.", latex: "y = x^2 \\text{ at } x=2", marks: 3, difficulty: 4,
    choices: [ { label: "A", text: "$-\\tfrac{1}{4}$" }, { label: "B", text: "$4$" }, { label: "C", text: "$-4$" }, { label: "D", text: "$\\tfrac{1}{4}$" } ],
    answer: "A", explanation: "Normal gradient = −1/(tangent gradient) = −1/4. B repeats the tangent gradient." },
  { id: "y12a-c1-tan-d4-5", prompt: "Find the gradient of the tangent to y = x³ at x = 1.", latex: "y = x^3", marks: 2, difficulty: 4,
    answer: "3", explanation: "dy/dx = 3x²; at x = 1 the gradient is 3." },
  { id: "y12a-c1-tan-d4-6", prompt: "Find the gradient of the tangent to y = 2x² − 3x at x = 2.", latex: "y = 2x^2 - 3x", marks: 2, difficulty: 4,
    answer: "5", explanation: "dy/dx = 4x − 3; at x = 2 the gradient is 5." },
  { id: "y12a-c1-tan-d4-7", prompt: "The tangent to y = x² at x = 2 is y = 4x − 4. Find y on this tangent when x = 3.", latex: "y = 4x - 4", marks: 3, difficulty: 4,
    answer: "8", explanation: "y = 4(3) − 4 = 8." },
  { id: "y12a-c1-tan-d4-8", prompt: "The tangent to y = x³ at x = 1 has gradient 3. Find the gradient of the normal there.", latex: "y = x^3 \\text{ at } x=1", marks: 3, difficulty: 4,
    answer: "-1/3", acceptedAnswers: ["−1/3"], explanation: "Normal gradient = −1/3." },
  { id: "y12a-c1-tan-d4-9", prompt: "Find the x-value of the point on y = x² where the tangent has gradient 6.", latex: "y = x^2", marks: 3, difficulty: 4,
    answer: "3", explanation: "2x = 6 ⇒ x = 3." },
  { id: "y12a-c1-tan-d4-10", prompt: "Find the gradient of the tangent to y = x² + 1 at x = 0.", latex: "y = x^2 + 1", marks: 2, difficulty: 4,
    answer: "0", explanation: "dy/dx = 2x; at x = 0 the gradient is 0 (horizontal)." },
];
const tanNormD5: TopicTestQuestion[] = [
  { id: "y12a-c1-tan-d5-1", prompt: "The tangent to y = x² at x = a is parallel to y = 6x. Find a.", latex: "\\text{tangent} \\parallel y = 6x", marks: 4, difficulty: 5,
    answer: "3", explanation: "2a = 6 ⇒ a = 3." },
  { id: "y12a-c1-tan-d5-2", prompt: "For y = x³ − 3x, find the positive x where the tangent is horizontal.", latex: "y = x^3 - 3x", marks: 4, difficulty: 5,
    answer: "1", explanation: "dy/dx = 3x² − 3 = 0 ⇒ x = ±1; positive is 1." },
  { id: "y12a-c1-tan-d5-3", prompt: "The tangent to y = x² at x = 2 is y = 4x − 4. Find its x-intercept.", latex: "y = 4x - 4", marks: 4, difficulty: 5,
    answer: "1", explanation: "0 = 4x − 4 ⇒ x = 1." },
  { id: "y12a-c1-tan-d5-4", prompt: "The normal to y = x² at x = 1 is y − 1 = −½(x − 1). Find y on it when x = 3.", latex: "y - 1 = -\\tfrac{1}{2}(x-1)", marks: 4, difficulty: 5,
    answer: "0", explanation: "y = 1 − ½(3 − 1) = 1 − 1 = 0." },
  { id: "y12a-c1-tan-d5-5", prompt: "The curve y = x² + bx has tangent gradient 5 at x = 1. Find b.", latex: "y = x^2 + bx", marks: 4, difficulty: 5,
    answer: "3", explanation: "dy/dx = 2x + b; at x = 1, 2 + b = 5 ⇒ b = 3." },
  { id: "y12a-c1-tan-d5-6", prompt: "Find the gradient of the tangent to y = √x at x = 4 (exact fraction).", latex: "y = \\sqrt{x}", marks: 4, difficulty: 5,
    answer: "1/4", acceptedAnswers: ["0.25"], explanation: "dy/dx = 1/(2√x); at x = 4 it is 1/4." },
  { id: "y12a-c1-tan-d5-7", prompt: "The tangent to y = x³ at x = 2 is y − 8 = 12(x − 2). Find its y-intercept.", latex: "y - 8 = 12(x - 2)", marks: 4, difficulty: 5,
    answer: "-16", acceptedAnswers: ["−16"], explanation: "y = 8 + 12(0 − 2) = 8 − 24 = −16." },
  { id: "y12a-c1-tan-d5-8", prompt: "Find the x-value where y = x² − 4x has a horizontal tangent.", latex: "y = x^2 - 4x", marks: 3, difficulty: 5,
    answer: "2", explanation: "dy/dx = 2x − 4 = 0 ⇒ x = 2." },
  { id: "y12a-c1-tan-d5-9", prompt: "The normal to y = x² at x = 2 is y − 4 = −¼(x − 2). Find y on it when x = 6.", latex: "y - 4 = -\\tfrac{1}{4}(x-2)", marks: 4, difficulty: 5,
    answer: "3", explanation: "y = 4 − ¼(6 − 2) = 4 − 1 = 3." },
  { id: "y12a-c1-tan-d5-10", prompt: "Find the gradient of the tangent to y = x² at x = −1.", latex: "y = x^2", marks: 3, difficulty: 5,
    answer: "-2", acceptedAnswers: ["−2"], explanation: "dy/dx = 2x; at x = −1 the gradient is −2." },
];

// ── Subtopic 5: Stationary Points ────────────────────────────────────────────
const statD4: TopicTestQuestion[] = [
  { id: "y12a-c1-stat-d4-1", prompt: "Find the x-coordinate of the stationary point of y = x² − 4x.", latex: "y = x^2 - 4x", marks: 2, difficulty: 4,
    answer: "2", explanation: "dy/dx = 2x − 4 = 0 ⇒ x = 2." },
  { id: "y12a-c1-stat-d4-2", prompt: "Find the y-coordinate of the stationary point of y = x² − 4x.", latex: "y = x^2 - 4x", marks: 3, difficulty: 4,
    answer: "-4", acceptedAnswers: ["−4"], explanation: "At x = 2, y = 4 − 8 = −4." },
  { id: "y12a-c1-stat-d4-3", prompt: "Find the positive stationary-point x-value of y = x³ − 3x.", latex: "y = x^3 - 3x", marks: 3, difficulty: 4,
    answer: "1", explanation: "dy/dx = 3x² − 3 = 0 ⇒ x = ±1; positive is 1." },
  { id: "y12a-c1-stat-d4-4", prompt: "Find the x-coordinate of the stationary point of y = x² + 6x + 5.", latex: "y = x^2 + 6x + 5", marks: 2, difficulty: 4,
    answer: "-3", acceptedAnswers: ["−3"], explanation: "dy/dx = 2x + 6 = 0 ⇒ x = −3." },
  { id: "y12a-c1-stat-d4-5", prompt: "Find the positive stationary-point x-value of y = x³ − 12x.", latex: "y = x^3 - 12x", marks: 3, difficulty: 4,
    answer: "2", explanation: "dy/dx = 3x² − 12 = 0 ⇒ x = ±2; positive is 2." },
  { id: "y12a-c1-stat-d4-6", prompt: "Find the x-coordinate of the stationary point of y = 2x² − 8x + 1.", latex: "y = 2x^2 - 8x + 1", marks: 2, difficulty: 4,
    answer: "2", explanation: "dy/dx = 4x − 8 = 0 ⇒ x = 2." },
  { id: "y12a-c1-stat-d4-7", prompt: "The stationary point of y = x² − 4x is a minimum or maximum? Answer 'minimum' or 'maximum'.", latex: "y = x^2 - 4x", marks: 2, difficulty: 4,
    answer: "minimum", acceptedAnswers: ["min"], explanation: "The parabola opens upward, so the stationary point is a minimum." },
  { id: "y12a-c1-stat-d4-8", prompt: "Find the x-coordinate of the stationary point of y = −x² + 2x.", latex: "y = -x^2 + 2x", marks: 2, difficulty: 4,
    answer: "1", explanation: "dy/dx = −2x + 2 = 0 ⇒ x = 1." },
  { id: "y12a-c1-stat-d4-9", prompt: "Find the non-zero stationary-point x-value of y = x³ − 3x².", latex: "y = x^3 - 3x^2", marks: 3, difficulty: 4,
    answer: "2", explanation: "dy/dx = 3x² − 6x = 3x(x − 2) = 0 ⇒ x = 0 or 2; non-zero is 2." },
  { id: "y12a-c1-stat-d4-10", prompt: "How many stationary points does y = x³ − 3x have?", latex: "y = x^3 - 3x", marks: 2, difficulty: 4,
    answer: "2", explanation: "dy/dx = 3x² − 3 = 0 has two solutions x = ±1, so two stationary points." },
];
const statD5: TopicTestQuestion[] = [
  { id: "y12a-c1-stat-d5-1", prompt: "Find the smaller stationary-point x-value of y = x³ − 6x² + 9x.", latex: "y = x^3 - 6x^2 + 9x", marks: 4, difficulty: 5,
    answer: "1", explanation: "dy/dx = 3x² − 12x + 9 = 3(x − 1)(x − 3) = 0 ⇒ x = 1 or 3; smaller is 1." },
  { id: "y12a-c1-stat-d5-2", prompt: "Find the y-value at the local maximum of y = x³ − 3x (at x = −1).", latex: "y = x^3 - 3x", marks: 4, difficulty: 5,
    answer: "2", explanation: "At x = −1, y = −1 + 3 = 2." },
  { id: "y12a-c1-stat-d5-3", prompt: "y = x² + bx has a stationary point at x = 3. Find b.", latex: "y = x^2 + bx", marks: 4, difficulty: 5,
    answer: "-6", acceptedAnswers: ["−6"], explanation: "dy/dx = 2x + b = 0 at x = 3 ⇒ 6 + b = 0 ⇒ b = −6." },
  { id: "y12a-c1-stat-d5-4", prompt: "Find the positive non-zero stationary-point x-value of y = x⁴ − 2x².", latex: "y = x^4 - 2x^2", marks: 4, difficulty: 5,
    answer: "1", explanation: "dy/dx = 4x³ − 4x = 4x(x² − 1) = 0 ⇒ x = 0, ±1; positive is 1." },
  { id: "y12a-c1-stat-d5-5", prompt: "y = ax² − 12x has a stationary point at x = 3. Find a.", latex: "y = ax^2 - 12x", marks: 4, difficulty: 5,
    answer: "2", explanation: "dy/dx = 2ax − 12 = 0 at x = 3 ⇒ 6a = 12 ⇒ a = 2." },
  { id: "y12a-c1-stat-d5-6", prompt: "Find the y-value at the stationary point x = 2 of y = x³ − 3x² + 2.", latex: "y = x^3 - 3x^2 + 2", marks: 4, difficulty: 5,
    answer: "-2", acceptedAnswers: ["−2"], explanation: "y(2) = 8 − 12 + 2 = −2." },
  { id: "y12a-c1-stat-d5-7", prompt: "y = x³ + px has a stationary point at x = 2. Find p.", latex: "y = x^3 + px", marks: 4, difficulty: 5,
    answer: "-12", acceptedAnswers: ["−12"], explanation: "dy/dx = 3x² + p = 0 at x = 2 ⇒ 12 + p = 0 ⇒ p = −12." },
  { id: "y12a-c1-stat-d5-8", prompt: "Find the minimum value of y = x² − 6x + 11.", latex: "y = x^2 - 6x + 11", marks: 4, difficulty: 5,
    answer: "2", explanation: "Stationary at x = 3; y(3) = 9 − 18 + 11 = 2." },
  { id: "y12a-c1-stat-d5-9", prompt: "Find the positive stationary-point x-value of y = 12x − x³.", latex: "y = 12x - x^3", marks: 4, difficulty: 5,
    answer: "2", explanation: "dy/dx = 12 − 3x² = 0 ⇒ x² = 4 ⇒ x = 2 (positive)." },
  { id: "y12a-c1-stat-d5-10", prompt: "The stationary points of y = x³ − 3x are at x = ±1. Find the distance between their x-values.", latex: "y = x^3 - 3x", marks: 3, difficulty: 5,
    answer: "2", explanation: "From x = −1 to x = 1 is a distance of 2." },
];

// ── Subtopic 6: Increasing and Decreasing Functions ──────────────────────────
const incDecD4: TopicTestQuestion[] = [
  { id: "y12a-c1-incdec-d4-1", prompt: "For y = x² − 4x, f is increasing for x > k. Find k.", latex: "y = x^2 - 4x", marks: 2, difficulty: 4,
    answer: "2", explanation: "f'(x) = 2x − 4 > 0 ⇒ x > 2." },
  { id: "y12a-c1-incdec-d4-2", prompt: "If f'(x) = 2x − 6, f is increasing for x > k. Find k.", latex: "f'(x) = 2x - 6", marks: 2, difficulty: 4,
    answer: "3", explanation: "2x − 6 > 0 ⇒ x > 3." },
  { id: "y12a-c1-incdec-d4-3", prompt: "f(x) = x² is decreasing for x < k. Find k.", latex: "f(x) = x^2", marks: 2, difficulty: 4,
    answer: "0", explanation: "f'(x) = 2x < 0 ⇒ x < 0." },
  { id: "y12a-c1-incdec-d4-4", prompt: "If f'(x) = 3x² − 12, f is increasing for x > k (k > 0). Find k.", latex: "f'(x) = 3x^2 - 12", marks: 3, difficulty: 4,
    answer: "2", explanation: "3x² − 12 > 0 ⇒ x² > 4 ⇒ x > 2 (for the positive branch)." },
  { id: "y12a-c1-incdec-d4-5", prompt: "Is f(x) = x³ increasing or never-decreasing everywhere? Answer 'increasing'.", latex: "f(x) = x^3", marks: 2, difficulty: 4,
    answer: "increasing", acceptedAnswers: ["always increasing"], explanation: "f'(x) = 3x² ≥ 0, so f is increasing (non-decreasing) everywhere." },
  { id: "y12a-c1-incdec-d4-6", prompt: "For y = −x² + 4x, f is increasing for x < k. Find k.", latex: "y = -x^2 + 4x", marks: 3, difficulty: 4,
    answer: "2", explanation: "f'(x) = −2x + 4 > 0 ⇒ x < 2." },
  { id: "y12a-c1-incdec-d4-7", prompt: "If f'(x) = 2x − 6, is f increasing or decreasing at x = 5? Answer 'increasing' or 'decreasing'.", latex: "f'(x) = 2x - 6", marks: 2, difficulty: 4,
    answer: "increasing", explanation: "f'(5) = 4 > 0, so increasing." },
  { id: "y12a-c1-incdec-d4-8", prompt: "For f(x) = x² − 2x, find the x where it switches from decreasing to increasing.", latex: "f(x) = x^2 - 2x", marks: 2, difficulty: 4,
    answer: "1", explanation: "f'(x) = 2x − 2 = 0 ⇒ x = 1 (the turning point)." },
  { id: "y12a-c1-incdec-d4-9", prompt: "If f'(x) = (x − 1)(x − 3), f is decreasing on (1, 3). Find the left boundary.", latex: "f'(x) = (x-1)(x-3)", marks: 3, difficulty: 4,
    answer: "1", explanation: "f' < 0 between its roots 1 and 3; the left boundary is 1." },
  { id: "y12a-c1-incdec-d4-10", prompt: "For y = x³ − 3x, f is increasing for x > k (k > 0). Find k.", latex: "y = x^3 - 3x", marks: 3, difficulty: 4,
    answer: "1", explanation: "f'(x) = 3x² − 3 > 0 ⇒ x² > 1 ⇒ x > 1 (positive branch)." },
];
const incDecD5: TopicTestQuestion[] = [
  { id: "y12a-c1-incdec-d5-1", prompt: "f(x) = x³ − 3x is decreasing on (−1, 1). Find the length of this interval.", latex: "f(x) = x^3 - 3x", marks: 4, difficulty: 5,
    answer: "2", explanation: "From −1 to 1 the length is 2." },
  { id: "y12a-c1-incdec-d5-2", prompt: "f(x) = x³ − 6x² + 9x is decreasing between its turning points. Find the larger turning-point x.", latex: "f(x) = x^3 - 6x^2 + 9x", marks: 4, difficulty: 5,
    answer: "3", explanation: "f'(x) = 3(x − 1)(x − 3) = 0 ⇒ x = 1, 3; larger is 3." },
  { id: "y12a-c1-incdec-d5-3", prompt: "f(x) = x³ + ax is increasing everywhere for a ≥ k. Find the smallest such k.", latex: "f(x) = x^3 + ax", marks: 4, difficulty: 5,
    answer: "0", explanation: "f'(x) = 3x² + a ≥ 0 for all x requires a ≥ 0; smallest k = 0." },
  { id: "y12a-c1-incdec-d5-4", prompt: "If f'(x) = x² − 4, f is decreasing on (−2, 2). Find the right boundary.", latex: "f'(x) = x^2 - 4", marks: 4, difficulty: 5,
    answer: "2", explanation: "f' < 0 between roots ±2; the right boundary is 2." },
  { id: "y12a-c1-incdec-d5-5", prompt: "f(x) = 2x³ − 3x² is decreasing on (0, 1). Find the right endpoint.", latex: "f(x) = 2x^3 - 3x^2", marks: 4, difficulty: 5,
    answer: "1", explanation: "f'(x) = 6x² − 6x = 6x(x − 1) < 0 on (0, 1); right endpoint 1." },
  { id: "y12a-c1-incdec-d5-6", prompt: "f(x) = x² − 6x + k is increasing for x > m, for any k. Find m.", latex: "f(x) = x^2 - 6x + k", marks: 3, difficulty: 5,
    answer: "3", explanation: "f'(x) = 2x − 6 > 0 ⇒ x > 3 (independent of k)." },
  { id: "y12a-c1-incdec-d5-7", prompt: "f(x) = x⁴ − 2x² is increasing for x > p (p > 0). Find p.", latex: "f(x) = x^4 - 2x^2", marks: 4, difficulty: 5,
    answer: "1", explanation: "f'(x) = 4x³ − 4x = 4x(x² − 1); for x > 0, f' > 0 when x > 1." },
  { id: "y12a-c1-incdec-d5-8", prompt: "f(x) = (x − 2)² is decreasing for x < m. Find m.", latex: "f(x) = (x-2)^2", marks: 3, difficulty: 5,
    answer: "2", explanation: "f'(x) = 2(x − 2) < 0 ⇒ x < 2." },
  { id: "y12a-c1-incdec-d5-9", prompt: "If f'(x) = −(x − 1)(x − 5), f is increasing on (1, 5). Find the midpoint of that interval.", latex: "f'(x) = -(x-1)(x-5)", marks: 4, difficulty: 5,
    answer: "3", explanation: "Midpoint of (1, 5) is 3 (where f' is largest)." },
  { id: "y12a-c1-incdec-d5-10", prompt: "f(x) = x³ − 12x is decreasing on (−2, 2). Find the right endpoint.", latex: "f(x) = x^3 - 12x", marks: 4, difficulty: 5,
    answer: "2", explanation: "f'(x) = 3x² − 12 < 0 ⇒ x² < 4 ⇒ −2 < x < 2; right endpoint 2." },
];

// ── Subtopic 7: First Derivative Test (with a D6 synoptic band) ──────────────
const fdtD4: TopicTestQuestion[] = [
  { id: "y12a-c1-fdt-d4-1", prompt: "f'(x) = 2x − 4 changes from negative to positive at x = 2. Is x = 2 a minimum or maximum? Answer 'minimum' or 'maximum'.", latex: "f'(x) = 2x - 4", marks: 2, difficulty: 4,
    answer: "minimum", acceptedAnswers: ["min"], explanation: "f' goes − to +, so x = 2 is a local minimum." },
  { id: "y12a-c1-fdt-d4-2", prompt: "f'(x) = (x − 1)(x − 3). At x = 1, f' changes + to −. Minimum or maximum?", latex: "f'(x) = (x-1)(x-3)", marks: 3, difficulty: 4,
    answer: "maximum", acceptedAnswers: ["max"], explanation: "f' goes + to − at x = 1, so it is a local maximum." },
  { id: "y12a-c1-fdt-d4-3", prompt: "f'(x) = (x − 1)(x − 3). At x = 3, f' changes − to +. Minimum or maximum?", latex: "f'(x) = (x-1)(x-3)", marks: 3, difficulty: 4,
    answer: "minimum", acceptedAnswers: ["min"], explanation: "f' goes − to + at x = 3, so it is a local minimum." },
  { id: "y12a-c1-fdt-d4-4", prompt: "f(x) = x² − 6x has a stationary point at x = 3. Classify it (minimum or maximum).", latex: "f(x) = x^2 - 6x", marks: 2, difficulty: 4,
    answer: "minimum", acceptedAnswers: ["min"], explanation: "Upward parabola ⇒ minimum at x = 3." },
  { id: "y12a-c1-fdt-d4-5", prompt: "f(x) = −x² + 2x has a stationary point at x = 1. Classify it (minimum or maximum).", latex: "f(x) = -x^2 + 2x", marks: 2, difficulty: 4,
    answer: "maximum", acceptedAnswers: ["max"], explanation: "Downward parabola ⇒ maximum at x = 1." },
  { id: "y12a-c1-fdt-d4-6", prompt: "f'(x) = 3x² does not change sign at x = 0. Is x = 0 a max, min, or neither? Answer 'neither'.", latex: "f'(x) = 3x^2", marks: 3, difficulty: 4,
    answer: "neither", acceptedAnswers: ["inflection", "horizontal inflection"], explanation: "f' = 3x² ≥ 0 (no sign change), so x = 0 is neither a max nor a min (a horizontal point of inflection)." },
  { id: "y12a-c1-fdt-d4-7", prompt: "For f(x) = x³ − 3x, classify the stationary point at x = 1 (minimum or maximum).", latex: "f(x) = x^3 - 3x", marks: 3, difficulty: 4,
    answer: "minimum", acceptedAnswers: ["min"], explanation: "f'(x) = 3x² − 3 goes − to + at x = 1, so a local minimum." },
  { id: "y12a-c1-fdt-d4-8", prompt: "How many local maxima does a function with f'(x) = (x − 1)(x − 3) have?", latex: "f'(x) = (x-1)(x-3)", marks: 2, difficulty: 4,
    answer: "1", explanation: "Only at x = 1 does f' go + to − (one local maximum)." },
  { id: "y12a-c1-fdt-d4-9", prompt: "f'(x) = x(x − 2). At x = 0, f' changes + to −. Minimum or maximum?", latex: "f'(x) = x(x-2)", marks: 3, difficulty: 4,
    answer: "maximum", acceptedAnswers: ["max"], explanation: "f' goes + to − at x = 0, so a local maximum." },
  { id: "y12a-c1-fdt-d4-10", prompt: "f(x) = x² + 4x has a stationary point at x = −2. Classify it (minimum or maximum).", latex: "f(x) = x^2 + 4x", marks: 2, difficulty: 4,
    answer: "minimum", acceptedAnswers: ["min"], explanation: "Upward parabola ⇒ minimum at x = −2." },
];
const fdtD5: TopicTestQuestion[] = [
  { id: "y12a-c1-fdt-d5-1", prompt: "For f(x) = x³ − 6x² + 9x, classify the stationary point at x = 1 (minimum or maximum).", latex: "f(x) = x^3 - 6x^2 + 9x", marks: 4, difficulty: 5,
    answer: "maximum", acceptedAnswers: ["max"], explanation: "f'(x) = 3(x − 1)(x − 3) goes + to − at x = 1, so a local maximum." },
  { id: "y12a-c1-fdt-d5-2", prompt: "For f(x) = x³ − 6x² + 9x, classify the stationary point at x = 3 (minimum or maximum).", latex: "f(x) = x^3 - 6x^2 + 9x", marks: 4, difficulty: 5,
    answer: "minimum", acceptedAnswers: ["min"], explanation: "f' goes − to + at x = 3, so a local minimum." },
  { id: "y12a-c1-fdt-d5-3", prompt: "For f(x) = x³ − 3x², classify the stationary point at x = 0 (minimum or maximum).", latex: "f(x) = x^3 - 3x^2", marks: 4, difficulty: 5,
    answer: "maximum", acceptedAnswers: ["max"], explanation: "f'(x) = 3x(x − 2) goes + to − at x = 0, so a local maximum." },
  { id: "y12a-c1-fdt-d5-4", prompt: "For f(x) = 2x³ − 3x² − 12x, classify the stationary point at x = −1 (minimum or maximum).", latex: "f(x) = 2x^3 - 3x^2 - 12x", marks: 4, difficulty: 5,
    answer: "maximum", acceptedAnswers: ["max"], explanation: "f'(x) = 6(x − 2)(x + 1) goes + to − at x = −1, so a local maximum." },
  { id: "y12a-c1-fdt-d5-5", prompt: "For f(x) = x⁴ − 4x³, classify the stationary point at x = 0 (answer 'neither').", latex: "f(x) = x^4 - 4x^3", marks: 4, difficulty: 5,
    answer: "neither", acceptedAnswers: ["inflection", "horizontal inflection"], explanation: "f'(x) = 4x²(x − 3); the x² factor means no sign change at x = 0, so neither (a horizontal inflection)." },
  { id: "y12a-c1-fdt-d5-6", prompt: "For f(x) = x + 1/x (x > 0), classify the stationary point at x = 1 (minimum or maximum).", latex: "f(x) = x + \\tfrac{1}{x}", marks: 4, difficulty: 5,
    answer: "minimum", acceptedAnswers: ["min"], explanation: "f'(x) = 1 − 1/x² = 0 ⇒ x = 1; f' goes − to + there, so a local minimum." },
  { id: "y12a-c1-fdt-d5-7", prompt: "Find the local maximum value of f(x) = 3x − x³.", latex: "f(x) = 3x - x^3", marks: 4, difficulty: 5,
    answer: "2", explanation: "f'(x) = 3 − 3x² = 0 ⇒ x = 1 (max); f(1) = 3 − 1 = 2." },
  { id: "y12a-c1-fdt-d5-8", prompt: "Find the local minimum value of f(x) = x³ − 3x.", latex: "f(x) = x^3 - 3x", marks: 4, difficulty: 5,
    answer: "-2", acceptedAnswers: ["−2"], explanation: "Local min at x = 1; f(1) = 1 − 3 = −2." },
  { id: "y12a-c1-fdt-d5-9", prompt: "For f(x) = x³ − 3x² + 1, classify the stationary point at x = 2 (minimum or maximum).", latex: "f(x) = x^3 - 3x^2 + 1", marks: 4, difficulty: 5,
    answer: "minimum", acceptedAnswers: ["min"], explanation: "f'(x) = 3x² − 6x = 3x(x − 2) goes − to + at x = 2, so a local minimum." },
  { id: "y12a-c1-fdt-d5-10", prompt: "How many turning points does f(x) = x⁴ − 2x² have?", latex: "f(x) = x^4 - 2x^2", marks: 4, difficulty: 5,
    answer: "3", explanation: "f'(x) = 4x³ − 4x = 4x(x² − 1) = 0 ⇒ x = 0, ±1: three turning points." },
];
const fdtD6: TopicTestQuestion[] = [
  { id: "y12a-c1-fdt-d6-1", prompt: "Consider the curve y = x³ − 3x.", latex: "y = x^3 - 3x", marks: 6, difficulty: 6,
    explanation: "Stationary points, classification, a value, and a gradient.",
    parts: [
      { key: "a", label: "(a)", prompt: "Find the positive stationary-point x-value.", marks: 1, answer: "1", explanation: "3x² − 3 = 0 ⇒ x = ±1; positive is 1." },
      { key: "b", label: "(b)", prompt: "Classify the stationary point at x = 1 (minimum or maximum).", marks: 2, answer: "minimum", acceptedAnswers: ["min"], explanation: "f' goes − to + at x = 1, so a local minimum." },
      { key: "c", label: "(c)", prompt: "Find the local minimum value (y at x = 1).", marks: 2, answer: "-2", acceptedAnswers: ["−2"], explanation: "y(1) = 1 − 3 = −2." },
      { key: "d", label: "(d)", prompt: "Find the gradient of the curve at x = 2.", marks: 1, answer: "9", explanation: "dy/dx = 3x² − 3; at x = 2, 12 − 3 = 9." },
    ],
  },
  { id: "y12a-c1-fdt-d6-2", prompt: "Consider the curve y = x³ − 6x² + 9x.", latex: "y = x^3 - 6x^2 + 9x", marks: 6, difficulty: 6,
    explanation: "Stationary points, classification, the local max value, and concavity.",
    parts: [
      { key: "a", label: "(a)", prompt: "Find the smaller stationary-point x-value.", marks: 1, answer: "1", explanation: "3(x − 1)(x − 3) = 0 ⇒ x = 1 or 3; smaller is 1." },
      { key: "b", label: "(b)", prompt: "Classify the stationary point at x = 1 (minimum or maximum).", marks: 2, answer: "maximum", acceptedAnswers: ["max"], explanation: "f' goes + to − at x = 1, so a local maximum." },
      { key: "c", label: "(c)", prompt: "Find the local maximum value (y at x = 1).", marks: 2, answer: "4", explanation: "y(1) = 1 − 6 + 9 = 4." },
      { key: "d", label: "(d)", prompt: "Find f''(3) (the second derivative at x = 3).", marks: 1, answer: "6", explanation: "f''(x) = 6x − 12; f''(3) = 6." },
    ],
  },
];

export const introDifferentiationPool: TopicTestPool = {
  courseSlug: "year-12-advanced",
  courseTitle: "Year 12 Mathematics Advanced",
  topicSlug: "ma-c1-introduction-to-differentiation",
  topicTitle: "Introduction to Differentiation",
  subtopics: [
    {
      subtopicSlug: "rate-of-change",
      subtopicTitle: "The Derivative as Rate of Change",
      remediationHref: href("rate-of-change"),
      d4: rocD4,
      d5: rocD5,
    },
    {
      subtopicSlug: "differentiating-polynomial-terms",
      subtopicTitle: "Differentiating Polynomial Terms",
      remediationHref: href("differentiating-polynomial-terms"),
      d4: termsD4,
      d5: termsD5,
    },
    {
      subtopicSlug: "differentiating-polynomial-functions",
      subtopicTitle: "Differentiating Polynomial Functions",
      remediationHref: href("differentiating-polynomial-functions"),
      d4: polyD4,
      d5: polyD5,
    },
    {
      subtopicSlug: "tangents-and-normals",
      subtopicTitle: "Tangents and Normals",
      remediationHref: href("tangents-and-normals"),
      d4: tanNormD4,
      d5: tanNormD5,
    },
    {
      subtopicSlug: "stationary-points",
      subtopicTitle: "Stationary Points",
      remediationHref: href("stationary-points"),
      d4: statD4,
      d5: statD5,
    },
    {
      subtopicSlug: "increasing-decreasing-functions",
      subtopicTitle: "Increasing and Decreasing Functions",
      remediationHref: href("increasing-decreasing-functions"),
      d4: incDecD4,
      d5: incDecD5,
    },
    {
      subtopicSlug: "first-derivative-test",
      subtopicTitle: "First Derivative Test",
      remediationHref: href("first-derivative-test"),
      d4: fdtD4,
      d5: fdtD5,
      d6: fdtD6,
    },
  ],
};
