import type { DiagnosticData } from "./types";

export const diagnosticData: DiagnosticData = {
  yearLevelTitle: "Year 12 Mathematics Standard 1",

  units: [
    {
      slug: "algebraic-relationships",
      title: "Algebraic Relationships",
      startHref: "/course/year-12-standard-1/algebraic-relationships",
    },
    {
      slug: "trigonometry-ratios-rates",
      title: "Rates, Ratios and Unit Conversion",
      startHref: "/course/year-12-standard-1/trigonometry-ratios-rates",
    },
    {
      slug: "investments-loans-annuities",
      title: "Investments, Loans and Annuities",
      startHref: "/course/year-12-standard-1/investments-loans-annuities",
    },
  ],

  questions: [
    {
      id: "y12s1-ar1",
      unitSlug: "algebraic-relationships",
      prompt: "Solve $5x + 3 = 18$.",
      choices: [
        { label: "A", text: "$x = 2$" },
        { label: "B", text: "$x = 3$" },
        { label: "C", text: "$x = 4$" },
        { label: "D", text: "$x = 5$" },
      ],
      correctAnswer: "B",
      explanation: "$5x = 18 - 3 = 15$, so $x = 3$.",
    },
    {
      id: "y12s1-ar2",
      unitSlug: "algebraic-relationships",
      prompt: "The equation $y = 2x + 7$ models cost in dollars. What does the 7 represent?",
      choices: [
        { label: "A", text: "The rate per unit" },
        { label: "B", text: "The starting cost when x = 0" },
        { label: "C", text: "The number of units" },
        { label: "D", text: "The total profit" },
      ],
      correctAnswer: "B",
      explanation: "In $y = mx + b$, the intercept $b$ is the starting cost when $x = 0$.",
    },
    {
      id: "y12s1-ar3",
      unitSlug: "algebraic-relationships",
      prompt: "Which equation shows an inverse variation between x and y?",
      choices: [
        { label: "A", text: "$y = 4x + 1$" },
        { label: "B", text: "$y = \\frac{12}{x}$" },
        { label: "C", text: "$y = x^2 - 3$" },
        { label: "D", text: "$y = 3x - 5$" },
      ],
      correctAnswer: "B",
      explanation: "$y = \\frac{12}{x}$ is an inverse variation because y changes as the reciprocal of x.",
    },
    {
      id: "y12s1-ar4",
      unitSlug: "algebraic-relationships",
      prompt: "A taxi charges $4$ dollars flagfall plus $2$ dollars per kilometre. Which equation models the fare y for x kilometres?",
      choices: [
        { label: "A", text: "$y = 4x + 2$" },
        { label: "B", text: "$y = 2x + 4$" },
        { label: "C", text: "$y = 4 + 2x^2$" },
        { label: "D", text: "$y = 2 + 4x$" },
      ],
      correctAnswer: "B",
      explanation: "The rate is $2$ dollars per km and the starting cost is $4$, so $y = 2x + 4$.",
    },
    {
      id: "y12s1-ar5",
      unitSlug: "algebraic-relationships",
      prompt: "Find x when two plans are equal: Plan A is $100 + 15x$ and Plan B is $130 + 10x$.",
      choices: [
        { label: "A", text: "$x = 2$" },
        { label: "B", text: "$x = 3$" },
        { label: "C", text: "$x = 4$" },
        { label: "D", text: "$x = 6$" },
      ],
      correctAnswer: "D",
      explanation: "Solve $100 + 15x = 130 + 10x$ leads to $5x = 30$, so $x = 6$.",
    },
    {
      id: "y12s1-ar6",
      unitSlug: "algebraic-relationships",
      prompt: "Which graph is most likely a quadratic model?",
      choices: [
        { label: "A", text: "A straight line" },
        { label: "B", text: "A parabola" },
        { label: "C", text: "A hyperbola" },
        { label: "D", text: "A horizontal line" },
      ],
      correctAnswer: "B",
      explanation: "A quadratic model typically produces a parabola, not a straight line or hyperbola.",
    },
    {
      id: "y12s1-rr1",
      unitSlug: "trigonometry-ratios-rates",
      prompt: "A recipe uses a ratio of 2:5 sugar to flour. If 350 g of flour is used, how much sugar is needed?",
      choices: [
        { label: "A", text: "70 g" },
        { label: "B", text: "100 g" },
        { label: "C", text: "140 g" },
        { label: "D", text: "175 g" },
      ],
      correctAnswer: "C",
      explanation: "One part is 350 ÷ 5 = 70 g, so sugar is 2 × 70 = 140 g.",
    },
    {
      id: "y12s1-rr2",
      unitSlug: "trigonometry-ratios-rates",
      prompt: "A driver travels 90 km in 1 hour 30 minutes. What is the average speed in km/h?",
      choices: [
        { label: "A", text: "45" },
        { label: "B", text: "60" },
        { label: "C", text: "65" },
        { label: "D", text: "75" },
      ],
      correctAnswer: "B",
      explanation: "Time is 1.5 h, so speed = 90 ÷ 1.5 = 60 km/h.",
    },
    {
      id: "y12s1-rr3",
      unitSlug: "trigonometry-ratios-rates",
      prompt: "Convert 2.5 kilometres to metres.",
      choices: [
        { label: "A", text: "250 m" },
        { label: "B", text: "2500 m" },
        { label: "C", text: "25 000 m" },
        { label: "D", text: "250 000 m" },
      ],
      correctAnswer: "B",
      explanation: "1 km = 1000 m, so 2.5 km = 2.5 × 1000 = 2500 m.",
    },
    {
      id: "y12s1-rr4",
      unitSlug: "trigonometry-ratios-rates",
      prompt: "A map scale is 1:50 000. A 3 cm map distance represents how many kilometres in reality?",
      choices: [
        { label: "A", text: "1.5 km" },
        { label: "B", text: "15 km" },
        { label: "C", text: "150 km" },
        { label: "D", text: "0.15 km" },
      ],
      correctAnswer: "A",
      explanation: "3 cm × 50 000 = 150 000 cm = 1500 m = 1.5 km.",
    },
    {
      id: "y12s1-rr5",
      unitSlug: "trigonometry-ratios-rates",
      prompt: "Which is a rate rather than a ratio?",
      choices: [
        { label: "A", text: "3 apples to 5 oranges" },
        { label: "B", text: "5:8 in a class" },
        { label: "C", text: "60 km/h" },
        { label: "D", text: "7 to 2" },
      ],
      correctAnswer: "C",
      explanation: "60 km/h compares distance to time, so it is a rate.",
    },
    {
      id: "y12s1-il1",
      unitSlug: "investments-loans-annuities",
      prompt: "An investment of $2000 earns 5% compound interest annually for 2 years. The value at the end is closest to:",
      choices: [
        { label: "A", text: "$2100" },
        { label: "B", text: "$2205" },
        { label: "C", text: "$2310" },
        { label: "D", text: "$2400" },
      ],
      correctAnswer: "B",
      explanation: "$2000 × 1.05^2 = $2000 × 1.1025 ≈ $2205.",
    },
    {
      id: "y12s1-il2",
      unitSlug: "investments-loans-annuities",
      prompt: "A car value falls by 12% each year. If it is worth $20 000 now, what is the value after one year?",
      choices: [
        { label: "A", text: "$17 600" },
        { label: "B", text: "$18 400" },
        { label: "C", text: "$19 760" },
        { label: "D", text: "$22 400" },
      ],
      correctAnswer: "A",
      explanation: "Depreciation factor is 0.88, so $20 000 × 0.88 = $17 600.",
    },
    {
      id: "y12s1-il3",
      unitSlug: "investments-loans-annuities",
      prompt: "A loan repayment is $250 per month for 24 months. What is the total repaid?",
      choices: [
        { label: "A", text: "$4 500" },
        { label: "B", text: "$5 000" },
        { label: "C", text: "$6 000" },
        { label: "D", text: "$6 250" },
      ],
      correctAnswer: "C",
      explanation: "$250 × 24 = $6 000.$",
    },
    {
      id: "y12s1-il4",
      unitSlug: "investments-loans-annuities",
      prompt: "Which expression models compound interest for principal P, rate r and n years?",
      choices: [
        { label: "A", text: "$P(1 + rn)$" },
        { label: "B", text: "$P(1 + r)^n$" },
        { label: "C", text: "$Pr^n$" },
        { label: "D", text: "$P + rn$" },
      ],
      correctAnswer: "B",
      explanation: "Compound interest grows by multiplying by (1 + r) each year, giving $P(1 + r)^n$.",
    },
    {
      id: "y12s1-il5",
      unitSlug: "investments-loans-annuities",
      prompt: "If $500 is deposited each year into an account, this type of regular payment is called an:",
      choices: [
        { label: "A", text: "An annuity" },
        { label: "B", text: "A simple interest loan" },
        { label: "C", text: "A ratio" },
        { label: "D", text: "A depreciation" },
      ],
      correctAnswer: "A",
      explanation: "A sequence of equal regular deposits is called an annuity.",
    },
  ],
};
