import type { DiagnosticData } from "./types";

export const diagnosticData: DiagnosticData = {
  yearLevelTitle: "Year 8 Mathematics",

  units: [
    {
      slug: "number-operations",
      title: "Number Operations and Properties",
      startHref: "/course/year-8-mathematics/number-operations",
    },
    {
      slug: "algebra-equations",
      title: "Algebra and Equations",
      startHref: "/course/year-8-mathematics/algebra-equations",
    },
    {
      slug: "linear-relationships",
      title: "Linear Relationships",
      startHref: "/course/year-8-mathematics/linear-relationships",
    },
    {
      slug: "pythagoras-theorem",
      title: "Pythagoras' Theorem",
      startHref: "/course/year-8-mathematics/pythagoras-theorem",
    },
    {
      slug: "geometry-properties",
      title: "Geometric Properties and Reasoning",
      startHref: "/course/year-8-mathematics/geometry-properties",
    },
    {
      slug: "volume-and-surface-area",
      title: "Volume and Surface Area",
      startHref: "/course/year-8-mathematics/volume-and-surface-area",
    },
    {
      slug: "data-and-graphs",
      title: "Data Analysis and Graphs",
      startHref: "/course/year-8-mathematics/data-and-graphs",
    },
    {
      slug: "probability-and-chance",
      title: "Probability and Chance",
      startHref: "/course/year-8-mathematics/probability-and-chance",
    },
  ],

  questions: [
    {
      id: "y8-no1",
      unitSlug: "number-operations",
      prompt: "Evaluate $-6 + 14$.",
      choices: [
        { label: "A", text: "$-20$" },
        { label: "B", text: "$-8$" },
        { label: "C", text: "$8$" },
        { label: "D", text: "$20$" },
      ],
      correctAnswer: "C",
      explanation: "Adding 14 moves 14 places to the right from -6, landing at 8.",
    },
    {
      id: "y8-no2",
      unitSlug: "number-operations",
      prompt: "Which number is irrational?",
      choices: [
        { label: "A", text: "$0.75$" },
        { label: "B", text: "$\\sqrt{16}$" },
        { label: "C", text: "$\\sqrt{20}$" },
        { label: "D", text: "$\\frac{3}{5}$" },
      ],
      correctAnswer: "C",
      explanation: "$\\sqrt{20}$ cannot be written as an exact fraction because 20 is not a perfect square.",
    },
    {
      id: "y8-no3",
      unitSlug: "number-operations",
      prompt: "A $20\\%$ discount is applied to an item priced at $80 before sale. What is the sale price?",
      choices: [
        { label: "A", text: "$16" },
        { label: "B", text: "$60" },
        { label: "C", text: "$64" },
        { label: "D", text: "$96" },
      ],
      correctAnswer: "C",
      explanation: "A 20% discount removes 16 dollars from 80 dollars, so the sale price is 64 dollars.",
    },
    {
      id: "y8-ae1",
      unitSlug: "algebra-equations",
      prompt: "Expand $3(x + 4)$.",
      choices: [
        { label: "A", text: "$3x + 4$" },
        { label: "B", text: "$3x + 7$" },
        { label: "C", text: "$3x + 12$" },
        { label: "D", text: "$x + 12$" },
      ],
      correctAnswer: "C",
      explanation: "The 3 multiplies both terms inside the bracket: $3 \\times x$ and $3 \\times 4$.",
    },
    {
      id: "y8-ae2",
      unitSlug: "algebra-equations",
      prompt: "Solve $2x + 5 = 17$.",
      choices: [
        { label: "A", text: "$x = 6$" },
        { label: "B", text: "$x = 11$" },
        { label: "C", text: "$x = 24$" },
        { label: "D", text: "$x = 34$" },
      ],
      correctAnswer: "A",
      explanation: "Undo the +5 first to get 12, then divide by 2 to get $x = 6$.",
    },
    {
      id: "y8-ae3",
      unitSlug: "algebra-equations",
      prompt: "Factorise $6x + 9$ using the highest common factor.",
      choices: [
        { label: "A", text: "$3(2x + 3)$" },
        { label: "B", text: "$3(6x + 9)$" },
        { label: "C", text: "$6(x + 9)$" },
        { label: "D", text: "$9(6x + 1)$" },
      ],
      correctAnswer: "A",
      explanation: "Both terms share a factor of 3, and dividing each term by 3 leaves $2x + 3$.",
    },
    {
      id: "y8-lr1",
      unitSlug: "linear-relationships",
      prompt: "For the rule $y = 2x + 3$, what is $y$ when $x = 4$?",
      choices: [
        { label: "A", text: "$8$" },
        { label: "B", text: "$9$" },
        { label: "C", text: "$11$" },
        { label: "D", text: "$14$" },
      ],
      correctAnswer: "C",
      explanation: "Replace x with 4: $2 \\times 4 + 3 = 11$.",
    },
    {
      id: "y8-lr2",
      unitSlug: "linear-relationships",
      prompt: "A line rises 6 units while running 3 units to the right. What is its gradient?",
      choices: [
        { label: "A", text: "$\\frac{1}{2}$" },
        { label: "B", text: "$2$" },
        { label: "C", text: "$3$" },
        { label: "D", text: "$6$" },
      ],
      correctAnswer: "B",
      explanation: "Gradient is rise divided by run, so $6 \\div 3 = 2$.",
    },
    {
      id: "y8-py1",
      unitSlug: "pythagoras-theorem",
      prompt: "A right-angled triangle has shorter sides 3 cm and 4 cm. What is the hypotenuse?",
      choices: [
        { label: "A", text: "$5$ cm" },
        { label: "B", text: "$6$ cm" },
        { label: "C", text: "$7$ cm" },
        { label: "D", text: "$12$ cm" },
      ],
      correctAnswer: "A",
      explanation: "$3^2 + 4^2 = 25$, so the hypotenuse is $\\sqrt{25} = 5$ cm.",
    },
    {
      id: "y8-py2",
      unitSlug: "pythagoras-theorem",
      prompt: "A right-angled triangle has hypotenuse 13 cm and one shorter side 5 cm. What is the other shorter side?",
      choices: [
        { label: "A", text: "$8$ cm" },
        { label: "B", text: "$10$ cm" },
        { label: "C", text: "$12$ cm" },
        { label: "D", text: "$18$ cm" },
      ],
      correctAnswer: "C",
      explanation: "For a shorter side, subtract the known square: $13^2 - 5^2 = 144$, so the side is 12 cm.",
    },
    {
      id: "y8-py3",
      unitSlug: "pythagoras-theorem",
      prompt: "What is the distance between $(1, 2)$ and $(4, 6)$?",
      choices: [
        { label: "A", text: "$3$" },
        { label: "B", text: "$4$" },
        { label: "C", text: "$5$" },
        { label: "D", text: "$7$" },
      ],
      correctAnswer: "C",
      explanation: "The horizontal change is 3 and the vertical change is 4, making a 3-4-5 right triangle.",
    },
    {
      id: "y8-gp1",
      unitSlug: "geometry-properties",
      prompt: "Which test proves two triangles are congruent using three equal side pairs?",
      choices: [
        { label: "A", text: "AA" },
        { label: "B", text: "SSS" },
        { label: "C", text: "SAS" },
        { label: "D", text: "RHS" },
      ],
      correctAnswer: "B",
      explanation: "SSS means all three corresponding side lengths match, so the triangles must be congruent.",
    },
    {
      id: "y8-gp2",
      unitSlug: "geometry-properties",
      prompt: "Two similar shapes have scale factor 4. What happens to each corresponding side length?",
      choices: [
        { label: "A", text: "It is multiplied by 2" },
        { label: "B", text: "It is multiplied by 4" },
        { label: "C", text: "It is multiplied by 8" },
        { label: "D", text: "It is multiplied by 16" },
      ],
      correctAnswer: "B",
      explanation: "A linear scale factor acts directly on lengths, so each matching side is multiplied by 4.",
    },
    {
      id: "y8-vs1",
      unitSlug: "volume-and-surface-area",
      prompt: "What is the volume of a rectangular prism with length 5 cm, width 4 cm and height 3 cm?",
      choices: [
        { label: "A", text: "$12$ cm$^3$" },
        { label: "B", text: "$20$ cm$^3$" },
        { label: "C", text: "$60$ cm$^3$" },
        { label: "D", text: "$94$ cm$^3$" },
      ],
      correctAnswer: "C",
      explanation: "Volume fills 3D space, so multiply length, width and height: $5 \\times 4 \\times 3 = 60$.",
    },
    {
      id: "y8-vs2",
      unitSlug: "volume-and-surface-area",
      prompt: "A cylinder has radius 3 cm and height 10 cm. Which expression gives its volume?",
      choices: [
        { label: "A", text: "$\\pi \\times 3 \\times 10$" },
        { label: "B", text: "$\\pi \\times 3^2 \\times 10$" },
        { label: "C", text: "$2\\pi \\times 3 \\times 10$" },
        { label: "D", text: "$2\\pi \\times 3^2$" },
      ],
      correctAnswer: "B",
      explanation: "Cylinder volume is circular base area times height, so use $\\pi r^2 h$.",
    },
    {
      id: "y8-dg1",
      unitSlug: "data-and-graphs",
      prompt: "For the data set $2, 4, 4, 7, 9$, what is the median?",
      choices: [
        { label: "A", text: "$2$" },
        { label: "B", text: "$4$" },
        { label: "C", text: "$5.2$" },
        { label: "D", text: "$9$" },
      ],
      correctAnswer: "B",
      explanation: "The median is the middle value after ordering; the third value is 4.",
    },
    {
      id: "y8-dg2",
      unitSlug: "data-and-graphs",
      prompt: "The lower quartile is 6 and the upper quartile is 15. What is the IQR?",
      choices: [
        { label: "A", text: "$6$" },
        { label: "B", text: "$9$" },
        { label: "C", text: "$15$" },
        { label: "D", text: "$21$" },
      ],
      correctAnswer: "B",
      explanation: "IQR is the spread of the middle half: $Q_3 - Q_1 = 15 - 6 = 9$.",
    },
    {
      id: "y8-dg3",
      unitSlug: "data-and-graphs",
      prompt: "Which sampling method is usually most fair for a school survey?",
      choices: [
        { label: "A", text: "Ask only your closest friends" },
        { label: "B", text: "Ask students chosen at random across the school" },
        { label: "C", text: "Ask only students who volunteer first" },
        { label: "D", text: "Ask only one class" },
      ],
      correctAnswer: "B",
      explanation: "Randomly choosing across the school reduces bias because different groups have a chance to be included.",
    },
    {
      id: "y8-pc1",
      unitSlug: "probability-and-chance",
      prompt: "A fair die is rolled. What is the probability of rolling an even number?",
      choices: [
        { label: "A", text: "$\\frac{1}{6}$" },
        { label: "B", text: "$\\frac{1}{3}$" },
        { label: "C", text: "$\\frac{1}{2}$" },
        { label: "D", text: "$\\frac{2}{3}$" },
      ],
      correctAnswer: "C",
      explanation: "There are 3 even outcomes out of 6 possible outcomes, so the probability is $\\frac{3}{6}=\\frac{1}{2}$.",
    },
    {
      id: "y8-pc2",
      unitSlug: "probability-and-chance",
      prompt: "A coin is flipped twice. Which outcome list shows the full sample space?",
      choices: [
        { label: "A", text: "HH, TT" },
        { label: "B", text: "HT, TH" },
        { label: "C", text: "HH, HT, TH, TT" },
        { label: "D", text: "H, T" },
      ],
      correctAnswer: "C",
      explanation: "A two-stage experiment needs both results in order, giving four possible outcomes.",
    },
  ],
};
