import type { DiagnosticData } from "./types";

export const diagnosticData: DiagnosticData = {
  yearLevelTitle: "Year 8 Mathematics",

  units: [
    {
      slug: "index-laws-extension",
      title: "Indices A",
      startHref: "/course/year-8-mathematics/index-laws-extension",
    },
    {
      slug: "number-financial-mathematics",
      title: "Number and Financial Mathematics",
      startHref: "/course/year-8-mathematics/number-financial-mathematics",
    },
    {
      slug: "algebraic-techniques-stage5",
      title: "Algebraic Techniques (Stage 5)",
      startHref: "/course/year-8-mathematics/algebraic-techniques-stage5",
    },
    {
      slug: "linear-relationships",
      title: "Linear Relationships",
      startHref: "/course/year-8-mathematics/linear-relationships",
    },
    {
      slug: "pythagoras-theorem",
      title: "Pythagoras' Theorem",
      startHref: "/course/year-8-mathematics/pythagoras-theorem",
    },
    {
      slug: "geometry-angles",
      title: "Geometry and Angles",
      startHref: "/course/year-8-mathematics/geometry-angles",
    },
    {
      slug: "volume-of-composite-solids",
      title: "Volume of Composite Solids",
      startHref: "/course/year-8-mathematics/volume-of-composite-solids",
    },
    {
      slug: "data-and-graphs",
      title: "Data Analysis and Graphs",
      startHref: "/course/year-8-mathematics/data-and-graphs",
    },
    {
      slug: "introduction-to-networks",
      title: "Introduction to Networks",
      startHref: "/course/year-8-mathematics/introduction-to-networks",
    },
  ],

  questions: [

    {
      id: "y8-no2",
      unitSlug: "index-laws-extension",
      prompt: "Which number is equal to $4.5 \\times 10^{-3}$?",
      choices: [
        { label: "A", text: "$4500$" },
        { label: "B", text: "$0.45$" },
        { label: "C", text: "$0.0045$" },
        { label: "D", text: "$0.00045$" },
      ],
      correctAnswer: "C",
      explanation: "$10^{-3}$ moves the decimal point three places left, so $4.5 \\times 10^{-3}=0.0045$.",
    },
    {
      id: "y8-no3",
      unitSlug: "number-financial-mathematics",
      prompt: "A $20\\%$ discount is applied to an item priced at $80 before sale. What is the sale price?",
      choices: [
        { label: "A", text: "$16" },
        { label: "B", text: "$60" },
        { label: "C", text: "$64" },
        { label: "D", text: "$96" },
      ],
      correctAnswer: "C",
      explanation: "A 20% discount removes 16 dollars from 80 dollars, so the sale price is 64 dollars.",
    },
    {
      id: "y8-fm1",
      unitSlug: "number-financial-mathematics",
      prompt: "An item is bought for $80 and sold for $100. What is the percentage profit?",
      choices: [
        { label: "A", text: "20%" },
        { label: "B", text: "25%" },
        { label: "C", text: "80%" },
        { label: "D", text: "125%" },
      ],
      correctAnswer: "B",
      explanation: "Profit = $100 − $80 = $20. Percentage profit = (20 ÷ 80) × 100 = 25%.",
    },
    {
      id: "y8-fm2",
      unitSlug: "number-financial-mathematics",
      prompt: "What is the simple interest on $500 invested at 4% per annum for 2 years?",
      choices: [
        { label: "A", text: "$20" },
        { label: "B", text: "$40" },
        { label: "C", text: "$80" },
        { label: "D", text: "$540" },
      ],
      correctAnswer: "B",
      explanation: "Using I = PRT ÷ 100: I = 500 × 4 × 2 ÷ 100 = 4000 ÷ 100 = 40. The simple interest is $40.",
    },
    {
      id: "y8-af1",
      unitSlug: "algebraic-techniques-stage5",
      prompt: "Simplify $5x - 3 + 2x + 7$.",
      choices: [
        { label: "A", text: "$7x + 4$" },
        { label: "B", text: "$7x - 4$" },
        { label: "C", text: "$3x + 4$" },
        { label: "D", text: "$10x + 4$" },
      ],
      correctAnswer: "A",
      explanation: "Collect the x-terms: $5x + 2x = 7x$. Collect the constants: $-3 + 7 = 4$. The result is $7x + 4$.",
    },
    {
      id: "y8-af2",
      unitSlug: "algebraic-techniques-stage5",
      prompt: "Evaluate $4p - 3$ when $p = 5$.",
      choices: [
        { label: "A", text: "$7$" },
        { label: "B", text: "$17$" },
        { label: "C", text: "$23$" },
        { label: "D", text: "$32$" },
      ],
      correctAnswer: "B",
      explanation: "Replace $p$ with 5: $4 \\times 5 - 3 = 20 - 3 = 17$.",
    },
    {
      id: "y8-ae2",
      unitSlug: "algebraic-techniques-stage5",
      prompt: "Solve $2x + 5 = 17$.",
      choices: [
        { label: "A", text: "$x = 6$" },
        { label: "B", text: "$x = 11$" },
        { label: "C", text: "$x = 24$" },
        { label: "D", text: "$x = 34$" },
      ],
      correctAnswer: "A",
      explanation: "Undo the +5 first to get 12, then divide by 2 to get $x = 6$.",
    },
    {
      id: "y8-ae3",
      unitSlug: "algebraic-techniques-stage5",
      prompt: "Factorise $6x + 9$ using the highest common factor.",
      choices: [
        { label: "A", text: "$3(2x + 3)$" },
        { label: "B", text: "$3(6x + 9)$" },
        { label: "C", text: "$6(x + 9)$" },
        { label: "D", text: "$9(6x + 1)$" },
      ],
      correctAnswer: "A",
      explanation: "Both terms share a factor of 3, and dividing each term by 3 leaves $2x + 3$.",
    },
    {
      id: "y8-lr1",
      unitSlug: "linear-relationships",
      prompt: "For the rule $y = 2x + 3$, what is $y$ when $x = 4$?",
      choices: [
        { label: "A", text: "$8$" },
        { label: "B", text: "$9$" },
        { label: "C", text: "$11$" },
        { label: "D", text: "$14$" },
      ],
      correctAnswer: "C",
      explanation: "Replace x with 4: $2 \\times 4 + 3 = 11$.",
    },
    {
      id: "y8-lr2",
      unitSlug: "linear-relationships",
      prompt: "A line rises 6 units while running 3 units to the right. What is its gradient?",
      choices: [
        { label: "A", text: "$\\frac{1}{2}$" },
        { label: "B", text: "$2$" },
        { label: "C", text: "$3$" },
        { label: "D", text: "$6$" },
      ],
      correctAnswer: "B",
      explanation: "Gradient is rise divided by run, so $6 \\div 3 = 2$.",
    },

    {
      id: "y8-py2",
      unitSlug: "pythagoras-theorem",
      prompt: "A right-angled triangle has hypotenuse 13 cm and one shorter side 5 cm. What is the other shorter side?",
      choices: [
        { label: "A", text: "$8$ cm" },
        { label: "B", text: "$10$ cm" },
        { label: "C", text: "$12$ cm" },
        { label: "D", text: "$18$ cm" },
      ],
      correctAnswer: "C",
      explanation: "For a shorter side, subtract the known square: $13^2 - 5^2 = 144$, so the side is 12 cm.",
    },
    {
      id: "y8-py3",
      unitSlug: "pythagoras-theorem",
      prompt: "What is the distance between $(1, 2)$ and $(4, 6)$?",
      choices: [
        { label: "A", text: "$3$" },
        { label: "B", text: "$4$" },
        { label: "C", text: "$5$" },
        { label: "D", text: "$7$" },
      ],
      correctAnswer: "C",
      explanation: "The horizontal change is 3 and the vertical change is 4, making a 3-4-5 right triangle.",
    },
    {
      id: "y8-gp1",
      unitSlug: "geometry-angles",
      prompt: "Which test proves two triangles are congruent using three equal side pairs?",
      choices: [
        { label: "A", text: "AA" },
        { label: "B", text: "SSS" },
        { label: "C", text: "SAS" },
        { label: "D", text: "RHS" },
      ],
      correctAnswer: "B",
      explanation: "SSS means all three corresponding side lengths match, so the triangles must be congruent.",
    },
    {
      id: "y8-gp2",
      unitSlug: "geometry-angles",
      prompt: "Two similar shapes have scale factor 4. What happens to each corresponding side length?",
      choices: [
        { label: "A", text: "It is multiplied by 2" },
        { label: "B", text: "It is multiplied by 4" },
        { label: "C", text: "It is multiplied by 8" },
        { label: "D", text: "It is multiplied by 16" },
      ],
      correctAnswer: "B",
      explanation: "A linear scale factor acts directly on lengths, so each matching side is multiplied by 4.",
    },
    {
      id: "y8-vs1",
      unitSlug: "volume-of-composite-solids",
      prompt: "What is the volume of a rectangular prism with length 5 cm, width 4 cm and height 3 cm?",
      choices: [
        { label: "A", text: "$12$ cm$^3$" },
        { label: "B", text: "$20$ cm$^3$" },
        { label: "C", text: "$60$ cm$^3$" },
        { label: "D", text: "$94$ cm$^3$" },
      ],
      correctAnswer: "C",
      explanation: "Volume fills 3D space, so multiply length, width and height: $5 \\times 4 \\times 3 = 60$.",
    },
    {
      id: "y8-vs2",
      unitSlug: "volume-of-composite-solids",
      prompt: "A cylinder has radius 3 cm and height 10 cm. Which expression gives its volume?",
      choices: [
        { label: "A", text: "$\\pi \\times 3 \\times 10$" },
        { label: "B", text: "$\\pi \\times 3^2 \\times 10$" },
        { label: "C", text: "$2\\pi \\times 3 \\times 10$" },
        { label: "D", text: "$2\\pi \\times 3^2$" },
      ],
      correctAnswer: "B",
      explanation: "Cylinder volume is circular base area times height, so use $\\pi r^2 h$.",
    },

    {
      id: "y8-dg2",
      unitSlug: "data-and-graphs",
      prompt: "The lower quartile is 6 and the upper quartile is 15. What is the IQR?",
      choices: [
        { label: "A", text: "$6$" },
        { label: "B", text: "$9$" },
        { label: "C", text: "$15$" },
        { label: "D", text: "$21$" },
      ],
      correctAnswer: "B",
      explanation: "IQR is the spread of the middle half: $Q_3 - Q_1 = 15 - 6 = 9$.",
    },
    {
      id: "y8-dg3",
      unitSlug: "data-and-graphs",
      prompt: "Which sampling method is usually most fair for a school survey?",
      choices: [
        { label: "A", text: "Ask only your closest friends" },
        { label: "B", text: "Ask students chosen at random across the school" },
        { label: "C", text: "Ask only students who volunteer first" },
        { label: "D", text: "Ask only one class" },
      ],
      correctAnswer: "B",
      explanation: "Randomly choosing across the school reduces bias because different groups have a chance to be included.",
    },
    {
      id: "y8-net1",
      unitSlug: "introduction-to-networks",
      prompt: "In a network diagram, what do vertices represent?",
      choices: [
        { label: "A", text: "The connection lines between locations" },
        { label: "B", text: "The points or locations in the network" },
        { label: "C", text: "The total distance around the network" },
        { label: "D", text: "The number of possible routes only" },
      ],
      correctAnswer: "B",
      explanation: "Vertices are the points or locations in a network. Edges are the connections between them.",
    },
    {
      id: "y8-net2",
      unitSlug: "introduction-to-networks",
      prompt: "Which route type starts and finishes at the same vertex?",
      choices: [
        { label: "A", text: "A path" },
        { label: "B", text: "A circuit" },
        { label: "C", text: "A bridge" },
        { label: "D", text: "A vertex" },
      ],
      correctAnswer: "B",
      explanation: "A circuit is a route that starts and ends at the same vertex.",
    },
  ],
};
