export type DiagnosticQuestion = {
  id: string;
  section: string;
  skill: string;
  difficulty: "core" | "standard" | "extension";
  prompt: string;
  latex?: string;
  image?: string;
  answer: string;
  acceptedAnswers?: string[];
  choices?: {
    label: string;
    text: string;
  }[];
  diagnosticTag: string;
};

export const questions: DiagnosticQuestion[] = [
  {
    id: "q1",
    section: "Algebra foundations",
    skill: "Expanding and collecting like terms",
    difficulty: "core",
    prompt: "Simplify the expression.",
    latex: "3(x - 2)^2 - 2x(x + 1)",
    answer: "x^2-14x+12",
    acceptedAnswers: ["x^2 - 14x + 12", "1x^2-14x+12"],
    diagnosticTag: "algebra-expansion-collection",
  },
  {
    id: "q2",
    section: "Algebra foundations",
    skill: "Rearranging exponential equations",
    difficulty: "standard",
    prompt: "Make x the subject.",
    latex: "y = 3e^{2x} - 5",
    answer: "1/2 ln((y+5)/3)",
    acceptedAnswers: [
      "\\frac{1}{2}\\ln\\left(\\frac{y+5}{3}\\right)",
      "0.5ln((y+5)/3)",
      "(1/2)ln((y+5)/3)",
      "ln((y+5)/3)/2",
    ],
    diagnosticTag: "algebra-make-subject-exponential",
  },
  {
    id: "q3",
    section: "Algebra foundations",
    skill: "Solving quadratic equations",
    difficulty: "core",
    prompt: "Choose the correct solutions.",
    latex: "2x^2 - 5x - 3 = 0",
    answer: "B",
    choices: [
      { label: "A", text: "$x=3,\\;x=\\frac{1}{2}$" },
      { label: "B", text: "$x=3,\\;x=-\\frac{1}{2}$" },
      { label: "C", text: "$x=-3,\\;x=\\frac{1}{2}$" },
      { label: "D", text: "$x=-3,\\;x=-\\frac{1}{2}$" },
    ],
    diagnosticTag: "algebra-quadratic-factorising",
  },
  {
    id: "q4",
    section: "Algebra foundations",
    skill: "Index laws with negative powers",
    difficulty: "standard",
    prompt: "Simplify using positive indices.",
    latex: "\\frac{(2x^3y^{-2})^2}{4xy^{-1}}",
    answer: "x^5/y^3",
    acceptedAnswers: [
      "\\frac{x^5}{y^3}",
      "x^5y^-3",
      "x^5y^{-3}",
      "x^5/y^3",
    ],
    diagnosticTag: "algebra-index-laws-negative-powers",
  },
  {
    id: "q5",
    section: "Functions and graphs",
    skill: "Substitution into functions",
    difficulty: "standard",
    prompt: "Find and simplify $f(x+2)$.",
    latex: "f(x)=2x^2-3x+1",
    answer: "2x^2+5x+3",
    acceptedAnswers: ["2x^2 + 5x + 3"],
    diagnosticTag: "functions-substitution-composite-input",
  },
  {
    id: "q6",
    section: "Functions and graphs",
    skill: "Domain restrictions from square roots",
    difficulty: "core",
    prompt: "Choose the domain.",
    latex: "f(x)=\\sqrt{5-2x}",
    answer: "A",
    choices: [
      { label: "A", text: "$x\\le \\frac{5}{2}$" },
      { label: "B", text: "$x\\ge \\frac{5}{2}$" },
      { label: "C", text: "$x<\\frac{5}{2}$" },
      { label: "D", text: "all real $x$" },
    ],
    diagnosticTag: "functions-domain-square-root",
  },
  {
    id: "q7",
    section: "Functions and graphs",
    skill: "Reading intercepts from graphs",
    difficulty: "core",
    prompt: "Use the graph to choose the correct x-intercepts.",
    image: "/diagnostic/graphs/parabola-intercepts.svg",
    answer: "A",
    choices: [
      { label: "A", text: "$x=-1$ and $x=3$" },
      { label: "B", text: "$x=1$ and $x=3$" },
      { label: "C", text: "$x=-3$ and $x=1$" },
      { label: "D", text: "$x=-1$ and $x=-3$" },
    ],
    diagnosticTag: "graph-x-intercepts",
  },
  {
    id: "q8",
    section: "Functions and graphs",
    skill: "Reading domain and range from graphs",
    difficulty: "standard",
    prompt: "Use the graph to choose the correct domain and range.",
    image: "/diagnostic/graphs/domain-range-curve.svg",
    answer: "C",
    choices: [
      { label: "A", text: "Domain $[-1,5]$, range $[-1,4]$" },
      { label: "B", text: "Domain $[-1,4]$, range $[0,5]$" },
      { label: "C", text: "Domain $[-1,5]$, range $[0,4]$" },
      { label: "D", text: "Domain $[0,4]$, range $[-1,5]$" },
    ],
    diagnosticTag: "graph-domain-range",
  },
  {
    id: "q9",
    section: "Functions and graphs",
    skill: "Identifying increasing and decreasing intervals",
    difficulty: "standard",
    prompt: "Use the graph to choose where the function is increasing.",
    image: "/diagnostic/graphs/increasing-decreasing.svg",
    answer: "D",
    choices: [
      { label: "A", text: "$(-\\infty,-2)$ only" },
      { label: "B", text: "$(-2,1)$ only" },
      { label: "C", text: "$(1,\\infty)$ only" },
      { label: "D", text: "$(-\\infty,-2)$ and $(1,\\infty)$" },
    ],
    diagnosticTag: "graph-increasing-decreasing",
  },
  {
    id: "q10",
    section: "Functions and graphs",
    skill: "Interpreting tangent gradient visually",
    difficulty: "core",
    prompt: "At the marked point, what is the sign of the tangent gradient?",
    image: "/diagnostic/graphs/tangent-gradient-sign.svg",
    answer: "A",
    choices: [
      { label: "A", text: "Positive" },
      { label: "B", text: "Negative" },
      { label: "C", text: "Zero" },
      { label: "D", text: "Undefined" },
    ],
    diagnosticTag: "graph-tangent-gradient-sign",
  },
  {
    id: "q11",
    section: "Trigonometry",
    skill: "Exact angle conversion",
    difficulty: "core",
    prompt: "Convert to radians.",
    latex: "150^\\circ",
    answer: "5pi/6",
    acceptedAnswers: ["5π/6", "\\frac{5\\pi}{6}", "5\\pi/6"],
    diagnosticTag: "trig-degrees-to-radians",
  },
  {
    id: "q12",
    section: "Trigonometry",
    skill: "Exact trigonometric values",
    difficulty: "core",
    prompt: "Evaluate exactly.",
    latex: "\\sin\\left(\\frac{\\pi}{3}\\right)+\\cos(\\pi)",
    answer: "(sqrt(3)-2)/2",
    acceptedAnswers: [
      "\\frac{\\sqrt{3}}{2}-1",
      "(√3-2)/2",
      "sqrt(3)/2-1",
      "\\frac{\\sqrt{3}-2}{2}",
    ],
    diagnosticTag: "trig-exact-values",
  },
  {
    id: "q13",
    section: "Trigonometry",
    skill: "Solving trigonometric equations on a domain",
    difficulty: "standard",
    prompt: "Choose the solution set.",
    latex: "0\\le x\\le 2\\pi, \\quad 2\\sin(x)-1=0",
    answer: "B",
    choices: [
      { label: "A", text: "$x=\\frac{\\pi}{6}$ only" },
      { label: "B", text: "$x=\\frac{\\pi}{6},\\;\\frac{5\\pi}{6}$" },
      { label: "C", text: "$x=\\frac{7\\pi}{6},\\;\\frac{11\\pi}{6}$" },
      { label: "D", text: "$x=\\frac{\\pi}{3},\\;\\frac{2\\pi}{3}$" },
    ],
    diagnosticTag: "trig-equation-domain",
  },
  {
    id: "q14",
    section: "Differential calculus",
    skill: "Differentiating polynomial functions",
    difficulty: "core",
    prompt: "Differentiate.",
    latex: "y=4x^5-3x^2+7x-9",
    answer: "20x^4-6x+7",
    acceptedAnswers: ["dy/dx=20x^4-6x+7", "y'=20x^4-6x+7"],
    diagnosticTag: "calculus-differentiate-polynomial",
  },
  {
    id: "q15",
    section: "Differential calculus",
    skill: "Finding tangent gradients",
    difficulty: "core",
    prompt: "Find the gradient of the tangent at $x=2$.",
    latex: "y=x^3-4x",
    answer: "8",
    diagnosticTag: "calculus-tangent-gradient",
  },
  {
    id: "q16",
    section: "Differential calculus",
    skill: "Solving for stationary x-values",
    difficulty: "standard",
    prompt: "Find the smaller stationary x-value.",
    latex: "y=x^3-3x^2-9x+5",
    answer: "-1",
    diagnosticTag: "calculus-stationary-x-values",
  },
  {
    id: "q17",
    section: "Differential calculus",
    skill: "Finding stationary point coordinates",
    difficulty: "standard",
    prompt: "Find the stationary point when $x=3$.",
    latex: "y=x^3-3x^2-9x+5",
    answer: "(3,-22)",
    acceptedAnswers: ["3,-22", "3, -22", "(3, -22)"],
    diagnosticTag: "calculus-stationary-coordinate",
  },
  {
    id: "q18",
    section: "Differential calculus",
    skill: "Classifying stationary points",
    difficulty: "standard",
    prompt: "For the same function, classify the stationary point at $x=3$.",
    latex: "y=x^3-3x^2-9x+5",
    answer: "B",
    choices: [
      { label: "A", text: "Local maximum" },
      { label: "B", text: "Local minimum" },
      { label: "C", text: "Neither" },
      { label: "D", text: "Point of inflection only" },
    ],
    diagnosticTag: "calculus-stationary-classification",
  },
  {
    id: "q19",
    section: "Differential calculus",
    skill: "Interpreting derivative signs",
    difficulty: "extension",
    prompt: "Choose the interval where the function is decreasing.",
    latex: "f'(x)=3(x+1)(x-3)",
    answer: "C",
    choices: [
      { label: "A", text: "$(-\\infty,-1)$" },
      { label: "B", text: "$(3,\\infty)$" },
      { label: "C", text: "$(-1,3)$" },
      { label: "D", text: "all real $x$" },
    ],
    diagnosticTag: "calculus-derivative-sign-intervals",
  },
  {
    id: "q20",
    section: "Integral calculus",
    skill: "Indefinite integration of polynomials",
    difficulty: "core",
    prompt: "Find the indefinite integral.",
    latex: "\\int \\left(6x^2-4x+3\\right)\\,dx",
    answer: "2x^3-2x^2+3x+C",
    acceptedAnswers: ["2x^3 - 2x^2 + 3x + C", "2x^3-2x^2+3x+c"],
    diagnosticTag: "integration-indefinite-polynomial",
  },
  {
    id: "q21",
    section: "Integral calculus",
    skill: "Evaluating definite integrals",
    difficulty: "standard",
    prompt: "Evaluate the definite integral.",
    latex: "\\int_0^2 \\left(3x^2+1\\right)\\,dx",
    answer: "10",
    diagnosticTag: "integration-definite-polynomial",
  },
  {
    id: "q22",
    section: "Exponential and logarithmic functions",
    skill: "Logarithm laws",
    difficulty: "core",
    prompt: "Simplify, where $x>0$.",
    latex: "\\ln(x^3)-\\ln(x)",
    answer: "2ln(x)",
    acceptedAnswers: ["2 ln(x)", "ln(x^2)", "\\ln(x^2)", "2\\ln(x)"],
    diagnosticTag: "logs-log-laws",
  },
  {
    id: "q23",
    section: "Exponential and logarithmic functions",
    skill: "Solving exponential equations",
    difficulty: "standard",
    prompt: "Solve for $x$.",
    latex: "5e^{2x}=20",
    answer: "ln(2)",
    acceptedAnswers: ["\\ln(2)", "ln 2"],
    diagnosticTag: "exponential-equation-solving",
  },
  {
    id: "q24",
    section: "Statistics and probability",
    skill: "Standardised scores",
    difficulty: "core",
    prompt: "How many standard deviations above the mean is Student A?",
    latex: "\\text{Mean}=68, \\quad \\text{Standard deviation}=8, \\quad \\text{Student A score}=84",
    answer: "2",
    acceptedAnswers: ["2 standard deviations", "z=2"],
    diagnosticTag: "statistics-standardised-score",
  },
  {
    id: "q25",
    section: "Statistics and probability",
    skill: "Probability without replacement",
    difficulty: "standard",
    prompt: "Find the probability that both balls are red.",
    latex: "\\text{A bag contains 5 red balls and 3 blue balls. Two balls are selected without replacement.}",
    answer: "5/14",
    acceptedAnswers: ["\\frac{5}{14}", "0.357", "0.3571"],
    diagnosticTag: "probability-without-replacement",
  },
  {
    id: "q26",
    section: "Statistics and probability",
    skill: "Interpreting correlation",
    difficulty: "core",
    prompt: "Choose the best description of the relationship.",
    latex: "r=-0.82",
    answer: "A",
    choices: [
      { label: "A", text: "Strong negative linear relationship" },
      { label: "B", text: "Weak negative linear relationship" },
      { label: "C", text: "Strong positive linear relationship" },
      { label: "D", text: "No linear relationship" },
    ],
    diagnosticTag: "statistics-correlation-interpretation",
  },
  {
    id: "q27",
    section: "Financial mathematics",
    skill: "Compound interest",
    difficulty: "standard",
    prompt: "Find the value of the investment after 3 years, to the nearest cent.",
    latex: "\\$2000 \\text{ is invested at } 4\\% \\text{ p.a. compound interest for 3 years.}",
    answer: "2249.73",
    acceptedAnswers: ["$2249.73", "\\$2249.73"],
    diagnosticTag: "financial-compound-interest",
  },
];
