export type DiagnosticQuestion = {
  id: string;
  section: string;
  skill: string;
  difficulty: "core" | "standard" | "extension";
  prompt: string;
  latex?: string;
  image?: string;
  answer: string;
  acceptedAnswers?: string[];
  choices?: {
    label: string;
    text: string;
  }[];
  diagnosticTag: string;
};

export const questions: DiagnosticQuestion[] = [
  {
    id: "q1",
    section: "Functions and Graphing Techniques",
    skill: "Function notation and substitution",
    difficulty: "core",
    prompt: "Find $f(3)$.",
    latex: "f(x)=2x^2-x+1",
    answer: "16",
    diagnosticTag: "functions-function-notation-substitution",
  },
  {
    id: "q2",
    section: "Functions and Graphing Techniques",
    skill: "Composite input substitution",
    difficulty: "standard",
    prompt: "Find and simplify $f(x+2)$.",
    latex: "f(x)=2x^2-3x+1",
    answer: "2x^2+5x+3",
    acceptedAnswers: ["2x^2 + 5x + 3"],
    diagnosticTag: "functions-substitution-composite-input",
  },
  {
    id: "q3",
    section: "Functions and Graphing Techniques",
    skill: "Domain restrictions from square roots",
    difficulty: "core",
    prompt: "Choose the domain.",
    latex: "f(x)=\\sqrt{5-2x}",
    answer: "A",
    choices: [
      { label: "A", text: "$x\\le \\frac{5}{2}$" },
      { label: "B", text: "$x\\ge \\frac{5}{2}$" },
      { label: "C", text: "$x<\\frac{5}{2}$" },
      { label: "D", text: "all real $x$" },
    ],
    diagnosticTag: "functions-domain-square-root",
  },
  {
    id: "q4",
    section: "Functions and Graphing Techniques",
    skill: "Reading intercepts from graphs",
    difficulty: "core",
    prompt: "Use the graph to choose the correct x-intercepts.",
    image: "/diagnostic/graphs/parabola-intercepts.svg",
    answer: "A",
    choices: [
      { label: "A", text: "$x=-1$ and $x=3$" },
      { label: "B", text: "$x=1$ and $x=3$" },
      { label: "C", text: "$x=-3$ and $x=1$" },
      { label: "D", text: "$x=-1$ and $x=-3$" },
    ],
    diagnosticTag: "graph-x-intercepts",
  },
  {
    id: "q5",
    section: "Functions and Graphing Techniques",
    skill: "Graph transformations",
    difficulty: "standard",
    prompt: "Choose the transformation from $y=f(x)$ to $y=f(x-3)+2$.",
    latex: "y=f(x-3)+2",
    answer: "C",
    choices: [
      { label: "A", text: "Left 3 and up 2" },
      { label: "B", text: "Right 3 and down 2" },
      { label: "C", text: "Right 3 and up 2" },
      { label: "D", text: "Left 3 and down 2" },
    ],
    diagnosticTag: "functions-graph-transformations",
  },
  {
    id: "q6",
    section: "Functions and Graphing Techniques",
    skill: "Reciprocal graph asymptotes",
    difficulty: "standard",
    prompt: "Choose the vertical asymptote.",
    latex: "y=\\frac{1}{x-2}+3",
    answer: "B",
    choices: [
      { label: "A", text: "$x=-2$" },
      { label: "B", text: "$x=2$" },
      { label: "C", text: "$y=2$" },
      { label: "D", text: "$y=3$" },
    ],
    diagnosticTag: "functions-reciprocal-asymptote",
  },
  {
    id: "q7",
    section: "Trigonometric Functions and Graphs",
    skill: "Radians and exact angle conversion",
    difficulty: "core",
    prompt: "Convert to radians.",
    latex: "150^\\circ",
    answer: "5pi/6",
    acceptedAnswers: ["5π/6", "5\\pi/6", "\\frac{5\\pi}{6}"],
    diagnosticTag: "trig-degrees-to-radians",
  },
  {
    id: "q8",
    section: "Trigonometric Functions and Graphs",
    skill: "Exact trigonometric values",
    difficulty: "core",
    prompt: "Evaluate exactly.",
    latex: "\\sin\\left(\\frac{\\pi}{3}\\right)",
    answer: "sqrt(3)/2",
    acceptedAnswers: [
      "√3/2",
      "sqrt3/2",
      "\\sqrt{3}/2",
      "\\frac{\\sqrt{3}}{2}",
    ],
    diagnosticTag: "trig-exact-values",
  },
  {
    id: "q9",
    section: "Trigonometric Functions and Graphs",
    skill: "Quadrant signs",
    difficulty: "core",
    prompt: "Choose the correct sign of $\\cos(5\\pi/6)$.",
    latex: "\\cos\\left(\\frac{5\\pi}{6}\\right)",
    answer: "B",
    choices: [
      { label: "A", text: "Positive" },
      { label: "B", text: "Negative" },
      { label: "C", text: "Zero" },
      { label: "D", text: "Undefined" },
    ],
    diagnosticTag: "trig-unit-circle-signs",
  },
  {
    id: "q10",
    section: "Trigonometric Functions and Graphs",
    skill: "Period of transformed trigonometric graphs",
    difficulty: "standard",
    prompt: "Find the period.",
    latex: "y=3\\sin(2x)+1",
    answer: "pi",
    acceptedAnswers: ["π", "\\pi"],
    diagnosticTag: "trig-amplitude-period",
  },
  {
    id: "q11",
    section: "Trigonometric Functions and Graphs",
    skill: "Solving trigonometric equations on a domain",
    difficulty: "standard",
    prompt: "Choose the solution set.",
    latex: "0\\le x\\le 2\\pi, \\quad 2\\sin(x)-1=0",
    answer: "B",
    choices: [
      { label: "A", text: "$x=\\frac{\\pi}{6}$ only" },
      { label: "B", text: "$x=\\frac{\\pi}{6},\\;\\frac{5\\pi}{6}$" },
      { label: "C", text: "$x=\\frac{7\\pi}{6},\\;\\frac{11\\pi}{6}$" },
      { label: "D", text: "$x=\\frac{\\pi}{3},\\;\\frac{2\\pi}{3}$" },
    ],
    diagnosticTag: "trig-equation-domain",
  },
  {
    id: "q12",
    section: "Trigonometric Functions and Graphs",
    skill: "Trigonometric identities",
    difficulty: "standard",
    prompt: "Simplify.",
    latex: "\\tan(x)\\cos(x)",
    answer: "sin(x)",
    acceptedAnswers: ["\\sin(x)", "sin x", "\\sin x"],
    diagnosticTag: "trig-identities-simplification",
  },
  {
    id: "q13",
    section: "Differential Calculus",
    skill: "Average rate of change",
    difficulty: "core",
    prompt: "Find the average rate of change from $x=1$ to $x=5$.",
    latex: "f(1)=3, \\quad f(5)=15",
    answer: "3",
    diagnosticTag: "calculus-average-rate-of-change",
  },
  {
    id: "q14",
    section: "Differential Calculus",
    skill: "Differentiating polynomial functions",
    difficulty: "core",
    prompt: "Differentiate.",
    latex: "y=4x^5-3x^2+7x-9",
    answer: "20x^4-6x+7",
    acceptedAnswers: ["dy/dx=20x^4-6x+7", "y'=20x^4-6x+7"],
    diagnosticTag: "calculus-differentiate-polynomial",
  },
  {
    id: "q15",
    section: "Differential Calculus",
    skill: "Finding tangent gradients",
    difficulty: "core",
    prompt: "Find the gradient of the tangent at $x=2$.",
    latex: "y=x^3-4x",
    answer: "8",
    diagnosticTag: "calculus-tangent-gradient",
  },
  {
    id: "q16",
    section: "Differential Calculus",
    skill: "Solving for stationary x-values",
    difficulty: "standard",
    prompt: "Find the smaller stationary x-value.",
    latex: "y=x^3-3x^2-9x+5",
    answer: "-1",
    diagnosticTag: "calculus-stationary-x-values",
  },
  {
    id: "q17",
    section: "Differential Calculus",
    skill: "Classifying stationary points",
    difficulty: "standard",
    prompt: "For $f''(2)<0$, choose the stationary point classification.",
    latex: "f'(2)=0, \\quad f''(2)<0",
    answer: "A",
    choices: [
      { label: "A", text: "Local maximum" },
      { label: "B", text: "Local minimum" },
      { label: "C", text: "Horizontal point of inflection" },
      { label: "D", text: "Not stationary" },
    ],
    diagnosticTag: "calculus-stationary-classification",
  },
  {
    id: "q18",
    section: "Differential Calculus",
    skill: "Interpreting derivative signs",
    difficulty: "extension",
    prompt: "Choose the interval where the function is decreasing.",
    latex: "f'(x)=3(x+1)(x-3)",
    answer: "C",
    choices: [
      { label: "A", text: "$(-\\infty,-1)$" },
      { label: "B", text: "$(3,\\infty)$" },
      { label: "C", text: "$(-1,3)$" },
      { label: "D", text: "all real $x$" },
    ],
    diagnosticTag: "calculus-derivative-sign-intervals",
  },
  {
    id: "q19",
    section: "Integral Calculus",
    skill: "Indefinite integration of polynomials",
    difficulty: "core",
    prompt: "Find the indefinite integral.",
    latex: "\\int \\left(6x^2-4x+3\\right)\\,dx",
    answer: "2x^3-2x^2+3x+C",
    acceptedAnswers: ["2x^3 - 2x^2 + 3x + C", "2x^3-2x^2+3x+c"],
    diagnosticTag: "integration-indefinite-polynomial",
  },
  {
    id: "q20",
    section: "Integral Calculus",
    skill: "Initial conditions and particular primitives",
    difficulty: "standard",
    prompt: "Find $C$.",
    latex: "f'(x)=6x+4, \\quad f(x)=3x^2+4x+C, \\quad f(1)=9",
    answer: "2",
    diagnosticTag: "integration-initial-condition-c",
  },
  {
    id: "q21",
    section: "Integral Calculus",
    skill: "Evaluating definite integrals",
    difficulty: "standard",
    prompt: "Evaluate the definite integral.",
    latex: "\\int_0^2 \\left(3x^2+1\\right)\\,dx",
    answer: "10",
    diagnosticTag: "integration-definite-polynomial",
  },
  {
    id: "q22",
    section: "Integral Calculus",
    skill: "Signed area and total area",
    difficulty: "standard",
    prompt: "Choose the total area between the curve and the x-axis.",
    latex: "y=x-1, \\quad 0\\le x\\le 3",
    answer: "C",
    choices: [
      { label: "A", text: "$2$" },
      { label: "B", text: "$\\frac{3}{2}$ square units" },
      { label: "C", text: "$\\frac{5}{2}$ square units" },
      { label: "D", text: "$4$ square units" },
    ],
    diagnosticTag: "integration-signed-total-area",
  },
  {
    id: "q23",
    section: "Integral Calculus",
    skill: "Trapezoidal rule",
    difficulty: "standard",
    prompt: "Use the Trapezoidal rule to approximate the area.",
    latex: "h=1, \\quad y_0=2, \\quad y_1=5, \\quad y_2=10, \\quad y_3=17",
    answer: "24.5",
    acceptedAnswers: ["49/2", "24.5 square units"],
    diagnosticTag: "integration-trapezoidal-rule",
  },
  {
    id: "q24",
    section: "Integral Calculus",
    skill: "Area between two curves",
    difficulty: "extension",
    prompt: "Find the area between the curves on the given interval.",
    latex: "y=x+4, \\quad y=x^2, \\quad 0\\le x\\le 2",
    answer: "22/3",
    acceptedAnswers: ["7.333", "7.33", "\\frac{22}{3}"],
    diagnosticTag: "integration-area-between-curves",
  },
  {
    id: "q25",
    section: "Financial Mathematics",
    skill: "Growth and decay factors",
    difficulty: "core",
    prompt: "Choose the growth factor for a $6.5\\%$ increase.",
    latex: "6.5\\% \\text{ increase}",
    answer: "C",
    choices: [
      { label: "A", text: "$0.065$" },
      { label: "B", text: "$0.935$" },
      { label: "C", text: "$1.065$" },
      { label: "D", text: "$1.65$" },
    ],
    diagnosticTag: "financial-growth-decay-factor",
  },
  {
    id: "q26",
    section: "Financial Mathematics",
    skill: "Compound interest",
    difficulty: "standard",
    prompt: "Find the value after 3 years, to the nearest cent.",
    latex: "\\$2000 \\text{ is invested at } 4\\% \\text{ p.a. compounded annually.}",
    answer: "2249.73",
    acceptedAnswers: ["$2249.73", "\\$2249.73"],
    diagnosticTag: "financial-compound-interest",
  },
  {
    id: "q27",
    section: "Financial Mathematics",
    skill: "Depreciation",
    difficulty: "standard",
    prompt: "Find the value after 2 years, to the nearest dollar.",
    latex: "\\$10000 \\text{ depreciates by } 10\\% \\text{ per year.}",
    answer: "8100",
    acceptedAnswers: ["$8100", "$8,100", "8100 dollars"],
    diagnosticTag: "financial-depreciation",
  },
  {
    id: "q28",
    section: "Financial Mathematics",
    skill: "Recurrence relations in finance",
    difficulty: "standard",
    prompt: "Find $B_1$.",
    latex: "B_0=1000, \\quad B_{n+1}=1.03B_n+100",
    answer: "1130",
    acceptedAnswers: ["$1130", "$1,130"],
    diagnosticTag: "financial-recurrence-next-term",
  },
  {
    id: "q29",
    section: "Financial Mathematics",
    skill: "Future value of annuities",
    difficulty: "extension",
    prompt: "Find the future value after three end-of-year deposits.",
    latex: "\\$1000 \\text{ is deposited at the end of each year at } 5\\% \\text{ p.a. for 3 years.}",
    answer: "3152.50",
    acceptedAnswers: ["$3152.50", "$3,152.50", "3152.5"],
    diagnosticTag: "financial-future-value-annuities",
  },
  {
    id: "q30",
    section: "Financial Mathematics",
    skill: "Comparing financial options",
    difficulty: "core",
    prompt: "Choose the better option for the larger final value.",
    latex: "\\text{Option A: } \\$3000(1.05)^2 \\quad \\text{Option B: } \\$3000(1.04)^2+\\$80",
    answer: "B",
    choices: [
      { label: "A", text: "Option A" },
      { label: "B", text: "Option B" },
      { label: "C", text: "They are equal" },
      { label: "D", text: "There is not enough information" },
    ],
    diagnosticTag: "financial-comparing-options",
  },
  {
    id: "q31",
    section: "Statistical Analysis",
    skill: "Summary statistics",
    difficulty: "core",
    prompt: "Find the median.",
    latex: "4,\\;6,\\;7,\\;8,\\;10",
    answer: "7",
    diagnosticTag: "statistics-summary-median",
  },
  {
    id: "q32",
    section: "Statistical Analysis",
    skill: "Standardised scores",
    difficulty: "core",
    prompt: "Find the z-score.",
    latex: "\\text{Mean}=68, \\quad \\text{standard deviation}=8, \\quad x=84",
    answer: "2",
    acceptedAnswers: ["z=2", "2 standard deviations"],
    diagnosticTag: "statistics-standardised-score",
  },
  {
    id: "q33",
    section: "Statistical Analysis",
    skill: "Interpreting correlation",
    difficulty: "core",
    prompt: "Choose the best description of the relationship.",
    latex: "r=-0.82",
    answer: "A",
    choices: [
      { label: "A", text: "Strong negative linear relationship" },
      { label: "B", text: "Weak negative linear relationship" },
      { label: "C", text: "Strong positive linear relationship" },
      { label: "D", text: "No linear relationship" },
    ],
    diagnosticTag: "statistics-correlation-interpretation",
  },
  {
    id: "q34",
    section: "Statistical Analysis",
    skill: "Regression prediction",
    difficulty: "standard",
    prompt: "Use the regression line to predict $y$ when $x=8$.",
    latex: "y=2.5x+12",
    answer: "32",
    diagnosticTag: "statistics-regression-prediction",
  },
  {
    id: "q35",
    section: "Statistical Analysis",
    skill: "Residuals",
    difficulty: "standard",
    prompt: "Find the residual.",
    latex: "\\text{actual } y=26, \\quad \\text{predicted } y=20",
    answer: "6",
    acceptedAnswers: ["+6"],
    diagnosticTag: "statistics-residuals",
  },
  {
    id: "q36",
    section: "Statistical Analysis",
    skill: "Normal distribution and empirical rule",
    difficulty: "standard",
    prompt: "Choose the interval containing approximately $95\\%$ of values.",
    latex: "\\mu=70, \\quad \\sigma=5",
    answer: "C",
    choices: [
      { label: "A", text: "$65$ to $75$" },
      { label: "B", text: "$60$ to $75$" },
      { label: "C", text: "$60$ to $80$" },
      { label: "D", text: "$55$ to $85$" },
    ],
    diagnosticTag: "statistics-normal-empirical-rule",
  },
];
