import type { PracticeQuestion } from "../lessons/differentialCalculus";

// Level-6 single-answer challenge sets for Year 12 Extension 2 "Mechanics". The D5 pool and
// multipart D6 are auto-generated by enrichYear12Extension2Depth; these add the single-answer
// D6 the topic was missing. Difficulty comes from reverse/relational mechanics reasoning —
// recover μ from impending-motion conditions, link a–v–x without time, recover an SHM
// amplitude from a speed–position state, a friction-limited circular speed, a terminal
// velocity, or a launch angle from a range/height condition — not from plugging into SUVAT.
// Auto-markable, hand-verified. One per lesson.

// → forces-inclined-planes
export const mechForcesChallenge: PracticeQuestion[] = [
  {
    // Impending up vs down motion: averaging the two limiting forces cancels friction.
    id: "chal-y12e2-mech-1",
    prompt:
      "A block on a rough incline is on the point of slipping UP the plane when a force of 7 N up the plane is applied, and on the point of slipping DOWN when a force of 1 N up the plane is applied. Find the component of gravity down the plane, mg sin θ.",
    latex: "F_{\\uparrow} = mg\\sin\\theta + \\mu mg\\cos\\theta,\\quad F_{\\downarrow} = mg\\sin\\theta - \\mu mg\\cos\\theta",
    answer: "4",
    acceptedAnswers: ["4 N"],
    hint: "Write both limiting conditions; the friction term has opposite sign in each, so add them.",
    explanation:
      "Slipping up: 7 = mg sin θ + μmg cos θ. On the point of slipping down: 1 = mg sin θ − μmg cos θ. Adding eliminates friction: 8 = 2·mg sin θ, so mg sin θ = 4.",
  },
];

// → rectilinear-motion-calculus
export const mechRectilinearChallenge: PracticeQuestion[] = [
  {
    // a = v·dv/dx with v given as a function of position.
    id: "chal-y12e2-mech-2",
    prompt:
      "A particle moving in a straight line (x > 0) has velocity v = 2x. Find its acceleration when x = 3.",
    latex: "a = v\\frac{dv}{dx}",
    answer: "12",
    acceptedAnswers: ["12 m/s²", "12 m/s^2"],
    hint: "When v is a function of x, use a = v·dv/dx.",
    explanation:
      "a = v·dv/dx = (2x)(2) = 4x. At x = 3, a = 12.",
  },
];

// → simple-harmonic-motion-extended
export const mechShmChallenge: PracticeQuestion[] = [
  {
    // Recover the amplitude from a speed–position state using v² = n²(a² − x²).
    id: "chal-y12e2-mech-3",
    prompt:
      "A particle in SHM, x = a cos(nt), has period π and is moving with speed 8 as it passes through x = 3. Find the amplitude a.",
    latex: "v^2 = n^2(a^2 - x^2),\\quad T = \\frac{2\\pi}{n}",
    answer: "5",
    acceptedAnswers: ["a=5"],
    hint: "Find n from the period, then use v² = n²(a² − x²).",
    explanation:
      "T = 2π/n = π ⟹ n = 2. v² = n²(a² − x²): 8² = 2²(a² − 3²) ⟹ 64 = 4(a² − 9) ⟹ a² − 9 = 16 ⟹ a² = 25 ⟹ a = 5.",
  },
];

// → circular-motion-uniform
export const mechCircularChallenge: PracticeQuestion[] = [
  {
    // Friction supplies the centripetal force: v² = μgr.
    id: "chal-y12e2-mech-4",
    prompt:
      "A car rounds a flat circular bend of radius 50 m. Friction (μ = 0.8) provides the centripetal force; g = 10. Find the maximum speed (m/s) at which it can take the bend without slipping.",
    latex: "\\frac{mv^2}{r} = \\mu mg",
    answer: "20",
    acceptedAnswers: ["20 m/s"],
    hint: "Set the required centripetal force mv²/r equal to the maximum friction μmg; the mass cancels.",
    explanation:
      "mv²/r = μmg ⟹ v² = μgr = 0.8 × 10 × 50 = 400 ⟹ v = 20 m/s.",
  },
];

// → resisted-motion
export const mechResistedChallenge: PracticeQuestion[] = [
  {
    // Terminal velocity: set acceleration to zero.
    id: "chal-y12e2-mech-5",
    prompt:
      "A body falls under gravity against a resistance, with acceleration a = g − kv² where g = 10 and k = 0.1. Find its terminal velocity (m/s).",
    latex: "a = g - kv^2",
    answer: "10",
    acceptedAnswers: ["10 m/s"],
    hint: "Terminal velocity is reached when the acceleration is zero.",
    explanation:
      "At terminal velocity a = 0, so kv² = g ⟹ v² = g/k = 10/0.1 = 100 ⟹ v = 10 m/s.",
  },
];

// → projectile-motion-resistance
export const mechProjectileChallenge: PracticeQuestion[] = [
  {
    // Recover the launch angle from a range = max-height condition.
    id: "chal-y12e2-mech-6",
    prompt:
      "A projectile (no air resistance) is launched so that its horizontal range equals its maximum height. Find tan θ, where θ is the launch angle.",
    latex: "R = \\frac{v^2\\sin 2\\theta}{g},\\quad H = \\frac{v^2\\sin^2\\theta}{2g}",
    answer: "4",
    acceptedAnswers: ["tan θ = 4", "tanθ=4"],
    hint: "Set R = H and use sin 2θ = 2 sin θ cos θ.",
    explanation:
      "R = H: v²sin2θ/g = v²sin²θ/(2g) ⟹ sin 2θ = sin²θ/2 ⟹ 2 sin θ cos θ = sin²θ/2 ⟹ 4 cos θ = sin θ ⟹ tan θ = 4.",
  },
];
