import type { PracticeQuestion } from "../lessons/differentialCalculus";

// Level-6 single-answer challenge sets for Year 12 Extension 2 "Calculus" (advanced
// integration). The D5 pool and multipart D6 are auto-generated by enrichYear12Extension2Depth;
// these add the SINGLE-ANSWER D6 the topic was missing. Difficulty is carried by selecting and
// executing the right advanced technique (reduction recurrence, partial fractions, symmetry/
// King rule, Weierstrass t-substitution, volume reconstruction, completing-square → arctan),
// not by routine antidifferentiation. Auto-markable, hand-verified. ≤2 per lesson.

// → reduction-formulae-introduction
export const calcReductionChallenge: PracticeQuestion[] = [
  {
    // Apply the reduction recurrence down the chain from I0.
    id: "chal-y12e2-calc-1",
    prompt:
      "For Iₙ = ∫ sinⁿx dx from 0 to π/2, the reduction formula gives Iₙ = ((n−1)/n)·Iₙ₋₂. Given I₀ = π/2, find I₄.",
    latex: "I_n = \\frac{n-1}{n}\\,I_{n-2},\\quad I_0 = \\tfrac{\\pi}{2}",
    answer: "3π/16",
    acceptedAnswers: ["3pi/16", "\\frac{3\\pi}{16}", "0.589"],
    hint: "Step down twice: I₂ = (1/2)I₀, then I₄ = (3/4)I₂.",
    explanation:
      "I₂ = (1/2)·I₀ = (1/2)(π/2) = π/4. I₄ = (3/4)·I₂ = (3/4)(π/4) = 3π/16.",
  },
];

// → partial-fractions-integration
export const calcPartialFractionsChallenge: PracticeQuestion[] = [
  {
    // Decompose, integrate to logs, then simplify the log combination.
    id: "chal-y12e2-calc-2",
    prompt:
      "∫₁² (3x+5)/((x+1)(x+2)) dx = ln k. Find k.",
    latex: "\\int_1^2 \\frac{3x+5}{(x+1)(x+2)}\\,dx = \\ln k",
    answer: "3",
    acceptedAnswers: ["k=3"],
    hint: "Split into A/(x+1) + B/(x+2), integrate to logs, then combine using log laws.",
    explanation:
      "Partial fractions: (3x+5)/((x+1)(x+2)) = 2/(x+1) + 1/(x+2). Integral = [2ln(x+1) + ln(x+2)]₁² = (2ln3 + ln4) − (2ln2 + ln3) = ln3 + (ln4 − 2ln2) = ln3. So k = 3.",
  },
];

// → trig-identity-integration
export const calcSymmetryChallenge: PracticeQuestion[] = [
  {
    // King-rule symmetry: replace x by (a − x) and add.
    id: "chal-y12e2-calc-3",
    prompt:
      "Evaluate ∫ 1/(1 + tan x) dx from 0 to π/2.",
    latex: "\\int_0^{\\pi/2} \\frac{1}{1+\\tan x}\\,dx",
    answer: "π/4",
    acceptedAnswers: ["pi/4", "\\frac{\\pi}{4}", "0.785"],
    hint: "Let I be the integral; replace x by π/2 − x (so tan x → cot x) and add the two forms.",
    explanation:
      "With x → π/2 − x, I = ∫ 1/(1+cot x) dx from 0 to π/2 = ∫ tan x/(1+tan x) dx from 0 to π/2. Adding to the original: 2I = ∫ 1 dx from 0 to π/2 = π/2, so I = π/4.",
  },
];

// → t-substitution-weierstrass
export const calcTSubstitutionChallenge: PracticeQuestion[] = [
  {
    // Weierstrass substitution reduces the integral to a rational one.
    id: "chal-y12e2-calc-4",
    prompt:
      "Using t = tan(x/2), the integral ∫ 1/(1 + sin x) dx from 0 to π/2 becomes ∫₀¹ 2/(1+t)² dt. Evaluate it.",
    latex: "t = \\tan\\tfrac{x}{2}:\\ \\int_0^1 \\frac{2}{(1+t)^2}\\,dt",
    answer: "1",
    acceptedAnswers: [],
    hint: "Antiderivative of 2/(1+t)² is −2/(1+t).",
    explanation:
      "∫₀¹ 2/(1+t)² dt = [−2/(1+t)]₀¹ = −2/2 − (−2/1) = −1 + 2 = 1.",
  },
];

// → volumes-of-revolution
export const calcVolumeChallenge: PracticeQuestion[] = [
  {
    // Reconstruct a constant from the volume integral.
    id: "chal-y12e2-calc-5",
    prompt:
      "The region under y = eˣ from x = 0 to x = 1 is rotated about the x-axis. Its volume is V = (π/2)(e² − k). Find k.",
    latex: "V = \\pi\\int_0^1 (e^x)^2\\,dx = \\tfrac{\\pi}{2}(e^2 - k)",
    answer: "1",
    acceptedAnswers: ["k=1"],
    hint: "V = π∫₀¹ e²ˣ dx; integrate and compare with (π/2)(e² − k).",
    explanation:
      "V = π∫₀¹ e²ˣ dx = π[e²ˣ/2]₀¹ = π(e² − 1)/2 = (π/2)(e² − 1). Matching gives k = 1.",
  },
];

// → completing-square-integration
export const calcCompletingSquareChallenge: PracticeQuestion[] = [
  {
    // Completing the square → arctan form → definite evaluation (integral-structural).
    id: "chal-y12e2-calc-6",
    prompt:
      "∫₂⁴ 1/(x² − 4x + 8) dx = π/k. Find k.",
    latex: "\\int_2^4 \\frac{1}{x^2 - 4x + 8}\\,dx = \\frac{\\pi}{k}",
    answer: "8",
    acceptedAnswers: ["k=8"],
    hint: "Complete the square to (x−2)² + 2², use ∫1/(u²+a²)du = (1/a)arctan(u/a), then evaluate.",
    explanation:
      "x² − 4x + 8 = (x−2)² + 4 = (x−2)² + 2². So the antiderivative is (1/2)arctan((x−2)/2). Evaluating 2→4: (1/2)[arctan(1) − arctan(0)] = (1/2)(π/4) = π/8. Thus π/k = π/8, k = 8.",
  },
];
