import type { PracticeQuestion } from "../lessons/differentialCalculus";

// Level-6 single-answer challenge sets for Year 12 Extension 2 "Vectors in 3D". The D5 pool
// and multipart D6 are auto-generated by enrichYear12Extension2Depth; these add the single-
// answer D6 the topic was missing. Difficulty comes from recovering a component/parameter or
// proving a perpendicularity through 3D vector structure (magnitude, dot product, line
// parameter, projection, sphere geometry, vector proof), not from routine arithmetic.
// Auto-markable, hand-verified. One per lesson.

// → vectors-and-points-3d
export const vec3dMagnitudeChallenge: PracticeQuestion[] = [
  {
    // Recover a component from a magnitude condition.
    id: "chal-y12e2-v3d-1",
    prompt:
      "The vector a = (2, k, 4) has magnitude 6. Find the positive value of k.",
    latex: "|\\mathbf{a}| = \\sqrt{2^2 + k^2 + 4^2} = 6",
    answer: "4",
    acceptedAnswers: ["k=4"],
    hint: "Square the magnitude: 2² + k² + 4² = 36.",
    explanation:
      "|a|² = 4 + k² + 16 = 36 ⟹ k² = 16 ⟹ k = 4 (positive value).",
  },
];

// → dot-product-and-angle
export const vec3dPerpendicularChallenge: PracticeQuestion[] = [
  {
    // Recover k from the perpendicularity (zero dot product) condition.
    id: "chal-y12e2-v3d-2",
    prompt:
      "Find the value of k for which the vectors (1, 2, k) and (3, −1, 2) are perpendicular.",
    latex: "(1,2,k)\\cdot(3,-1,2) = 0",
    answer: "-1/2",
    acceptedAnswers: ["k=-1/2", "−1/2", "-0.5"],
    hint: "Perpendicular vectors have a zero dot product.",
    explanation:
      "(1,2,k)·(3,−1,2) = 3 − 2 + 2k = 1 + 2k. Setting this to 0 gives 2k = −1, so k = −1/2.",
  },
];

// → equations-of-lines-3d
export const vec3dLineChallenge: PracticeQuestion[] = [
  {
    // Recover a coordinate via the line parameter (consistency across components).
    id: "chal-y12e2-v3d-3",
    prompt:
      "The line r = (1, 0, 2) + t(2, 1, −1) passes through the point (5, 2, k). Find k.",
    latex: "\\mathbf{r} = (1,0,2) + t(2,1,-1)",
    answer: "0",
    acceptedAnswers: ["k=0"],
    hint: "Find t from the x-coordinate, check it is consistent in y, then read off z.",
    explanation:
      "x: 1 + 2t = 5 ⟹ t = 2. Check y: 0 + 2 = 2 ✓. Then z: 2 − t = 2 − 2 = 0, so k = 0.",
  },
];

// → vector-applications-exam-practice
export const vec3dProjectionChallenge: PracticeQuestion[] = [
  {
    // Recover a component from a scalar-projection condition.
    id: "chal-y12e2-v3d-4",
    prompt:
      "The scalar projection of a = (4, k, 2) onto b = (2, 1, 2) has length 5. Find k.",
    latex: "\\frac{\\mathbf{a}\\cdot\\mathbf{b}}{|\\mathbf{b}|} = 5",
    answer: "3",
    acceptedAnswers: ["k=3"],
    hint: "Scalar projection = (a·b)/|b|; here |b| = 3.",
    explanation:
      "a·b = 8 + k + 4 = 12 + k, and |b| = √(4+1+4) = 3. So (12 + k)/3 = 5 ⟹ 12 + k = 15 ⟹ k = 3.",
  },
];

// → vector-curves-circles-spheres
export const vec3dSphereChallenge: PracticeQuestion[] = [
  {
    // Recover the radius from a point on the sphere, then the extremal coordinate.
    id: "chal-y12e2-v3d-5",
    prompt:
      "A sphere has centre (1, 2, 2) and passes through the point (1, 5, 6). Find the largest z-coordinate of any point on the sphere.",
    latex: "|\\mathbf{r} - (1,2,2)| = R",
    answer: "7",
    acceptedAnswers: [],
    hint: "First find the radius as the distance from the centre to the given point, then add it to the centre's z-coordinate.",
    explanation:
      "Radius R = |(1,5,6) − (1,2,2)| = |(0,3,4)| = √(9+16) = 5. The largest z is the centre's z plus the radius: 2 + 5 = 7.",
  },
];

// → geometric-proofs-vectors
export const vec3dProofChallenge: PracticeQuestion[] = [
  {
    // Vector proof that the median to the base of an isosceles triangle is perpendicular.
    id: "chal-y12e2-v3d-6",
    prompt:
      "In triangle OAB, OA = a and OB = b with |a| = |b|. M is the midpoint of AB. Find the value of OM · AB.",
    latex: "\\overrightarrow{OM} = \\tfrac{1}{2}(\\mathbf{a}+\\mathbf{b}),\\quad \\overrightarrow{AB} = \\mathbf{b}-\\mathbf{a}",
    answer: "0",
    acceptedAnswers: [],
    hint: "Write OM and AB in terms of a and b, then expand the dot product.",
    explanation:
      "OM · AB = ½(a + b)·(b − a) = ½(|b|² − |a|²). Since |a| = |b|, this is 0 — the median to the base of an isosceles triangle is perpendicular to the base.",
  },
];
