import {
  answer,
  choice,
  cubicGraph,
  cubicLineGraph,
  quadraticLineGraph,
  type GraphsEquationsMasteryMap,
} from "./graphsEquationsQualityHelpers";

export const graphsEquationsQualityApplied: GraphsEquationsMasteryMap = {
  "simultaneous-equations-nonlinear": [
    answer({ id: "y11adv-ge-sim-qm1", prompt: "Find both points of intersection.", latex: "y=x^2,\\qquad y=x+2", answer: "(-1,1) and (2,4)", acceptedAnswers: ["(2,4), (-1,1)"], hint: "Equate the two expressions for y, solve the resulting quadratic, then recover each y-coordinate.", explanation: "At an intersection, $x^2=x+2$, so $x^2-x-2=(x-2)(x+1)=0$. Thus $x=2$ or $x=-1$. Substitution into the line gives $y=4$ or $y=1$, producing points $(2,4)$ and $(-1,1)$.", diagnosticIntent: "Checks the complete substitution workflow, including returning from x-values to coordinate pairs.", taskType: "procedural", difficulty: 3 }),
    choice({ id: "y11adv-ge-sim-qm2", prompt: "Which equation in x correctly represents the intersections?", latex: "y=2x-1,\\qquad y=x^2+3", answer: "B", choices: ["x^2+2x+2=0", "x^2-2x+4=0", "x^2-2x-4=0", "2x^3-x+3=0"], distractorMisconceptions: { A: "Moves the linear terms with the wrong signs.", C: "Changes the sign of the constant from the quadratic.", D: "Multiplies the two equations instead of equating their y-values." }, hint: "Set the right-hand sides equal, then move every term to one side without multiplying them.", explanation: "Intersections satisfy $2x-1=x^2+3$. Rearranging gives $x^2-2x+4=0$, which is option B. The negative discriminant also shows that these particular graphs have no real intersection.", diagnosticIntent: "Diagnoses algebraic setup errors before the discriminant or quadratic formula is applied.", taskType: "analytical", difficulty: 3 }),
    answer({ id: "y11adv-ge-sim-qm3", prompt: "Find the intersection points of the circle and horizontal line.", latex: "x^2+y^2=25,\\qquad y=3", answer: "(-4,3) and (4,3)", acceptedAnswers: ["(4,3), (-4,3)"], hint: "Substitute the fixed y-value into the circle, then take both square roots for x.", explanation: "Substitution gives $x^2+3^2=25$, hence $x^2=16$ and $x=\\pm4$. The y-coordinate remains 3 for both solutions, so the intersection points are $(-4,3)$ and $(4,3)$.", diagnosticIntent: "Checks a nonlinear system in which the square-root symmetry must produce two coordinate solutions.", taskType: "problem-solving", difficulty: 3 }),
    choice({ id: "y11adv-ge-sim-qm4", prompt: "After substitution, the quadratic has discriminant zero. What does this mean geometrically?", latex: "\\Delta=0", answer: "C", choices: ["the line misses the curve", "the line crosses the curve at two points", "the line is tangent and shares one point with the curve", "the two equations are identical everywhere"], distractorMisconceptions: { A: "Confuses zero discriminant with a negative discriminant.", B: "Confuses a repeated solution with two distinct solutions.", D: "Treats one repeated intersection as infinitely many common points." }, hint: "Relate the number of distinct real roots of the substituted quadratic to common points of the graphs.", explanation: "A zero discriminant gives one repeated real x-value. The line and quadratic curve therefore share one point and have equal local direction there: the line is tangent. A negative discriminant would instead mean no real intersection.", diagnosticIntent: "Checks the geometric meaning of a repeated algebraic solution in a line-curve system.", taskType: "analytical", difficulty: 3 }),
    choice({ id: "y11adv-ge-sim-qm5", prompt: "A student solves the substituted quadratic and reports only x=-1 and x=2. What is missing?", latex: "y=x^2,\\qquad y=x+2", answer: "D", choices: ["nothing; simultaneous solutions are always x-values only", "the discriminant", "a third x-value", "the corresponding y-values and the coordinate pairs"], distractorMisconceptions: { A: "Stops before satisfying both unknowns in the system.", B: "Adds an unnecessary calculation after the roots are already known.", C: "Assumes every nonlinear system must produce three solutions." }, hint: "A solution of two equations in x and y must specify values for both variables.", explanation: "The x-values locate only the horizontal coordinates. Substituting them into either original equation gives $y=1$ and $y=4$, so the actual simultaneous solutions are $(-1,1)$ and $(2,4)$. Therefore D identifies the incomplete step.", diagnosticIntent: "Targets incomplete reporting that loses the geometric meaning of simultaneous solutions as intersection points.", taskType: "analytical", difficulty: 4 }),
    answer({ id: "y11adv-ge-sim-qm6", prompt: "Find k so that the line is tangent to the parabola, then give the tangent point.", latex: "y=2x+k,\\qquad y=x^2", answer: "k=-1; tangent point (1,1)", acceptedAnswers: ["k=-1 at (1,1)"], hint: "Substitute the line into the parabola and set the resulting discriminant to zero.", explanation: "Tangency requires $x^2-2x-k=0$ to have a repeated root. Its discriminant is $4+4k$, so $k=-1$. The repeated root is $x=1$, and either equation gives $y=1$, hence the tangent point is $(1,1)$.", diagnosticIntent: "Assesses parameter recovery from the discriminant and completion of the geometric tangency information.", taskType: "problem-solving", difficulty: 4 }),
    answer({ id: "y11adv-ge-sim-qm7", prompt: "Classify the number of real intersections for every real k.", latex: "y=x^2+1,\\qquad y=kx", answer: "two if |k|>2; one tangent if |k|=2; none if |k|<2", acceptedAnswers: ["0 for -2<k<2, 1 for k=±2, 2 otherwise"], hint: "The intersection equation has discriminant k^2-4; classify its sign.", explanation: "Equating gives $x^2-kx+1=0$, whose discriminant is $k^2-4$. It is positive for $|k|>2$, zero for $|k|=2$, and negative for $|k|<2$. These cases yield two, one tangent, and zero real intersections respectively.", diagnosticIntent: "Investigates an entire parameter family by translating discriminant sign intervals into graph geometry.", taskType: "investigative", difficulty: 4 }),
    answer({ id: "y11adv-ge-sim-qm8", prompt: "Use the graph and algebra to find both intersection points and explain why there cannot be a third.", latex: "y=x^2-1,\\qquad y=x+1", answer: "(-1,0) and (2,3); no third point because the intersection equation is quadratic", acceptedAnswers: ["(-1,0),(2,3), at most two roots"], hint: "Equate the two functions, factor the resulting quadratic, then connect its degree to the maximum number of solutions.", explanation: "$x^2-1=x+1$ gives $x^2-x-2=(x+1)(x-2)=0$. The points are $(-1,0)$ and $(2,3)$. Since the substituted equation is a nonzero quadratic, it has at most two real roots, so no third intersection is possible.", diagnosticIntent: "Synthesises graphical evidence, exact algebra and a degree argument about the completeness of the solution set.", taskType: "synthesis", difficulty: 5, cartesianGraph: quadraticLineGraph({ a: 1, b: 0, c: -1, label: "y=x²-1" }, { m: 1, b: 1, label: "y=x+1" }, { description: "Upward parabola and rising line intersecting at negative one and two", points: [{ x: -1, y: 0, label: "(-1,0)" }, { x: 2, y: 3, label: "(2,3)" }], xMin: -3, xMax: 3, yMin: -3, yMax: 6 }) }),
    answer({ id: "y11adv-ge-sim-qm9", prompt: "Find all c for which the line is tangent to the circle, and find each tangent point.", latex: "x^2+y^2=4,\\qquad y=x+c", answer: "c=±2sqrt(2); points (-sqrt(2),sqrt(2)) and (sqrt(2),-sqrt(2))", acceptedAnswers: ["c=2√2 at (-√2,√2); c=-2√2 at (√2,-√2)"], hint: "Substitute the line into the circle and require the quadratic in x to have a repeated root.", explanation: "Substitution gives $2x^2+2cx+c^2-4=0$. Tangency requires $\\Delta=(2c)^2-8(c^2-4)=32-4c^2=0$, so $c=\\pm2\\sqrt2$. The repeated root is $x=-c/2$, and $y=x+c=c/2$, giving the two stated points.", diagnosticIntent: "Investigates a line-circle parameter family and connects the repeated root to exact tangent coordinates.", taskType: "investigative", difficulty: 5 }),
    answer({ id: "y11adv-ge-sim-qm10", prompt: "Find every slope m for a line through (0,1) tangent to the parabola, then state the tangent x-coordinates.", latex: "y=mx+1,\\qquad y=x^2-3x+4", answer: "m=-3±2sqrt(3); tangent x=(m+3)/2=±sqrt(3)", acceptedAnswers: ["m=-3+2√3 or -3-2√3; x=±√3"], hint: "Equate the functions and force the resulting quadratic to have one repeated root.", explanation: "Intersections satisfy $x^2-(m+3)x+3=0$. Tangency requires $(m+3)^2-12=0$, so $m=-3\\pm2\\sqrt3$. The repeated root is $x=(m+3)/2$, giving $x=\\sqrt3$ for the plus case and $x=-\\sqrt3$ for the minus case.", diagnosticIntent: "Synthesises a fixed-point line family, discriminant constraint and exact recovery of both tangent locations.", taskType: "synthesis", difficulty: 5 }),
  ],

  "graphs-equations-exam-practice": [
    answer({ id: "y11adv-ge-ex-qm1", prompt: "Show that x-2 is a factor, then fully factorise P.", latex: "P(x)=x^3-4x^2+x+6", answer: "P(2)=0; P(x)=(x-2)(x-3)(x+1)", acceptedAnswers: ["(x+1)(x-2)(x-3)"], hint: "Evaluate P(2), then divide by x-2 and factor the resulting quadratic.", explanation: "$P(2)=8-16+2+6=0$, so $x-2$ is a factor. Division gives $x^2-2x-3=(x-3)(x+1)$. Hence $P(x)=(x-2)(x-3)(x+1)$.", diagnosticIntent: "Checks a complete exam-style factor-theorem chain from verification to full cubic factorisation.", taskType: "procedural", difficulty: 3 }),
    choice({ id: "y11adv-ge-ex-qm2", prompt: "Find alpha^2+beta^2 without solving for the roots.", latex: "2x^2-5x+1=0", answer: "C", choices: ["25/4", "17/4", "21/4", "23/2"], distractorMisconceptions: { A: "Uses the square of the root sum without subtracting twice the product.", B: "Subtracts the product only once.", D: "Uses unnormalised coefficients in the identity." }, hint: "First find the root sum and product, then use S^2-2P.", explanation: "Vieta gives $S=5/2$ and $P=1/2$. Therefore $\\alpha^2+\\beta^2=S^2-2P=25/4-1=21/4$. Option C uses the normalised product and removes the full cross term.", diagnosticIntent: "Tests efficient selection and execution of a Vieta identity in an exam context.", taskType: "analytical", difficulty: 3 }),
    answer({ id: "y11adv-ge-ex-qm3", prompt: "State the intercepts, multiplicity behaviour and end behaviour shown by the polynomial.", latex: "P(x)=(x+1)^2(x-3)", answer: "touches at (-1,0), crosses at (3,0), y-intercept (0,-3); falls left and rises right", acceptedAnswers: ["x=-1 touch, x=3 cross, y=-3, left down right up"], hint: "Use each factor's exponent, evaluate P(0), and read the sign of the cubic leading term.", explanation: "The double root $-1$ is a touch and the simple root 3 is a crossing. Also $P(0)=1(-3)=-3$. Since the leading term is positive $x^3$, the graph falls on the left and rises on the right.", diagnosticIntent: "Checks rapid extraction of the full qualitative graph from factored form.", taskType: "problem-solving", difficulty: 3, cartesianGraph: cubicGraph({ a: 1, b: -1, c: -5, d: -3 }, { description: "Positive cubic touching at negative one and crossing the x-axis at three", label: "y=P(x)", points: [{ x: -1, y: 0, label: "(-1,0)" }, { x: 3, y: 0, label: "(3,0)" }], xMin: -3, xMax: 4, yMin: -8, yMax: 8 }) }),
    choice({ id: "y11adv-ge-ex-qm4", prompt: "How many real intersection points do the two graphs have?", latex: "y=x^2-2,\\qquad y=2x+1", answer: "B", choices: ["none", "two", "one tangent point", "three"], distractorMisconceptions: { A: "Assumes the upward parabola lies above the line everywhere.", C: "Treats a positive discriminant as a repeated root.", D: "Uses the cubic maximum rather than the quadratic intersection limit." }, hint: "Equate the functions and inspect the discriminant or factor the resulting quadratic.", explanation: "$x^2-2=2x+1$ gives $x^2-2x-3=0$, which factors as $(x-3)(x+1)$. There are two distinct real x-values, so the graphs meet at two points and B is correct.", diagnosticIntent: "Checks efficient classification of a nonlinear system before coordinate calculation.", taskType: "analytical", difficulty: 3 }),
    choice({ id: "y11adv-ge-ex-qm5", prompt: "A student evaluates P(3) to test whether x+3 is a factor. Which correction is required?", latex: "\\text{candidate factor }x+3", answer: "A", choices: ["evaluate P(-3)", "evaluate P(0)", "differentiate P at 3", "divide the leading coefficient by 3"], distractorMisconceptions: { B: "Confuses a factor test with the polynomial's constant term.", C: "Introduces a derivative test that is relevant only after a root is known and multiplicity is questioned.", D: "Uses coefficient arithmetic unrelated to the factor theorem." }, hint: "Find the x-value that makes x+3 equal zero.", explanation: "The factor $x+3=x-(-3)$ corresponds to the root $x=-3$. The factor theorem therefore requires $P(-3)=0$. Evaluating $P(3)$ tests the different candidate factor $x-3$, so A is the necessary correction.", diagnosticIntent: "Targets a high-frequency sign error inside a mixed exam-practice setting.", taskType: "analytical", difficulty: 4 }),
    answer({ id: "y11adv-ge-ex-qm6", prompt: "Fully factorise P and solve P(x)>=0.", latex: "P(x)=x^3+2x^2-x-2", answer: "P=(x+2)(x+1)(x-1); x in [-2,-1] union [1,infinity)", acceptedAnswers: ["(x+2)(x+1)(x-1), [-2,-1]∪[1,∞)"], hint: "Factor by grouping, then track the sign across the three simple roots from the positive right end.", explanation: "$P=x^2(x+2)-1(x+2)=(x+2)(x^2-1)=(x+2)(x+1)(x-1)$. A positive cubic alternates sign across the simple roots $-2,-1,1$, so it is nonnegative on $[-2,-1]\\cup[1,\\infty)$.", diagnosticIntent: "Combines factorisation and graphical sign reasoning in a complete inequality solution.", taskType: "problem-solving", difficulty: 4 }),
    answer({ id: "y11adv-ge-ex-qm7", prompt: "Investigate all k for which one root is twice the other.", latex: "x^2+(k+2)x+2k=0", answer: "k=1 or k=4", acceptedAnswers: ["1,4"], hint: "Let the roots be r and 2r, use both Vieta equations, then eliminate r without discarding valid signs.", explanation: "Vieta gives $3r=-(k+2)$ and $2r^2=2k$, so $r^2=k$. Squaring the sum equation yields $9k=(k+2)^2$, hence $k^2-5k+4=0$. Therefore $k=1$ or $k=4$, and direct substitution confirms both root pairs.", diagnosticIntent: "Investigates a relational root constraint through simultaneous Vieta equations and verification.", taskType: "investigative", difficulty: 4 }),
    answer({ id: "y11adv-ge-ex-qm8", prompt: "Fully factorise P, state its intercept behaviour, and solve P(x)>=0.", latex: "P(x)=x^3+x^2-4x-4", answer: "P=(x+2)(x+1)(x-2); crosses at -2,-1,2; solution [-2,-1] union [2,infinity)", acceptedAnswers: ["(x+1)(x-2)(x+2), [-2,-1]∪[2,∞)"], hint: "Group terms to expose x+1, then use the three simple roots to build a sign chart.", explanation: "$P=x^2(x+1)-4(x+1)=(x+1)(x-2)(x+2)$. Each root is simple, so the graph crosses at $-2,-1,2$. Its positive cubic sign pattern is $-,+,-,+$, giving $P\\ge0$ on $[-2,-1]\\cup[2,\\infty)$.", diagnosticIntent: "Synthesises factorisation, multiplicity, end behaviour and interval reasoning in one exam-standard response.", taskType: "synthesis", difficulty: 5 }),
    answer({ id: "y11adv-ge-ex-qm9", prompt: "Find c so the line is tangent to the parabola, then find the tangent point.", latex: "y=x+c,\\qquad y=x^2-4x+5", answer: "c=-5/4; tangent point (5/2,5/4)", acceptedAnswers: ["c=-1.25 at (2.5,1.25)"], hint: "Equate the functions, set the discriminant to zero, and use the repeated root for the coordinate.", explanation: "Equating gives $x^2-5x+5-c=0$. Tangency requires $25-4(5-c)=5+4c=0$, so $c=-5/4$. The repeated root is $x=5/2$, and the line gives $y=5/2-5/4=5/4$.", diagnosticIntent: "Synthesises discriminant-based parameter recovery with exact coordinate reporting.", taskType: "investigative", difficulty: 5 }),
    answer({ id: "y11adv-ge-ex-qm10", prompt: "Reconstruct P from the graph information, then find every intersection with y=4.", latex: "\\text{cross at }x=-2,\\quad \\text{touch at }x=1,\\quad P(0)=4", answer: "P=2(x+2)(x-1)^2; intersections (-sqrt(3),4), (0,4), (sqrt(3),4)", acceptedAnswers: ["2x^3-6x+4; x=0,±√3 at y=4"], hint: "Use the root multiplicities and P(0) to find the scale factor, then solve P(x)=4 by factoring.", explanation: "The graph data gives $P=a(x+2)(x-1)^2$. Since $P(0)=2a=4$, $a=2$. Solving $2(x+2)(x-1)^2=4$ simplifies to $2x^3-6x=2x(x^2-3)=0$, so $x=0,\\pm\\sqrt3$ and each point has y-coordinate 4.", diagnosticIntent: "Synthesises graph-to-equation reconstruction, multiplicity, scale recovery and a nonlinear line-cubic system.", taskType: "synthesis", difficulty: 5, cartesianGraph: cubicLineGraph({ a: 2, b: 0, c: -6, d: 4, label: "y=P(x)" }, { m: 0, b: 4, label: "y=4" }, { description: "Cubic crossing at negative two, touching at one, and meeting a horizontal line three times", points: [{ x: 0, y: 4, label: "(0,4)" }], xMin: -3, xMax: 3, yMin: -5, yMax: 8 }) }),
  ],
};
