import {
  richAnswer as a,
  richChoice as c,
  type WorkingFunctionsMasteryMap,
} from "./workingFunctionsQualityHelpers";

export const workingFunctionsQualityCore: WorkingFunctionsMasteryMap = {
  "function-notation-domain-range": [
    a({
      id: "y11adv-fn-qm1",
      prompt: "Evaluate the two stated outputs and enter their sum.",
      latex: "f(x)=x^2-3x+2,\\qquad f(-2)+f(3)",
      answer: "14",
      acceptedAnswers: ["f(-2)+f(3)=14"],
      hint: "Substitute each input with brackets, evaluate the powers first, and only then add the two outputs.",
      explanation: "Using brackets gives f(-2)=(-2)²-3(-2)+2=12 and f(3)=3²-3(3)+2=2. Therefore the requested sum is 12+2=14.",
      diagnosticIntent: "This checks accurate substitution of a negative input and whether both function evaluations are combined as requested.",
      taskType: "procedural",
      difficulty: 3,
    }),
    c({
      id: "y11adv-fn-qm2",
      prompt: "Which set is the real domain of the stated function?",
      latex: "g(x)=\\frac{\\sqrt{x+1}}{x-3}",
      answer: "C",
      choices: ["x\\ge -1", "x\\ne3", "[-1,3)\\cup(3,\\infty)", "(-1,3)\\cup(3,\\infty)"],
      hint: "Intersect the square-root condition x+1 greater than or equal to zero with the denominator restriction x not equal to 3.",
      explanation: "The square root requires x+1≥0, so x≥-1, while the denominator requires x≠3. Their intersection is [-1,3)∪(3,∞), including -1 but excluding 3.",
      diagnosticIntent: "This distinguishes students who combine simultaneous domain restrictions from those who apply only one restriction or make it strict.",
      taskType: "analytical",
      difficulty: 3,
      distractorMisconceptions: {
        A: "Applies the square-root restriction but ignores the zero denominator.",
        B: "Applies the denominator restriction but ignores the square-root boundary.",
        D: "Incorrectly excludes the valid square-root endpoint x=-1.",
      },
    }),
    a({
      id: "y11adv-fn-qm3",
      prompt: "Determine the parameter from the stated function value.",
      latex: "f(x)=ax^2-2x+1,\\qquad f(-2)=17",
      answer: "3",
      acceptedAnswers: ["a=3"],
      hint: "Replace x by -2, retain the bracket through squaring, and solve the resulting linear equation in a.",
      explanation: "Substitution gives 4a+4+1=17 because (-2)²=4 and -2(-2)=4. Hence 4a=12 and the required parameter is a=3.",
      diagnosticIntent: "This checks reverse use of function notation, negative-input sign control, and recovery of an unknown coefficient.",
      taskType: "problem-solving",
      difficulty: 3,
    }),
    c({
      id: "y11adv-fn-qm4",
      prompt: "Which range follows from the completed-square form?",
      latex: "h(x)=-(x-3)^2+5,\\qquad x\\in\\mathbb R",
      cartesianGraph: {
        description: "Downward-opening parabola h with maximum point (3,5), supporting inference of its complete output range.",
        xMin: -1,
        xMax: 7,
        yMin: -5,
        yMax: 7,
        parabolas: [{ kind: "quadratic", a: -1, b: 6, c: -4, label: "h(x)" }],
        points: [{ x: 3, y: 5, label: "maximum" }],
      },
      answer: "B",
      choices: ["y\\ge5", "y\\le5", "y\\ge3", "y\\le3"],
      hint: "A square is non-negative; multiplying it by -1 makes that term non-positive, so identify the largest possible output.",
      explanation: "Since (x-3)²≥0, the term -(x-3)²≤0. Thus h(x) can equal 5 at x=3 and otherwise lies below 5, giving the range y≤5.",
      diagnosticIntent: "This checks whether range is inferred from structure rather than confused with the horizontal coordinate of the vertex.",
      taskType: "analytical",
      difficulty: 3,
      distractorMisconceptions: {
        A: "Treats the downward-opening quadratic as having a minimum instead of a maximum.",
        C: "Uses the vertex x-coordinate as a lower range bound.",
        D: "Uses the vertex x-coordinate as an upper range bound.",
      },
    }),
    a({
      id: "y11adv-fn-qm5",
      prompt: "Find the real domain and give it in interval notation.",
      latex: "p(x)=\\sqrt{\\frac{x-1}{x+2}}",
      answer: "(-infinity,-2) union [1,infinity)",
      acceptedAnswers: ["(-∞,-2)∪[1,∞)", "x<-2 or x>=1"],
      hint: "Use the critical values -2 and 1 to test where the rational expression is non-negative, while excluding the denominator zero.",
      explanation: "The quotient changes sign only at x=-2 and x=1. It is non-negative for x<-2 and x≥1; x=-2 is forbidden and x=1 gives a valid zero. Therefore the domain is (-∞,-2)∪[1,∞).",
      diagnosticIntent: "This tests a sign-interval investigation that coordinates a radicand inequality with an excluded denominator value.",
      taskType: "investigative",
      difficulty: 4,
    }),
    c({
      id: "y11adv-fn-qm6",
      prompt: "A student states that only x=1 must be excluded. Which correction gives the complete real domain?",
      latex: "q(x)=\\frac{\\sqrt{9-x^2}}{x-1}",
      answer: "D",
      choices: ["x\\ne1", "-3<x<3", "[-3,3]", "[-3,1)\\cup(1,3]"],
      hint: "The numerator requires 9-x squared to be non-negative, and the denominator independently excludes x=1.",
      explanation: "The square root requires -3≤x≤3, including both endpoints. Intersecting this with x≠1 gives [-3,1)∪(1,3], so the student's restriction is incomplete.",
      diagnosticIntent: "This diagnoses the common error of noticing the denominator while overlooking the bounded square-root domain.",
      taskType: "problem-solving",
      difficulty: 4,
      distractorMisconceptions: {
        A: "Repeats the student's denominator-only restriction.",
        B: "Makes the square-root endpoints strict and still omits the internal exclusion.",
        C: "Finds the square-root interval but allows the denominator to vanish at x=1.",
      },
    }),
    a({
      id: "y11adv-fn-qm7",
      prompt: "The domain restriction makes the function one-to-one. Solve for the permitted input.",
      latex: "f(x)=x^2-4x,\\qquad x\\ge2,\\qquad f(x)=5",
      answer: "5",
      acceptedAnswers: ["x=5"],
      hint: "Solve the quadratic equation first, then use x greater than or equal to 2 to reject the inadmissible root.",
      explanation: "The equation x²-4x=5 becomes x²-4x-5=(x-5)(x+1)=0. Its roots are 5 and -1, but the stated domain x≥2 leaves only x=5.",
      diagnosticIntent: "This checks synthesis of algebraic preimages with a domain restriction instead of reporting every algebraic root.",
      taskType: "synthesis",
      difficulty: 4,
    }),
    a({
      id: "y11adv-fn-qm8",
      prompt: "The domain identifies the two zeros of the radicand. Determine b+c.",
      latex: "r(x)=\\frac{1}{\\sqrt{x^2+bx+c}},\\qquad \\operatorname{Dom}(r)=(-\\infty,-1)\\cup(3,\\infty)",
      answer: "-5",
      acceptedAnswers: ["b+c=-5", "−5"],
      hint: "A denominator square root must be strictly positive, so its boundary roots are -1 and 3; reconstruct the monic quadratic.",
      explanation: "The radicand is positive outside roots -1 and 3, so x²+bx+c=(x+1)(x-3)=x²-2x-3. Hence b=-2, c=-3 and b+c=-5.",
      diagnosticIntent: "This tests reverse inference from a domain set to a factorised quadratic and then to its coefficients.",
      taskType: "investigative",
      difficulty: 5,
    }),
    a({
      id: "y11adv-fn-qm9",
      prompt: "Determine the range after accounting for the restricted input interval.",
      latex: "s(x)=(x-2)^2+1,\\qquad -1\\le x\\le4",
      answer: "[1,10]",
      acceptedAnswers: ["1<=y<=10", "1≤y≤10"],
      hint: "Compare the vertex output with both endpoint outputs; the farther endpoint from x=2 supplies the maximum.",
      explanation: "The vertex x=2 lies in the interval and gives the minimum s(2)=1. The endpoints give s(-1)=10 and s(4)=5, so continuity yields every output from 1 through 10: [1,10].",
      diagnosticIntent: "This checks range analysis on a restricted domain, including the need to compare unequal endpoint distances from the vertex.",
      taskType: "analytical",
      difficulty: 5,
    }),
    a({
      id: "y11adv-fn-qm10",
      prompt: "Find the real domain of the nested function and give it in interval notation.",
      latex: "t(x)=\\sqrt{5-\\frac{1}{x-1}}",
      answer: "(-infinity,1) union [6/5,infinity)",
      acceptedAnswers: ["(-∞,1)∪[6/5,∞)", "x<1 or x>=6/5"],
      hint: "Rewrite the radicand as one rational expression, then solve its non-negative sign condition around x=1 and x=6/5.",
      explanation: "The radicand is (5x-6)/(x-1). Its critical values are 1 and 6/5; a sign check gives non-negative values for x<1 and x≥6/5. Thus the domain is (-∞,1)∪[6/5,∞).",
      diagnosticIntent: "This tests synthesis of rational sign analysis, a nested square-root condition, and the denominator exclusion.",
      taskType: "synthesis",
      difficulty: 5,
    }),
  ],

  "linear-quadratic-cubic-functions": [
    a({
      id: "y11adv-lqc-qm1",
      prompt: "The outputs at consecutive integer inputs are stated. Determine the coefficient of x squared.",
      latex: "f(0)=1,\\ f(1)=4,\\ f(2)=9,\\ f(3)=16,\\qquad f(x)=ax^2+bx+c",
      answer: "1",
      acceptedAnswers: ["a=1"],
      hint: "Compute first and second differences; for unit input spacing the constant second difference equals 2a.",
      explanation: "The first differences are 3,5,7 and the second differences are 2,2. For ax²+bx+c with unit spacing, the second difference is 2a, so 2a=2 and a=1.",
      diagnosticIntent: "This checks procedural use of finite differences to identify the leading coefficient of a quadratic model.",
      taskType: "procedural",
      difficulty: 3,
    }),
    c({
      id: "y11adv-lqc-qm2",
      prompt: "Which claim about real cubic polynomials is always true?",
      latex: "p(x)=ax^3+bx^2+cx+d,\\qquad a\\ne0",
      answer: "C",
      choices: ["It has three distinct real zeros", "It has exactly two turning points", "It has at least one real zero", "It is odd"],
      hint: "Compare opposite end behaviour for an odd-degree polynomial, but do not assume how many turning points or distinct zeros occur.",
      explanation: "A real cubic has opposite end behaviour as x tends to positive and negative infinity, so continuity forces at least one real zero. It may have one or three real zeros and need not be odd.",
      diagnosticIntent: "This distinguishes guaranteed degree-based behaviour from properties that hold only for special cubic coefficients.",
      taskType: "analytical",
      difficulty: 3,
      distractorMisconceptions: {
        A: "Confuses degree three with three distinct real roots.",
        B: "Assumes the maximum possible number of turning points must occur.",
        D: "Confuses odd degree with the symmetry definition of an odd function.",
      },
    }),
    a({
      id: "y11adv-lqc-qm3",
      prompt: "Construct the monic quadratic from its zeros and enter its expanded expression.",
      latex: "f(-2)=0,\\qquad f(4)=0,\\qquad \\text{leading coefficient }1",
      answer: "x^2-2x-8",
      acceptedAnswers: ["(x+2)(x-4)", "x²−2x−8"],
      hint: "A zero r produces the factor x-r; multiply the two factors after using the monic leading coefficient.",
      explanation: "The zeros -2 and 4 give factors (x+2) and (x-4). With leading coefficient 1, f(x)=(x+2)(x-4)=x²-2x-8.",
      diagnosticIntent: "This checks construction of a quadratic rule from root information rather than merely finding roots from a supplied rule.",
      taskType: "problem-solving",
      difficulty: 3,
    }),
    c({
      id: "y11adv-lqc-qm4",
      prompt: "Which function has both ends rising as the magnitude of x increases?",
      latex: "x\\to\\pm\\infty",
      answer: "B",
      choices: ["-2x^3+x", "3x^2-5x+1", "x^3-4x", "-x^2+7"],
      hint: "Use the degree and sign of the leading term; lower-degree terms do not control end behaviour.",
      explanation: "The positive even-degree leading term 3x² makes both ends tend to positive infinity. Cubics have opposite ends, while -x²+7 has both ends falling.",
      diagnosticIntent: "This checks whether end behaviour is inferred from leading degree and coefficient rather than isolated lower-order terms.",
      taskType: "analytical",
      difficulty: 3,
      distractorMisconceptions: {
        A: "Uses the negative leading coefficient but ignores odd-degree opposite ends.",
        C: "Treats a positive cubic coefficient as making both ends rise.",
        D: "Recognises even degree but ignores the negative leading coefficient.",
      },
    }),
    a({
      id: "y11adv-lqc-qm5",
      prompt: "Determine how many times the sign of the function changes as x moves from negative to positive infinity.",
      latex: "p(x)=x^3-4x=x(x-2)(x+2)",
      cartesianGraph: {
        description: "Cubic p crossing the horizontal axis at the three simple zeros -2, 0 and 2, with alternating sign intervals.",
        xMin: -3,
        xMax: 3,
        yMin: -8,
        yMax: 8,
        curves: [{ kind: "cubic", a: 1, b: 0, c: -4, d: 0, label: "p(x)" }],
        points: [
          { x: -2, y: 0, label: "-2" },
          { x: 0, y: 0, label: "0" },
          { x: 2, y: 0, label: "2" },
        ],
      },
      answer: "3",
      acceptedAnswers: ["three", "3 sign changes"],
      hint: "Order the three simple zeros and note that a polynomial changes sign whenever it crosses a zero of odd multiplicity.",
      explanation: "The ordered zeros are -2, 0 and 2, each with multiplicity one. The sign therefore alternates at every zero, producing three sign changes across the real line.",
      diagnosticIntent: "This tests an investigation of factor multiplicity and sign intervals rather than simple recall of the number of roots.",
      taskType: "investigative",
      difficulty: 4,
    }),
    c({
      id: "y11adv-lqc-qm6",
      prompt: "A student says constant second differences prove a function is cubic. Which response is correct?",
      latex: "\\Delta^2 f=6\\ \\text{for equally spaced inputs}",
      answer: "A",
      choices: ["The function is quadratic with leading coefficient 3", "The function is cubic with leading coefficient 1", "The function is linear with gradient 6", "No polynomial degree can be inferred"],
      hint: "For equally spaced unit inputs, a quadratic has constant second difference 2a; a cubic is identified by constant third differences.",
      explanation: "A constant non-zero second difference identifies a quadratic, not a cubic. Since 2a=6 for unit spacing, its leading coefficient is a=3.",
      diagnosticIntent: "This diagnoses confusion between the order of a finite difference and the degree of the underlying polynomial.",
      taskType: "problem-solving",
      difficulty: 4,
      distractorMisconceptions: {
        B: "Equates the second-difference value with a cubic leading coefficient.",
        C: "Confuses a constant second difference with a constant first difference.",
        D: "Fails to use the standard finite-difference degree test.",
      },
    }),
    a({
      id: "y11adv-lqc-qm7",
      prompt: "Find the sum of the x-coordinates where the two functions have equal outputs.",
      latex: "f(x)=x^2-3x+2,\\qquad g(x)=x+2",
      answer: "4",
      acceptedAnswers: ["x-values 0 and 4; sum 4", "0+4=4"],
      hint: "Set f(x)=g(x), simplify to a quadratic, and use both intersection inputs in the requested sum.",
      explanation: "Equating outputs gives x²-3x+2=x+2, so x²-4x=x(x-4)=0. The inputs are 0 and 4, whose sum is 4.",
      diagnosticIntent: "This checks synthesis of two function families through equality of outputs and complete use of both solutions.",
      taskType: "synthesis",
      difficulty: 4,
    }),
    a({
      id: "y11adv-lqc-qm8",
      prompt: "Count the integer parameters in the stated set that give three distinct real zeros.",
      latex: "p_k(x)=x^3-kx=x(x^2-k),\\qquad k\\in\\{-3,-2,-1,0,1,2,3\\}",
      answer: "3",
      acceptedAnswers: ["k=1,2,3", "three values"],
      hint: "The additional zeros are plus or minus the square root of k; determine when they are real, non-zero, and distinct from x=0.",
      explanation: "Three distinct real zeros occur exactly when k>0: they are 0 and ±√k. In the supplied integer set this gives k=1,2,3, so there are three parameters.",
      diagnosticIntent: "This tests a bounded parameter investigation linking factor structure to the number and distinctness of real zeros.",
      taskType: "investigative",
      difficulty: 5,
    }),
    a({
      id: "y11adv-lqc-qm9",
      prompt: "Reconstruct the monic cubic and enter the coefficient of x.",
      latex: "x=-1\\ \\text{is a double zero},\\qquad x=2\\ \\text{is a simple zero}",
      answer: "-3",
      acceptedAnswers: ["coefficient=-3", "−3"],
      hint: "Write (x+1)²(x-2), expand carefully, and then read the coefficient of the linear term.",
      explanation: "The multiplicities give p(x)=(x+1)²(x-2). Expanding produces x³-3x-2, so the coefficient multiplying x is -3.",
      diagnosticIntent: "This checks reconstruction from zeros with multiplicity and accurate extraction of a non-leading coefficient.",
      taskType: "analytical",
      difficulty: 5,
    }),
    a({
      id: "y11adv-lqc-qm10",
      prompt: "Use the stated symmetries to determine the combined expression without finding either rule.",
      latex: "p(-x)=p(x),\\ q(-x)=-q(x),\\ p(1)=2,\\ q(1)=3,\\qquad [p(1)+q(1)]+[p(-1)+q(-1)]",
      answer: "4",
      acceptedAnswers: ["2p(1)=4", "4"],
      hint: "Replace p(-1) and q(-1) using even and odd symmetry before combining like terms.",
      explanation: "Even symmetry gives p(-1)=2 and odd symmetry gives q(-1)=-3. Hence (2+3)+(2-3)=4; equivalently, the odd contributions cancel and 2p(1)=4.",
      diagnosticIntent: "This tests synthesis of polynomial-family behaviour with even and odd function structure in a cancellation argument.",
      taskType: "synthesis",
      difficulty: 5,
    }),
  ],

  "polynomial-reciprocal-functions": [
    a({
      id: "y11adv-poly-qm1",
      prompt: "Evaluate the factorised polynomial at zero.",
      latex: "p(x)=(x-1)^2(x+3),\\qquad p(0)",
      answer: "3",
      acceptedAnswers: ["p(0)=3"],
      hint: "Substitute zero into every factor before multiplying; the squared factor remains positive.",
      explanation: "At x=0, p(0)=(0-1)²(0+3)=(-1)²·3=3. The double factor does not introduce a negative sign.",
      diagnosticIntent: "This checks accurate evaluation of a factorised polynomial and handling of an even multiplicity.",
      taskType: "procedural",
      difficulty: 3,
    }),
    c({
      id: "y11adv-poly-qm2",
      prompt: "Which pair gives the vertical and horizontal asymptotes respectively?",
      latex: "f(x)=\\frac{3}{x+2}-4",
      cartesianGraph: {
        description: "Translated reciprocal function with branches approaching the vertical line x=-2 and horizontal line y=-4.",
        xMin: -8,
        xMax: 4,
        yMin: -10,
        yMax: 3,
        curves: [{ kind: "reciprocal", a: 3, h: -2, k: -4, label: "f(x)" }],
      },
      answer: "B",
      choices: ["x=2,\\ y=4", "x=-2,\\ y=-4", "x=-4,\\ y=-2", "x=2,\\ y=-4"],
      hint: "Set the denominator to zero for the vertical line, and use the surviving vertical shift as the reciprocal term approaches zero.",
      explanation: "The denominator x+2 vanishes at x=-2, giving the vertical asymptote. As |x| grows, 3/(x+2) tends to zero, so the horizontal asymptote is y=-4.",
      diagnosticIntent: "This distinguishes denominator zeros from shifts and tests the correct ordering of vertical and horizontal asymptotes.",
      taskType: "analytical",
      difficulty: 3,
      distractorMisconceptions: {
        A: "Reverses both translation signs.",
        C: "Swaps the horizontal and vertical shift roles.",
        D: "Finds the horizontal asymptote but reverses the denominator-zero sign.",
      },
    }),
    a({
      id: "y11adv-poly-qm3",
      prompt: "Find the x-intercept of the rational function.",
      latex: "h(x)=\\frac{2x-6}{x+1}",
      answer: "3",
      acceptedAnswers: ["x=3", "(3,0)"],
      hint: "A rational output is zero when its numerator is zero and its denominator is non-zero.",
      explanation: "Set 2x-6=0 to obtain x=3. The denominator is then 4, not zero, so the x-intercept is x=3, or the point (3,0).",
      diagnosticIntent: "This checks selection of the numerator condition for a rational zero and validation against the denominator restriction.",
      taskType: "problem-solving",
      difficulty: 3,
    }),
    c({
      id: "y11adv-poly-qm4",
      prompt: "What feature occurs at x=2 after simplifying the expression?",
      latex: "r(x)=\\frac{x^2-4}{x-2},\\qquad x\\ne2",
      answer: "D",
      choices: ["A vertical asymptote", "A horizontal asymptote", "An x-intercept", "A removable hole at (2,4)"],
      hint: "Factor the numerator and cancel only algebraically; the original domain exclusion remains part of the function.",
      explanation: "For x≠2, r(x)=(x-2)(x+2)/(x-2)=x+2. The excluded input remains, so the line has a removable hole where x=2 and y=4, not an asymptote.",
      diagnosticIntent: "This diagnoses the misconception that every denominator zero becomes a vertical asymptote even after a common factor cancels.",
      taskType: "analytical",
      difficulty: 3,
      distractorMisconceptions: {
        A: "Treats the cancelled denominator zero as a vertical asymptote.",
        B: "Confuses a local domain hole with end behaviour.",
        C: "Assumes the excluded input remains a zero after cancellation.",
      },
    }),
    a({
      id: "y11adv-poly-qm5",
      prompt: "Determine the horizontal asymptote from leading-term behaviour.",
      latex: "s(x)=\\frac{2x^2-3x+1}{x^2+x-2}",
      answer: "y=2",
      acceptedAnswers: ["2", "horizontal asymptote 2"],
      hint: "Divide numerator and denominator by x squared, then let the lower-order fractions approach zero.",
      explanation: "Both polynomials have degree two. Dividing by x² leaves (2-3/x+1/x²)/(1+1/x-2/x²), which tends to 2/1, so the horizontal asymptote is y=2.",
      diagnosticIntent: "This tests an end-behaviour investigation based on degree and leading coefficients rather than a memorised reciprocal shift.",
      taskType: "investigative",
      difficulty: 4,
    }),
    c({
      id: "y11adv-poly-qm6",
      prompt: "A student adds the fractions as 2/(2x). Which corrected result preserves the original domain?",
      latex: "\\frac1{x-2}+\\frac1{x+2}",
      answer: "A",
      choices: ["\\frac{2x}{x^2-4},\\ x\\ne\\pm2", "\\frac1x,\\ x\\ne0", "\\frac2{x^2-4},\\ x\\ne\\pm2", "\\frac{2x}{x^2-4},\\ x\\ne0"],
      hint: "Use the product (x-2)(x+2) as the common denominator and add the cross-multiplied numerators.",
      explanation: "The numerator becomes (x+2)+(x-2)=2x and the denominator is x²-4. The original denominators exclude x=2 and x=-2, so the corrected expression is 2x/(x²-4), x≠±2.",
      diagnosticIntent: "This diagnoses invalid addition of denominators and whether original excluded values are retained after algebraic simplification.",
      taskType: "problem-solving",
      difficulty: 4,
      distractorMisconceptions: {
        B: "Adds numerator and denominator terms directly and invents x=0 as the restriction.",
        C: "Forms the common denominator but fails to cross-multiply the numerators.",
        D: "Gets the algebraic fraction but loses the original denominator restrictions.",
      },
    }),
    a({
      id: "y11adv-poly-qm7",
      prompt: "Find the parameter that makes the stated factor divide the polynomial exactly.",
      latex: "p(x)=x^3+ax+2,\\qquad (x-2)\\text{ is a factor}",
      answer: "-5",
      acceptedAnswers: ["a=-5", "−5"],
      hint: "Apply the factor theorem by setting p(2)=0, then solve the resulting equation in a.",
      explanation: "If x-2 is a factor, p(2)=0. Therefore 8+2a+2=0, so 2a=-10 and a=-5. Substitution confirms the remainder is zero.",
      diagnosticIntent: "This checks synthesis of polynomial factor structure with reverse parameter recovery through the factor theorem.",
      taskType: "synthesis",
      difficulty: 4,
    }),
    a({
      id: "y11adv-poly-qm8",
      prompt: "Determine a+b for the translated reciprocal function satisfying both conditions and the positive-shift restriction.",
      latex: "f(x)=\\frac1{x-a}+b,\\qquad f(0)=1,\\qquad f(2)=-1,\\qquad a>0",
      answer: "1+2sqrt(2)",
      acceptedAnswers: ["1+2√2", "a=1+√2, b=√2"],
      hint: "Form one equation from each function value, eliminate b, solve the resulting quadratic in a, and apply a greater than zero.",
      explanation: "The conditions give -1/a+b=1 and 1/(2-a)+b=-1. Eliminating b yields a²-2a-1=0, so a=1±√2. The restriction selects a=1+√2; then b=1+1/a=√2, giving a+b=1+2√2.",
      diagnosticIntent: "This tests a bounded parameter investigation using two reciprocal-function constraints, a quadratic branch choice, and a sign restriction.",
      taskType: "investigative",
      difficulty: 5,
    }),
    a({
      id: "y11adv-poly-qm9",
      prompt: "Find the real input where the polynomial and reciprocal outputs are equal.",
      latex: "x^2=\\frac4x,\\qquad x\\ne0",
      answer: "cube root of 4",
      acceptedAnswers: ["∛4", "4^(1/3)", "x=∛4"],
      hint: "Multiply by the permitted non-zero input, then solve the resulting cubic equation over the reals.",
      explanation: "Because x≠0, multiplying by x is reversible and gives x³=4. A strictly increasing cubic has one real solution, so x=∛4.",
      diagnosticIntent: "This checks analysis across polynomial and reciprocal representations without introducing spurious zero solutions.",
      taskType: "analytical",
      difficulty: 5,
    }),
    a({
      id: "y11adv-poly-qm10",
      prompt: "Find the positive parameter for which the line and reciprocal function meet at exactly one real point.",
      latex: "y=x,\\qquad y=\\frac{-4}{x-a}",
      answer: "4",
      acceptedAnswers: ["a=4"],
      hint: "Equate the two outputs, form a quadratic in x, and impose a zero discriminant for exactly one real intersection.",
      explanation: "Equating gives x(x-a)=-4, or x²-ax+4=0. Exactly one real solution requires a²-16=0, hence a=±4; the requested positive parameter is a=4.",
      diagnosticIntent: "This tests synthesis of reciprocal intersections, quadratic discriminants, and a parameter sign constraint.",
      taskType: "synthesis",
      difficulty: 5,
    }),
  ],

  "absolute-value-functions": [
    a({
      id: "y11adv-abs-qm1",
      prompt: "Solve the absolute-value equation and enter the positive solution.",
      latex: "|2x-3|=7",
      answer: "5",
      acceptedAnswers: ["x=5"],
      hint: "Create the two linear branches 2x-3=7 and 2x-3=-7, then select the positive result.",
      explanation: "The branches give 2x=10, so x=5, and 2x=-4, so x=-2. The question asks for the positive solution, which is x=5.",
      diagnosticIntent: "This checks complete two-branch solving and selection of the solution matching an explicit condition.",
      taskType: "procedural",
      difficulty: 3,
    }),
    c({
      id: "y11adv-abs-qm2",
      prompt: "Which proposed identity is not true for all real a and b?",
      latex: "a,b\\in\\mathbb R",
      answer: "D",
      choices: ["|a|\\ge0", "|-a|=|a|", "|ab|=|a||b|", "|a+b|=|a|+|b|"],
      hint: "Test each claim with a and b having opposite signs, such as 2 and -1.",
      explanation: "The first three are absolute-value identities. The last fails when cancellation occurs: for a=2 and b=-1, |a+b|=1 but |a|+|b|=3.",
      diagnosticIntent: "This checks whether the triangle inequality is incorrectly treated as an equality in every case.",
      taskType: "analytical",
      difficulty: 3,
      distractorMisconceptions: {
        A: "Rejects the defining non-negativity property of absolute value.",
        B: "Thinks changing a sign changes distance from zero.",
        C: "Does not recognise the product property of absolute value.",
      },
    }),
    a({
      id: "y11adv-abs-qm3",
      prompt: "Solve the inequality and give the closed interval.",
      latex: "|x-2|\\le5",
      answer: "[-3,7]",
      acceptedAnswers: ["-3<=x<=7", "−3≤x≤7"],
      hint: "Interpret the inequality as inputs whose distance from 2 is at most 5, or write -5 less than or equal to x-2 less than or equal to 5.",
      explanation: "The compound inequality -5≤x-2≤5 becomes -3≤x≤7 after adding 2 throughout. Equality is allowed, so both endpoints are included.",
      diagnosticIntent: "This checks conversion of a distance condition into a two-sided inequality with correct inclusive endpoints.",
      taskType: "problem-solving",
      difficulty: 3,
    }),
    c({
      id: "y11adv-abs-qm4",
      prompt: "For which inputs does the absolute-value expression equal its interior expression?",
      latex: "|x+1|=x+1",
      answer: "A",
      choices: ["x\\ge-1", "x\\le-1", "x>-1", "x\\ne-1"],
      hint: "Absolute value leaves an expression unchanged exactly when that expression is non-negative.",
      explanation: "We need x+1≥0, which gives x≥-1. At x=-1 both sides equal zero, so the endpoint must be included.",
      diagnosticIntent: "This distinguishes the sign condition defining absolute value from a memorised but incorrect strict inequality.",
      taskType: "analytical",
      difficulty: 3,
      distractorMisconceptions: {
        B: "Uses the region where the interior is non-positive rather than non-negative.",
        C: "Excludes the valid zero boundary.",
        D: "Treats the condition as a single forbidden point instead of a half-line.",
      },
    }),
    a({
      id: "y11adv-abs-qm5",
      prompt: "Count the integer centres that produce exactly one solution in the stated interval.",
      latex: "|x-a|=3,\\qquad 0\\le x\\le5,\\qquad a\\in\\{0,1,2,3,4,5\\}",
      answer: "6",
      acceptedAnswers: ["six", "all 6 values"],
      hint: "For each centre the candidates are a-3 and a+3; the interval length is less than the distance between those two candidates.",
      explanation: "The two candidates are six units apart, while [0,5] has length five, so at most one can lie inside. For every listed a, either a-3 or a+3 lies in [0,5]. Thus all six centres give exactly one solution.",
      diagnosticIntent: "This tests a bounded investigation of how parameter shifts affect the number of admissible absolute-value solutions.",
      taskType: "investigative",
      difficulty: 4,
    }),
    c({
      id: "y11adv-abs-qm6",
      prompt: "A student squares both sides and keeps two roots. Which statement gives the valid solution?",
      latex: "|x-1|=x+3",
      answer: "B",
      choices: ["x=-3", "x=-1", "x=-3\\text{ or }-1", "There is no real solution"],
      hint: "The right side must be non-negative; solve the two absolute-value branches and verify candidates in the original equation.",
      explanation: "The branch x-1=x+3 is impossible. The branch -(x-1)=x+3 gives x=-1, and checking yields |-2|=2. Therefore x=-1 is the sole valid solution.",
      diagnosticIntent: "This diagnoses extraneous solutions introduced by squaring and checks validation against the original absolute-value equation.",
      taskType: "problem-solving",
      difficulty: 4,
      distractorMisconceptions: {
        A: "Keeps the boundary where the right side is zero without satisfying the equation.",
        C: "Reports both roots from an unverified squared equation.",
        D: "Rejects the valid negative input because the right-hand expression was assumed negative.",
      },
    }),
    a({
      id: "y11adv-abs-qm7",
      prompt: "Find the inclusive time interval for which the temperature is acceptable.",
      latex: "|T-22|\\le1.5,\\qquad T=18+0.8t",
      answer: "[3.125,6.875]",
      acceptedAnswers: ["3.125<=t<=6.875", "3.125≤t≤6.875"],
      hint: "Convert the temperature tolerance to 20.5 less than or equal to T less than or equal to 23.5, then substitute the linear model.",
      explanation: "The tolerance gives 20.5≤18+0.8t≤23.5. Subtracting 18 and dividing by 0.8 yields 3.125≤t≤6.875, including the tolerance boundaries.",
      diagnosticIntent: "This checks synthesis of an absolute-value tolerance with a linear contextual model and correct compound-inequality operations.",
      taskType: "synthesis",
      difficulty: 4,
    }),
    a({
      id: "y11adv-abs-qm8",
      prompt: "Find the smallest positive integer parameter giving exactly one real solution.",
      latex: "|x|=kx+2",
      answer: "1",
      acceptedAnswers: ["k=1"],
      hint: "Solve separately for x greater than or equal to zero and x less than zero, then determine when each branch satisfies its own sign condition.",
      explanation: "The non-negative branch gives x=2/(1-k), valid for k<1; the negative branch gives x=-2/(1+k), valid for k>-1. Exactly one solution occurs when |k|≥1, so the smallest positive integer is k=1.",
      diagnosticIntent: "This tests a parameter investigation that tracks branch validity rather than only solving the two linear equations formally.",
      taskType: "investigative",
      difficulty: 5,
    }),
    a({
      id: "y11adv-abs-qm9",
      prompt: "Determine the number of distinct real solutions.",
      latex: "\\bigl||x-1|-2\\bigr|=1",
      answer: "4",
      acceptedAnswers: ["four", "x=-2,0,2,4"],
      hint: "First set the inner absolute value equal to 3 or 1, then solve both resulting distance equations.",
      explanation: "The outer equation gives |x-1|=3 or |x-1|=1. These produce x=4,-2 and x=2,0 respectively, so there are four distinct real solutions.",
      diagnosticIntent: "This checks analysis of a nested absolute-value equation and systematic retention of every branch without duplication.",
      taskType: "analytical",
      difficulty: 5,
    }),
    a({
      id: "y11adv-abs-qm10",
      prompt: "Solve the distance-sum equation and enter the sum of its real solutions.",
      latex: "|x-1|+|x-5|=6",
      answer: "6",
      acceptedAnswers: ["solutions 0 and 6; sum 6", "0+6=6"],
      hint: "Split at x=1 and x=5; between these points the distance sum is 4, so solutions must lie outside the interval.",
      explanation: "For x≤1, the sum is (1-x)+(5-x)=6-2x, giving x=0. For x≥5, it is (x-1)+(x-5)=2x-6, giving x=6. Their sum is 6.",
      diagnosticIntent: "This tests synthesis of piecewise distance reasoning, interval selection, and use of all valid solutions in a final quantity.",
      taskType: "synthesis",
      difficulty: 5,
    }),
  ],
};
