import {
  richAnswer as a,
  richChoice as c,
  type WorkingFunctionsMasteryMap,
} from "./workingFunctionsQualityHelpers";

export const workingFunctionsQualityAdvanced: WorkingFunctionsMasteryMap = {
  "composite-functions": [
    a({
      id: "y11adv-comp-qm1",
      prompt: "Evaluate the composite function at the stated input.",
      latex: "f(x)=2x+1,\\qquad g(x)=x^2-3,\\qquad (f\\circ g)(2)",
      answer: "3",
      acceptedAnswers: ["f(g(2))=3"],
      hint: "Evaluate the inner function g at 2 first, then use that output as the input to f.",
      explanation: "The inner output is g(2)=4-3=1. Applying f gives f(1)=2(1)+1=3, so the composite output at 2 is 3.",
      diagnosticIntent: "This checks procedural composition in the correct inside-to-outside order.",
      taskType: "procedural",
      difficulty: 3,
    }),
    c({
      id: "y11adv-comp-qm2",
      prompt: "Which set is the domain of the composite function?",
      latex: "f(x)=\\sqrt{x},\\qquad g(x)=x-4,\\qquad (f\\circ g)(x)",
      answer: "C",
      choices: ["x\\ge0", "x\\ne4", "x\\ge4", "x\\le4"],
      hint: "The output of g must belong to the domain of f, so require x-4 to be non-negative.",
      explanation: "The composite is √(x-4). Real outputs require x-4≥0, hence x≥4.",
      diagnosticIntent: "This distinguishes the domain of the outer function from the preimage condition imposed on the original input.",
      taskType: "analytical",
      difficulty: 3,
      distractorMisconceptions: {
        A: "Copies the outer function's input domain without translating through g.",
        B: "Treats the square-root boundary as a denominator restriction.",
        D: "Reverses the square-root inequality.",
      },
    }),
    a({
      id: "y11adv-comp-qm3",
      prompt: "Find the parameter from the composite function value.",
      latex: "f(x)=kx-1,\\qquad g(x)=x+2,\\qquad (f\\circ g)(3)=19",
      answer: "4",
      acceptedAnswers: ["k=4"],
      hint: "First evaluate g(3), then substitute that output into the parameterised function f.",
      explanation: "We have g(3)=5, so f(g(3))=f(5)=5k-1. Setting 5k-1=19 gives 5k=20 and k=4.",
      diagnosticIntent: "This checks reverse parameter recovery through a two-stage composition.",
      taskType: "problem-solving",
      difficulty: 3,
    }),
    c({
      id: "y11adv-comp-qm4",
      prompt: "Which statement correctly compares the two compositions?",
      latex: "f(x)=x^2,\\qquad g(x)=x+1",
      cartesianGraph: {
        description: "Two upward parabolas representing the differently ordered compositions, one shifted left and one shifted upward.",
        xMin: -4,
        xMax: 4,
        yMin: -1,
        yMax: 10,
        parabolas: [
          { kind: "quadratic", a: 1, b: 2, c: 1, label: "f after g" },
          { kind: "quadratic", a: 1, b: 0, c: 1, label: "g after f" },
        ],
      },
      answer: "B",
      choices: ["f\\circ g=g\\circ f", "(f\\circ g)(x)=x^2+2x+1,\\ (g\\circ f)(x)=x^2+1", "(f\\circ g)(x)=x^2+1,\\ (g\\circ f)(x)=x^2+2x+1", "Both compositions equal x^3+x"],
      hint: "Substitute the entire inner expression into the outer rule in each order.",
      explanation: "We get f(g(x))=(x+1)²=x²+2x+1, while g(f(x))=x²+1. The extra 2x shows composition is not generally commutative.",
      diagnosticIntent: "This checks order-sensitive substitution and diagnoses the assumption that function composition commutes.",
      taskType: "analytical",
      difficulty: 3,
      distractorMisconceptions: {
        A: "Assumes composition is commutative.",
        C: "Reverses the two composition labels.",
        D: "Multiplies function rules rather than composing them.",
      },
    }),
    a({
      id: "y11adv-comp-qm5",
      prompt: "Count the integer parameters for which the two compositions are identical.",
      latex: "f_k(x)=x+k,\\qquad g(x)=2x-1,\\qquad k\\in\\{-3,-2,-1,0,1,2,3\\}",
      answer: "1",
      acceptedAnswers: ["k=0 only", "one"],
      hint: "Form both compositions algebraically and equate their constant terms.",
      explanation: "We have f_k(g(x))=2x-1+k and g(f_k(x))=2x+2k-1. Equality for every x requires k=2k, so k=0. Exactly one listed parameter works.",
      diagnosticIntent: "This tests a bounded investigation of when two non-commuting function families happen to commute.",
      taskType: "investigative",
      difficulty: 4,
    }),
    c({
      id: "y11adv-comp-qm6",
      prompt: "A student writes f(g(x)) as f(x)g(x). Which expression is the actual composite?",
      latex: "f(x)=3x-2,\\qquad g(x)=x^2+1",
      answer: "D",
      choices: ["(3x-2)(x^2+1)", "3x^2-2", "3x^2-1", "3x^2+1"],
      hint: "Replace the input x in f by the entire expression g(x), then simplify.",
      explanation: "Composition gives f(g(x))=3(x²+1)-2=3x²+1. It is substitution, not multiplication of the two function outputs.",
      diagnosticIntent: "This diagnoses confusion between the composition symbol and ordinary multiplication of functions.",
      taskType: "problem-solving",
      difficulty: 4,
      distractorMisconceptions: {
        A: "Multiplies the function outputs instead of composing.",
        B: "Substitutes x squared but drops the inner constant before applying f.",
        C: "Applies the outer multiplier but omits its -2 term.",
      },
    }),
    a({
      id: "y11adv-comp-qm7",
      prompt: "Show the functions undo each other by evaluating the requested composition.",
      latex: "f(x)=2x+3,\\qquad g(x)=\\frac{x-3}{2},\\qquad (g\\circ f)(7)",
      answer: "7",
      acceptedAnswers: ["g(f(7))=7"],
      hint: "Apply f first and then g, keeping the full output grouped in the numerator.",
      explanation: "First f(7)=17. Then g(17)=(17-3)/2=14/2=7. Algebraically g(f(x))=[(2x+3)-3]/2=x.",
      diagnosticIntent: "This checks synthesis of inverse-like linear functions through both numerical and algebraic composition.",
      taskType: "synthesis",
      difficulty: 4,
    }),
    a({
      id: "y11adv-comp-qm8",
      prompt: "Find the greatest integer parameter for which the composite has all real numbers as its domain.",
      latex: "f(x)=\\sqrt{x-1},\\qquad g_k(x)=x^2-k,\\qquad (f\\circ g_k)(x)",
      answer: "-1",
      acceptedAnswers: ["k=-1", "−1"],
      hint: "The radicand x squared minus k minus 1 must be non-negative for every real x; test its minimum at x=0.",
      explanation: "The composite is √(x²-k-1). Its minimum radicand is -k-1 at x=0, so all real inputs require -k-1≥0, or k≤-1. The greatest integer is -1.",
      diagnosticIntent: "This tests a parameter investigation combining composition domain with a global quadratic minimum.",
      taskType: "investigative",
      difficulty: 5,
    }),
    a({
      id: "y11adv-comp-qm9",
      prompt: "Find the input at which the two compositions have equal outputs.",
      latex: "f(x)=x^2,\\qquad g(x)=x+2,\\qquad (f\\circ g)(x)=(g\\circ f)(x)",
      answer: "-1/2",
      acceptedAnswers: ["x=-1/2", "−0.5"],
      hint: "Expand (x+2) squared, compare it with x squared plus 2, and cancel common terms.",
      explanation: "The equation is (x+2)²=x²+2. Expanding and cancelling x² gives 4x+4=2, so 4x=-2 and x=-1/2.",
      diagnosticIntent: "This checks analytical comparison of non-commuting compositions and efficient cancellation.",
      taskType: "analytical",
      difficulty: 5,
    }),
    a({
      id: "y11adv-comp-qm10",
      prompt: "Solve the composite equation under the stated input restriction.",
      latex: "f(x)=2x+1,\\qquad g(x)=x^2,\\qquad (g\\circ f)(x)=49,\\qquad x>0",
      answer: "3",
      acceptedAnswers: ["x=3"],
      hint: "Solve (2x+1) squared equals 49 using both signs, then apply x greater than zero.",
      explanation: "The equation (2x+1)²=49 gives 2x+1=±7, so x=3 or x=-4. The restriction x>0 leaves x=3.",
      diagnosticIntent: "This tests synthesis of composition, a two-branch square equation, and domain-based solution selection.",
      taskType: "synthesis",
      difficulty: 5,
    }),
  ],

  "completing-the-square": [
    a({
      id: "y11adv-cts-qm1",
      prompt: "Write the quadratic in completed-square form.",
      latex: "x^2+8x+3",
      answer: "(x+4)^2-13",
      acceptedAnswers: ["(x+4)²−13"],
      hint: "Add and subtract the square of half the x-coefficient.",
      explanation: "Half of 8 is 4, so x²+8x+3=(x+4)²-16+3=(x+4)²-13.",
      diagnosticIntent: "This checks procedural completion of the square with the compensating constant retained.",
      taskType: "procedural",
      difficulty: 3,
    }),
    c({
      id: "y11adv-cts-qm2",
      prompt: "Which vertex follows from the completed-square form?",
      latex: "f(x)=-3(x+2)^2+7",
      answer: "B",
      choices: ["(2,7)", "(-2,7)", "(-2,-7)", "(2,-7)"],
      hint: "Compare x+2 with x-h, so h has the opposite sign; k is the outside constant.",
      explanation: "The form is -3[x-(-2)]²+7, so the vertex is (-2,7). The negative coefficient affects opening direction, not the vertex coordinates.",
      diagnosticIntent: "This diagnoses sign reversal in reading h from vertex form and confusion with the leading coefficient.",
      taskType: "analytical",
      difficulty: 3,
      distractorMisconceptions: {
        A: "Reads the sign inside the bracket without reversal.",
        C: "Reads h correctly but reverses the outside constant.",
        D: "Reverses neither coordinate correctly.",
      },
    }),
    a({
      id: "y11adv-cts-qm3",
      prompt: "Find the parameter by matching the two equivalent forms.",
      latex: "x^2-6x+k=(x-3)^2+5",
      answer: "14",
      acceptedAnswers: ["k=14"],
      hint: "Expand the right-hand side and match its constant term with k.",
      explanation: "Expanding gives (x-3)²+5=x²-6x+9+5=x²-6x+14. Therefore k=14.",
      diagnosticIntent: "This checks reverse coefficient matching from completed-square form.",
      taskType: "problem-solving",
      difficulty: 3,
    }),
    c({
      id: "y11adv-cts-qm4",
      prompt: "Which completed-square form is correct?",
      latex: "3x^2+12x+1",
      answer: "C",
      choices: ["3(x+2)^2+1", "3(x+4)^2-47", "3(x+2)^2-11", "(3x+2)^2-3"],
      hint: "Factor 3 from the x terms before completing the square inside the bracket.",
      explanation: "We write 3(x²+4x)+1=3[(x+2)²-4]+1=3(x+2)²-11.",
      diagnosticIntent: "This checks whether the leading coefficient is factored and applied to the compensating constant.",
      taskType: "analytical",
      difficulty: 3,
      distractorMisconceptions: {
        A: "Adds the square term without subtracting its contribution.",
        B: "Uses the full linear coefficient rather than half after factoring.",
        D: "Places the leading coefficient inside the squared linear term incorrectly.",
      },
    }),
    a({
      id: "y11adv-cts-qm5",
      prompt: "Find the minimum value when x is restricted to integers.",
      latex: "f(x)=2x^2-14x+30,\\qquad x\\in\\mathbb Z",
      cartesianGraph: {
        description: "Upward-opening parabola with real vertex at (3.5,5.5) and equal nearest-integer outputs at x=3 and x=4.",
        xMin: 0,
        xMax: 7,
        yMin: 4,
        yMax: 32,
        parabolas: [{ kind: "quadratic", a: 2, b: -14, c: 30, label: "f(x)" }],
        points: [
          { x: 3, y: 6, label: "(3,6)" },
          { x: 4, y: 6, label: "(4,6)" },
        ],
      },
      answer: "6",
      acceptedAnswers: ["minimum 6", "f(3)=f(4)=6"],
      hint: "Complete the square to locate the real vertex, then compare the two nearest integers.",
      explanation: "Completing gives f(x)=2(x-3.5)²+5.5. The nearest integers are 3 and 4; each gives 2(0.5)²+5.5=6, the integer-domain minimum.",
      diagnosticIntent: "This tests a bounded-domain investigation that distinguishes the real minimum from the attainable integer minimum.",
      taskType: "investigative",
      difficulty: 4,
    }),
    c({
      id: "y11adv-cts-qm6",
      prompt: "A student writes 3(x+2)²+1. Which term did the student fail to include?",
      latex: "3x^2+12x+1",
      answer: "D",
      choices: ["+12", "-4", "+3", "-12"],
      hint: "Expanding 3(x+2) squared creates a constant 12 that was not in the original expression.",
      explanation: "Since 3(x+2)²=3x²+12x+12, a compensating -12 is required before adding the original +1. The correct result is 3(x+2)²-11.",
      diagnosticIntent: "This diagnoses failure to compensate for the constant introduced while completing the square.",
      taskType: "problem-solving",
      difficulty: 4,
      distractorMisconceptions: {
        A: "Confuses the linear coefficient with the compensating constant.",
        B: "Subtracts the inside square 4 but ignores multiplication by 3.",
        C: "Adds rather than removes part of the introduced constant.",
      },
    }),
    a({
      id: "y11adv-cts-qm7",
      prompt: "Solve by completing the square and enter the difference between the larger and smaller roots.",
      latex: "x^2-6x+1=0",
      answer: "4sqrt(2)",
      acceptedAnswers: ["4√2", "difference=4√2"],
      hint: "Rewrite as (x-3) squared equals 8, obtain both roots, and subtract.",
      explanation: "We have (x-3)²=8, so x=3±2√2. The larger minus smaller root is (3+2√2)-(3-2√2)=4√2.",
      diagnosticIntent: "This checks synthesis of completing the square, both radical roots, and a derived root separation.",
      taskType: "synthesis",
      difficulty: 4,
    }),
    a({
      id: "y11adv-cts-qm8",
      prompt: "Count the integer parameters for which the vertex lies strictly in the first quadrant.",
      latex: "f_k(x)=(x-k)^2+k,\\qquad k\\in\\{-3,-2,-1,0,1,2,3\\}",
      answer: "3",
      acceptedAnswers: ["k=1,2,3", "three"],
      hint: "Read the vertex as (k,k) and require both coordinates to be strictly positive.",
      explanation: "The vertex is (k,k). It lies strictly in the first quadrant exactly when k>0, giving k=1,2,3 from the supplied set, so there are three values.",
      diagnosticIntent: "This tests a bounded parameter investigation using the geometric information exposed by vertex form.",
      taskType: "investigative",
      difficulty: 5,
    }),
    a({
      id: "y11adv-cts-qm9",
      prompt: "Construct the quadratic in expanded form from its vertex and one point.",
      latex: "\\text{vertex }(-2,5),\\qquad f(0)=13",
      answer: "2x^2+8x+13",
      acceptedAnswers: ["2(x+2)^2+5", "2x²+8x+13"],
      hint: "Start with a(x+2) squared plus 5, use f(0)=13 to find a, and then expand.",
      explanation: "Write f(x)=a(x+2)²+5. The point gives 13=4a+5, so a=2. Expanding yields f(x)=2x²+8x+13.",
      diagnosticIntent: "This checks analytical reconstruction of a quadratic by moving between vertex and expanded forms.",
      taskType: "analytical",
      difficulty: 5,
    }),
    a({
      id: "y11adv-cts-qm10",
      prompt: "Find the minimum possible value under the linear constraint.",
      latex: "x+y=10,\\qquad x^2+y^2",
      answer: "50",
      acceptedAnswers: ["minimum 50 at x=y=5", "50"],
      hint: "Substitute y=10-x and complete the square in the resulting quadratic.",
      explanation: "The expression becomes x²+(10-x)²=2x²-20x+100=2(x-5)²+50. Its minimum is 50, attained when x=y=5.",
      diagnosticIntent: "This tests synthesis of a linear constraint, quadratic construction, and optimisation by completing the square.",
      taskType: "synthesis",
      difficulty: 5,
    }),
  ],

  "quadratic-inequalities": [
    a({
      id: "y11adv-qi-qm1",
      prompt: "Solve the quadratic inequality.",
      latex: "(x-2)(x+3)>0",
      answer: "x<-3 or x>2",
      acceptedAnswers: ["(-infinity,-3) union (2,infinity)", "(-∞,-3)∪(2,∞)"],
      hint: "Use the roots -3 and 2 to determine where the product has matching factor signs.",
      explanation: "The factors have the same sign outside the two roots, so their product is positive for x<-3 or x>2. Strict inequality excludes both roots.",
      diagnosticIntent: "This checks procedural sign-interval solving with correct strict endpoints.",
      taskType: "procedural",
      difficulty: 3,
    }),
    c({
      id: "y11adv-qi-qm2",
      prompt: "Which interval solves the inequality?",
      latex: "x^2-x-6<0",
      answer: "B",
      choices: ["x<-2\\text{ or }x>3", "-2<x<3", "-3<x<2", "x\\le-2\\text{ or }x\\ge3"],
      hint: "Factor as (x-3)(x+2) and use the sign between the roots for an upward-opening quadratic.",
      explanation: "The roots are -2 and 3. An upward-opening quadratic is negative between its roots, so the solution is -2<x<3.",
      diagnosticIntent: "This distinguishes the negative middle interval from the positive outer intervals and tracks strict endpoints.",
      taskType: "analytical",
      difficulty: 3,
      distractorMisconceptions: {
        A: "Selects the positive outer intervals.",
        C: "Uses incorrect roots from the factorisation.",
        D: "Selects outer intervals and includes equality despite a strict inequality.",
      },
    }),
    a({
      id: "y11adv-qi-qm3",
      prompt: "Find the inclusive time interval for which the height is non-negative.",
      latex: "h(t)=-t^2+10t-16,\\qquad t\\ge0",
      cartesianGraph: {
        description: "Downward-opening height parabola crossing the time axis at t=2 and t=8, positive between the intercepts.",
        xMin: 0,
        xMax: 10,
        yMin: -18,
        yMax: 12,
        xAxisLabel: "t",
        yAxisLabel: "h",
        parabolas: [{ kind: "quadratic", a: -1, b: 10, c: -16, label: "h(t)", xMin: 0, xMax: 10 }],
        points: [
          { x: 2, y: 0, label: "2" },
          { x: 8, y: 0, label: "8" },
        ],
      },
      answer: "[2,8]",
      acceptedAnswers: ["2<=t<=8", "2≤t≤8"],
      hint: "Find the two zeros and use the fact that the quadratic opens downward.",
      explanation: "The height factors as -(t-2)(t-8). A downward-opening quadratic is non-negative between its roots, including them, so 2≤t≤8.",
      diagnosticIntent: "This checks construction of a contextual solution interval from roots and opening direction.",
      taskType: "problem-solving",
      difficulty: 3,
    }),
    c({
      id: "y11adv-qi-qm4",
      prompt: "For which real x is the inequality true?",
      latex: "x^2+4x+5>0",
      answer: "D",
      choices: ["x<-2", "x>-2", "x\\ne-2", "all real x"],
      hint: "Complete the square and identify the smallest possible value.",
      explanation: "The expression is (x+2)²+1, whose minimum is 1. It is therefore positive for every real x.",
      diagnosticIntent: "This checks global sign reasoning for a quadratic with no real zeros rather than forcing artificial intervals.",
      taskType: "analytical",
      difficulty: 3,
      distractorMisconceptions: {
        A: "Uses one side of the vertex as though it were a root.",
        B: "Uses the other side of the vertex as though it were a root.",
        C: "Treats the vertex input as an excluded zero.",
      },
    }),
    a({
      id: "y11adv-qi-qm5",
      prompt: "Count the integer parameters for which x=0 satisfies the inequality.",
      latex: "(x-k)^2<4,\\qquad k\\in\\{-3,-2,-1,0,1,2,3\\}",
      answer: "3",
      acceptedAnswers: ["k=-1,0,1", "three"],
      hint: "Substitute x=0 and solve the strict inequality k squared less than 4.",
      explanation: "At x=0 the condition is k²<4, equivalently |k|<2. The qualifying listed integers are -1,0,1, giving three values.",
      diagnosticIntent: "This tests a bounded parameter investigation of membership in a quadratic-inequality solution set.",
      taskType: "investigative",
      difficulty: 4,
    }),
    c({
      id: "y11adv-qi-qm6",
      prompt: "A student divides by x without knowing its sign. Which complete solution is correct?",
      latex: "x(x-3)>0",
      answer: "C",
      choices: ["x>3", "x<3", "x<0\\text{ or }x>3", "0<x<3"],
      hint: "Use critical values 0 and 3 rather than dividing by a variable whose sign can change.",
      explanation: "The product is positive when both factors are negative, x<0, or both are positive, x>3. Dividing by x would miss one case or reverse the inequality incorrectly.",
      diagnosticIntent: "This diagnoses unsafe division by a variable in an inequality and restores full sign-case analysis.",
      taskType: "problem-solving",
      difficulty: 4,
      distractorMisconceptions: {
        A: "Keeps only the positive-x case after dividing by x.",
        B: "Solves a linear remnant without respecting product signs.",
        D: "Selects the interval where the two factors have opposite signs.",
      },
    }),
    a({
      id: "y11adv-qi-qm7",
      prompt: "Solve both inequalities simultaneously.",
      latex: "x^2-5x+6\\le0,\\qquad 2x-1>4",
      answer: "(5/2,3]",
      acceptedAnswers: ["5/2<x<=3", "2.5<x≤3"],
      hint: "Solve each inequality separately and intersect the resulting intervals.",
      explanation: "The quadratic gives (x-2)(x-3)≤0, so 2≤x≤3. The linear inequality gives x>5/2. Their intersection is (5/2,3].",
      diagnosticIntent: "This checks synthesis of quadratic and linear inequality solution sets with mixed endpoint types.",
      taskType: "synthesis",
      difficulty: 4,
    }),
    a({
      id: "y11adv-qi-qm8",
      prompt: "Count the integer parameters for which the inequality has at least one real solution.",
      latex: "x^2+(k-1)x+k<0,\\qquad k\\in\\{-2,-1,0,1,2,3,4,5,6,7,8\\}",
      answer: "6",
      acceptedAnswers: ["k=-2,-1,0,6,7,8", "six"],
      hint: "An upward-opening quadratic is negative somewhere exactly when its discriminant is positive.",
      explanation: "The discriminant is (k-1)²-4k=k²-6k+1. It is positive for k<3-2√2 or k>3+2√2, giving -2,-1,0,6,7,8: six listed integers.",
      diagnosticIntent: "This tests a bounded parameter investigation linking non-empty inequality solutions to discriminant conditions.",
      taskType: "investigative",
      difficulty: 5,
    }),
    a({
      id: "y11adv-qi-qm9",
      prompt: "Solve the quartic inequality by treating x squared as one quantity.",
      latex: "x^4-5x^2+4\\le0",
      answer: "[-2,-1] union [1,2]",
      acceptedAnswers: ["[-2,-1]∪[1,2]", "-2<=x<=-1 or 1<=x<=2"],
      hint: "Let u=x squared, factor (u-1)(u-4), and translate 1 less than or equal to x squared less than or equal to 4 back to x.",
      explanation: "With u=x², the inequality is (u-1)(u-4)≤0, so 1≤x²≤4. Thus 1≤|x|≤2, giving [-2,-1]∪[1,2].",
      diagnosticIntent: "This checks analytical substitution and the two-sided translation from a squared-variable interval.",
      taskType: "analytical",
      difficulty: 5,
    }),
    a({
      id: "y11adv-qi-qm10",
      prompt: "Find all parameters for which the quadratic is non-negative for every real x.",
      latex: "q_a(x)=x^2-2ax+a+2",
      answer: "[-1,2]",
      acceptedAnswers: ["-1<=a<=2", "−1≤a≤2"],
      hint: "Because the leading coefficient is positive, require the discriminant to be less than or equal to zero.",
      explanation: "The discriminant is 4a²-4(a+2)=4(a-2)(a+1). Requiring it to be non-positive gives -1≤a≤2, including repeated-root endpoints.",
      diagnosticIntent: "This tests synthesis of a global quadratic inequality, discriminant logic, and parameter-interval solving.",
      taskType: "synthesis",
      difficulty: 5,
    }),
  ],

  "working-with-functions-exam-practice": [
    a({
      id: "y11adv-func-exam-qm1",
      prompt: "Evaluate the simplified function at the permitted input.",
      latex: "f(x)=\\frac{x^2-9}{x-3},\\qquad x\\ne3,\\qquad f(5)",
      answer: "8",
      acceptedAnswers: ["f(5)=8"],
      hint: "Factor and cancel for permitted inputs, then substitute x=5.",
      explanation: "For x≠3, f(x)=(x-3)(x+3)/(x-3)=x+3. Since 5 is permitted, f(5)=8.",
      diagnosticIntent: "This checks procedural simplification while retaining the original domain restriction.",
      taskType: "procedural",
      difficulty: 3,
    }),
    c({
      id: "y11adv-func-exam-qm2",
      prompt: "Which combined function is guaranteed to be odd?",
      latex: "f(x)=x^3+x,\\qquad g(x)=x^2+1",
      answer: "C",
      choices: ["f+g", "f-g", "fg", "g^2"],
      hint: "Identify f as odd and g as even, then apply parity rules for products and sums.",
      explanation: "The product of an odd function and an even function is odd: (fg)(-x)=(-f(x))g(x)=-(fg)(x). The sums mix parity, and g² is even.",
      diagnosticIntent: "This checks synoptic parity reasoning across algebraic combinations.",
      taskType: "analytical",
      difficulty: 3,
      distractorMisconceptions: {
        A: "Assumes adding any symmetric functions preserves odd symmetry.",
        B: "Assumes subtraction removes the even component.",
        D: "Forgets that squaring an even function remains even.",
      },
    }),
    a({
      id: "y11adv-func-exam-qm3",
      prompt: "Construct the linear model from the two observations.",
      latex: "C(10)=74,\\qquad C(25)=119",
      answer: "C(x)=3x+44",
      acceptedAnswers: ["y=3x+44", "3x+44"],
      hint: "Find the gradient from the change in cost over the change in input, then recover the fixed term.",
      explanation: "The gradient is (119-74)/(25-10)=45/15=3. Using C(10)=74 gives 74=30+c, so c=44 and C(x)=3x+44.",
      diagnosticIntent: "This checks problem-solving construction of a rate-plus-fixed-charge model from data.",
      taskType: "problem-solving",
      difficulty: 3,
    }),
    c({
      id: "y11adv-func-exam-qm4",
      prompt: "Which description matches the roots of the quadratic?",
      latex: "2x^2-4x+1=0",
      answer: "B",
      choices: ["Two distinct rational roots", "Two distinct irrational real roots", "One repeated root", "No real roots"],
      hint: "Calculate the discriminant and decide whether it is positive and whether it is a perfect square.",
      explanation: "The discriminant is 16-8=8, which is positive but not a perfect square. Therefore there are two distinct irrational real roots.",
      diagnosticIntent: "This checks complete discriminant classification, including rationality as well as existence.",
      taskType: "analytical",
      difficulty: 3,
      distractorMisconceptions: {
        A: "Treats any positive discriminant as giving rational roots.",
        C: "Confuses positive discriminant with zero.",
        D: "Subtracts the discriminant terms incorrectly to obtain a negative value.",
      },
    }),
    a({
      id: "y11adv-func-exam-qm5",
      prompt: "Count the integer parameters for which x=0 belongs to the real domain.",
      latex: "h_k(x)=\\frac{\\sqrt{x-k}}{x-4},\\qquad k\\in\\{-2,-1,0,1,2,3,4,5\\}",
      answer: "3",
      acceptedAnswers: ["k=-2,-1,0", "three"],
      hint: "At x=0, require the radicand -k to be non-negative; the denominator is already non-zero.",
      explanation: "The square root at x=0 is real when -k≥0, so k≤0. The listed values -2,-1,0 qualify, giving three parameters.",
      diagnosticIntent: "This tests a bounded domain investigation with parameter-dependent square-root restrictions.",
      taskType: "investigative",
      difficulty: 4,
    }),
    c({
      id: "y11adv-func-exam-qm6",
      prompt: "A student uses the second branch at x=1. Which value is correct?",
      latex: "p(x)=\\begin{cases}2x+3,&x\\le1\\\\x^2-1,&x>1\\end{cases},\\qquad p(1)",
      answer: "D",
      choices: ["0", "1", "4", "5"],
      hint: "The equality sign is attached to the first branch, so substitute x=1 there.",
      explanation: "Since x=1 satisfies x≤1, use 2x+3 to obtain p(1)=2(1)+3=5. The second branch excludes the boundary.",
      diagnosticIntent: "This diagnoses incorrect reading of inclusive and strict piecewise conditions.",
      taskType: "problem-solving",
      difficulty: 4,
      distractorMisconceptions: {
        A: "Uses the excluded second branch at x=1.",
        B: "Returns the input rather than evaluating a branch.",
        C: "Substitutes into the first branch but omits the constant.",
      },
    }),
    a({
      id: "y11adv-func-exam-qm7",
      prompt: "Find the sum of the x-coordinates of the two intersection points.",
      latex: "(x-1)^2+(y-2)^2=25,\\qquad y=6",
      cartesianGraph: {
        description: "Circle centred at (1,2) with radius 5 and horizontal line y=6 meeting it at two symmetric points.",
        xMin: -5,
        xMax: 7,
        yMin: -4,
        yMax: 8,
        circles: [{ h: 1, k: 2, r: 5, label: "circle" }],
        lines: [{ kind: "linear", m: 0, b: 6, label: "y=6" }],
        points: [
          { x: -2, y: 6, label: "(-2,6)" },
          { x: 4, y: 6, label: "(4,6)" },
        ],
      },
      answer: "2",
      acceptedAnswers: ["x=-2 and 4; sum 2", "-2+4=2"],
      hint: "Substitute y=6 into the circle relation and solve the resulting square equation.",
      explanation: "Substitution gives (x-1)²+16=25, so (x-1)²=9 and x=1±3, namely -2 and 4. Their sum is 2.",
      diagnosticIntent: "This checks synthesis of circle-line intersections and retention of both square-root branches.",
      taskType: "synthesis",
      difficulty: 4,
    }),
    a({
      id: "y11adv-func-exam-qm8",
      prompt: "Count the integer parameters for which the quadratic is positive for every real x.",
      latex: "q_k(x)=x^2-2kx+9,\\qquad k\\in\\{-5,-4,\\ldots,4,5\\}",
      answer: "5",
      acceptedAnswers: ["k=-2,-1,0,1,2", "five"],
      hint: "A monic quadratic is strictly positive everywhere when its discriminant is negative.",
      explanation: "The discriminant is 4k²-36. Strict positivity requires 4k²-36<0, so |k|<3. The integer values -2,-1,0,1,2 give five parameters.",
      diagnosticIntent: "This tests a bounded investigation of a global sign condition through the discriminant.",
      taskType: "investigative",
      difficulty: 5,
    }),
    a({
      id: "y11adv-func-exam-qm9",
      prompt: "Find the domain of the composite function.",
      latex: "f(x)=\\sqrt{x+2},\\qquad g(x)=3x-1,\\qquad (f\\circ g)(x)",
      answer: "[-1/3,infinity)",
      acceptedAnswers: ["x>=-1/3", "x≥−1/3"],
      hint: "Require the inner output plus 2 to be non-negative.",
      explanation: "The composite is √((3x-1)+2)=√(3x+1). Real outputs require 3x+1≥0, so x≥-1/3.",
      diagnosticIntent: "This checks analytical propagation of an outer square-root domain through an inner linear function.",
      taskType: "analytical",
      difficulty: 5,
    }),
    a({
      id: "y11adv-func-exam-qm10",
      prompt: "A rectangle has perimeter 20. Find all widths that make its area at least 21.",
      latex: "w+\\ell=10,\\qquad A=w\\ell\\ge21",
      answer: "[3,7]",
      acceptedAnswers: ["3<=w<=7", "3≤w≤7"],
      hint: "Write length as 10-w, form a quadratic inequality in w, and solve between its roots.",
      explanation: "The area condition is w(10-w)≥21, or w²-10w+21≤0. Factoring gives (w-3)(w-7)≤0, so 3≤w≤7.",
      diagnosticIntent: "This tests synthesis of a geometric constraint, model construction, and a quadratic inequality with contextual endpoints.",
      taskType: "synthesis",
      difficulty: 5,
    }),
  ],
};
