import {
  richAnswer as a,
  richChoice as c,
  type WorkingFunctionsMasteryMap,
} from "./workingFunctionsQualityHelpers";

export const workingFunctionsQualityAlgebra: WorkingFunctionsMasteryMap = {
  "odd-even-functions": [
    a({
      id: "y11adv-sym-qm1",
      prompt: "Use the stated symmetry to determine the missing function value.",
      latex: "f(-x)=f(x),\\qquad f(3)=7,\\qquad f(-3)",
      answer: "7",
      acceptedAnswers: ["f(-3)=7"],
      hint: "The defining equation says opposite inputs have equal outputs; substitute x=3 directly into that relationship.",
      explanation: "Because f is even, f(-3)=f(3). The supplied value f(3)=7 therefore gives f(-3)=7 without needing an explicit formula.",
      diagnosticIntent: "This checks direct procedural use of the defining equation for an even function rather than a visual guess.",
      taskType: "procedural",
      difficulty: 3,
    }),
    c({
      id: "y11adv-sym-qm2",
      prompt: "Which polynomial is an odd function on the real numbers?",
      latex: "f(-x)=-f(x)",
      answer: "C",
      choices: ["x^4-2x^2", "x^3+1", "x^5-2x", "x^4+x"],
      hint: "An odd polynomial contains only odd powers and has no non-zero constant term.",
      explanation: "The expression x⁵-2x contains only odd powers, so replacing x by -x negates every term. The other choices are even or mix incompatible parity.",
      diagnosticIntent: "This distinguishes algebraic parity structure from the unrelated fact that a polynomial may have odd degree.",
      taskType: "analytical",
      difficulty: 3,
      distractorMisconceptions: {
        A: "Recognises a symmetric polynomial but confuses even symmetry with odd symmetry.",
        B: "Uses the odd leading degree while ignoring the non-zero constant term.",
        D: "Treats a mixture of even and odd powers as odd because one odd term appears.",
      },
    }),
    a({
      id: "y11adv-sym-qm3",
      prompt: "Find the parameter that makes the polynomial an even function.",
      latex: "p(x)=x^4+(k-2)x^3+3x^2+5",
      answer: "2",
      acceptedAnswers: ["k=2"],
      hint: "Every coefficient of an odd power must be zero for a polynomial to be even.",
      explanation: "The only odd-power term is (k-2)x³. Even symmetry requires k-2=0, so k=2; the remaining powers 4, 2 and 0 are all even.",
      diagnosticIntent: "This checks reverse parameter recovery from a parity condition instead of merely classifying a completed polynomial.",
      taskType: "problem-solving",
      difficulty: 3,
    }),
    c({
      id: "y11adv-sym-qm4",
      prompt: "Which statement is guaranteed when f is even and g is odd?",
      latex: "f(-x)=f(x),\\qquad g(-x)=-g(x)",
      answer: "B",
      choices: ["f+g is even", "fg is odd", "f-g is even", "g^2 is odd"],
      hint: "Apply x to -x to each proposed combination and compare with the original expression.",
      explanation: "For the product, (fg)(-x)=f(-x)g(-x)=f(x)[-g(x)]=-(fg)(x), so fg is odd. Sums generally mix parity, while g² is even.",
      diagnosticIntent: "This checks structural reasoning with parity operations rather than memorising isolated examples.",
      taskType: "analytical",
      difficulty: 3,
      distractorMisconceptions: {
        A: "Assumes adding an even and odd function preserves even symmetry.",
        C: "Assumes subtraction removes the odd component automatically.",
        D: "Forgets that squaring cancels the sign change of an odd function.",
      },
    }),
    a({
      id: "y11adv-sym-qm5",
      prompt: "Count the functions in the bounded family that are even.",
      latex: "f_n(x)=x^n,\\qquad n\\in\\{1,2,3,4,5,6,7,8\\}",
      answer: "4",
      acceptedAnswers: ["n=2,4,6,8", "four"],
      hint: "Compare the output at -x with the output at x and separate the even and odd integer exponents.",
      explanation: "When n is even, raising -x to the nth power gives the same output as raising x to that power. The qualifying exponents are 2,4,6 and 8, giving four functions.",
      diagnosticIntent: "This tests a bounded investigation that generalises parity from repeated cases to exponent structure.",
      taskType: "investigative",
      difficulty: 4,
    }),
    c({
      id: "y11adv-sym-qm6",
      prompt: "A student concludes that the function is even because two negative signs cancel. Which calculation is correct?",
      latex: "h(x)=x^3-4x",
      answer: "D",
      choices: ["h(-x)=h(x)", "h(-x)=x^3+4x", "h(-x)=-x^3-4x", "h(-x)=-x^3+4x=-h(x)"],
      hint: "Substitute -x into both occurrences of x and evaluate the odd powers before comparing.",
      explanation: "We obtain h(-x)=(-x)³-4(-x)=-x³+4x=-(x³-4x)=-h(x). Thus h is odd, and the student's cancellation argument mishandles the cubic term.",
      diagnosticIntent: "This diagnoses incomplete substitution of -x and confusion between term signs and whole-function parity.",
      taskType: "problem-solving",
      difficulty: 4,
      distractorMisconceptions: {
        A: "Accepts the student's unsupported even conclusion.",
        B: "Changes only the linear-term sign while leaving the cubic positive.",
        C: "Changes the cubic sign but fails to reverse -4(-x).",
      },
    }),
    a({
      id: "y11adv-sym-qm7",
      prompt: "Recover the even component at x=2 from the combined function values.",
      latex: "h(x)=p(x)+q(x),\\quad p\\text{ even},\\quad q\\text{ odd},\\quad h(2)=9,\\quad h(-2)=1",
      answer: "5",
      acceptedAnswers: ["p(2)=5"],
      hint: "Add h(2) and h(-2); the odd contributions cancel while the even contributions double.",
      explanation: "We have h(2)=p(2)+q(2) and h(-2)=p(2)-q(2). Adding gives 10=2p(2), hence the even component is p(2)=5.",
      diagnosticIntent: "This checks synthesis of symmetry with simultaneous-equation elimination to separate even and odd components.",
      taskType: "synthesis",
      difficulty: 4,
    }),
    a({
      id: "y11adv-sym-qm8",
      prompt: "Determine a+b+c from the symmetry and value constraints.",
      latex: "f(x)=x^4+ax^3+bx^2+cx+1,\\qquad f\\text{ even},\\qquad f(1)=6",
      answer: "4",
      acceptedAnswers: ["a=0,b=4,c=0", "a+b+c=4"],
      hint: "Even symmetry eliminates the odd-power coefficients a and c; then use the supplied function value.",
      explanation: "Evenness forces a=0 and c=0. Substituting x=1 gives 1+b+1=6, so b=4 and therefore a+b+c=4.",
      diagnosticIntent: "This tests a parameter investigation combining coefficient parity constraints with a numerical function condition.",
      taskType: "investigative",
      difficulty: 5,
    }),
    a({
      id: "y11adv-sym-qm9",
      prompt: "Find the simplified expression that isolates the even part of the function.",
      latex: "f(x)=x^2+x+3,\\qquad f(x)+f(-x)",
      answer: "2x^2+6",
      acceptedAnswers: ["2(x^2+3)", "2x²+6"],
      hint: "Compute f(-x) term by term and add; the odd-powered terms should cancel.",
      explanation: "Since f(-x)=x²-x+3, adding gives (x²+x+3)+(x²-x+3)=2x²+6. The operation cancels the odd component and doubles the even component.",
      diagnosticIntent: "This checks analytical decomposition of a neither-even-nor-odd function into its even contribution.",
      taskType: "analytical",
      difficulty: 5,
    }),
    a({
      id: "y11adv-sym-qm10",
      prompt: "Use the constructed odd function to find the requested product.",
      latex: "g(x)=f(x)-f(-x),\\qquad f(3)=8,\\qquad f(-3)=2,\\qquad g(3)g(-3)",
      answer: "-36",
      acceptedAnswers: ["−36", "g(3)=6, g(-3)=-6, product -36"],
      hint: "First compute g(3); then use either the definition or the fact that g is necessarily odd.",
      explanation: "The definition gives g(3)=8-2=6. Also g(-3)=f(-3)-f(3)=2-8=-6, confirming odd symmetry. Their product is 6(-6)=-36.",
      diagnosticIntent: "This tests synthesis of a general odd-function construction with supplied asymmetric data and a derived calculation.",
      taskType: "synthesis",
      difficulty: 5,
    }),
  ],

  "algebraic-techniques": [
    a({
      id: "y11adv-alg-qm1",
      prompt: "Simplify the index expression for non-zero x.",
      latex: "\\frac{x^4x^{-1}}{x^2}",
      answer: "x",
      acceptedAnswers: ["x^1"],
      hint: "Add exponents in the numerator and subtract the denominator exponent.",
      explanation: "The numerator exponent is 4+(-1)=3, giving x³. Dividing by x² subtracts 2 from that exponent, leaving x for non-zero x.",
      diagnosticIntent: "This checks coordinated application of multiplication, negative-index, and division laws with the domain condition retained.",
      taskType: "procedural",
      difficulty: 3,
    }),
    c({
      id: "y11adv-alg-qm2",
      prompt: "Which value is equal to the stated negative fractional power?",
      latex: "16^{-3/4}",
      answer: "B",
      choices: ["-8", "\\frac18", "\\frac1{64}", "8"],
      hint: "Evaluate the fourth root first, cube it, and then apply the reciprocal indicated by the negative exponent.",
      explanation: "The fourth root of 16 is 2, and cubing gives 8. The negative exponent then takes the reciprocal, so the stated value is 1/8.",
      diagnosticIntent: "This distinguishes a negative exponent from a negative value and checks the order of fractional-index operations.",
      taskType: "analytical",
      difficulty: 3,
      distractorMisconceptions: {
        A: "Treats the negative exponent as an external negative sign.",
        C: "Raises 16 to the third power before incorrectly applying the fourth root.",
        D: "Evaluates the positive fractional power but omits the reciprocal.",
      },
    }),
    a({
      id: "y11adv-alg-qm3",
      prompt: "Rationalise the denominator and simplify.",
      latex: "\\frac3{\\sqrt5-1}",
      answer: "3(sqrt(5)+1)/4",
      acceptedAnswers: ["3(√5+1)/4", "(3√5+3)/4"],
      hint: "Multiply numerator and denominator by the conjugate square root of 5 plus 1.",
      explanation: "Multiplying by (\\sqrt5+1)/(\\sqrt5+1) gives numerator 3(\\sqrt5+1) and denominator 5-1=4. The simplified result is 3(\\sqrt5+1)/4.",
      diagnosticIntent: "This checks purposeful use of a conjugate and accurate simplification of the difference-of-squares denominator.",
      taskType: "problem-solving",
      difficulty: 3,
    }),
    c({
      id: "y11adv-alg-qm4",
      prompt: "Which identity is valid for all positive a and b?",
      latex: "a>0,\\qquad b>0",
      answer: "C",
      choices: ["\\sqrt{a+b}=\\sqrt a+\\sqrt b", "\\sqrt{a-b}=\\sqrt a-\\sqrt b", "\\sqrt{ab}=\\sqrt a\\sqrt b", "\\frac1{\\sqrt a+\\sqrt b}=\\frac1{\\sqrt a}+\\frac1{\\sqrt b}"],
      hint: "Recall that square roots distribute over products of non-negative factors, but not generally over sums or differences.",
      explanation: "For positive a and b, √(ab)=√a·√b is valid. Square roots do not distribute over addition or subtraction, and reciprocals do not split across a sum.",
      diagnosticIntent: "This identifies overgeneralisation of surd product laws to operations for which distribution is invalid.",
      taskType: "analytical",
      difficulty: 3,
      distractorMisconceptions: {
        A: "Incorrectly distributes a square root across addition.",
        B: "Incorrectly distributes a square root across subtraction.",
        D: "Incorrectly separates the reciprocal of a sum.",
      },
    }),
    a({
      id: "y11adv-alg-qm5",
      prompt: "Find the sum of all real solutions.",
      latex: "x^{2/3}=4",
      answer: "0",
      acceptedAnswers: ["solutions -8 and 8; sum 0", "x=±8, sum=0"],
      hint: "Let u be the real cube root of x, solve u squared equals 4, and cube both possible values.",
      explanation: "Let u be the real cube root of x. Then u²=4, so u=±2. Cubing these values gives x=8 or x=-8, whose sum is 0.",
      diagnosticIntent: "This tests an investigation of fractional powers that retains both signs rather than taking only the principal square root.",
      taskType: "investigative",
      difficulty: 4,
    }),
    c({
      id: "y11adv-alg-qm6",
      prompt: "A student writes the reciprocal of a sum as the sum of reciprocals. Which correction is valid?",
      latex: "(a+b)^{-1},\\qquad a+b\\ne0",
      answer: "A",
      choices: ["\\frac1{a+b}", "\\frac1a+\\frac1b", "a^{-1}+b", "\\frac1{ab}"],
      hint: "A negative exponent applies to the entire bracketed base, not separately to each term.",
      explanation: "The base is the whole quantity a+b, so exponent -1 gives its reciprocal 1/(a+b). Exponents do not distribute over addition.",
      diagnosticIntent: "This diagnoses invalid distribution of negative indices across addition and checks attention to grouping.",
      taskType: "problem-solving",
      difficulty: 4,
      distractorMisconceptions: {
        B: "Distributes the reciprocal over addition.",
        C: "Applies the negative exponent to only the first term.",
        D: "Changes an additive base into a product.",
      },
    }),
    a({
      id: "y11adv-alg-qm7",
      prompt: "Use conjugate structure to evaluate the expression exactly.",
      latex: "u=\\sqrt3+\\sqrt2,\\quad v=\\sqrt3-\\sqrt2,\\quad u^4+v^4",
      answer: "98",
      acceptedAnswers: ["u^4+v^4=98"],
      hint: "First find uv and u squared plus v squared, then square the latter and subtract twice u squared v squared.",
      explanation: "We have uv=3-2=1 and u²+v²=2(3+2)=10. Hence u⁴+v⁴=(u²+v²)²-2u²v²=100-2=98.",
      diagnosticIntent: "This checks synthesis of conjugates, symmetric expressions, and an identity that avoids lengthy direct expansion.",
      taskType: "synthesis",
      difficulty: 4,
    }),
    a({
      id: "y11adv-alg-qm8",
      prompt: "Determine the positive integer n from the conjugate reciprocal condition.",
      latex: "z=\\sqrt n+\\sqrt{n-1},\\qquad z+\\frac1z=6",
      answer: "9",
      acceptedAnswers: ["n=9"],
      hint: "Use the conjugate: the product of square root of n plus square root of n-1 and its conjugate is 1.",
      explanation: "Because [√n+√(n-1)][√n-√(n-1)]=1, the second bracket is 1/z. Thus z+1/z=2√n=6, so n=9.",
      diagnosticIntent: "This tests an investigative reverse use of conjugates to recover a parameter from a reciprocal relationship.",
      taskType: "investigative",
      difficulty: 5,
    }),
    a({
      id: "y11adv-alg-qm9",
      prompt: "Simplify completely for positive x and non-zero y.",
      latex: "\\frac{(x^{3/2}y^{-1})^2}{x^{-1}y^{-3}}",
      answer: "x^4y",
      acceptedAnswers: ["yx^4", "x⁴y"],
      hint: "Apply the outer square first, then subtract each denominator exponent from the corresponding numerator exponent.",
      explanation: "The outer square gives x³ divided by y². Subtracting denominator exponents leaves exponent 4 on x and exponent 1 on y, so the result is x⁴y.",
      diagnosticIntent: "This checks analytical coordination of power, quotient, negative, and fractional index laws across two variables.",
      taskType: "analytical",
      difficulty: 5,
    }),
    a({
      id: "y11adv-alg-qm10",
      prompt: "Solve the surd equation over the real numbers.",
      latex: "\\sqrt{x+5}-\\sqrt x=1",
      answer: "4",
      acceptedAnswers: ["x=4"],
      hint: "Isolate one radical, square once, solve for the remaining square root, and verify the candidate in the original equation.",
      explanation: "Rearrange to √(x+5)=√x+1. Squaring gives x+5=x+2√x+1, so √x=2 and x=4. Checking gives 3-2=1, so it is valid.",
      diagnosticIntent: "This tests synthesis of surd manipulation, controlled squaring, domain awareness, and final verification.",
      taskType: "synthesis",
      difficulty: 5,
    }),
  ],

  "quadratic-equations-discriminant": [
    a({
      id: "y11adv-quad-qm1",
      prompt: "Calculate the discriminant of the quadratic equation.",
      latex: "3x^2-4x-2=0",
      answer: "40",
      acceptedAnswers: ["Delta=40", "Δ=40"],
      hint: "Identify a=3, b=-4 and c=-2 before substituting into b squared minus 4ac.",
      explanation: "The discriminant is (-4)²-4(3)(-2)=16+24=40. The negative constant makes the product -4ac positive here.",
      diagnosticIntent: "This checks accurate coefficient signs and procedural evaluation of the discriminant.",
      taskType: "procedural",
      difficulty: 3,
    }),
    c({
      id: "y11adv-quad-qm2",
      prompt: "How many distinct real roots does the equation have?",
      latex: "2x^2+5x+7=0",
      answer: "D",
      choices: ["Two rational roots", "Two irrational roots", "One repeated root", "No real roots"],
      hint: "Evaluate the discriminant and interpret its sign before attempting to solve.",
      explanation: "The discriminant is 5²-4(2)(7)=25-56=-31. Because it is negative, the equation has no real roots.",
      diagnosticIntent: "This checks interpretation of discriminant sign rather than confusing root sign with discriminant sign.",
      taskType: "analytical",
      difficulty: 3,
      distractorMisconceptions: {
        A: "Assumes integer coefficients guarantee rational roots.",
        B: "Treats a non-square discriminant as irrational without checking that it is negative.",
        C: "Confuses a negative discriminant with a zero discriminant.",
      },
    }),
    a({
      id: "y11adv-quad-qm3",
      prompt: "Find the positive parameter that makes the equation have a repeated root.",
      latex: "x^2+kx+9=0",
      answer: "6",
      acceptedAnswers: ["k=6"],
      hint: "A repeated root requires the discriminant k squared minus 36 to equal zero, then select the requested sign.",
      explanation: "Setting the discriminant to zero gives k²-4(1)(9)=0, so k²=36 and k=±6. The positive parameter is k=6.",
      diagnosticIntent: "This checks reverse use of the repeated-root condition and careful selection from two parameter values.",
      taskType: "problem-solving",
      difficulty: 3,
    }),
    c({
      id: "y11adv-quad-qm4",
      prompt: "Which equation has two distinct irrational real roots?",
      latex: "x\\in\\mathbb R",
      answer: "B",
      choices: ["x^2-5x+6=0", "x^2-2x-1=0", "x^2+4x+4=0", "x^2+x+1=0"],
      hint: "Look for a positive discriminant that is not a perfect square.",
      explanation: "For x²-2x-1=0, the discriminant is 4+4=8, positive but not a perfect square, so the two real roots are distinct and irrational.",
      diagnosticIntent: "This distinguishes root existence from rationality by using both the sign and square status of the discriminant.",
      taskType: "analytical",
      difficulty: 3,
      distractorMisconceptions: {
        A: "Selects a positive perfect-square discriminant, which gives rational roots.",
        C: "Selects zero discriminant, which gives one repeated root.",
        D: "Selects a negative discriminant, which gives no real roots.",
      },
    }),
    a({
      id: "y11adv-quad-qm5",
      prompt: "Count the integer parameters in the stated set that produce no real roots.",
      latex: "x^2-2kx+k+3=0,\\qquad k\\in\\{-3,-2,-1,0,1,2,3\\}",
      answer: "4",
      acceptedAnswers: ["k=-1,0,1,2", "four"],
      hint: "Form the discriminant as a quadratic in k and solve the strict inequality that makes it negative.",
      explanation: "The discriminant is 4(k²-k-3). It is negative between (1-√13)/2 and (1+√13)/2, approximately -1.30 and 2.30. Thus k=-1,0,1,2: four values.",
      diagnosticIntent: "This tests a bounded parameter investigation connecting a discriminant inequality to an integer count.",
      taskType: "investigative",
      difficulty: 4,
    }),
    c({
      id: "y11adv-quad-qm6",
      prompt: "A student substitutes b=3 instead of b=-3. Which solution set is correct?",
      latex: "2x^2-3x-2=0",
      answer: "C",
      choices: ["x=-2,\\ \\frac12", "x=2,\\ \\frac12", "x=2,\\ -\\frac12", "x=-2,\\ -\\frac12"],
      hint: "Either factor the quadratic or use -b=3 in the quadratic formula.",
      explanation: "The quadratic factors as (2x+1)(x-2)=0, giving x=-1/2 or x=2. The student's sign error changes the linear term and therefore the roots.",
      diagnosticIntent: "This diagnoses failure to carry the signed coefficient b into the quadratic formula.",
      taskType: "problem-solving",
      difficulty: 4,
      distractorMisconceptions: {
        A: "Uses the wrong sign for both roots after substituting b incorrectly.",
        B: "Finds the positive root but loses the negative sign on the fractional root.",
        D: "Keeps the negative fractional root but reverses the integer root.",
      },
    }),
    a({
      id: "y11adv-quad-qm7",
      prompt: "Without solving for the roots, find the sum of their squares.",
      latex: "\\alpha,\\beta\\text{ are roots of }x^2-5x+2=0,\\qquad \\alpha^2+\\beta^2",
      answer: "21",
      acceptedAnswers: ["alpha^2+beta^2=21", "α²+β²=21"],
      hint: "Use alpha plus beta equals 5 and alpha beta equals 2, then expand their sum squared.",
      explanation: "Vieta's relations give α+β=5 and αβ=2. Hence α²+β²=(α+β)²-2αβ=25-4=21.",
      diagnosticIntent: "This checks synthesis of quadratic coefficient information with a symmetric expression in the roots.",
      taskType: "synthesis",
      difficulty: 4,
    }),
    a({
      id: "y11adv-quad-qm8",
      prompt: "Find the parameter for which the equation has a repeated positive root.",
      latex: "x^2-2(k+1)x+k^2=0",
      answer: "-1/2",
      acceptedAnswers: ["k=-1/2", "−0.5"],
      hint: "Set the discriminant to zero, then verify that the repeated root k+1 is positive.",
      explanation: "The discriminant is 4(k+1)²-4k²=4(2k+1). Setting it to zero gives k=-1/2. The repeated root is k+1=1/2, which is positive.",
      diagnosticIntent: "This tests an investigative parameter condition with both multiplicity and root-sign requirements.",
      taskType: "investigative",
      difficulty: 5,
    }),
    a({
      id: "y11adv-quad-qm9",
      prompt: "Construct the monic quadratic with the stated roots.",
      latex: "2+\\sqrt3,\\qquad 2-\\sqrt3",
      answer: "x^2-4x+1=0",
      acceptedAnswers: ["x²−4x+1=0", "(x-(2+√3))(x-(2-√3))=0"],
      hint: "Use the sum and product of the conjugate roots to form x squared minus their sum times x plus their product.",
      explanation: "The roots sum to 4 and multiply to 4-3=1. Therefore the monic quadratic is x²-4x+1=0.",
      diagnosticIntent: "This checks analytical reconstruction of rational coefficients from a conjugate irrational root pair.",
      taskType: "analytical",
      difficulty: 5,
    }),
    a({
      id: "y11adv-quad-qm10",
      prompt: "Find the positive gradient for which the line meets the parabola at exactly one point.",
      latex: "y=mx,\\qquad y=x^2+4",
      answer: "4",
      acceptedAnswers: ["m=4"],
      hint: "Equate the two functions and impose a zero discriminant on the resulting quadratic in x.",
      explanation: "Intersections satisfy x²-mx+4=0. Exactly one point requires m²-16=0, so m=±4; the requested positive gradient is m=4.",
      diagnosticIntent: "This tests synthesis of function intersections, tangency as a repeated root, and parameter selection.",
      taskType: "synthesis",
      difficulty: 5,
    }),
  ],

  "linear-functions": [
    a({
      id: "y11adv-lin-qm1",
      prompt: "Find the gradient of the line through the two points.",
      latex: "A(-2,5),\\qquad B(4,-7)",
      answer: "-2",
      acceptedAnswers: ["m=-2", "−2"],
      hint: "Use change in y over change in x in the same point order for numerator and denominator.",
      explanation: "The gradient is [-7-5]/[4-(-2)]=-12/6=-2. Using a consistent point order prevents an accidental sign reversal.",
      diagnosticIntent: "This checks procedural calculation of gradient from signed coordinate differences.",
      taskType: "procedural",
      difficulty: 3,
    }),
    c({
      id: "y11adv-lin-qm2",
      prompt: "Which equation is perpendicular to the stated line?",
      latex: "3x-2y+5=0",
      answer: "D",
      choices: ["y=\\frac32x-1", "y=-\\frac32x+4", "y=\\frac23x+1", "y=-\\frac23x+7"],
      hint: "Rearrange the given line to find its gradient, then take the negative reciprocal.",
      explanation: "The given line is y=(3/2)x+5/2, so its gradient is 3/2. A perpendicular gradient is -2/3, which appears only in choice D.",
      diagnosticIntent: "This checks conversion from general form and distinguishes opposite gradient from negative reciprocal gradient.",
      taskType: "analytical",
      difficulty: 3,
      distractorMisconceptions: {
        A: "Chooses a parallel line with the same gradient.",
        B: "Negates the gradient without taking its reciprocal.",
        C: "Takes the reciprocal without changing sign.",
      },
    }),
    a({
      id: "y11adv-lin-qm3",
      prompt: "Find the equation of the line through the point and parallel to the given line.",
      latex: "(3,1),\\qquad y=-2x+5",
      answer: "y=-2x+7",
      acceptedAnswers: ["2x+y-7=0", "y=−2x+7"],
      hint: "Keep the parallel gradient -2 and substitute the supplied point to determine the intercept.",
      explanation: "A parallel line has gradient -2, so write y=-2x+c. Substituting (3,1) gives 1=-6+c and c=7, hence y=-2x+7.",
      diagnosticIntent: "This checks construction of a line from a relational condition and one point.",
      taskType: "problem-solving",
      difficulty: 3,
    }),
    c({
      id: "y11adv-lin-qm4",
      prompt: "Which solution correctly handles division by a negative coefficient?",
      latex: "5-3x\\ge14",
      answer: "B",
      choices: ["x\\ge-3", "x\\le-3", "x\\ge3", "x\\le3"],
      hint: "Subtract 5, then reverse the inequality when dividing both sides by -3.",
      explanation: "Subtracting 5 gives -3x≥9. Dividing by -3 reverses the inequality, so x≤-3.",
      diagnosticIntent: "This diagnoses the common failure to reverse an inequality after division by a negative number.",
      taskType: "analytical",
      difficulty: 3,
      distractorMisconceptions: {
        A: "Divides by -3 without reversing the inequality.",
        C: "Loses the negative sign and also keeps the original direction.",
        D: "Loses the negative sign but reverses the direction.",
      },
    }),
    a({
      id: "y11adv-lin-qm5",
      prompt: "Count the integer gradients that make the intersection x-coordinate positive.",
      latex: "y=kx+4,\\qquad y=2x-1,\\qquad k\\in\\{-2,-1,0,1,2,3,4\\}",
      answer: "4",
      acceptedAnswers: ["k=-2,-1,0,1", "four"],
      hint: "Solve the intersection input as 5 divided by 2 minus k and analyse when it is positive, excluding parallel lines.",
      explanation: "Equating gives (2-k)x=5, so x=5/(2-k). This is positive when k<2. The listed values -2,-1,0,1 qualify, giving four gradients.",
      diagnosticIntent: "This tests a bounded parameter investigation involving intersection, sign, and the parallel exceptional case.",
      taskType: "investigative",
      difficulty: 4,
    }),
    c({
      id: "y11adv-lin-qm6",
      prompt: "A student assigns gradient zero to the stated line. Which correction is valid?",
      latex: "x=4",
      answer: "C",
      choices: ["Its gradient is 0", "Its gradient is 4", "Its gradient is undefined", "Its gradient is -4"],
      hint: "A vertical line has zero horizontal change, so the gradient quotient would require division by zero.",
      explanation: "Every point on x=4 has the same x-coordinate. Since run equals zero, rise/run is undefined; gradient zero belongs to a horizontal line, not a vertical one.",
      diagnosticIntent: "This diagnoses confusion between horizontal zero gradient and vertical undefined gradient.",
      taskType: "problem-solving",
      difficulty: 4,
      distractorMisconceptions: {
        A: "Confuses a vertical line with a horizontal line.",
        B: "Reads the coordinate constant as the gradient.",
        D: "Adds a negative sign to the coordinate constant without using rise over run.",
      },
    }),
    a({
      id: "y11adv-lin-qm7",
      prompt: "Solve the simultaneous equations and enter x+y.",
      latex: "2x+y=7,\\qquad x-y=2",
      answer: "4",
      acceptedAnswers: ["x=3,y=1, so x+y=4", "3+1=4"],
      hint: "Add the equations to eliminate y, then substitute the resulting x-value.",
      explanation: "Adding gives 3x=9, so x=3. Then 3-y=2 gives y=1, and therefore x+y=4.",
      diagnosticIntent: "This checks synthesis of two linear constraints and use of the solved ordered pair in a derived quantity.",
      taskType: "synthesis",
      difficulty: 4,
    }),
    a({
      id: "y11adv-lin-qm8",
      prompt: "Find the parameter that makes all three lines concurrent.",
      latex: "y=2x+1,\\qquad y=-x+7,\\qquad y=kx-1",
      answer: "3",
      acceptedAnswers: ["k=3"],
      hint: "Find the intersection of the first two lines, then force the parameterised line through that point.",
      explanation: "The first two lines meet where 2x+1=-x+7, giving x=2 and y=5. Substituting into y=kx-1 gives 5=2k-1, so k=3.",
      diagnosticIntent: "This tests an investigative concurrency condition by linking an intersection point to a parameterised line.",
      taskType: "investigative",
      difficulty: 5,
    }),
    a({
      id: "y11adv-lin-qm9",
      prompt: "Find the input at which the two linear cost models are equal.",
      latex: "C_1(x)=25+4x,\\qquad C_2(x)=10+6x",
      answer: "7.5",
      acceptedAnswers: ["x=7.5", "15/2"],
      hint: "Set the two costs equal and isolate x; a non-integer input is permitted by the algebraic model.",
      explanation: "Equating gives 25+4x=10+6x. Thus 15=2x and x=7.5. Substitution gives both costs as 55, confirming equality.",
      diagnosticIntent: "This checks analytical interpretation of equality between two rate-plus-fixed-charge models.",
      taskType: "analytical",
      difficulty: 5,
    }),
    a({
      id: "y11adv-lin-qm10",
      prompt: "Find the y-intercept of the line through the stated intercept and perpendicular to the given line.",
      latex: "3x+4y=12,\\qquad \\text{new line passes through the original x-intercept}",
      answer: "-16/3",
      acceptedAnswers: ["-5 1/3", "y-intercept=-16/3", "−16/3"],
      hint: "Find the original x-intercept, take the negative reciprocal of its gradient, and use point-gradient form.",
      explanation: "The original line has gradient -3/4 and x-intercept (4,0). The perpendicular gradient is 4/3, so y=(4/3)(x-4)=(4/3)x-16/3. Its y-intercept is -16/3.",
      diagnosticIntent: "This tests synthesis of intercepts, general-form gradient, perpendicularity, and line construction.",
      taskType: "synthesis",
      difficulty: 5,
    }),
  ],
};
