import {
  richAnswer as a,
  richChoice as c,
  type WorkingFunctionsMasteryMap,
} from "./workingFunctionsQualityHelpers";

export const workingFunctionsQualityModels: WorkingFunctionsMasteryMap = {
  "constructing-using-functions": [
    a({
      id: "y11adv-model-qm1",
      prompt: "Evaluate the cost model after five hours.",
      latex: "C(h)=50+12h,\\qquad C(5)",
      answer: "110",
      acceptedAnswers: ["$110", "C(5)=110"],
      hint: "Substitute h=5 into the fixed-charge plus hourly-rate expression.",
      explanation: "The fixed charge is 50 and five hourly charges total 12(5)=60. Therefore C(5)=50+60=110.",
      diagnosticIntent: "This checks procedural evaluation of a linear model and separation of fixed and variable components.",
      taskType: "procedural",
      difficulty: 3,
    }),
    c({
      id: "y11adv-model-qm2",
      prompt: "Which linear rule matches both stated input-output pairs?",
      latex: "f(2)=19,\\qquad f(5)=31",
      answer: "B",
      choices: ["f(x)=4x+7", "f(x)=4x+11", "f(x)=6x+7", "f(x)=6x+1"],
      hint: "Find the rate of change from the two pairs, then substitute one pair to recover the intercept.",
      explanation: "The gradient is (31-19)/(5-2)=12/3=4. Using f(2)=19 gives 19=8+c, so c=11 and f(x)=4x+11.",
      diagnosticIntent: "This distinguishes a model fitted to both conditions from choices that use only the gradient or one point.",
      taskType: "analytical",
      difficulty: 3,
      distractorMisconceptions: {
        A: "Finds the correct gradient but subtracts the intercept incorrectly.",
        C: "Uses the output difference divided by the first input rather than the input difference.",
        D: "Uses the wrong gradient and adjusts an intercept to fit only one point.",
      },
    }),
    a({
      id: "y11adv-model-qm3",
      prompt: "A rectangle has the stated dimensions and area. Find the positive width.",
      latex: "W=x,\\qquad L=x+3,\\qquad LW=40",
      answer: "5",
      acceptedAnswers: ["x=5", "width 5"],
      hint: "Form x(x+3)=40, rearrange to zero, factor, and reject the negative dimension.",
      explanation: "The area equation is x²+3x-40=0=(x+8)(x-5). The roots are -8 and 5, but a width must be positive, so x=5.",
      diagnosticIntent: "This checks construction of a quadratic model from geometry and interpretation of an admissible contextual root.",
      taskType: "problem-solving",
      difficulty: 3,
    }),
    c({
      id: "y11adv-model-qm4",
      prompt: "Which practical domain keeps the population model non-negative from its initial time?",
      latex: "P(t)=1200-75t,\\qquad t\\ge0",
      answer: "C",
      choices: ["t\\ge16", "0\\le t<16", "0\\le t\\le16", "t\\le16"],
      hint: "Solve 1200-75t greater than or equal to zero and retain the initial-time condition t greater than or equal to zero.",
      explanation: "Non-negative population requires 1200-75t≥0, so t≤16. Intersecting with t≥0 gives the practical domain 0≤t≤16.",
      diagnosticIntent: "This checks whether algebraic model restrictions and contextual time restrictions are intersected correctly.",
      taskType: "analytical",
      difficulty: 3,
      distractorMisconceptions: {
        A: "Reverses the feasible side of the depletion time.",
        B: "Incorrectly excludes the valid zero-population endpoint.",
        D: "Omits the contextual condition that time starts at zero.",
      },
    }),
    a({
      id: "y11adv-model-qm5",
      prompt: "Count the integer usage levels for which plan A is strictly cheaper.",
      latex: "A(x)=30+5x,\\quad B(x)=12+8x,\\quad x\\in\\{0,1,\\ldots,12\\}",
      answer: "6",
      acceptedAnswers: ["x=7,8,9,10,11,12", "six"],
      hint: "Solve A(x)<B(x) first, then count only the integers in the supplied bounded set.",
      explanation: "The inequality 30+5x<12+8x gives 18<3x, so x>6. Within 0 through 12, the qualifying integers are 7,8,9,10,11,12: six values.",
      diagnosticIntent: "This tests a bounded investigation comparing two linear models with a strict break-even boundary.",
      taskType: "investigative",
      difficulty: 4,
    }),
    c({
      id: "y11adv-model-qm6",
      prompt: "A student divides the fixed cost by the selling price to find break-even. Which result correctly uses revenue equals cost?",
      latex: "C(n)=200+4n,\\qquad R(n)=9n",
      answer: "D",
      choices: ["n=200/9", "n=50", "n=20", "n=40"],
      hint: "At break-even, set the entire cost function, including variable cost, equal to revenue.",
      explanation: "Break-even requires 200+4n=9n, not 200=9n. Thus 200=5n and n=40, where both cost and revenue equal 360.",
      diagnosticIntent: "This diagnoses omission of variable costs when constructing a break-even equation.",
      taskType: "problem-solving",
      difficulty: 4,
      distractorMisconceptions: {
        A: "Divides fixed cost by price and ignores variable cost.",
        B: "Divides fixed cost by unit variable cost.",
        C: "Uses the difference between revenue and variable cost incorrectly.",
      },
    }),
    a({
      id: "y11adv-model-qm7",
      prompt: "Find the non-negative time when the object reaches ground level.",
      latex: "h(t)=-5t^2+20t+25",
      answer: "5",
      acceptedAnswers: ["t=5", "5 seconds"],
      hint: "Set h(t)=0, factor out -5, and interpret the two algebraic roots in the time context.",
      explanation: "Setting height to zero gives -5(t²-4t-5)=0=-5(t-5)(t+1). The roots are 5 and -1; only the non-negative time t=5 is physical.",
      diagnosticIntent: "This checks synthesis of a quadratic motion model, zeros, and contextual rejection of negative time.",
      taskType: "synthesis",
      difficulty: 4,
    }),
    a({
      id: "y11adv-model-qm8",
      prompt: "Find the missing input when the model has the stated constant rate of change.",
      latex: "f(2)=11,\\qquad f(k)=23,\\qquad \\text{gradient}=3",
      answer: "6",
      acceptedAnswers: ["k=6"],
      hint: "Use change in output equals gradient times change in input.",
      explanation: "The output rises by 23-11=12. At gradient 3 this requires an input increase of 12/3=4, so k=2+4=6.",
      diagnosticIntent: "This tests an investigative reverse inference from two function values and a prescribed rate.",
      taskType: "investigative",
      difficulty: 5,
    }),
    a({
      id: "y11adv-model-qm9",
      prompt: "Find the sum of the zeros of the quadratic model.",
      latex: "f(x)=a(x-2)^2+9,\\qquad f(0)=1",
      cartesianGraph: {
        description: "Calibrated downward-opening quadratic through (0,1), with vertex (2,9) and zeros symmetric about x=2.",
        xMin: -1,
        xMax: 5,
        yMin: -3,
        yMax: 11,
        parabolas: [{ kind: "quadratic", a: -2, b: 8, c: 1, label: "f(x)" }],
        points: [
          { x: 0, y: 1, label: "(0,1)" },
          { x: 2, y: 9, label: "vertex" },
        ],
      },
      answer: "4",
      acceptedAnswers: ["sum=4", "x_1+x_2=4"],
      hint: "Use f(0)=1 to determine a, then exploit symmetry about x=2 rather than calculating both zeros.",
      explanation: "The condition 1=4a+9 gives a=-2. The zeros of -2(x-2)²+9 are symmetric about x=2, so their average is 2 and their sum is 4.",
      diagnosticIntent: "This checks analytical use of vertex form, parameter recovery, and symmetry to obtain a root invariant efficiently.",
      taskType: "analytical",
      difficulty: 5,
    }),
    a({
      id: "y11adv-model-qm10",
      prompt: "Find the sum of the two break-even production levels.",
      latex: "C(x)=100+2x,\\qquad p(x)=12-0.1x,\\qquad R(x)=xp(x)",
      answer: "100",
      acceptedAnswers: ["x_1+x_2=100", "sum 100"],
      hint: "Set revenue equal to cost, rearrange to a quadratic, and use the sum-of-roots coefficient relation.",
      explanation: "Break-even gives 12x-0.1x²=100+2x, or x²-100x+1000=0 after multiplying by -10. The sum of its roots is -(-100)/1=100.",
      diagnosticIntent: "This tests synthesis of price, revenue, cost, quadratic modelling, and a root invariant without unnecessary solving.",
      taskType: "synthesis",
      difficulty: 5,
    }),
  ],

  "direct-inverse-variation": [
    a({
      id: "y11adv-var-qm1",
      prompt: "Find the constant of direct variation.",
      latex: "y\\propto x,\\qquad y=18\\text{ when }x=6",
      answer: "3",
      acceptedAnswers: ["k=3"],
      hint: "Write y=kx and substitute the supplied pair.",
      explanation: "Direct variation has the form y=kx. Substituting 18=6k gives k=3, so the relationship is y=3x.",
      diagnosticIntent: "This checks procedural conversion of proportional notation into an equation and recovery of its constant.",
      taskType: "procedural",
      difficulty: 3,
    }),
    c({
      id: "y11adv-var-qm2",
      prompt: "If y varies inversely as x, what happens to y when x is doubled?",
      latex: "y=\\frac{k}{x}",
      answer: "B",
      choices: ["It doubles", "It halves", "It increases by 2", "It stays constant"],
      hint: "Replace x by 2x in k/x and compare the new expression with the original y.",
      explanation: "Replacing x by 2x gives k/(2x)=(1/2)(k/x)=y/2. Therefore doubling x halves y.",
      diagnosticIntent: "This distinguishes multiplicative inverse scaling from additive or direct-variation reasoning.",
      taskType: "analytical",
      difficulty: 3,
      distractorMisconceptions: {
        A: "Applies direct variation instead of inverse variation.",
        C: "Treats a scale change as an additive change.",
        D: "Assumes the variation constant makes y independent of x.",
      },
    }),
    a({
      id: "y11adv-var-qm3",
      prompt: "Find the constant in the joint-variation model.",
      latex: "z\\propto xy,\\qquad z=30\\text{ when }x=3,\\ y=5",
      answer: "2",
      acceptedAnswers: ["k=2"],
      hint: "Write z=kxy and substitute all three supplied values.",
      explanation: "Joint variation gives z=kxy. Thus 30=k(3)(5)=15k, so k=2 and the model is z=2xy.",
      diagnosticIntent: "This checks construction and calibration of a joint direct-variation relationship.",
      taskType: "problem-solving",
      difficulty: 3,
    }),
    c({
      id: "y11adv-var-qm4",
      prompt: "Which rule represents y varying inversely as the square of x?",
      latex: "x\\ne0",
      answer: "C",
      choices: ["y=kx^2", "y=\\frac{k}{x}", "y=\\frac{k}{x^2}", "y=\\frac{x^2}{k}"],
      hint: "Inverse means the stated power of x belongs in the denominator.",
      explanation: "Inverse-square variation is y=k/x². Choice B is inverse variation only to the first power, while A and D increase with x squared.",
      diagnosticIntent: "This checks precise translation of verbal variation language into algebraic structure.",
      taskType: "analytical",
      difficulty: 3,
      distractorMisconceptions: {
        A: "Uses direct-square variation.",
        B: "Omits the stated square on the inverse variable.",
        D: "Places the constant and variable in reversed roles.",
      },
    }),
    a({
      id: "y11adv-var-qm5",
      prompt: "Count the positive integer inputs up to 12 that produce an integer output.",
      latex: "y=\\frac{24}{x},\\qquad x\\in\\{1,2,\\ldots,12\\}",
      answer: "7",
      acceptedAnswers: ["x=1,2,3,4,6,8,12", "seven"],
      hint: "The output is an integer exactly when x is a positive divisor of 24.",
      explanation: "The positive divisors of 24 not exceeding 12 are 1,2,3,4,6,8 and 12. Each makes 24/x integral, so there are seven inputs.",
      diagnosticIntent: "This tests a bounded investigation of an inverse model through divisibility rather than continuous substitution.",
      taskType: "investigative",
      difficulty: 4,
    }),
    c({
      id: "y11adv-var-qm6",
      prompt: "A student multiplies y by four when x is multiplied by four. Which corrected value follows from inverse variation?",
      latex: "xy=k,\\qquad y=8\\text{ when }x=3,\\qquad x=12",
      answer: "A",
      choices: ["2", "8", "24", "32"],
      hint: "First calculate the constant product xy, then divide it by the new x-value.",
      explanation: "The constant is k=3(8)=24. At x=12, y=24/12=2; quadrupling x divides y by four.",
      diagnosticIntent: "This diagnoses substitution of direct scaling into an inverse-variation relationship.",
      taskType: "problem-solving",
      difficulty: 4,
      distractorMisconceptions: {
        B: "Keeps y unchanged despite changing x.",
        C: "Uses the constant product itself as the new output.",
        D: "Applies direct variation by multiplying y by four.",
      },
    }),
    a({
      id: "y11adv-var-qm7",
      prompt: "Use square variation to find the new area-like quantity.",
      latex: "A\\propto r^2,\\qquad A=50\\text{ when }r=5,\\qquad r=8",
      answer: "128",
      acceptedAnswers: ["A=128"],
      hint: "Compare squared radii or determine k from A=kr squared.",
      explanation: "The scale factor is (8/5)²=64/25. Therefore the new value is 50(64/25)=2(64)=128.",
      diagnosticIntent: "This checks synthesis of a calibrated model with non-linear scale-factor reasoning.",
      taskType: "synthesis",
      difficulty: 4,
    }),
    a({
      id: "y11adv-var-qm8",
      prompt: "Find the constant and then evaluate the same combined-variation model.",
      latex: "y=\\frac{kx^2}{z},\\quad y=12\\text{ at }(x,z)=(2,3),\\quad \\text{then }(x,z)=(3,3)",
      answer: "27",
      acceptedAnswers: ["k=9 and y=27", "y=27"],
      hint: "Use the first condition to find k, then substitute the second pair without changing the variation law.",
      explanation: "The first condition gives 12=4k/3, so k=9. At x=3 and z=3, y=9(3²)/3=27.",
      diagnosticIntent: "This tests an investigation that calibrates and transfers a direct-square/inverse combined model.",
      taskType: "investigative",
      difficulty: 5,
    }),
    a({
      id: "y11adv-var-qm9",
      prompt: "Infer the variation law and predict the output at x=4.",
      latex: "(x,y)=(1,12),(2,3),(3,4/3),\\qquad y(4)",
      answer: "3/4",
      acceptedAnswers: ["0.75", "y(4)=3/4"],
      hint: "Test whether y times x or y times x squared is constant across all three pairs.",
      explanation: "The products yx² are 12,12 and 12, so y=12/x². Therefore y(4)=12/16=3/4.",
      diagnosticIntent: "This checks analytical model selection between inverse and inverse-square variation from numerical evidence.",
      taskType: "analytical",
      difficulty: 5,
    }),
    a({
      id: "y11adv-var-qm10",
      prompt: "Find the new distance that preserves exposure after the shielding factor is applied.",
      latex: "E=\\frac{k}{d^2},\\qquad \\frac{0.6k}{d^2}=\\frac{k}{3^2}",
      answer: "3sqrt(3/5)",
      acceptedAnswers: ["3√(3/5)", "sqrt(27/5)", "√(27/5)"],
      hint: "Cancel k, solve for d squared, and take the positive root because distance is positive.",
      explanation: "Cancelling k gives 0.6/d²=1/9, so d²=9(0.6)=27/5. Hence the positive distance is d=√(27/5)=3√(3/5).",
      diagnosticIntent: "This tests synthesis of inverse-square scaling, a multiplicative intervention, and physical root selection.",
      taskType: "synthesis",
      difficulty: 5,
    }),
  ],

  "circles-semicircles": [
    a({
      id: "y11adv-cir-qm1",
      prompt: "State the centre and radius of the circle.",
      latex: "(x-2)^2+(y+1)^2=25",
      answer: "(2,-1), radius 5",
      acceptedAnswers: ["centre (2,−1), r=5", "(2,-1), 5"],
      hint: "Compare with (x-h) squared plus (y-k) squared equals r squared, noting the sign inside each bracket.",
      explanation: "The standard form has h=2, k=-1 and r²=25. Therefore the centre is (2,-1) and the radius is 5.",
      diagnosticIntent: "This checks procedural reading of circle parameters, including the reversed sign in the y-bracket.",
      taskType: "procedural",
      difficulty: 3,
    }),
    c({
      id: "y11adv-cir-qm2",
      prompt: "Which point lies on the stated circle?",
      latex: "x^2+y^2=25",
      answer: "B",
      choices: ["(2,4)", "(3,4)", "(4,4)", "(0,4)"],
      hint: "Substitute each coordinate pair and look for squared coordinates summing to 25.",
      explanation: "For (3,4), 3²+4²=9+16=25, so it lies on the circle. The other squared sums are not 25.",
      diagnosticIntent: "This checks algebraic verification of a point against an implicit relation rather than visual estimation.",
      taskType: "analytical",
      difficulty: 3,
      distractorMisconceptions: {
        A: "Adds coordinates or miscalculates 2 squared plus 4 squared.",
        C: "Uses equal coordinates without checking the radius condition.",
        D: "Treats y=4 as sufficient regardless of x.",
      },
    }),
    a({
      id: "y11adv-cir-qm3",
      prompt: "Write the upper semicircle as a function of x and include its domain.",
      latex: "x^2+y^2=9,\\qquad y\\ge0",
      answer: "y=sqrt(9-x^2), -3<=x<=3",
      acceptedAnswers: ["y=√(9−x²), x∈[-3,3]", "f(x)=sqrt(9-x^2), [-3,3]"],
      hint: "Isolate y squared, take the non-negative square root, and require the radicand to be non-negative.",
      explanation: "From y²=9-x², the upper half uses y=√(9-x²). Real outputs require 9-x²≥0, so -3≤x≤3.",
      diagnosticIntent: "This checks construction of a single-valued semicircle function with the correct square-root branch and domain.",
      taskType: "problem-solving",
      difficulty: 3,
    }),
    c({
      id: "y11adv-cir-qm4",
      prompt: "How many points satisfy both relations?",
      latex: "x^2+y^2=25,\\qquad y=4",
      answer: "C",
      choices: ["0", "1", "2", "4"],
      hint: "Substitute y=4 into the circle equation and count both real x-values.",
      explanation: "Substitution gives x²+16=25, so x²=9 and x=±3. Therefore the horizontal line meets the circle at two points.",
      diagnosticIntent: "This checks intersection counting and retention of both square-root signs.",
      taskType: "analytical",
      difficulty: 3,
      distractorMisconceptions: {
        A: "Incorrectly concludes y=4 exceeds the radius.",
        B: "Keeps only the principal square root x=3.",
        D: "Counts sign choices for both coordinates even though y is fixed.",
      },
    }),
    a({
      id: "y11adv-cir-qm5",
      prompt: "Count the integer parameters that produce two distinct intersection points.",
      latex: "x^2+y^2=25,\\qquad y=k,\\qquad k\\in\\{-6,-5,\\ldots,5,6\\}",
      answer: "9",
      acceptedAnswers: ["k=-4,-3,-2,-1,0,1,2,3,4", "nine"],
      hint: "A horizontal line has two intersections exactly when its distance from the centre is strictly less than the radius.",
      explanation: "Two distinct points require |k|<5. The qualifying integers are -4 through 4 inclusive, which gives nine values; k=±5 are tangents.",
      diagnosticIntent: "This tests a bounded investigation distinguishing secant, tangent, and non-intersecting parameter cases.",
      taskType: "investigative",
      difficulty: 4,
    }),
    c({
      id: "y11adv-cir-qm6",
      prompt: "A student writes one square-root branch and claims it is the whole circle. Which correction is valid?",
      latex: "y=\\sqrt{16-x^2}",
      answer: "A",
      choices: ["It is only the upper semicircle", "It is only the lower semicircle", "It is the whole circle", "It is not real for any x"],
      hint: "The principal square root is always non-negative, so inspect which y-values it can produce.",
      explanation: "The rule y=√(16-x²) gives only y≥0, the upper semicircle. The whole circle relation also needs y=-√(16-x²).",
      diagnosticIntent: "This diagnoses loss of the negative square-root branch when converting an implicit circle relation to functions.",
      taskType: "problem-solving",
      difficulty: 4,
      distractorMisconceptions: {
        B: "Assigns the principal square root to negative outputs.",
        C: "Assumes isolating y with one root preserves the full relation.",
        D: "Ignores the valid radicand interval -4 to 4.",
      },
    }),
    a({
      id: "y11adv-cir-qm7",
      prompt: "Construct the circle with the stated centre that is tangent to the y-axis.",
      latex: "\\text{centre }(2,-1)",
      cartesianGraph: {
        description: "Circle centred at (2,-1) with radius 2, touching the vertical axis at the single point (0,-1).",
        xMin: -1,
        xMax: 5,
        yMin: -4,
        yMax: 2,
        circles: [{ h: 2, k: -1, r: 2, label: "circle" }],
        points: [
          { x: 2, y: -1, label: "centre" },
          { x: 0, y: -1, label: "tangent point" },
        ],
      },
      answer: "(x-2)^2+(y+1)^2=4",
      acceptedAnswers: ["(x−2)²+(y+1)²=2²", "(x-2)^2+(y-(-1))^2=4"],
      hint: "Tangency to the y-axis makes the radius equal to the horizontal distance from the centre to x=0.",
      explanation: "The centre is two units from the y-axis, so the tangent radius is 2. Standard form therefore gives (x-2)²+(y+1)²=2²=4.",
      diagnosticIntent: "This checks synthesis of coordinate distance, tangency, and standard circle form.",
      taskType: "synthesis",
      difficulty: 4,
    }),
    a({
      id: "y11adv-cir-qm8",
      prompt: "Find the parameter that makes the circle have radius 5.",
      latex: "x^2+y^2-6x+4y+k=0",
      answer: "-12",
      acceptedAnswers: ["k=-12", "−12"],
      hint: "Complete the square in x and y, then compare the resulting right-hand side with 25.",
      explanation: "Completing squares gives (x-3)²+(y+2)²=13-k. Radius 5 requires 13-k=25, hence k=-12.",
      diagnosticIntent: "This tests an investigative reverse parameter condition through completing the square in two variables.",
      taskType: "investigative",
      difficulty: 5,
    }),
    a({
      id: "y11adv-cir-qm9",
      prompt: "Find the sum of all coordinates of the two intersection points.",
      latex: "x^2+y^2=25,\\qquad y=x+1",
      answer: "0",
      acceptedAnswers: ["points (3,4) and (-4,-3); sum 0", "3+4-4-3=0"],
      hint: "Substitute the line into the circle, solve the resulting quadratic, then calculate both y-values.",
      explanation: "Substitution gives x²+(x+1)²=25, or x²+x-12=0, so x=3 or -4. The points are (3,4) and (-4,-3), whose coordinates sum to 0.",
      diagnosticIntent: "This checks analytical intersection solving across implicit and explicit relations with complete coordinate recovery.",
      taskType: "analytical",
      difficulty: 5,
    }),
    a({
      id: "y11adv-cir-qm10",
      prompt: "Find the exact radius of the unique circle through the three stated points.",
      latex: "(0,0),\\qquad (4,0),\\qquad (0,6)",
      answer: "sqrt(13)",
      acceptedAnswers: ["√13", "r=√13"],
      hint: "Use x squared plus y squared plus Dx plus Ey plus F equals zero and substitute the three points.",
      explanation: "The origin gives F=0; (4,0) gives D=-4, and (0,6) gives E=-6. Completing squares yields (x-2)²+(y-3)²=13, so r=√13.",
      diagnosticIntent: "This tests synthesis of three point constraints, general circle form, and conversion to centre-radius form.",
      taskType: "synthesis",
      difficulty: 5,
    }),
  ],

  "piecewise-defined-functions": [
    a({
      id: "y11adv-piece-qm1",
      prompt: "Evaluate both branches at the stated inputs and enter their sum.",
      latex: "f(x)=\\begin{cases}x^2,&x<0\\\\2x+1,&x\\ge0\\end{cases},\\qquad f(-3)+f(2)",
      answer: "14",
      acceptedAnswers: ["f(-3)+f(2)=14"],
      hint: "Choose the branch separately for each input before substituting.",
      explanation: "Since -3<0, f(-3)=(-3)²=9. Since 2≥0, f(2)=2(2)+1=5. Their sum is 14.",
      diagnosticIntent: "This checks procedural branch selection and evaluation across both sides of a boundary.",
      taskType: "procedural",
      difficulty: 3,
    }),
    c({
      id: "y11adv-piece-qm2",
      prompt: "Which parameter makes the two pieces meet continuously at x=1?",
      latex: "f(x)=\\begin{cases}2x+a,&x<1\\\\x^2+3,&x\\ge1\\end{cases}",
      answer: "B",
      choices: ["a=1", "a=2", "a=3", "a=4"],
      hint: "Equate the left-hand value 2+a with the included right-hand value 4.",
      explanation: "Continuity requires 2(1)+a=1²+3. Thus 2+a=4 and a=2.",
      diagnosticIntent: "This checks algebraic continuity at a branch point rather than choosing the branch that contains equality only.",
      taskType: "analytical",
      difficulty: 3,
      distractorMisconceptions: {
        A: "Subtracts the boundary input rather than the left output contribution.",
        C: "Uses the right constant 3 as the parameter directly.",
        D: "Uses the entire right-hand value without solving for a.",
      },
    }),
    a({
      id: "y11adv-piece-qm3",
      prompt: "Solve f(x)=3 and enter the sum of all valid solutions.",
      latex: "f(x)=\\begin{cases}x+4,&x<0\\\\x^2+2,&x\\ge0\\end{cases}",
      answer: "0",
      acceptedAnswers: ["solutions -1 and 1; sum 0", "-1+1=0"],
      hint: "Solve in each branch, then test each candidate against that branch's input condition.",
      explanation: "The first branch gives x+4=3, so x=-1, valid for x<0. The second gives x²=1; only x=1 satisfies x≥0. Their sum is 0.",
      diagnosticIntent: "This checks branchwise equation solving and rejection of a candidate that belongs to the wrong branch.",
      taskType: "problem-solving",
      difficulty: 3,
    }),
    c({
      id: "y11adv-piece-qm4",
      prompt: "Which set is the range of the piecewise function?",
      latex: "g(x)=\\begin{cases}x+2,&x<1\\\\(x-1)^2+5,&x\\ge1\\end{cases}",
      cartesianGraph: {
        description: "Piecewise function with a line approaching output 3 from below and an upward parabola beginning at the included point (1,5).",
        xMin: -4,
        xMax: 5,
        yMin: -3,
        yMax: 10,
        lines: [{ kind: "linear", m: 1, b: 2, label: "x+2", xMin: -4, xMax: 0.99 }],
        parabolas: [{ kind: "quadratic", a: 1, b: -2, c: 6, label: "(x-1)^2+5", xMin: 1, xMax: 3.2 }],
        points: [{ x: 1, y: 5, label: "included endpoint" }],
      },
      answer: "D",
      choices: ["(-\\infty,3]\\cup[5,\\infty)", "(-\\infty,5)", "[3,\\infty)", "(-\\infty,3)\\cup[5,\\infty)"],
      hint: "Find the output set of each branch separately and track whether each boundary output is included.",
      explanation: "For x<1, x+2 produces y<3, excluding 3. For x≥1, (x-1)²+5 produces y≥5, including 5. The range is (-∞,3)∪[5,∞).",
      diagnosticIntent: "This checks range union and endpoint inclusion across branches rather than copying domain inequalities.",
      taskType: "analytical",
      difficulty: 3,
      distractorMisconceptions: {
        A: "Incorrectly includes the unattained first-branch endpoint y=3.",
        B: "Fills the gap between branch output sets.",
        C: "Uses boundary outputs as one continuous interval.",
      },
    }),
    a({
      id: "y11adv-piece-qm5",
      prompt: "Find the parameter that makes the function continuous at x=2.",
      latex: "f(x)=\\begin{cases}kx+1,&x<2\\\\x^2-k,&x\\ge2\\end{cases}",
      answer: "1",
      acceptedAnswers: ["k=1"],
      hint: "Equate the two expressions at x=2 and solve the resulting linear equation in k.",
      explanation: "Continuity requires 2k+1=4-k. Hence 3k=3 and k=1; both branch values are then 3.",
      diagnosticIntent: "This tests an investigation of a parameterised join through equality of limiting and included values.",
      taskType: "investigative",
      difficulty: 4,
    }),
    c({
      id: "y11adv-piece-qm6",
      prompt: "A student uses the second rule because x=2 is near the boundary. Which value follows from the actual inclusion symbols?",
      latex: "h(x)=\\begin{cases}3x-1,&x\\le2\\\\x^2+4,&x>2\\end{cases},\\qquad h(2)",
      answer: "A",
      choices: ["5", "8", "9", "undefined"],
      hint: "The equality sign belongs to the first condition x less than or equal to 2.",
      explanation: "At x=2 the first branch applies, giving h(2)=3(2)-1=5. The second branch is restricted to x>2 and cannot be used at the boundary.",
      diagnosticIntent: "This diagnoses casual branch selection that ignores strict versus inclusive inequalities.",
      taskType: "problem-solving",
      difficulty: 4,
      distractorMisconceptions: {
        B: "Uses the second branch at an excluded boundary.",
        C: "Substitutes incorrectly into the second branch.",
        D: "Assumes a piecewise boundary is automatically undefined.",
      },
    }),
    a({
      id: "y11adv-piece-qm7",
      prompt: "Evaluate the tiered charge at 180 units.",
      latex: "C(n)=\\begin{cases}20,&0\\le n\\le100\\\\20+0.15(n-100),&n>100\\end{cases}",
      answer: "32",
      acceptedAnswers: ["$32", "C(180)=32"],
      hint: "Use the second tier and charge the rate only on units above 100.",
      explanation: "At n=180, the excess is 80 units. The additional charge is 0.15(80)=12, so the total is 20+12=32.",
      diagnosticIntent: "This checks synthesis of a contextual piecewise tariff and correct interpretation of marginal rather than total usage.",
      taskType: "synthesis",
      difficulty: 4,
    }),
    a({
      id: "y11adv-piece-qm8",
      prompt: "Find the smallest positive integer parameter for which the function has exactly two distinct zeros.",
      latex: "f_k(x)=\\begin{cases}x+k,&x<0\\\\x^2-1,&x\\ge0\\end{cases}",
      answer: "1",
      acceptedAnswers: ["k=1"],
      hint: "The second branch contributes one admissible zero; determine when the first branch's zero lies below zero.",
      explanation: "The second branch has roots ±1, but only x=1 satisfies x≥0. The first branch has zero x=-k, valid exactly when k>0. Thus the smallest positive integer is k=1.",
      diagnosticIntent: "This tests a bounded parameter investigation of zeros with branch-domain validity.",
      taskType: "investigative",
      difficulty: 5,
    }),
    a({
      id: "y11adv-piece-qm9",
      prompt: "Use a piecewise representation to find the sum of all solutions.",
      latex: "|2x-4|=6",
      answer: "4",
      acceptedAnswers: ["solutions -1 and 5; sum 4", "-1+5=4"],
      hint: "Split at x=2, using 4-2x on the left and 2x-4 on the right.",
      explanation: "For x<2, 4-2x=6 gives x=-1. For x≥2, 2x-4=6 gives x=5. Both satisfy their branches, and the sum is 4.",
      diagnosticIntent: "This checks analytical conversion between absolute-value and piecewise representations with branch validation.",
      taskType: "analytical",
      difficulty: 5,
    }),
    a({
      id: "y11adv-piece-qm10",
      prompt: "Determine whether parameters a and b can make the function continuous at both joins.",
      latex: "f(x)=\\begin{cases}ax+1,&x<1\\\\x^2+b,&1\\le x<3\\\\2x+a,&x\\ge3\\end{cases}",
      answer: "no solution",
      acceptedAnswers: ["no such a,b", "impossible"],
      hint: "Write one continuity equation at x=1 and another at x=3, then compare what they imply.",
      explanation: "At x=1, continuity gives a+1=1+b, so a=b. At x=3 it gives 9+b=6+a. Substituting a=b would require 9=6, impossible; no parameters satisfy both joins.",
      diagnosticIntent: "This tests synthesis of multiple continuity constraints and recognition of an inconsistent parameter system.",
      taskType: "synthesis",
      difficulty: 5,
    }),
  ],
};
