import type {
  CourseLessonSeed,
  CoursePathwaySeed,
  CourseUnitSeed,
} from "../../courseTypes";
import type {
  ExplicitLesson,
  PracticeQuestion,
  WorkedExample,
} from "../differentialCalculus";

// ── Helper builders ──────────────────────────────────────────────────────────

function answer(
  id: string,
  prompt: string,
  latex: string,
  value: string,
  explanation: string,
  hint: string,
  acceptedAnswers: string[] = [],
  difficulty?: number
): PracticeQuestion {
  return {
    id,
    prompt,
    latex,
    ...(difficulty ? { difficulty } : {}),
    answer: value,
    acceptedAnswers: Array.from(new Set([value, ...acceptedAnswers])),
    hint,
    explanation,
  };
}

function choice(
  id: string,
  prompt: string,
  value: "A" | "B" | "C" | "D",
  choices: [string, string, string, string],
  explanation: string,
  hint: string,
  latex = "\\text{Select A, B, C or D.}",
  difficulty?: number
): PracticeQuestion {
  return {
    id,
    prompt,
    latex,
    ...(difficulty ? { difficulty } : {}),
    choices: ["A", "B", "C", "D"].map((label, i) => ({ label, text: choices[i] })),
    answer: value,
    acceptedAnswers: [],
    hint,
    explanation,
  };
}

const VIDEO = {
  title: "Algebraic Techniques",
  url: "https://www.youtube.com/embed/NybHckSEQBI",
};

// ── Lesson 1: Algebraic Fractions ────────────────────────────────────────────

const algebraicFractions: Partial<ExplicitLesson> = {
  moduleTitle: "Algebraic Techniques",
  syllabusArea: "Number and Algebra",
  masteryPassMark: 0.8,
  video: VIDEO,
  description:
    "Identify algebraic fractions, simplify and reduce fractions with numerical denominators, and add or subtract algebraic fractions that have numerical denominators.",
  learningIntention:
    "Work with algebraic fractions that have numerical denominators: simplify, reduce, and add or subtract them confidently.",
  successCriteria: [
    "Identify an algebraic fraction and name its numerator and denominator.",
    "Reduce an algebraic fraction by cancelling a common numerical factor.",
    "Add and subtract algebraic fractions that already share the same denominator.",
    "Find a common denominator for fractions with different numerical denominators.",
    "Simplify the result and check by substituting a value for the variable.",
  ],
  teaching: {
    paragraphs: [
      "An algebraic fraction is just a fraction in which a letter appears somewhere in the top or bottom. $\\frac{x}{3}$, $\\frac{2a+1}{5}$ and $\\frac{4m}{6}$ are all algebraic fractions. The top is still called the numerator and the bottom the denominator, exactly as with number fractions. In this lesson every denominator is an ordinary number, which keeps the work close to the fraction arithmetic you already know.",
      "Think of $\\frac{x}{3}$ as 'one third of $x$'. If $x$ were 12, then $\\frac{x}{3}$ would be $\\frac{12}{3}=4$. Nothing new is happening — the letter just stands in for a number we have not been told yet. This is the key idea: every rule you trust for $\\frac{12}{3}$ still works for $\\frac{x}{3}$, because $x$ is only a placeholder.",
      "To reduce a fraction such as $\\frac{4m}{6}$, look for a number that divides both the numerator and the denominator. Here 4 and 6 share a factor of 2, so divide top and bottom by 2: $\\frac{4m}{6}=\\frac{2m}{3}$. We may cancel the 2 because dividing the top and the bottom by the same number does not change the value of the fraction — it is the same trick as turning $\\frac{4}{6}$ into $\\frac{2}{3}$.",
      "Adding fractions with the same denominator is easy: keep the denominator and add the numerators, because the pieces are already the same size. So $\\frac{x}{5}+\\frac{2x}{5}=\\frac{x+2x}{5}=\\frac{3x}{5}$. We are counting how many fifths we have in total — one fifth of $x$ plus two fifths of $x$ makes three fifths of $x$.",
      "When the denominators differ, we cannot add the pieces until they are the same size, so we rewrite each fraction over a common denominator first. For $\\frac{x}{2}+\\frac{x}{3}$ the lowest common denominator is 6. Rewrite $\\frac{x}{2}=\\frac{3x}{6}$ and $\\frac{x}{3}=\\frac{2x}{6}$, then add: $\\frac{3x}{6}+\\frac{2x}{6}=\\frac{5x}{6}$. The common error here is to add the denominators (writing $\\frac{2x}{5}$); we never add denominators, because the denominator names the size of the pieces, not how many there are.",
      "Subtraction works the same way, but be careful when a numerator has more than one term. In $\\frac{2x+1}{3}-\\frac{x}{3}$ the whole numerator $2x+1$ is being kept and only $x$ subtracted: $\\frac{(2x+1)-x}{3}=\\frac{x+1}{3}$. Writing the bracket $(2x+1)$ first reminds you that the subtraction applies to the entire numerator.",
      "Finally, always sanity-check by substituting a number. For $\\frac{x}{2}+\\frac{x}{3}=\\frac{5x}{6}$, try $x=6$: the left side is $3+2=5$ and the right side is $\\frac{30}{6}=5$. They agree, so the algebra is sound. Substitution is a fast, reliable way to catch a slip.",
    ],
    latexBlocks: [
      "\\frac{a}{c}+\\frac{b}{c}=\\frac{a+b}{c}",
      "\\frac{a}{m}\\pm\\frac{b}{n}=\\frac{an\\pm bm}{mn}",
      "\\frac{4m}{6}=\\frac{2m}{3}\\quad(\\text{divide top and bottom by }2)",
    ],
  },
  workedExamples: [
    {
      title: "Reduce an algebraic fraction",
      questionLatex: "\\text{Simplify } \\frac{6x}{9}.",
      steps: [
        { explanation: "Find a number that divides both 6 and 9. They share a factor of 3.", latex: "\\frac{6x}{9}=\\frac{6x\\div 3}{9\\div 3}" },
        { explanation: "Carry out the division on the top and the bottom.", latex: "=\\frac{2x}{3}" },
      ],
      finalAnswerLatex: "\\frac{2x}{3}",
    } as WorkedExample,
    {
      title: "Add fractions with the same denominator",
      questionLatex: "\\text{Simplify } \\frac{3a}{7}+\\frac{2a}{7}.",
      steps: [
        { explanation: "The denominators match, so keep 7 and add the numerators.", latex: "=\\frac{3a+2a}{7}" },
        { explanation: "Collect the like terms in the numerator.", latex: "=\\frac{5a}{7}" },
      ],
      finalAnswerLatex: "\\frac{5a}{7}",
    } as WorkedExample,
    {
      title: "Add fractions with different denominators",
      questionLatex: "\\text{Simplify } \\frac{x}{4}+\\frac{x}{6}.",
      steps: [
        { explanation: "The lowest common denominator of 4 and 6 is 12.", latex: "\\text{LCD}=12" },
        { explanation: "Rewrite each fraction over 12.", latex: "\\frac{x}{4}=\\frac{3x}{12},\\quad \\frac{x}{6}=\\frac{2x}{12}" },
        { explanation: "Add the numerators over the common denominator.", latex: "=\\frac{3x+2x}{12}=\\frac{5x}{12}" },
      ],
      finalAnswerLatex: "\\frac{5x}{12}",
    } as WorkedExample,
    {
      title: "Subtract with a two-term numerator",
      questionLatex: "\\text{Simplify } \\frac{3x+2}{5}-\\frac{x}{5}.",
      steps: [
        { explanation: "Same denominator, so keep 5 and subtract the whole numerator $x$ from $3x+2$. Bracket the first numerator.", latex: "=\\frac{(3x+2)-x}{5}" },
        { explanation: "Collect like terms in the numerator.", latex: "=\\frac{2x+2}{5}" },
      ],
      finalAnswerLatex: "\\frac{2x+2}{5}",
    } as WorkedExample,
  ],
  guidedPractice: [
    choice(
      "y8-alg-af-g1",
      "Which of these is an algebraic fraction?",
      "C",
      ["$\\frac{3}{4}$", "$2x+5$", "$\\frac{2x}{5}$", "$x^2$"],
      "An algebraic fraction has a letter in the numerator or denominator and is written as a fraction. $\\frac{2x}{5}$ fits both conditions.",
      "Look for a fraction bar with a variable in the top or bottom.",
    ),
    answer(
      "y8-alg-af-g2",
      "Simplify $\\frac{8x}{12}$.",
      "",
      "2x/3",
      "8 and 12 share a factor of 4: $\\frac{8x}{12}=\\frac{2x}{3}$.",
      "Divide the top and the bottom by their highest common factor.",
      ["\\frac{2x}{3}", "(2x)/3"],
    ),
    answer(
      "y8-alg-af-g3",
      "Simplify $\\frac{2y}{9}+\\frac{4y}{9}$.",
      "",
      "6y/9",
      "Same denominator: $\\frac{2y+4y}{9}=\\frac{6y}{9}=\\frac{2y}{3}$.",
      "Keep the denominator and add the numerators, then reduce.",
      ["\\frac{6y}{9}", "2y/3", "\\frac{2y}{3}"],
    ),
    answer(
      "y8-alg-af-g4",
      "Simplify $\\frac{x}{2}+\\frac{x}{5}$.",
      "",
      "7x/10",
      "LCD is 10: $\\frac{5x}{10}+\\frac{2x}{10}=\\frac{7x}{10}$.",
      "Rewrite both fractions over 10 first.",
      ["\\frac{7x}{10}", "(7x)/10"],
    ),
  ],
  independentPractice: [
    answer(
      "y8-alg-af-i1",
      "Simplify $\\frac{10m}{15}$.",
      "",
      "2m/3",
      "10 and 15 share a factor of 5: $\\frac{10m}{15}=\\frac{2m}{3}$.",
      "Divide top and bottom by 5.",
      ["\\frac{2m}{3}", "(2m)/3"],
    ),
    answer(
      "y8-alg-af-i2",
      "Simplify $\\frac{5a}{8}-\\frac{a}{8}$.",
      "",
      "a/2",
      "Same denominator: $\\frac{5a-a}{8}=\\frac{4a}{8}=\\frac{a}{2}$.",
      "Subtract the numerators, then reduce.",
      ["\\frac{a}{2}", "4a/8", "\\frac{4a}{8}"],
    ),
    answer(
      "y8-alg-af-i3",
      "Simplify $\\frac{x}{3}+\\frac{x}{4}$.",
      "",
      "7x/12",
      "LCD is 12: $\\frac{4x}{12}+\\frac{3x}{12}=\\frac{7x}{12}$.",
      "Rewrite both fractions over 12.",
      ["\\frac{7x}{12}", "(7x)/12"],
    ),
    answer(
      "y8-alg-af-i4",
      "Simplify $\\frac{2x+1}{4}+\\frac{x}{4}$.",
      "",
      "(3x+1)/4",
      "Same denominator: $\\frac{(2x+1)+x}{4}=\\frac{3x+1}{4}$.",
      "Add the whole numerators over 4 and collect like terms.",
      ["\\frac{3x+1}{4}", "(3x + 1)/4"],
    ),
    choice(
      "y8-alg-af-i5",
      "Which is the correct simplification of $\\frac{x}{2}+\\frac{x}{3}$?",
      "B",
      ["$\\frac{2x}{5}$", "$\\frac{5x}{6}$", "$\\frac{x}{6}$", "$\\frac{2x}{6}$"],
      "LCD is 6: $\\frac{3x}{6}+\\frac{2x}{6}=\\frac{5x}{6}$. Never add the denominators.",
      "Find the common denominator before adding; do not add the bottoms.",
    ),
  ],
  commonMistakes: [
    {
      mistake: "Adding the denominators: $\\frac{x}{2}+\\frac{x}{3}=\\frac{2x}{5}$.",
      fix: "Use a common denominator. $\\frac{x}{2}+\\frac{x}{3}=\\frac{3x}{6}+\\frac{2x}{6}=\\frac{5x}{6}$. Denominators are never added.",
    },
    {
      mistake: "Cancelling only part of the numerator: $\\frac{2x+4}{2}=x+4$.",
      fix: "Every term must be divided: $\\frac{2x+4}{2}=\\frac{2x}{2}+\\frac{4}{2}=x+2$.",
    },
    {
      mistake: "Forgetting the bracket when subtracting: $\\frac{3x+2}{5}-\\frac{x}{5}=\\frac{3x+2-x}{5}$ treated as $\\frac{3x+2}{5}$.",
      fix: "Subtract the entire second numerator: $\\frac{(3x+2)-x}{5}=\\frac{2x+2}{5}$.",
    },
    {
      mistake: "Reducing $\\frac{4m}{6}$ to $\\frac{4m}{3}$ by halving only the denominator.",
      fix: "Divide both top and bottom by the common factor: $\\frac{4m}{6}=\\frac{2m}{3}$.",
    },
  ],
  masteryQuiz: [
    answer("y8-alg-af-m1", "Simplify $\\frac{6x}{8}$.", "", "3x/4", "Divide top and bottom by 2: $\\frac{3x}{4}$.", "Cancel the common factor 2.", ["\\frac{3x}{4}", "(3x)/4"]),
    answer("y8-alg-af-m2", "Simplify $\\frac{3a}{11}+\\frac{5a}{11}$.", "", "8a/11", "Same denominator: $\\frac{3a+5a}{11}=\\frac{8a}{11}$.", "Add the numerators over 11.", ["\\frac{8a}{11}", "(8a)/11"]),
    answer("y8-alg-af-m3", "Simplify $\\frac{x}{2}+\\frac{x}{4}$.", "", "3x/4", "LCD 4: $\\frac{2x}{4}+\\frac{x}{4}=\\frac{3x}{4}$.", "Rewrite over 4 first.", ["\\frac{3x}{4}", "(3x)/4"]),
    choice("y8-alg-af-m4", "Which is an algebraic fraction?", "D", ["$5$", "$3x-1$", "$\\frac{7}{8}$", "$\\frac{m}{4}$"], "$\\frac{m}{4}$ has a variable in a fraction.", "A variable inside a fraction."),
    answer("y8-alg-af-m5", "Simplify $\\frac{7y}{10}-\\frac{2y}{10}$.", "", "y/2", "$\\frac{5y}{10}=\\frac{y}{2}$.", "Subtract then reduce.", ["\\frac{y}{2}", "5y/10", "\\frac{5y}{10}"]),
    answer("y8-alg-af-m6", "Simplify $\\frac{x}{3}+\\frac{x}{6}$.", "", "x/2", "LCD 6: $\\frac{2x}{6}+\\frac{x}{6}=\\frac{3x}{6}=\\frac{x}{2}$.", "Rewrite over 6, add, reduce.", ["\\frac{x}{2}", "3x/6", "\\frac{3x}{6}"]),
    answer("y8-alg-af-m7", "Simplify $\\frac{2x+3}{5}+\\frac{x}{5}$.", "", "(3x+3)/5", "$\\frac{(2x+3)+x}{5}=\\frac{3x+3}{5}$.", "Add whole numerators over 5.", ["\\frac{3x+3}{5}", "(3x + 3)/5"]),
    answer("y8-alg-af-m8", "Simplify $\\frac{12m}{18}$.", "", "2m/3", "Divide top and bottom by 6: $\\frac{2m}{3}$.", "Cancel the HCF 6.", ["\\frac{2m}{3}", "(2m)/3"]),
    choice("y8-alg-af-m9", "What is $\\frac{x}{2}+\\frac{x}{3}$?", "C", ["$\\frac{2x}{5}$", "$\\frac{x}{5}$", "$\\frac{5x}{6}$", "$\\frac{x}{6}$"], "LCD 6: $\\frac{3x}{6}+\\frac{2x}{6}=\\frac{5x}{6}$.", "Common denominator 6; do not add denominators."),
    answer("y8-alg-af-m10", "Simplify $\\frac{3x+4}{6}-\\frac{x}{6}$.", "", "(x+2)/3", "$\\frac{(3x+4)-x}{6}=\\frac{2x+4}{6}=\\frac{x+2}{3}$.", "Subtract the whole numerator, then reduce if possible.", ["\\frac{2x+4}{6}", "\\frac{x+2}{3}"]),
  ],
  masteryQuizPool: [
    answer("y8-alg-af-p1", "Simplify $\\frac{4x}{6}$.", "", "2x/3", "Divide by 2: $\\frac{2x}{3}$.", "Cancel the factor 2.", ["\\frac{2x}{3}", "(2x)/3"], 1),
    answer("y8-alg-af-p2", "Simplify $\\frac{9x}{12}$.", "", "3x/4", "Divide by 3: $\\frac{3x}{4}$.", "Cancel the factor 3.", ["\\frac{3x}{4}", "(3x)/4"], 1),
    answer("y8-alg-af-p3", "Simplify $\\frac{a}{5}+\\frac{2a}{5}$.", "", "3a/5", "Same denominator: $\\frac{3a}{5}$.", "Add the numerators over 5.", ["\\frac{3a}{5}", "(3a)/5"], 1),
    answer("y8-alg-af-p4", "Simplify $\\frac{5m}{7}-\\frac{2m}{7}$.", "", "3m/7", "$\\frac{5m-2m}{7}=\\frac{3m}{7}$.", "Subtract numerators over 7.", ["\\frac{3m}{7}", "(3m)/7"], 1),
    choice("y8-alg-af-p5", "Which is an algebraic fraction?", "B", ["$2x$", "$\\frac{x}{3}$", "$\\frac{1}{4}$", "$x-2$"], "$\\frac{x}{3}$ is a fraction containing a variable.", "Fraction bar plus a variable.", "\\text{Select A, B, C or D.}", 1),
    answer("y8-alg-af-p6", "Simplify $\\frac{10x}{25}$.", "", "2x/5", "Divide by 5: $\\frac{2x}{5}$.", "Cancel 5.", ["\\frac{2x}{5}", "(2x)/5"], 1),
    answer("y8-alg-af-p7", "Simplify $\\frac{6y}{8}$.", "", "3y/4", "Divide by 2: $\\frac{3y}{4}$.", "Cancel 2.", ["\\frac{3y}{4}", "(3y)/4"], 2),
    answer("y8-alg-af-p8", "Simplify $\\frac{x}{2}+\\frac{x}{4}$.", "", "3x/4", "LCD 4: $\\frac{2x}{4}+\\frac{x}{4}=\\frac{3x}{4}$.", "Rewrite over 4.", ["\\frac{3x}{4}", "(3x)/4"], 2),
    answer("y8-alg-af-p9", "Simplify $\\frac{x}{3}+\\frac{x}{6}$.", "", "x/2", "LCD 6: $\\frac{2x}{6}+\\frac{x}{6}=\\frac{3x}{6}=\\frac{x}{2}$.", "Rewrite over 6.", ["\\frac{x}{2}", "3x/6", "\\frac{3x}{6}"], 2),
    answer("y8-alg-af-p10", "Simplify $\\frac{2x}{5}+\\frac{x}{5}$.", "", "3x/5", "$\\frac{3x}{5}$.", "Add numerators over 5.", ["\\frac{3x}{5}", "(3x)/5"], 2),
    answer("y8-alg-af-p11", "Simplify $\\frac{8a}{9}-\\frac{2a}{9}$.", "", "2a/3", "$\\frac{6a}{9}=\\frac{2a}{3}$.", "Subtract then reduce.", ["\\frac{2a}{3}", "6a/9", "\\frac{6a}{9}"], 2),
    choice("y8-alg-af-p12", "Which equals $\\frac{x}{2}+\\frac{x}{3}$?", "C", ["$\\frac{2x}{5}$", "$\\frac{x}{5}$", "$\\frac{5x}{6}$", "$\\frac{x}{6}$"], "LCD 6 gives $\\frac{5x}{6}$.", "Common denominator 6.", "\\text{Select A, B, C or D.}", 2),
    answer("y8-alg-af-p13", "Simplify $\\frac{x}{4}+\\frac{x}{6}$.", "", "5x/12", "LCD 12: $\\frac{3x}{12}+\\frac{2x}{12}=\\frac{5x}{12}$.", "Rewrite over 12.", ["\\frac{5x}{12}", "(5x)/12"], 3),
    answer("y8-alg-af-p14", "Simplify $\\frac{2a+1}{3}+\\frac{a}{3}$.", "", "(3a+1)/3", "$\\frac{(2a+1)+a}{3}=\\frac{3a+1}{3}$.", "Add whole numerators over 3.", ["\\frac{3a+1}{3}", "(3a + 1)/3"], 3),
    answer("y8-alg-af-p15", "Simplify $\\frac{3x+2}{5}-\\frac{x}{5}$.", "", "(2x+2)/5", "$\\frac{(3x+2)-x}{5}=\\frac{2x+2}{5}$.", "Subtract the whole numerator.", ["\\frac{2x+2}{5}", "(2x + 2)/5"], 3),
    answer("y8-alg-af-p16", "Simplify $\\frac{x}{2}+\\frac{x}{5}$.", "", "7x/10", "LCD 10: $\\frac{5x}{10}+\\frac{2x}{10}=\\frac{7x}{10}$.", "Rewrite over 10.", ["\\frac{7x}{10}", "(7x)/10"], 3),
    answer("y8-alg-af-p17", "Simplify $\\frac{2x+4}{2}$.", "", "x+2", "Divide every term by 2: $\\frac{2x}{2}+\\frac{4}{2}=x+2$.", "Divide both terms by 2.", ["x + 2"], 3),
    answer("y8-alg-af-p18", "Simplify $\\frac{x}{3}+\\frac{2x}{9}$.", "", "5x/9", "LCD 9: $\\frac{3x}{9}+\\frac{2x}{9}=\\frac{5x}{9}$.", "Rewrite over 9.", ["\\frac{5x}{9}", "(5x)/9"], 3),
    answer("y8-alg-af-p19", "Simplify $\\frac{3a}{4}-\\frac{a}{6}$, then evaluate the simplified expression when $a=24$.", "", "7a/12, 14", "Using denominator 12 gives $9a/12-2a/12=7a/12$. At $a=24$, this is $7\\times24/12=14$.", "Simplify symbolically before substituting.", ["\\frac{7a}{12}, 14", "(7a)/12, 14"], 4),
    answer("y8-alg-af-p20", "Simplify $\\frac{2x}{3}+\\frac{3x}{4}$. A student claims the coefficient is $5/7$ by adding tops and bottoms. Give the correct expression and its value at $x=12$.", "", "17x/12, 17", "Using denominator 12 gives $8x/12+9x/12=17x/12$. At $x=12$ the value is 17. Numerators and denominators cannot be added separately.", "Build equivalent fractions with a common denominator.", ["\\frac{17x}{12}, 17", "(17x)/12, 17"], 4),
    answer("y8-alg-af-p21", "Simplify $\\frac{x+1}{2}+\\frac{x}{3}$, then evaluate it at $x=3$.", "", "(5x+3)/6, 3", "Over denominator 6, the expression is $3(x+1)/6+2x/6=(5x+3)/6$. At $x=3$, it is $18/6=3$.", "Multiply the entire first numerator by 3.", ["\\frac{5x+3}{6}, 3", "(5x + 3)/6, 3"], 4),
    answer("y8-alg-af-p22", "Simplify $\\frac{5x+6}{8}-\\frac{x}{8}$ fully, then evaluate the result at $x=5$.", "", "(2x+3)/4, 13/4", "Combining gives $(4x+6)/8$, which reduces to $(2x+3)/4$. At $x=5$, the value is $13/4$.", "Combine the equal-denominator numerators, then reduce every term by 2.", ["\\frac{2x+3}{4}, \\frac{13}{4}", "(2x+3)/4, 3.25"], 4),
    answer("y8-alg-af-p23", "Simplify $\\frac{x}{4}-\\frac{x}{6}$, then find $x$ if the simplified expression equals 5.", "", "x/12, x = 60", "Using denominator 12 gives $3x/12-2x/12=x/12$. If $x/12=5$, then $x=60$.", "Simplify first, then solve the resulting one-step equation.", ["\\frac{x}{12}, 60", "x/12, 60"], 4),
    answer("y8-alg-af-p24", "Simplify $\\frac{2x-1}{3}+\\frac{x+2}{4}$, then evaluate at $x=2$.", "", "(11x+2)/12, 2", "Using LCD 12 gives $(11x+2)/12$; at $x=2$ this is $24/12=2$.", "Simplify before substituting.", ["\\frac{11x+2}{12},2"], 5),
    answer("y8-alg-af-p25", "Simplify $\\frac{3x+1}{2}-\\frac{x-2}{5}$, then evaluate at $x=7$.", "", "(13x+9)/10, 10", "LCD 10 gives $(13x+9)/10$; at 7 this is $100/10=10$.", "Watch subtraction, then substitute.", ["\\frac{13x+9}{10},10"], 5),
    answer("y8-alg-af-p26", "Simplify $\\frac{x}{2}+\\frac{x}{3}+\\frac{x}{6}$ and verify at $x=12$ using both forms.", "", "x; both give 12", "The numerator becomes $3x+2x+x=6x$, so the expression is $x$. At 12, the fractions total $6+4+2=12$.", "Simplify and independently check.", ["x,12"], 5),
    answer("y8-alg-af-p27", "Simplify $\\frac{4x+2}{6}-\\frac{x-1}{3}$, then evaluate at $x=4$.", "", "(x+2)/3, 2", "Combining over 6 gives $(2x+4)/6=(x+2)/3$; at 4 the value is 2.", "Distribute the subtraction before cancelling.", ["\\frac{x+2}{3},2"], 5),
    answer("y8-alg-af-p28", "Simplify $\\frac{5x}{6}-\\frac{x}{4}+\\frac{x}{3}$, then evaluate at $x=12$.", "", "11x/12, 11", "Over 12 the numerator is $10x-3x+4x=11x$; at 12 the value is 11.", "Use a common denominator, then substitute.", ["\\frac{11x}{12},11"], 5),
  ],
  multiPartPractice: [
    {
      id: "y8-alg-af-mp1",
      prompt:
        "A recipe uses $\\frac{x}{2}$ cups of flour for the base and $\\frac{x}{3}$ cups for the topping, where $x$ is the batch size.",
      latex: "\\frac{x}{2}+\\frac{x}{3}",
      answer: "5x/6",
      hint: "Use the common denominator 6, and substitute a value to check.",
      explanation:
        "Part (a): $\\frac{x}{2}=\\frac{3x}{6}$. Part (b): total $=\\frac{3x}{6}+\\frac{2x}{6}=\\frac{5x}{6}$. Part (c): at $x=6$, total $=\\frac{30}{6}=5$ cups.",
      parts: [
        {
          key: "a",
          label: "(a)",
          prompt: "Rewrite $\\frac{x}{2}$ with a denominator of 6.",
          latex: "",
          marks: 1,
          answer: "3x/6",
          acceptedAnswers: ["\\frac{3x}{6}", "(3x)/6"],
          hint: "Multiply top and bottom by 3.",
          explanation: "$\\frac{x}{2}=\\frac{x\\times 3}{2\\times 3}=\\frac{3x}{6}$.",
        },
        {
          key: "b",
          label: "(b)",
          prompt: "Add the two fractions and simplify.",
          latex: "",
          marks: 2,
          answer: "5x/6",
          acceptedAnswers: ["\\frac{5x}{6}", "(5x)/6"],
          hint: "Write both over 6, then add the numerators.",
          explanation: "$\\frac{3x}{6}+\\frac{2x}{6}=\\frac{5x}{6}$.",
        },
        {
          key: "c",
          label: "(c)",
          prompt: "How many cups of flour are used in total when $x = 6$?",
          latex: "",
          marks: 1,
          answer: "5",
          acceptedAnswers: ["5 cups"],
          hint: "Substitute $x=6$ into $\\frac{5x}{6}$.",
          explanation: "$\\frac{5\\times 6}{6}=\\frac{30}{6}=5$ cups.",
        },
      ],
    },
  ],
};

// ── Lesson 2: Expanding Expressions ──────────────────────────────────────────

const expandingExpressions: Partial<ExplicitLesson> = {
  moduleTitle: "Algebraic Techniques",
  syllabusArea: "Number and Algebra",
  masteryPassMark: 0.8,
  video: VIDEO,
  description:
    "Expand single brackets containing several terms, handle negative coefficients in front of brackets, and expand then collect like terms.",
  learningIntention:
    "Expand single brackets with multiple terms and negative coefficients, and simplify the result by collecting like terms.",
  successCriteria: [
    "Expand a single bracket by multiplying every inside term by the outside factor.",
    "Expand a bracket that has a negative number or $-x$ in front of it.",
    "Collect like terms after expanding.",
    "Expand and simplify expressions containing two brackets.",
    "Substitute a value to check an expansion is correct.",
  ],
  teaching: {
    paragraphs: [
      "Expanding a bracket means rewriting a product without the brackets. The rule is the distributive law: the factor on the outside multiplies every term on the inside, one at a time. So $3(x+4)$ means '3 lots of $(x+4)$', which is $3x+12$.",
      "It helps to picture this as area. A rectangle with height 3 and width $(x+4)$ can be split into two smaller rectangles: one of width $x$ and one of width 4. Their areas are $3\\times x = 3x$ and $3\\times 4 = 12$, and the whole area is the sum $3x+12$. The area picture is why we must multiply the outside factor by each inside term separately — each piece of the width gets the full height.",
      "When there are more than two terms inside, the same rule applies to every term: $2(x+3y-5)=2x+6y-10$. A common slip is to multiply only the first term; the distributive law is all-or-nothing — every inside term must be reached.",
      "Negative coefficients need extra care because the sign multiplies through as well. In $-3(x-2)$, the factor is $-3$. Multiplying: $-3\\times x = -3x$ and $-3\\times(-2)=+6$. So $-3(x-2)=-3x+6$. The second sign flips because a negative times a negative is positive — that flip is the single most common place students go wrong.",
      "A bare minus sign in front of a bracket means $-1$ times the bracket. So $-(x-5)=-1\\times x -1\\times(-5)=-x+5$. Reading the leading minus as $-1$ keeps you from forgetting to change the sign of the second term.",
      "Often we expand and then collect like terms — terms with exactly the same variable part. In $2(x+3)+4x$, expand to $2x+6+4x$, then add the $x$-terms: $2x+4x=6x$, giving $6x+6$. Like terms combine because $2x$ and $4x$ both count copies of the same thing, $x$; you can only add quantities that measure the same object, just as 2 apples plus 4 apples makes 6 apples.",
      "To check an expansion, substitute a convenient number. For $-3(x-2)=-3x+6$, try $x=1$: the left side is $-3(1-2)=-3(-1)=3$, and the right side is $-3+6=3$. They match, confirming the signs were handled correctly.",
    ],
    latexBlocks: [
      "a(b+c)=ab+ac",
      "-a(b-c)=-ab+ac",
      "2(x+3)+4x=2x+6+4x=6x+6",
    ],
  },
  workedExamples: [
    {
      title: "Expand a bracket with three terms",
      questionLatex: "\\text{Expand } 4(2x+3y-1).",
      steps: [
        { explanation: "Multiply the 4 by each term inside the bracket.", latex: "4\\times 2x + 4\\times 3y + 4\\times(-1)" },
        { explanation: "Evaluate each product.", latex: "=8x+12y-4" },
      ],
      finalAnswerLatex: "8x+12y-4",
    } as WorkedExample,
    {
      title: "Expand with a negative coefficient",
      questionLatex: "\\text{Expand } -3(x-2).",
      steps: [
        { explanation: "Multiply $-3$ by each inside term. Watch the second sign: negative times negative is positive.", latex: "-3\\times x + (-3)\\times(-2)" },
        { explanation: "Evaluate each product.", latex: "=-3x+6" },
      ],
      finalAnswerLatex: "-3x+6",
    } as WorkedExample,
    {
      title: "Expand a leading minus sign",
      questionLatex: "\\text{Expand } -(4x-7).",
      steps: [
        { explanation: "A leading minus means multiply the bracket by $-1$.", latex: "-1\\times 4x + (-1)\\times(-7)" },
        { explanation: "Each sign inside the bracket flips.", latex: "=-4x+7" },
      ],
      finalAnswerLatex: "-4x+7",
    } as WorkedExample,
    {
      title: "Expand and collect like terms",
      questionLatex: "\\text{Expand and simplify } 5(x+2)-2(x-3).",
      steps: [
        { explanation: "Expand the first bracket.", latex: "5(x+2)=5x+10" },
        { explanation: "Expand the second bracket, remembering the $-2$ flips the second sign.", latex: "-2(x-3)=-2x+6" },
        { explanation: "Collect like terms.", latex: "5x-2x+10+6=3x+16" },
      ],
      finalAnswerLatex: "3x+16",
    } as WorkedExample,
  ],
  guidedPractice: [
    choice(
      "y8-alg-ee-g1",
      "Which is the correct expansion of $3(2x+5)$?",
      "A",
      ["$6x+15$", "$6x+5$", "$5x+15$", "$2x+15$"],
      "Multiply 3 by each term: $3\\times 2x=6x$ and $3\\times 5=15$, giving $6x+15$.",
      "The 3 multiplies both terms inside.",
    ),
    answer(
      "y8-alg-ee-g2",
      "Expand $4(x+6)$. Type the result.",
      "",
      "4x+24",
      "$4\\times x=4x$ and $4\\times 6=24$, so $4x+24$.",
      "Multiply 4 by each inside term.",
      ["4x + 24"],
    ),
    answer(
      "y8-alg-ee-g3",
      "Expand $-2(x-5)$.",
      "",
      "-2x+10",
      "$-2\\times x=-2x$ and $-2\\times(-5)=+10$, so $-2x+10$.",
      "Negative times negative gives a positive second term.",
      ["-2x + 10"],
    ),
    choice(
      "y8-alg-ee-g4",
      "Expand and simplify $3(x+2)+2x$.",
      "C",
      ["$3x+6$", "$5x+2$", "$5x+6$", "$6x+6$"],
      "$3(x+2)=3x+6$, then $3x+2x+6=5x+6$.",
      "Expand first, then collect the $x$-terms.",
    ),
  ],
  independentPractice: [
    answer(
      "y8-alg-ee-i1",
      "Expand $5(3x-2)$.",
      "",
      "15x-10",
      "$5\\times 3x=15x$ and $5\\times(-2)=-10$, so $15x-10$.",
      "Multiply 5 by each inside term.",
      ["15x - 10"],
    ),
    answer(
      "y8-alg-ee-i2",
      "Expand $2(3x+4y-1)$.",
      "",
      "6x+8y-2",
      "$2\\times 3x=6x$, $2\\times 4y=8y$, $2\\times(-1)=-2$.",
      "Reach all three inside terms.",
      ["6x + 8y - 2"],
    ),
    answer(
      "y8-alg-ee-i3",
      "Expand $-(2x-9)$.",
      "",
      "-2x+9",
      "The leading minus is $-1$: $-1\\times 2x=-2x$ and $-1\\times(-9)=+9$.",
      "Treat the leading minus as $-1$; both signs flip.",
      ["-2x + 9"],
    ),
    answer(
      "y8-alg-ee-i4",
      "Expand and simplify $4(x+1)+3(x+2)$.",
      "",
      "7x+10",
      "$4x+4+3x+6=7x+10$.",
      "Expand both brackets, then collect like terms.",
      ["7x + 10"],
    ),
    choice(
      "y8-alg-ee-i5",
      "Expand and simplify $6(x+2)-4(x-1)$.",
      "B",
      ["$2x+8$", "$2x+16$", "$2x+11$", "$10x+8$"],
      "$6x+12-4x+4=2x+16$. The $-4(x-1)$ gives $-4x+4$.",
      "Watch the sign on the second bracket.",
    ),
  ],
  commonMistakes: [
    {
      mistake: "Multiplying only the first term: $3(x+4)=3x+4$.",
      fix: "Multiply every term inside: $3(x+4)=3x+12$.",
    },
    {
      mistake: "Keeping the second sign with a negative factor: $-3(x-2)=-3x-6$.",
      fix: "Negative times negative is positive: $-3(x-2)=-3x+6$.",
    },
    {
      mistake: "Forgetting a leading minus is $-1$: $-(x-5)=-x-5$.",
      fix: "$-(x-5)=-x+5$. Both inside signs flip.",
    },
    {
      mistake: "Combining unlike terms: $2x+6=8x$.",
      fix: "Only like terms combine. $2x$ and $6$ are different, so $2x+6$ cannot be simplified further.",
    },
  ],
  masteryQuiz: [
    choice("y8-alg-ee-m1", "Expand $2(x+7)$.", "A", ["$2x+14$", "$2x+7$", "$x+14$", "$2x+9$"], "$2\\times x=2x$, $2\\times 7=14$.", "Multiply 2 by both terms."),
    answer("y8-alg-ee-m2", "Expand $6(2x-3)$.", "", "12x-18", "$6\\times 2x=12x$, $6\\times(-3)=-18$.", "Multiply 6 through.", ["12x - 18"]),
    answer("y8-alg-ee-m3", "Expand $-4(x-1)$.", "", "-4x+4", "$-4\\times x=-4x$, $-4\\times(-1)=+4$.", "Negative times negative is positive.", ["-4x + 4"]),
    answer("y8-alg-ee-m4", "Expand $3(2x+y-4)$.", "", "6x+3y-12", "$6x+3y-12$.", "Reach all three terms.", ["6x + 3y - 12"]),
    answer("y8-alg-ee-m5", "Expand $-(5x-2)$.", "", "-5x+2", "Leading minus is $-1$: $-5x+2$.", "Both signs flip.", ["-5x + 2"]),
    choice("y8-alg-ee-m6", "Expand and simplify $2(x+3)+5x$.", "C", ["$2x+6$", "$7x+3$", "$7x+6$", "$10x+6$"], "$2x+6+5x=7x+6$.", "Expand then collect."),
    answer("y8-alg-ee-m7", "Expand and simplify $3(x+4)+2(x+1)$.", "", "5x+14", "$3x+12+2x+2=5x+14$.", "Expand both, then collect.", ["5x + 14"]),
    answer("y8-alg-ee-m8", "Expand and simplify $5(x+2)-3(x-1)$.", "", "2x+13", "$5x+10-3x+3=2x+13$.", "Mind the sign on $-3(x-1)$.", ["2x + 13"]),
    choice("y8-alg-ee-m9", "Which equals $-2(3x-4)$?", "D", ["$-6x-8$", "$6x-8$", "$-6x-4$", "$-6x+8$"], "$-2\\times 3x=-6x$, $-2\\times(-4)=+8$.", "Negative times negative is positive."),
    answer("y8-alg-ee-m10", "Expand and simplify $4(2x-1)-(x-3)$.", "", "7x-1", "$8x-4-x+3=7x-1$.", "The leading minus on $(x-3)$ flips both signs.", ["7x - 1"]),
  ],
  masteryQuizPool: [
    choice("y8-alg-ee-p1", "Expand $2(x+5)$.", "A", ["$2x+10$", "$2x+5$", "$x+10$", "$2x+7$"], "$2x+10$.", "Multiply 2 by both.", "\\text{Select A, B, C or D.}", 1),
    answer("y8-alg-ee-p2", "Expand $3(x+4)$.", "", "3x+12", "$3x+12$.", "Multiply 3 by both.", ["3x + 12"], 1),
    answer("y8-alg-ee-p3", "Expand $4(x-2)$.", "", "4x-8", "$4x-8$.", "Multiply 4 by both.", ["4x - 8"], 1),
    answer("y8-alg-ee-p4", "Expand $5(2x+1)$.", "", "10x+5", "$10x+5$.", "Multiply 5 through.", ["10x + 5"], 1),
    choice("y8-alg-ee-p5", "Expand $3(2x-1)$.", "B", ["$6x-1$", "$6x-3$", "$5x-3$", "$6x+3$"], "$6x-3$.", "Multiply 3 by both.", "\\text{Select A, B, C or D.}", 1),
    answer("y8-alg-ee-p6", "Expand $2(4x+3)$.", "", "8x+6", "$8x+6$.", "Multiply 2 through.", ["8x + 6"], 1),
    answer("y8-alg-ee-p7", "Expand $6(x-3)$.", "", "6x-18", "$6x-18$.", "Multiply 6 by both.", ["6x - 18"], 2),
    answer("y8-alg-ee-p8", "Expand $-2(x+4)$.", "", "-2x-8", "$-2\\times x=-2x$, $-2\\times 4=-8$.", "Both products are negative.", ["-2x - 8"], 2),
    answer("y8-alg-ee-p9", "Expand $-3(x-1)$.", "", "-3x+3", "$-3x+3$ (negative times negative).", "Second term becomes positive.", ["-3x + 3"], 2),
    answer("y8-alg-ee-p10", "Expand $3(x+2y-1)$.", "", "3x+6y-3", "$3x+6y-3$.", "Reach all three terms.", ["3x + 6y - 3"], 2),
    answer("y8-alg-ee-p11", "Expand $-(x-6)$.", "", "-x+6", "Leading minus is $-1$: $-x+6$.", "Both signs flip.", ["-x + 6"], 2),
    choice("y8-alg-ee-p12", "Which equals $-4(x+2)$?", "C", ["$-4x+8$", "$4x-8$", "$-4x-8$", "$-4x+2$"], "$-4x-8$.", "Both products negative.", "\\text{Select A, B, C or D.}", 2),
    answer("y8-alg-ee-p13", "Expand and simplify $2(x+3)+3x$.", "", "5x+6", "$2x+6+3x=5x+6$.", "Collect $x$-terms.", ["5x + 6"], 3),
    answer("y8-alg-ee-p14", "Expand and simplify $4(x+1)+2(x+5)$.", "", "6x+14", "$4x+4+2x+10=6x+14$.", "Expand both, then collect.", ["6x + 14"], 3),
    answer("y8-alg-ee-p15", "Expand and simplify $5(x+2)-2(x+1)$.", "", "3x+8", "$5x+10-2x-2=3x+8$.", "Watch the $-2(x+1)$.", ["3x + 8"], 3),
    answer("y8-alg-ee-p16", "Expand and simplify $3(2x-1)+4(x+2)$.", "", "10x+5", "$6x-3+4x+8=10x+5$.", "Expand both, then collect.", ["10x + 5"], 3),
    answer("y8-alg-ee-p17", "Expand $-2(3x-5)$.", "", "-6x+10", "$-6x+10$.", "Negative times negative is positive.", ["-6x + 10"], 3),
    answer("y8-alg-ee-p18", "Expand and simplify $6(x+2)-(x-4)$.", "", "5x+16", "$6x+12-x+4=5x+16$.", "Leading minus flips both signs.", ["5x + 16"], 3),
    answer("y8-alg-ee-p19", "Expand and simplify $4(2x+1)-3(x-2)$, then solve when the expression equals 35.", "", "5x+10, x = 5", "Expansion gives $8x+4-3x+6=5x+10$. Solving $5x+10=35$ gives $x=5$.", "The negative multiplier makes the final constant positive.", ["5x + 10, 5"], 4),
    answer("y8-alg-ee-p20", "Expand and simplify $5(2x-3)-2(3x-4)$, then evaluate at $x=-2$.", "", "4x-7, -15", "Expansion gives $10x-15-6x+8=4x-7$. At $x=-2$, the value is $-8-7=-15$.", "Distribute both negative signs before substituting.", ["4x - 7, -15"], 4),
    answer("y8-alg-ee-p21", "Expand and simplify $3(x+2y)-2(x-y)$, then evaluate for $x=2$ and $y=-1$.", "", "x+8y, -6", "The expression becomes $3x+6y-2x+2y=x+8y$. Substitution gives $2+8(-1)=-6$.", "Collect the two variable types separately before substitution.", ["x + 8y, -6"], 4),
    answer("y8-alg-ee-p22", "Expand and simplify $2(3x-1)-(4x-5)$, then solve when its value is 15.", "", "2x+3, x = 6", "Expansion gives $6x-2-4x+5=2x+3$. Solving $2x+3=15$ gives $x=6$.", "The subtraction changes both signs in the second bracket.", ["2x + 3, 6"], 4),
    answer("y8-alg-ee-p23", "Expand and simplify $4(x-2)-3(2x-5)$, then find $x$ when the result equals $-3$.", "", "-2x+7, x = 5", "Expansion gives $4x-8-6x+15=-2x+7$. Solving $-2x+7=-3$ gives $-2x=-10$ and $x=5$.", "A negative coefficient is valid; keep it when solving.", ["-2x + 7, 5"], 4),
    answer("y8-alg-ee-p24", "Expand and simplify $5(2x+3)-4(x+2)+x$, then evaluate at $x=-1$.", "", "7x+7, 0", "Expansion gives $7x+7$; at $-1$ this equals 0.", "Collect before substituting.", ["7x+7,0"], 5),
    answer("y8-alg-ee-p25", "Expand and simplify $3(2x-1)-2(x-4)-(x+1)$, then evaluate at $x=2$.", "", "3x+4, 10", "Expansion gives $3x+4$; at 2 it equals 10.", "Track both subtraction signs.", ["3x+4,10"], 5),
    answer("y8-alg-ee-p26", "Expand and simplify $2x(3)+4(x-2)-5$, then solve when the expression equals 17.", "", "10x-13, x=3", "It simplifies to $10x-13$. Solving $10x-13=17$ gives $x=3$.", "Simplify, then form the equation.", ["10x-13,3"], 5),
    answer("y8-alg-ee-p27", "Expand and simplify $6(x+1)-2(2x-3)-3(x-1)$, then find its zero.", "", "-x+15, x=15", "Expansion gives $-x+15$. Setting it to zero gives $x=15$.", "Collect, then solve $-x+15=0$.", ["-x+15,15"], 5),
    answer("y8-alg-ee-p28", "Expand and simplify $4(2x-3)+3(5-2x)-x$, then evaluate at $x=-3$.", "", "x+3, 0", "Expansion gives $x+3$, which is 0 at $x=-3$.", "Expand every bracket before collecting.", ["x+3,0"], 5),
  ],
  multiPartPractice: [
    {
      id: "y8-alg-ee-mp1",
      prompt:
        "A garden bed is a rectangle with height 3 and width $(x+5)$ metres.",
      latex: "3(x+5)",
      answer: "3x+15",
      hint: "Expand by multiplying 3 by each inside term, then substitute to check.",
      explanation:
        "Part (a): area $=3(x+5)=3x+15$. Part (b): split into $3\\times x=3x$ and $3\\times 5=15$. Part (c): at $x=4$, area $=3(9)=27$ square metres.",
      parts: [
        {
          key: "a",
          label: "(a)",
          prompt: "Expand $3(x+5)$ to find the area as an expression.",
          latex: "",
          marks: 1,
          answer: "3x+15",
          acceptedAnswers: ["3x + 15"],
          hint: "Multiply 3 by each term inside.",
          explanation: "$3\\times x=3x$ and $3\\times 5=15$, so $3x+15$.",
        },
        {
          key: "b",
          label: "(b)",
          prompt: "What is the area of the part with width $x$ only (height 3)?",
          latex: "",
          marks: 1,
          answer: "3x",
          acceptedAnswers: ["3*x"],
          hint: "Multiply the height 3 by the width $x$.",
          explanation: "$3\\times x=3x$.",
        },
        {
          key: "c",
          label: "(c)",
          prompt: "Find the total area in square metres when $x = 4$.",
          latex: "",
          marks: 1,
          answer: "27",
          acceptedAnswers: ["27 m^2"],
          hint: "Substitute $x=4$ into $3x+15$.",
          explanation: "$3(4)+15=12+15=27$ square metres.",
        },
      ],
    },
  ],
};

// ── Lesson 3: Binomial Products ──────────────────────────────────────────────

const binomialProducts: Partial<ExplicitLesson> = {
  moduleTitle: "Algebraic Techniques",
  syllabusArea: "Number and Algebra",
  masteryPassMark: 0.8,
  video: VIDEO,
  description:
    "Expand binomial products $(a+b)(c+d)$ using the distributive law and the area model, and simplify special products including perfect squares and the difference of two squares.",
  learningIntention:
    "Expand and simplify products of two binomials, including perfect squares $(a+b)^2$ and the difference of two squares $(a+b)(a-b)$.",
  successCriteria: [
    "Expand $(a+b)(c+d)$ by multiplying each term in the first bracket by each term in the second.",
    "Use the area model to organise the four products.",
    "Collect like terms to write the answer in simplest form.",
    "Expand a perfect square $(a+b)^2$ to $a^2+2ab+b^2$.",
    "Recognise and expand a difference of two squares $(a+b)(a-b)=a^2-b^2$.",
    "Substitute a value to check a binomial expansion.",
  ],
  teaching: {
    paragraphs: [
      "A binomial is an expression with two terms, such as $(x+3)$. A binomial product multiplies two of them together, such as $(x+3)(x+2)$. To expand it, every term in the first bracket must multiply every term in the second bracket — the distributive law applied twice.",
      "The area model makes this visible. Draw a rectangle whose side lengths are $(x+3)$ and $(x+2)$. Split each side at its plus sign, and the rectangle breaks into four smaller rectangles. Their areas are $x\\times x=x^2$, $x\\times 2=2x$, $3\\times x=3x$ and $3\\times 2=6$. Adding all four areas gives $x^2+2x+3x+6$, and collecting the like middle terms gives $x^2+5x+6$. The four small rectangles are exactly the four products you must not miss.",
      "Writing the four products in a fixed order helps you avoid dropping one: First terms, Outer terms, Inner terms, Last terms. For $(x+3)(x+2)$ that is $x\\cdot x$, $x\\cdot 2$, $3\\cdot x$, $3\\cdot 2$, i.e. $x^2+2x+3x+6=x^2+5x+6$. The two middle products are usually like terms and combine.",
      "A perfect square is a binomial multiplied by itself: $(a+b)^2=(a+b)(a+b)$. Expanding the four products gives $a\\cdot a + a\\cdot b + b\\cdot a + b\\cdot b = a^2+ab+ab+b^2 = a^2+2ab+b^2$. The middle term is $2ab$, not $ab$, because there are two identical cross-products. This is exactly why $(a+b)^2\\neq a^2+b^2$ — the common error is to forget the doubled middle term.",
      "You can see the $2ab$ in the area model too: a square of side $(a+b)$ contains a small square $a^2$, a small square $b^2$, and two identical rectangles each of area $ab$. The two $ab$ rectangles are why the middle term is doubled. So, for example, $(x+4)^2=x^2+2(x)(4)+16=x^2+8x+16$.",
      "The difference of two squares comes from $(a+b)(a-b)$. The four products are $a^2-ab+ab-b^2$. The two middle terms $-ab$ and $+ab$ are opposites, so they cancel, leaving $a^2-b^2$. The middle term vanishing is the signature of this pattern: $(x+5)(x-5)=x^2-25$. Recognising it lets you write the answer in one step.",
      "Always confirm with a substitution. For $(x+3)(x+2)=x^2+5x+6$, try $x=1$: the left side is $4\\times 3=12$ and the right side is $1+5+6=12$. The agreement tells you no product was dropped and no like term was mishandled.",
    ],
    latexBlocks: [
      "(a+b)(c+d)=ac+ad+bc+bd",
      "(a+b)^2=a^2+2ab+b^2",
      "(a+b)(a-b)=a^2-b^2",
    ],
  },
  workedExamples: [
    {
      title: "Expand a binomial product",
      questionLatex: "\\text{Expand } (x+4)(x+5).",
      steps: [
        { explanation: "Multiply each term in the first bracket by each term in the second (the four area pieces).", latex: "x\\cdot x + x\\cdot 5 + 4\\cdot x + 4\\cdot 5" },
        { explanation: "Write the four products.", latex: "=x^2+5x+4x+20" },
        { explanation: "Collect the like middle terms.", latex: "=x^2+9x+20" },
      ],
      finalAnswerLatex: "x^2+9x+20",
    } as WorkedExample,
    {
      title: "Expand a perfect square",
      questionLatex: "\\text{Expand } (x+6)^2.",
      steps: [
        { explanation: "A perfect square means $(x+6)(x+6)$. Use $a^2+2ab+b^2$ with $a=x$, $b=6$.", latex: "x^2+2(x)(6)+6^2" },
        { explanation: "Evaluate the middle and last terms. The middle term is doubled.", latex: "=x^2+12x+36" },
      ],
      finalAnswerLatex: "x^2+12x+36",
    } as WorkedExample,
    {
      title: "Difference of two squares",
      questionLatex: "\\text{Expand } (x+7)(x-7).",
      steps: [
        { explanation: "This matches $(a+b)(a-b)$ with $a=x$, $b=7$; the middle terms cancel.", latex: "x^2-7x+7x-49" },
        { explanation: "The $-7x$ and $+7x$ cancel, leaving the difference of squares.", latex: "=x^2-49" },
      ],
      finalAnswerLatex: "x^2-49",
    } as WorkedExample,
    {
      title: "Expand with a coefficient on x",
      questionLatex: "\\text{Expand } (2x+3)(x-4).",
      steps: [
        { explanation: "Multiply each pair of terms.", latex: "2x\\cdot x + 2x\\cdot(-4) + 3\\cdot x + 3\\cdot(-4)" },
        { explanation: "Write the four products.", latex: "=2x^2-8x+3x-12" },
        { explanation: "Collect the like middle terms.", latex: "=2x^2-5x-12" },
      ],
      finalAnswerLatex: "2x^2-5x-12",
    } as WorkedExample,
  ],
  guidedPractice: [
    choice(
      "y8-alg-bp-g1",
      "Which is the correct expansion of $(x+2)(x+3)$?",
      "B",
      ["$x^2+6$", "$x^2+5x+6$", "$x^2+6x+5$", "$2x+5$"],
      "Four products: $x^2+3x+2x+6=x^2+5x+6$.",
      "Multiply each term by each term, then collect the middle terms.",
    ),
    answer(
      "y8-alg-bp-g2",
      "Expand and simplify $(x+1)(x+4)$.",
      "",
      "x^2+5x+4",
      "$x^2+4x+x+4=x^2+5x+4$.",
      "Use First, Outer, Inner, Last, then collect.",
      ["x^2 + 5x + 4"],
    ),
    answer(
      "y8-alg-bp-g3",
      "Expand $(x+5)^2$.",
      "",
      "x^2+10x+25",
      "$a^2+2ab+b^2$ with $a=x$, $b=5$: $x^2+10x+25$.",
      "The middle term is $2\\times x\\times 5$.",
      ["x^2 + 10x + 25"],
    ),
    answer(
      "y8-alg-bp-g4",
      "Expand $(x+3)(x-3)$.",
      "",
      "x^2-9",
      "Difference of squares: the middle terms cancel, leaving $x^2-9$.",
      "Recognise $(a+b)(a-b)=a^2-b^2$.",
      ["x^2 - 9"],
    ),
  ],
  independentPractice: [
    answer(
      "y8-alg-bp-i1",
      "Expand and simplify $(x+2)(x+6)$.",
      "",
      "x^2+8x+12",
      "$x^2+6x+2x+12=x^2+8x+12$.",
      "Collect the middle terms $6x+2x$.",
      ["x^2 + 8x + 12"],
    ),
    answer(
      "y8-alg-bp-i2",
      "Expand and simplify $(x-3)(x+5)$.",
      "",
      "x^2+2x-15",
      "$x^2+5x-3x-15=x^2+2x-15$.",
      "Watch the signs on the inner and last products.",
      ["x^2 + 2x - 15"],
    ),
    answer(
      "y8-alg-bp-i3",
      "Expand $(x+4)^2$.",
      "",
      "x^2+8x+16",
      "$x^2+2(x)(4)+16=x^2+8x+16$.",
      "Do not forget the doubled middle term.",
      ["x^2 + 8x + 16"],
    ),
    answer(
      "y8-alg-bp-i4",
      "Expand $(x+8)(x-8)$.",
      "",
      "x^2-64",
      "Difference of squares: $x^2-64$.",
      "Middle terms cancel.",
      ["x^2 - 64"],
    ),
    choice(
      "y8-alg-bp-i5",
      "Which is the correct expansion of $(2x+1)(x+3)$?",
      "A",
      ["$2x^2+7x+3$", "$2x^2+3x+3$", "$2x^2+7x+1$", "$3x^2+7x+3$"],
      "$2x^2+6x+x+3=2x^2+7x+3$.",
      "Multiply $2x$ and 1 by each term in $(x+3)$.",
    ),
  ],
  commonMistakes: [
    {
      mistake: "Writing $(a+b)^2=a^2+b^2$ — forgetting the middle term.",
      fix: "$(a+b)^2=a^2+2ab+b^2$. There are two equal cross-products, so the middle term is $2ab$.",
    },
    {
      mistake: "Multiplying only the first terms: $(x+3)(x+2)=x^2+6$.",
      fix: "All four products are needed: $x^2+2x+3x+6=x^2+5x+6$.",
    },
    {
      mistake: "Keeping a middle term in a difference of squares: $(x+5)(x-5)=x^2+10x-25$.",
      fix: "The middle terms cancel: $(x+5)(x-5)=x^2-25$.",
    },
    {
      mistake: "Sign slips on negative terms: $(x-3)(x+5)=x^2+2x+15$.",
      fix: "The last product is $-3\\times 5=-15$: $(x-3)(x+5)=x^2+2x-15$.",
    },
  ],
  masteryQuiz: [
    choice("y8-alg-bp-m1", "Expand $(x+2)(x+5)$.", "C", ["$x^2+10$", "$x^2+7$", "$x^2+7x+10$", "$x^2+10x+7$"], "$x^2+5x+2x+10=x^2+7x+10$.", "Collect the middle terms."),
    answer("y8-alg-bp-m2", "Expand and simplify $(x+3)(x+4)$.", "", "x^2+7x+12", "$x^2+4x+3x+12=x^2+7x+12$.", "FOIL then collect.", ["x^2 + 7x + 12"]),
    answer("y8-alg-bp-m3", "Expand $(x+2)^2$.", "", "x^2+4x+4", "$x^2+2(x)(2)+4=x^2+4x+4$.", "Middle term is doubled.", ["x^2 + 4x + 4"]),
    answer("y8-alg-bp-m4", "Expand $(x+6)(x-6)$.", "", "x^2-36", "Difference of squares: $x^2-36$.", "Middle terms cancel.", ["x^2 - 36"]),
    answer("y8-alg-bp-m5", "Expand and simplify $(x-2)(x+7)$.", "", "x^2+5x-14", "$x^2+7x-2x-14=x^2+5x-14$.", "Mind the signs.", ["x^2 + 5x - 14"]),
    answer("y8-alg-bp-m6", "Expand $(x+9)^2$.", "", "x^2+18x+81", "$x^2+18x+81$.", "Double the cross-product.", ["x^2 + 18x + 81"]),
    choice("y8-alg-bp-m7", "Which equals $(x+10)(x-10)$?", "D", ["$x^2+20x-100$", "$x^2-20x-100$", "$x^2+100$", "$x^2-100$"], "Difference of squares: $x^2-100$.", "Middle terms cancel."),
    answer("y8-alg-bp-m8", "Expand and simplify $(2x+3)(x+2)$.", "", "2x^2+7x+6", "$2x^2+4x+3x+6=2x^2+7x+6$.", "Multiply each pair.", ["2x^2 + 7x + 6"]),
    answer("y8-alg-bp-m9", "Expand and simplify $(x-4)(x-5)$.", "", "x^2-9x+20", "$x^2-5x-4x+20=x^2-9x+20$.", "Two negatives in the middle add.", ["x^2 - 9x + 20"]),
    answer("y8-alg-bp-m10", "Expand and simplify $(3x-2)(x+4)$.", "", "3x^2+10x-8", "$3x^2+12x-2x-8=3x^2+10x-8$.", "Collect the middle terms.", ["3x^2 + 10x - 8"]),
  ],
  masteryQuizPool: [
    choice("y8-alg-bp-p1", "Expand $(x+1)(x+2)$.", "B", ["$x^2+2$", "$x^2+3x+2$", "$x^2+2x+1$", "$x^2+3$"], "$x^2+2x+x+2=x^2+3x+2$.", "Collect the middle terms.", "\\text{Select A, B, C or D.}", 1),
    answer("y8-alg-bp-p2", "Expand and simplify $(x+1)(x+3)$.", "", "x^2+4x+3", "$x^2+3x+x+3=x^2+4x+3$.", "FOIL then collect.", ["x^2 + 4x + 3"], 1),
    answer("y8-alg-bp-p3", "Expand and simplify $(x+2)(x+4)$.", "", "x^2+6x+8", "$x^2+4x+2x+8=x^2+6x+8$.", "FOIL then collect.", ["x^2 + 6x + 8"], 1),
    answer("y8-alg-bp-p4", "Expand and simplify $(x+5)(x+2)$.", "", "x^2+7x+10", "$x^2+2x+5x+10=x^2+7x+10$.", "Collect.", ["x^2 + 7x + 10"], 1),
    answer("y8-alg-bp-p5", "Expand $(x+3)^2$.", "", "x^2+6x+9", "$x^2+6x+9$.", "Double the cross-product.", ["x^2 + 6x + 9"], 1),
    answer("y8-alg-bp-p6", "Expand $(x+1)(x-1)$.", "", "x^2-1", "Difference of squares: $x^2-1$.", "Middle cancels.", ["x^2 - 1"], 1),
    answer("y8-alg-bp-p7", "Expand and simplify $(x+6)(x+1)$.", "", "x^2+7x+6", "$x^2+x+6x+6=x^2+7x+6$.", "Collect.", ["x^2 + 7x + 6"], 2),
    answer("y8-alg-bp-p8", "Expand $(x+4)^2$.", "", "x^2+8x+16", "$x^2+8x+16$.", "Double the cross-product.", ["x^2 + 8x + 16"], 2),
    answer("y8-alg-bp-p9", "Expand $(x+2)(x-2)$.", "", "x^2-4", "Difference of squares: $x^2-4$.", "Middle cancels.", ["x^2 - 4"], 2),
    answer("y8-alg-bp-p10", "Expand and simplify $(x-1)(x+6)$.", "", "x^2+5x-6", "$x^2+6x-x-6=x^2+5x-6$.", "Mind the signs.", ["x^2 + 5x - 6"], 2),
    answer("y8-alg-bp-p11", "Expand and simplify $(x-2)(x+3)$.", "", "x^2+x-6", "$x^2+3x-2x-6=x^2+x-6$.", "Mind the signs.", ["x^2 + x - 6"], 2),
    choice("y8-alg-bp-p12", "Which equals $(x+7)(x-7)$?", "C", ["$x^2+14x-49$", "$x^2+49$", "$x^2-49$", "$x^2-14x-49$"], "Difference of squares: $x^2-49$.", "Middle terms cancel.", "\\text{Select A, B, C or D.}", 2),
    answer("y8-alg-bp-p13", "Expand $(x+5)^2$.", "", "x^2+10x+25", "$x^2+10x+25$.", "Double the cross-product.", ["x^2 + 10x + 25"], 3),
    answer("y8-alg-bp-p14", "Expand and simplify $(x-3)(x-4)$.", "", "x^2-7x+12", "$x^2-4x-3x+12=x^2-7x+12$.", "Two negatives add in the middle.", ["x^2 - 7x + 12"], 3),
    answer("y8-alg-bp-p15", "Expand and simplify $(x+8)(x-3)$.", "", "x^2+5x-24", "$x^2-3x+8x-24=x^2+5x-24$.", "Collect the middle terms.", ["x^2 + 5x - 24"], 3),
    answer("y8-alg-bp-p16", "Expand and simplify $(2x+1)(x+5)$.", "", "2x^2+11x+5", "$2x^2+10x+x+5=2x^2+11x+5$.", "Multiply each pair.", ["2x^2 + 11x + 5"], 3),
    answer("y8-alg-bp-p17", "Expand $(x-6)^2$.", "", "x^2-12x+36", "$x^2-2(x)(6)+36=x^2-12x+36$.", "Cross-product is negative and doubled.", ["x^2 - 12x + 36"], 3),
    answer("y8-alg-bp-p18", "Expand $(2x+5)(2x-5)$.", "", "4x^2-25", "Difference of squares: $(2x)^2-5^2=4x^2-25$.", "Square each term.", ["4x^2 - 25"], 3),
    answer("y8-alg-bp-p19", "Expand and simplify $(3x+2)(x-1)$, then evaluate at $x=2$.", "", "3x^2-x-2, 8", "Expansion gives $3x^2-3x+2x-2=3x^2-x-2$. At $x=2$, the value is $12-2-2=8$.", "Collect unlike signed middle terms before evaluating.", ["3x^2 - x - 2, 8"], 4),
    answer("y8-alg-bp-p20", "Expand and simplify $(2x-3)(3x+4)$, then evaluate at $x=2$.", "", "6x^2-x-12, 10", "The four products give $6x^2+8x-9x-12=6x^2-x-12$. At $x=2$, this is $24-2-12=10$.", "Keep all four products and combine only like terms.", ["6x^2 - x - 12, 10"], 4),
    answer("y8-alg-bp-p21", "A student expands $(2x+3)^2$ as $4x^2+9$. Give the correct expansion and find the difference between the correct and student expressions at $x=1$.", "", "4x^2+12x+9, difference 12", "The doubled cross-product is $2(2x)(3)=12x$, so the correct expansion is $4x^2+12x+9$. At $x=1$, the missing term is 12, so the expressions differ by 12.", "A squared binomial contains a doubled middle product.", ["4x^2 + 12x + 9, 12"], 4),
    answer("y8-alg-bp-p22", "Expand and simplify $(x+4)(x-4)+5$, then solve when the expression equals 14.", "", "x^2-11, x = 5 or -5", "The product is a difference of squares: $x^2-16$, so the expression is $x^2-11$. Setting it equal to 14 gives $x^2=25$, hence $x=5$ or $x=-5$.", "After simplifying, remember that two numbers square to 25.", ["x^2 - 11, ±5", "x^2-11, x=5,-5"], 4),
    answer("y8-alg-bp-p23", "Expand and simplify $(x+3)^2-(x-3)^2$, then find $x$ when the result is 36.", "", "12x, x = 3", "Expanding and subtracting gives $(x^2+6x+9)-(x^2-6x+9)=12x$. Then $12x=36$, so $x=3$.", "The quadratic and constant terms cancel only after the second bracket's signs are changed.", ["12*x, 3", "12x, 3"], 4),
    answer("y8-alg-bp-p24", "Expand and simplify $(x+2)(x+3)+(x+1)(x+4)$, then evaluate at $x=1$.", "", "2x^2+10x+10, 22", "The expansion is $2x^2+10x+10$; at 1 it is 22.", "Expand both products before substituting.", ["2x^2+10x+10,22"], 5),
    answer("y8-alg-bp-p25", "Expand and simplify $(2x-1)^2-(x+2)(x-2)$, then evaluate at $x=2$.", "", "3x^2-4x+5, 9", "Expansion gives $3x^2-4x+5$; at 2 it equals 9.", "Subtract the whole second expansion.", ["3x^2-4x+5,9"], 5),
    answer("y8-alg-bp-p26", "Expand and simplify $(x+5)(x-5)-(x-3)^2$, then solve when it equals 2.", "", "6x-34, x=6", "The quadratic terms cancel to $6x-34$. Solving $6x-34=2$ gives $x=6$.", "Simplify first, then solve.", ["6x-34,6"], 5),
    answer("y8-alg-bp-p27", "Expand and simplify $(3x+1)(x-2)-(x-4)(x+1)$, then evaluate at $x=-1$.", "", "2x^2-2x+2, 6", "The simplified form is $2x^2-2x+2$; at $-1$ it is 6.", "Handle the outer subtraction carefully.", ["2x^2-2x+2,6"], 5),
    answer("y8-alg-bp-p28", "Expand and simplify $2(x+3)^2-(x+1)(x+5)$, then evaluate at $x=-3$.", "", "x^2+6x+13, 4", "It simplifies to $x^2+6x+13$; at $-3$ the value is 4.", "Expand, collect, then substitute.", ["x^2+6x+13,4"], 5),
  ],
  multiPartPractice: [
    {
      id: "y8-alg-bp-mp1",
      prompt:
        "A square has side length $(x+5)$ centimetres.",
      latex: "(x+5)^2",
      answer: "x^2+10x+25",
      hint: "Use the area model: $a^2+2ab+b^2$, then substitute to check.",
      explanation:
        "Part (a): area $=(x+5)^2=x^2+10x+25$. Part (b): the two identical $ab$ rectangles each have area $5x$, total $10x$. Part (c): at $x=3$, area $=8^2=64$ square centimetres.",
      parts: [
        {
          key: "a",
          label: "(a)",
          prompt: "Expand $(x+5)^2$ to find the area.",
          latex: "",
          marks: 2,
          answer: "x^2+10x+25",
          acceptedAnswers: ["x^2 + 10x + 25"],
          hint: "Use $a^2+2ab+b^2$ with $a=x$, $b=5$.",
          explanation: "$x^2+2(x)(5)+25=x^2+10x+25$.",
        },
        {
          key: "b",
          label: "(b)",
          prompt: "What is the combined area of the two $ab$ rectangles in the area model (the middle term)?",
          latex: "",
          marks: 1,
          answer: "10x",
          acceptedAnswers: ["10*x"],
          hint: "Each rectangle is $5\\times x$; there are two of them.",
          explanation: "$2\\times 5x=10x$, which is the middle term.",
        },
        {
          key: "c",
          label: "(c)",
          prompt: "Find the total area in square centimetres when $x = 3$.",
          latex: "",
          marks: 1,
          answer: "64",
          acceptedAnswers: ["64 cm^2"],
          hint: "Substitute $x=3$ into $(x+5)^2$ or into $x^2+10x+25$.",
          explanation: "$(3+5)^2=8^2=64$ square centimetres.",
        },
      ],
    },
  ],
};

// ── Lesson 4: Equivalent Expressions ─────────────────────────────────────────

const equivalentExpressions: Partial<ExplicitLesson> = {
  moduleTitle: "Algebraic Techniques",
  syllabusArea: "Number and Algebra",
  masteryPassMark: 0.8,
  video: VIDEO,
  description:
    "Recognise and verify when two algebraic expressions are equivalent, rewrite expressions in alternative forms, and use substitution to test equivalence.",
  learningIntention:
    "Decide whether two expressions are equivalent, rewrite an expression in an alternative form, and confirm equivalence by substitution.",
  successCriteria: [
    "Explain what it means for two expressions to be equivalent.",
    "Rewrite an expression in an alternative form by expanding or collecting like terms.",
    "Test equivalence by substituting a value into both expressions.",
    "Identify a non-equivalent expression from a substitution that disagrees.",
    "Match an expression to its equivalent simplified form.",
  ],
  teaching: {
    paragraphs: [
      "Two expressions are equivalent if they give the same value for every possible value of the variable. They are just two different ways of writing the same thing. For example, $2(x+3)$ and $2x+6$ are equivalent: whatever number you choose for $x$, both expressions produce the same result.",
      "The reason they always agree is that one was obtained from the other by valid algebra — here, expanding the bracket. Every legal step (expanding, collecting like terms, factorising) preserves value, so the new form is guaranteed to match the old for every $x$. Equivalence is not a coincidence; it is built in by the rules.",
      "To rewrite an expression in an alternative form, apply those same operations. Expanding turns $3(x+2)$ into $3x+6$. Collecting like terms turns $4x+2x+5$ into $6x+5$. Each rewrite is still the same expression wearing different clothes.",
      "The fastest way to test a claim of equivalence is substitution: pick a value for $x$, evaluate both expressions, and compare. If they ever disagree for even one value, they are not equivalent. For example, are $2x+6$ and $2x+3$ equivalent? At $x=0$ they give 6 and 3 — different, so no. One disagreement is enough to disprove equivalence.",
      "Substitution can build confidence but cannot, by one test, fully prove equivalence — two different expressions might happen to agree at a single value by chance. For example, $x^2$ and $2x$ both equal 4 at $x=2$, yet they are not equivalent (at $x=3$ they give 9 and 6). To be sure, either test several values or do the algebra. The safe rule: algebra proves equivalence; a single substitution can only disprove it.",
      "A common error is to call $(x+3)^2$ equivalent to $x^2+9$. A quick substitution exposes the mistake: at $x=1$, $(x+3)^2=16$ but $x^2+9=10$. They disagree, so they are not equivalent — the correct equivalent form is $x^2+6x+9$. Whenever you are unsure, substitute before you commit.",
    ],
    latexBlocks: [
      "2(x+3)=2x+6\\quad\\text{(equivalent for all }x)",
      "\\text{Test: substitute a value into both expressions and compare.}",
      "(x+3)^2=x^2+6x+9\\neq x^2+9",
    ],
  },
  workedExamples: [
    {
      title: "Verify equivalence by expanding",
      questionLatex: "\\text{Are } 4(x+2) \\text{ and } 4x+8 \\text{ equivalent?}",
      steps: [
        { explanation: "Expand the bracketed form.", latex: "4(x+2)=4x+8" },
        { explanation: "The expanded form matches the second expression exactly.", latex: "4x+8=4x+8" },
      ],
      finalAnswerLatex: "\\text{Yes, equivalent.}",
    } as WorkedExample,
    {
      title: "Disprove equivalence by substitution",
      questionLatex: "\\text{Are } 3x+5 \\text{ and } 3x+2 \\text{ equivalent?}",
      steps: [
        { explanation: "Substitute a value, say $x=0$, into each.", latex: "3(0)+5=5,\\quad 3(0)+2=2" },
        { explanation: "The values differ, so the expressions are not equivalent.", latex: "5\\neq 2" },
      ],
      finalAnswerLatex: "\\text{No, not equivalent.}",
    } as WorkedExample,
    {
      title: "Rewrite in an alternative form",
      questionLatex: "\\text{Write } 5x+2x+7 \\text{ in simplest form.}",
      steps: [
        { explanation: "Collect the like $x$-terms.", latex: "5x+2x=7x" },
        { explanation: "Combine with the constant term.", latex: "=7x+7" },
      ],
      finalAnswerLatex: "7x+7",
    } as WorkedExample,
    {
      title: "Check a suspected equivalence carefully",
      questionLatex: "\\text{Is } (x+3)^2 \\text{ equivalent to } x^2+9?",
      steps: [
        { explanation: "Substitute $x=1$ into both expressions.", latex: "(1+3)^2=16,\\quad 1^2+9=10" },
        { explanation: "The values differ, so they are not equivalent. The true expansion is different.", latex: "(x+3)^2=x^2+6x+9" },
      ],
      finalAnswerLatex: "\\text{Not equivalent; } (x+3)^2=x^2+6x+9.",
    } as WorkedExample,
  ],
  guidedPractice: [
    choice(
      "y8-alg-eq-g1",
      "Which expression is equivalent to $3(x+4)$?",
      "B",
      ["$3x+4$", "$3x+12$", "$x+12$", "$3x+7$"],
      "Expanding gives $3x+12$.",
      "Expand the bracket.",
    ),
    answer(
      "y8-alg-eq-g2",
      "Simplify $6x+3x-4$ to its equivalent form.",
      "",
      "9x-4",
      "Collect like terms: $6x+3x=9x$, giving $9x-4$.",
      "Add the $x$-terms.",
      ["9x - 4"],
    ),
    answer(
      "y8-alg-eq-g3",
      "At $x=2$, evaluate $2(x+3)$ to test equivalence with $2x+6$.",
      "",
      "10",
      "$2(2+3)=2(5)=10$, and $2x+6=4+6=10$. They agree.",
      "Substitute $x=2$ into the bracketed form.",
      ["10"],
    ),
    choice(
      "y8-alg-eq-g4",
      "Which expression is NOT equivalent to $2x+8$?",
      "D",
      ["$2(x+4)$", "$8+2x$", "$x+x+8$", "$2x+4$"],
      "$2x+4$ gives a different value (e.g. at $x=0$ it is 4, not 8).",
      "Substitute $x=0$ to spot the odd one out.",
    ),
  ],
  independentPractice: [
    answer(
      "y8-alg-eq-i1",
      "Rewrite $5(x+2)$ in expanded form.",
      "",
      "5x+10",
      "$5x+10$.",
      "Expand the bracket.",
      ["5x + 10"],
    ),
    answer(
      "y8-alg-eq-i2",
      "Simplify $4x+7x-2x$ to its equivalent form.",
      "",
      "9x",
      "$4+7-2=9$, so $9x$.",
      "Combine the coefficients.",
      ["9*x"],
    ),
    choice(
      "y8-alg-eq-i3",
      "Which expression is equivalent to $2(x+3)+x$?",
      "A",
      ["$3x+6$", "$2x+6$", "$3x+3$", "$2x+3$"],
      "$2x+6+x=3x+6$.",
      "Expand then collect.",
    ),
    answer(
      "y8-alg-eq-i4",
      "At $x=3$, evaluate $(x+1)^2$ to compare with $x^2+1$.",
      "",
      "16",
      "$(3+1)^2=16$, while $x^2+1=10$. They disagree, so the two are not equivalent.",
      "Substitute $x=3$ into $(x+1)^2$.",
      ["16"],
    ),
    choice(
      "y8-alg-eq-i5",
      "Which expression is NOT equivalent to $(x+2)(x+3)$?",
      "C",
      ["$x^2+5x+6$", "$x^2+2x+3x+6$", "$x^2+6$", "$x^2+5x+6$"],
      "$(x+2)(x+3)=x^2+5x+6$, not $x^2+6$ (the middle term is missing).",
      "Expand fully; do not drop the middle term.",
    ),
  ],
  commonMistakes: [
    {
      mistake: "Calling $(x+3)^2$ equivalent to $x^2+9$.",
      fix: "$(x+3)^2=x^2+6x+9$. Substituting $x=1$ shows $16\\neq 10$.",
    },
    {
      mistake: "Concluding two expressions are equivalent from a single matching substitution.",
      fix: "One match is not proof — $x^2$ and $2x$ both give 4 at $x=2$ but differ elsewhere. Use algebra or several values.",
    },
    {
      mistake: "Dropping the middle term when expanding a product, e.g. $(x+2)(x+3)=x^2+6$.",
      fix: "Include all four products: $x^2+5x+6$.",
    },
    {
      mistake: "Treating $2x+4$ as equivalent to $2(x+4)$.",
      fix: "$2(x+4)=2x+8$, not $2x+4$. Expand carefully before comparing.",
    },
  ],
  masteryQuiz: [
    choice("y8-alg-eq-m1", "Which is equivalent to $4(x+1)$?", "A", ["$4x+4$", "$4x+1$", "$x+4$", "$4x+5$"], "$4x+4$.", "Expand."),
    answer("y8-alg-eq-m2", "Simplify $5x+2x+3$ to its equivalent form.", "", "7x+3", "$7x+3$.", "Collect $x$-terms.", ["7x + 3"]),
    answer("y8-alg-eq-m3", "At $x=4$, evaluate $3(x+2)$.", "", "18", "$3(6)=18$; equals $3x+6=18$.", "Substitute $x=4$.", ["18"]),
    choice("y8-alg-eq-m4", "Which is NOT equivalent to $3x+9$?", "D", ["$3(x+3)$", "$9+3x$", "$x+2x+9$", "$3x+3$"], "$3x+3\\neq 3x+9$ (differ at every $x$).", "Compare constants."),
    answer("y8-alg-eq-m5", "Rewrite $2(2x+5)$ in expanded form.", "", "4x+10", "$4x+10$.", "Expand.", ["4x + 10"]),
    choice("y8-alg-eq-m6", "Which is equivalent to $(x+4)(x-4)$?", "B", ["$x^2+16$", "$x^2-16$", "$x^2-8x-16$", "$x^2+8x-16$"], "Difference of squares: $x^2-16$.", "Middle terms cancel."),
    answer("y8-alg-eq-m7", "Simplify $8x-3x+2x$ to its equivalent form.", "", "7x", "$8-3+2=7$, so $7x$.", "Combine coefficients.", ["7*x"]),
    choice("y8-alg-eq-m8", "Which is NOT equivalent to $(x+1)^2$?", "C", ["$x^2+2x+1$", "$(x+1)(x+1)$", "$x^2+1$", "$x^2+x+x+1$"], "$(x+1)^2=x^2+2x+1$, not $x^2+1$.", "Do not forget the doubled middle term."),
    answer("y8-alg-eq-m9", "At $x=2$, evaluate $(x+2)^2$ to compare with $x^2+4$.", "", "16", "$(2+2)^2=16$, while $x^2+4=8$. Not equivalent.", "Substitute $x=2$.", ["16"]),
    choice("y8-alg-eq-m10", "Which is equivalent to $5(x+2)-3x$?", "A", ["$2x+10$", "$8x+10$", "$2x+2$", "$2x+7$"], "$5x+10-3x=2x+10$.", "Expand then collect."),
  ],
  masteryQuizPool: [
    choice("y8-alg-eq-p1", "Which is equivalent to $2(x+5)$?", "B", ["$2x+5$", "$2x+10$", "$x+10$", "$2x+7$"], "$2x+10$.", "Expand.", "\\text{Select A, B, C or D.}", 1),
    answer("y8-alg-eq-p2", "Simplify $3x+4x$.", "", "7x", "$7x$.", "Add coefficients.", ["7*x"], 1),
    answer("y8-alg-eq-p3", "Rewrite $3(x+1)$ in expanded form.", "", "3x+3", "$3x+3$.", "Expand.", ["3x + 3"], 1),
    answer("y8-alg-eq-p4", "Simplify $6x+2x+1$.", "", "8x+1", "$8x+1$.", "Collect $x$-terms.", ["8x + 1"], 1),
    choice("y8-alg-eq-p5", "Which is equivalent to $x+x+4$?", "C", ["$x+4$", "$x^2+4$", "$2x+4$", "$2x$"], "$x+x=2x$, so $2x+4$.", "Add the two $x$-terms.", "\\text{Select A, B, C or D.}", 1),
    answer("y8-alg-eq-p6", "At $x=1$, evaluate $2(x+3)$.", "", "8", "$2(4)=8$.", "Substitute $x=1$.", ["8"], 1),
    answer("y8-alg-eq-p7", "Simplify $9x-4x+x$.", "", "6x", "$9-4+1=6$, so $6x$.", "Combine coefficients.", ["6*x"], 2),
    answer("y8-alg-eq-p8", "Rewrite $4(2x+1)$ in expanded form.", "", "8x+4", "$8x+4$.", "Expand.", ["8x + 4"], 2),
    choice("y8-alg-eq-p9", "Which is NOT equivalent to $2x+6$?", "D", ["$2(x+3)$", "$6+2x$", "$x+x+6$", "$2x+3$"], "$2x+3$ differs from $2x+6$.", "Compare the constants.", "\\text{Select A, B, C or D.}", 2),
    answer("y8-alg-eq-p10", "At $x=3$, evaluate $4(x+1)$.", "", "16", "$4(4)=16$.", "Substitute $x=3$.", ["16"], 2),
    choice("y8-alg-eq-p11", "Which is equivalent to $3(x+2)+x$?", "A", ["$4x+6$", "$3x+6$", "$4x+2$", "$3x+2$"], "$3x+6+x=4x+6$.", "Expand then collect.", "\\text{Select A, B, C or D.}", 2),
    answer("y8-alg-eq-p12", "Simplify $7x+x-3x$.", "", "5x", "$7+1-3=5$, so $5x$.", "Combine coefficients.", ["5*x"], 2),
    choice("y8-alg-eq-p13", "Which is equivalent to $(x+5)(x-5)$?", "B", ["$x^2+25$", "$x^2-25$", "$x^2-10x-25$", "$x^2+10x-25$"], "Difference of squares: $x^2-25$.", "Middle terms cancel.", "\\text{Select A, B, C or D.}", 3),
    answer("y8-alg-eq-p14", "Simplify $5(x+1)-2x$.", "", "3x+5", "$5x+5-2x=3x+5$.", "Expand then collect.", ["3x + 5"], 3),
    choice("y8-alg-eq-p15", "Which is NOT equivalent to $(x+2)(x+4)$?", "C", ["$x^2+6x+8$", "$x^2+4x+2x+8$", "$x^2+8$", "$x^2+6x+8$"], "$(x+2)(x+4)=x^2+6x+8$, not $x^2+8$.", "Do not drop the middle term.", "\\text{Select A, B, C or D.}", 3),
    answer("y8-alg-eq-p16", "At $x=2$, evaluate $(x+1)^2$.", "", "9", "$(2+1)^2=9$.", "Substitute $x=2$.", ["9"], 3),
    choice("y8-alg-eq-p17", "Which is NOT equivalent to $(x+3)^2$?", "D", ["$x^2+6x+9$", "$(x+3)(x+3)$", "$x^2+3x+3x+9$", "$x^2+9$"], "$(x+3)^2=x^2+6x+9$, not $x^2+9$.", "Remember the doubled middle term.", "\\text{Select A, B, C or D.}", 3),
    answer("y8-alg-eq-p18", "Simplify $4(x+3)-2(x+1)$.", "", "2x+10", "$4x+12-2x-2=2x+10$.", "Expand both, then collect.", ["2x + 10"], 3),
    answer("y8-alg-eq-p19", "Simplify $3(2x-1)+2(x+4)$ to an equivalent expression, then verify both forms at $x=-1$ by giving their common value.", "", "8x+5, -3", "Expansion gives $6x-3+2x+8=8x+5$. At $x=-1$, both the original and simplified forms equal $-3$.", "Algebraic simplification should be checked at the same substitution in both forms.", ["8x + 5, -3"], 4),
    answer("y8-alg-eq-p20", "Expand $(2x+1)(x+3)$ to an equivalent polynomial, then evaluate it at $x=2$.", "", "2x^2+7x+3, 25", "The four products give $2x^2+6x+x+3=2x^2+7x+3$. At $x=2$, this is $8+14+3=25$.", "Include both middle products before collecting.", ["2x^2 + 7x + 3, 25"], 4),
    answer("y8-alg-eq-p21", "Simplify the difference $(x+3)^2-(x^2+9)$, then use the result to explain why the two expressions are not equivalent.", "", "6x", "Since $(x+3)^2=x^2+6x+9$, subtracting $x^2+9$ leaves $6x$. This is not identically zero, so the original expressions are equal only for particular values such as $x=0$, not for all x.", "Equivalent expressions must have a difference of zero for every x.", ["6*x", "6x; not always zero"], 4),
    answer("y8-alg-eq-p22", "Simplify $2(x+1)+3(x+2)-x$, then solve when the expression equals 20.", "", "4x+8, x = 3", "Expansion gives $2x+2+3x+6-x=4x+8$. Solving $4x+8=20$ gives $x=3$.", "Collect all x-terms before solving the resulting equation.", ["4x + 8, 3"], 4),
    answer("y8-alg-eq-p23", "A student claims $(x-3)^2$ is equivalent to $x^2-9$. Use $x=0$ as a counterexample and give the two different values.", "", "9 and -9", "At $x=0$, $(0-3)^2=9$, while $0^2-9=-9$. Since one input gives different outputs, the expressions are not equivalent. The missing middle term is the cause.", "One valid counterexample is enough to disprove equivalence.", ["9, -9", "(x-3)^2 = 9, x^2-9 = -9"], 4),
    answer("y8-alg-eq-p24", "Simplify $5(x+2)-2(2x-3)$, then solve when it equals 25.", "", "x+16, x=9", "The expression is $x+16$; $x+16=25$ gives $x=9$.", "Simplify before solving.", ["x+16,9"], 5),
    answer("y8-alg-eq-p25", "Simplify $(x+4)^2-(x-1)(x+1)$, then find its value at $x=-2$.", "", "8x+17, 1", "Quadratics cancel to $8x+17$; at $-2$ this is 1.", "Use the difference of squares, then substitute.", ["8x+17,1"], 5),
    answer("y8-alg-eq-p26", "Simplify $3(x-2)+2(x+5)-(x-1)$, then solve when it equals 25.", "", "4x+5, x=5", "It simplifies to $4x+5$; solving $4x+5=25$ gives 5.", "Collect before solving.", ["4x+5,5"], 5),
    answer("y8-alg-eq-p27", "Simplify $(2x+3)(x-1)-(x+2)(x-3)$, then evaluate at $x=1$.", "", "x^2+2x+3, 6", "It simplifies to $x^2+2x+3$; at 1 it equals 6.", "Subtract the entire second product.", ["x^2+2x+3,6"], 5),
    answer("y8-alg-eq-p28", "Simplify $4(x+1)^2-(2x+1)(2x-1)$, then solve when it equals 29.", "", "8x+5, x=3", "Quadratic terms cancel to $8x+5$; $8x+5=29$ gives $x=3$.", "Simplify fully before solving.", ["8x+5,3"], 5),
  ],
  multiPartPractice: [
    {
      id: "y8-alg-eq-mp1",
      prompt:
        "A student claims that $(x+2)^2$ is equivalent to $x^2+4$.",
      latex: "(x+2)^2 \\text{ vs } x^2+4",
      answer: "no",
      hint: "Expand the square correctly, then substitute a value to test the claim.",
      explanation:
        "Part (a): $(x+2)^2=x^2+4x+4$. Part (b): at $x=3$, $(x+2)^2=25$ but $x^2+4=13$. Part (c): they disagree, so the claim is wrong — not equivalent.",
      parts: [
        {
          key: "a",
          label: "(a)",
          prompt: "Expand $(x+2)^2$ correctly.",
          latex: "",
          marks: 2,
          answer: "x^2+4x+4",
          acceptedAnswers: ["x^2 + 4x + 4"],
          hint: "Use $a^2+2ab+b^2$ with $a=x$, $b=2$.",
          explanation: "$x^2+2(x)(2)+4=x^2+4x+4$.",
        },
        {
          key: "b",
          label: "(b)",
          prompt: "Evaluate $(x+2)^2$ when $x=3$.",
          latex: "",
          marks: 1,
          answer: "25",
          acceptedAnswers: [],
          hint: "Substitute $x=3$ into $(x+2)^2$.",
          explanation: "$(3+2)^2=5^2=25$.",
        },
        {
          key: "c",
          label: "(c)",
          prompt: "Is the student's claim correct? Answer yes or no.",
          latex: "",
          marks: 1,
          answer: "no",
          acceptedAnswers: ["No", "not equivalent"],
          hint: "Compare $25$ with $x^2+4=13$ at $x=3$.",
          explanation: "At $x=3$, $25\\neq 13$, so the expressions are not equivalent.",
        },
      ],
    },
  ],
};

// ── Lesson map and export ─────────────────────────────────────────────────────

const lessons: Record<string, Partial<ExplicitLesson>> = {
  "algebraic-fractions": algebraicFractions,
  "expanding-expressions": expandingExpressions,
  "binomial-products": binomialProducts,
  "equivalent-expressions": equivalentExpressions,
};

export function year8AlgebraicTechniquesStage5LessonOverride(
  course: CoursePathwaySeed,
  unit: CourseUnitSeed,
  lesson: CourseLessonSeed
): Partial<ExplicitLesson> | null {
  if (course.slug !== "year-8-mathematics") return null;
  if (unit.slug !== "algebraic-techniques-stage5") return null;
  return lessons[lesson.slug] ?? null;
}
