import type {
  CourseLessonSeed,
  CoursePathwaySeed,
  CourseUnitSeed,
} from "../../courseTypes";
import type {
  ExplicitLesson,
  PracticeQuestion,
  WorkedExample,
} from "../differentialCalculus";

type LessonContent = Pick<
  ExplicitLesson,
  | "moduleTitle"
  | "video"
  | "description"
  | "learningIntention"
  | "successCriteria"
  | "teaching"
  | "workedExamples"
  | "guidedPractice"
  | "independentPractice"
  | "commonMistakes"
  | "masteryQuiz"
  | "masteryQuizPool"
  | "multiPartPractice"
>;

// ── Helper builders ──────────────────────────────────────────────────────────

function answer(
  id: string,
  prompt: string,
  latex: string,
  value: string,
  explanation: string,
  hint: string,
  acceptedAnswers: string[] = [],
  difficulty?: number
): PracticeQuestion {
  return {
    id,
    prompt,
    latex,
    ...(difficulty ? { difficulty } : {}),
    answer: value,
    acceptedAnswers: Array.from(new Set([value, ...acceptedAnswers])),
    hint,
    explanation,
  };
}

function choice(
  id: string,
  prompt: string,
  value: "A" | "B" | "C" | "D",
  choices: [string, string, string, string],
  explanation: string,
  hint: string,
  difficulty?: number,
  latex = "\\text{Select A, B, C or D.}"
): PracticeQuestion {
  return {
    id,
    prompt,
    latex,
    ...(difficulty ? { difficulty } : {}),
    choices: ["A", "B", "C", "D"].map((label, i) => ({ label, text: choices[i] })),
    answer: value,
    acceptedAnswers: [],
    hint,
    explanation,
  };
}

const video = {
  title: "Indices B",
  url: "https://www.youtube.com/embed/NRSmIE5MMBQ",
};

// ── Lesson 1: Advanced Index Manipulation ────────────────────────────────────

const advancedIndexManipulation: LessonContent = {
  moduleTitle: "Indices B",
  video,
  description:
    "Simplify products and quotients of powers that involve negative indices, and apply several index laws together — multiplication, division and the zero index — in a single simplification.",
  learningIntention:
    "Apply the multiplication, division and negative index laws together to simplify products and quotients of powers.",
  successCriteria: [
    "State the multiplication law $a^m \\times a^n = a^{m+n}$ and the division law $\\frac{a^m}{a^n} = a^{m-n}$.",
    "Explain why $a^{-n} = \\frac{1}{a^n}$ using the division law.",
    "Simplify products of powers that include negative indices.",
    "Simplify quotients of powers that include negative indices.",
    "Apply two or more index laws in a single problem and write the result with a positive index.",
    "Evaluate numerical expressions such as $2^{-3} \\times 2^5$ to a whole number or simple fraction.",
  ],
  teaching: {
    paragraphs: [
      "Every index law comes from one idea: a power is just repeated multiplication. Writing $a^5 = a \\times a \\times a \\times a \\times a$, then multiplying by $a^3 = a \\times a \\times a$, gives eight factors of $a$. That is why $a^5 \\times a^3 = a^{5+3} = a^8$: you add the indices because you are counting how many factors there are altogether.",
      "Division removes factors instead of adding them. In $\\frac{a^5}{a^3}$, three of the five factors of $a$ in the top cancel with the three in the bottom, leaving $a^{5-3} = a^2$. So the division law $\\frac{a^m}{a^n} = a^{m-n}$ just records how many factors survive the cancelling.",
      "Now push the division law past the point where the top runs out. $\\frac{a^3}{a^5}$ cancels three factors top and bottom, but two factors of $a$ remain in the denominator: $\\frac{a^3}{a^5} = \\frac{1}{a^2}$. The law also says $\\frac{a^3}{a^5} = a^{3-5} = a^{-2}$. Both must be equal, so $a^{-2} = \\frac{1}{a^2}$. This is exactly why a negative index means take the reciprocal — it is forced on us by keeping the division law consistent.",
      "Because negative indices obey the very same laws, you never need special rules for them. $a^4 \\times a^{-7} = a^{4+(-7)} = a^{-3} = \\frac{1}{a^3}$: just add the indices, even when one is negative. Likewise $\\frac{a^{-2}}{a^{-6}} = a^{-2-(-6)} = a^{4}$: subtract the bottom index from the top, being careful with the double negative.",
      "When a problem combines several powers, simplify in stages. First collect the numerator using the multiplication law, then collect the denominator, then apply the division law once. For example $\\frac{a^3 \\times a^{-5}}{a^{-4}} = \\frac{a^{-2}}{a^{-4}} = a^{-2-(-4)} = a^{2}$. Working one law at a time keeps the signs under control.",
      "Finish by writing the answer in the cleanest standard form: a single power with a positive index where possible. If an index comes out negative, convert it with $a^{-n} = \\frac{1}{a^n}$ as the last step. For numerical bases, evaluate as well: $2^{-3} \\times 2^5 = 2^{2} = 4$.",
    ],
    latexBlocks: [
      "a^m \\times a^n = a^{m+n}, \\quad \\frac{a^m}{a^n} = a^{m-n}",
      "a^{-n} = \\frac{1}{a^n} \\quad (a \\neq 0)",
      "\\frac{a^3 \\times a^{-5}}{a^{-4}} = a^{3-5-(-4)} = a^{2}",
    ],
  },
  workedExamples: [
    {
      title: "Product with a negative index",
      questionLatex: "\\text{Simplify } a^6 \\times a^{-9} \\text{, giving a positive index.}",
      steps: [
        { explanation: "Use the multiplication law: add the indices.", latex: "a^6 \\times a^{-9} = a^{6+(-9)}" },
        { explanation: "Simplify the index.", latex: "a^{6-9} = a^{-3}" },
        { explanation: "Convert to a positive index.", latex: "a^{-3} = \\frac{1}{a^3}" },
      ],
      finalAnswerLatex: "\\frac{1}{a^3}",
    } as WorkedExample,
    {
      title: "Quotient with negative indices",
      questionLatex: "\\text{Simplify } \\frac{a^{-2}}{a^{-7}}.",
      steps: [
        { explanation: "Use the division law: subtract the bottom index from the top.", latex: "\\frac{a^{-2}}{a^{-7}} = a^{-2-(-7)}" },
        { explanation: "Simplify the double negative.", latex: "a^{-2+7} = a^{5}" },
      ],
      finalAnswerLatex: "a^{5}",
    } as WorkedExample,
    {
      title: "Combine several laws",
      questionLatex: "\\text{Simplify } \\frac{m^4 \\times m^{-6}}{m^{-3}}.",
      steps: [
        { explanation: "Collect the numerator using the multiplication law.", latex: "m^4 \\times m^{-6} = m^{-2}" },
        { explanation: "Apply the division law to the whole expression.", latex: "\\frac{m^{-2}}{m^{-3}} = m^{-2-(-3)}" },
        { explanation: "Simplify the index.", latex: "m^{-2+3} = m^{1} = m" },
      ],
      finalAnswerLatex: "m",
    } as WorkedExample,
    {
      title: "Evaluate a numerical expression",
      questionLatex: "\\text{Evaluate } 2^{-4} \\times 2^{7}.",
      steps: [
        { explanation: "Add the indices.", latex: "2^{-4} \\times 2^{7} = 2^{-4+7}" },
        { explanation: "Simplify and evaluate.", latex: "2^{3} = 8" },
      ],
      finalAnswerLatex: "8",
    } as WorkedExample,
  ],
  guidedPractice: [
    choice(
      "y8-iadv-g1",
      "Simplify $x^5 \\times x^{-2}$.",
      "B",
      ["$x^{-3}$", "$x^{3}$", "$x^{10}$", "$x^{-10}$"],
      "Add the indices: $5 + (-2) = 3$, so $x^5 \\times x^{-2} = x^3$.",
      "Use the multiplication law: add the exponents.",
    ),
    choice(
      "y8-iadv-g2",
      "Simplify $\\frac{a^{-3}}{a^{2}}$, giving a positive index.",
      "C",
      ["$a^{5}$", "$a^{-1}$", "$\\frac{1}{a^5}$", "$a^{6}$"],
      "Subtract the indices: $-3 - 2 = -5$, so $\\frac{a^{-3}}{a^2} = a^{-5} = \\frac{1}{a^5}$.",
      "Use the division law, then convert the negative index to a fraction.",
    ),
    choice(
      "y8-iadv-g3",
      "Simplify $\\frac{a^{-4}}{a^{-9}}$.",
      "A",
      ["$a^{5}$", "$a^{-5}$", "$a^{13}$", "$a^{-13}$"],
      "Subtract the bottom index from the top: $-4 - (-9) = -4 + 9 = 5$, so the answer is $a^5$.",
      "Be careful with the double negative when subtracting.",
    ),
    answer(
      "y8-iadv-g4",
      "Evaluate $3^{-2} \\times 3^{4}$.",
      "",
      "9",
      "Add the indices: $-2 + 4 = 2$, so $3^{-2} \\times 3^4 = 3^2 = 9$.",
      "Add the indices first, then evaluate the power.",
    ),
  ],
  independentPractice: [
    choice(
      "y8-iadv-i1",
      "Simplify $m^{-5} \\times m^{8}$.",
      "D",
      ["$m^{-13}$", "$m^{-3}$", "$m^{40}$", "$m^{3}$"],
      "Add the indices: $-5 + 8 = 3$, so $m^{-5} \\times m^8 = m^3$.",
      "Add the exponents.",
    ),
    choice(
      "y8-iadv-i2",
      "Simplify $\\frac{p^{2}}{p^{6}}$, giving a positive index.",
      "B",
      ["$p^{4}$", "$\\frac{1}{p^4}$", "$p^{-4}$", "$\\frac{1}{p^3}$"],
      "Subtract the indices: $2 - 6 = -4$, so $\\frac{p^2}{p^6} = p^{-4} = \\frac{1}{p^4}$.",
      "Use the division law, then write the negative index as a fraction.",
    ),
    choice(
      "y8-iadv-i3",
      "Simplify $\\frac{k^{-3} \\times k^{7}}{k^{2}}$.",
      "A",
      ["$k^{2}$", "$k^{-2}$", "$k^{8}$", "$k^{12}$"],
      "Numerator: $k^{-3} \\times k^7 = k^4$. Then $\\frac{k^4}{k^2} = k^{4-2} = k^2$.",
      "Collect the numerator first, then apply the division law.",
    ),
    answer(
      "y8-iadv-i4",
      "Evaluate $5^{6} \\times 5^{-4}$.",
      "",
      "25",
      "Add the indices: $6 + (-4) = 2$, so $5^6 \\times 5^{-4} = 5^2 = 25$.",
      "Add the indices, then evaluate.",
    ),
    answer(
      "y8-iadv-i5",
      "Evaluate $\\frac{2^{3}}{2^{6}}$, giving a simple fraction.",
      "",
      "1/8",
      "$\\frac{2^3}{2^6} = 2^{3-6} = 2^{-3} = \\frac{1}{2^3} = \\frac{1}{8}$.",
      "Subtract the indices, then evaluate the reciprocal power.",
      ["1/8"],
    ),
  ],
  commonMistakes: [
    {
      mistake: "Multiplying the indices when multiplying powers: $a^4 \\times a^{-7} = a^{-28}$.",
      fix: "The multiplication law adds the indices: $a^4 \\times a^{-7} = a^{4+(-7)} = a^{-3}$.",
    },
    {
      mistake: "Mishandling the double negative in division: $\\frac{a^{-2}}{a^{-6}} = a^{-2-6} = a^{-8}$.",
      fix: "Subtract the bottom index from the top: $-2 - (-6) = -2 + 6 = 4$, so $\\frac{a^{-2}}{a^{-6}} = a^{4}$.",
    },
    {
      mistake: "Leaving a negative index in the final answer when a positive index was asked for.",
      fix: "Convert as the last step using $a^{-n} = \\frac{1}{a^n}$. For example $a^{-3} = \\frac{1}{a^3}$.",
    },
    {
      mistake: "Treating $2^{-3} \\times 2^{5}$ as a negative number, e.g. writing $-4$.",
      fix: "Add indices: $2^{-3} \\times 2^5 = 2^{2} = 4$. The result is positive; the negative is only in an exponent.",
    },
  ],
  masteryQuiz: [
    choice(
      "y8-iadv-m1",
      "Simplify $x^{7} \\times x^{-3}$.",
      "A",
      ["$x^{4}$", "$x^{-4}$", "$x^{21}$", "$x^{10}$"],
      "Add the indices: $7 + (-3) = 4$, so $x^7 \\times x^{-3} = x^4$.",
      "Add the exponents.",
    ),
    choice(
      "y8-iadv-m2",
      "Simplify $\\frac{a^{4}}{a^{9}}$, giving a positive index.",
      "C",
      ["$a^{5}$", "$a^{-5}$", "$\\frac{1}{a^5}$", "$\\frac{1}{a^{13}}$"],
      "$\\frac{a^4}{a^9} = a^{4-9} = a^{-5} = \\frac{1}{a^5}$.",
      "Subtract the indices, then convert to a fraction.",
    ),
    choice(
      "y8-iadv-m3",
      "Simplify $\\frac{m^{-3}}{m^{-8}}$.",
      "B",
      ["$m^{-5}$", "$m^{5}$", "$m^{11}$", "$m^{-11}$"],
      "$-3 - (-8) = -3 + 8 = 5$, so $\\frac{m^{-3}}{m^{-8}} = m^5$.",
      "Watch the double negative.",
    ),
    answer(
      "y8-iadv-m4",
      "Evaluate $2^{-2} \\times 2^{5}$.",
      "",
      "8",
      "$-2 + 5 = 3$, so $2^{-2} \\times 2^5 = 2^3 = 8$.",
      "Add the indices, then evaluate.",
    ),
    choice(
      "y8-iadv-m5",
      "Simplify $\\frac{k^{5} \\times k^{-2}}{k^{6}}$, giving a positive index.",
      "D",
      ["$k^{3}$", "$k^{-3}$", "$k^{9}$", "$\\frac{1}{k^3}$"],
      "Numerator: $k^5 \\times k^{-2} = k^3$. Then $\\frac{k^3}{k^6} = k^{-3} = \\frac{1}{k^3}$.",
      "Collect the numerator first, then divide.",
    ),
    answer(
      "y8-iadv-m6",
      "Evaluate $\\frac{3^{2}}{3^{5}}$, giving a simple fraction.",
      "",
      "1/27",
      "$\\frac{3^2}{3^5} = 3^{2-5} = 3^{-3} = \\frac{1}{27}$.",
      "Subtract the indices, then evaluate the reciprocal power.",
      ["1/27"],
    ),
    choice(
      "y8-iadv-m7",
      "Simplify $a^{-4} \\times a^{4}$.",
      "A",
      ["$1$", "$a^{8}$", "$a^{-16}$", "$0$"],
      "$-4 + 4 = 0$, so $a^{-4} \\times a^4 = a^0 = 1$.",
      "Add the indices; remember $a^0 = 1$.",
    ),
    choice(
      "y8-iadv-m8",
      "Simplify $\\frac{y^{-6}}{y^{-2}}$, giving a positive index.",
      "C",
      ["$y^{8}$", "$y^{4}$", "$\\frac{1}{y^4}$", "$y^{-8}$"],
      "$-6 - (-2) = -6 + 2 = -4$, so $\\frac{y^{-6}}{y^{-2}} = y^{-4} = \\frac{1}{y^4}$.",
      "Subtract the bottom index from the top, then convert.",
    ),
    answer(
      "y8-iadv-m9",
      "Evaluate $4^{-1} \\times 4^{3}$.",
      "",
      "16",
      "$-1 + 3 = 2$, so $4^{-1} \\times 4^3 = 4^2 = 16$.",
      "Add the indices, then evaluate.",
    ),
    answer(
      "y8-iadv-m10",
      "Simplify $\\frac{a^{5} \\times a^{-8}}{a^{-1}}$ and write the answer as a fraction with a positive index.",
      "",
      "1/a^2",
      "Numerator: $a^5 \\times a^{-8} = a^{-3}$. Then $\\frac{a^{-3}}{a^{-1}} = a^{-3-(-1)} = a^{-2} = \\frac{1}{a^2}$.",
      "Collect the numerator first, then apply the division law and convert.",
      ["1/a^2"],
    ),
  ],
  masteryQuizPool: [
    // ── Difficulty 1: single multiplication law, positive result ─────────
    choice("y8-iadv-p1", "Simplify $x^{3} \\times x^{4}$.", "A",
      ["$x^{7}$", "$x^{12}$", "$x^{1}$", "$x^{-1}$"],
      "Add the indices: $3 + 4 = 7$.", "Add the exponents.", 1),
    choice("y8-iadv-p2", "Simplify $a^{5} \\times a^{2}$.", "B",
      ["$a^{10}$", "$a^{7}$", "$a^{3}$", "$a^{25}$"],
      "Add the indices: $5 + 2 = 7$.", "Add the exponents.", 1),
    choice("y8-iadv-p3", "Simplify $m^{6} \\times m^{-2}$.", "C",
      ["$m^{-12}$", "$m^{8}$", "$m^{4}$", "$m^{-4}$"],
      "Add the indices: $6 + (-2) = 4$.", "Add the exponents.", 1),
    answer("y8-iadv-p4", "Evaluate $2^{2} \\times 2^{3}$.", "",
      "32", "$2 + 3 = 5$, so $2^2 \\times 2^3 = 2^5 = 32$.", "Add the indices, then evaluate.",
      [], 1),
    answer("y8-iadv-p5", "Evaluate $5^{1} \\times 5^{1}$.", "",
      "25", "$1 + 1 = 2$, so $5^1 \\times 5^1 = 5^2 = 25$.", "Add the indices, then evaluate.",
      [], 1),
    // ── Difficulty 2: single division law ────────────────────────────────
    choice("y8-iadv-p6", "Simplify $\\frac{a^{8}}{a^{3}}$.", "A",
      ["$a^{5}$", "$a^{11}$", "$a^{24}$", "$a^{-5}$"],
      "Subtract the indices: $8 - 3 = 5$.", "Subtract the exponents.", 2),
    choice("y8-iadv-p7", "Simplify $\\frac{x^{7}}{x^{2}}$.", "B",
      ["$x^{9}$", "$x^{5}$", "$x^{14}$", "$x^{-5}$"],
      "Subtract the indices: $7 - 2 = 5$.", "Subtract the exponents.", 2),
    choice("y8-iadv-p8", "Simplify $\\frac{m^{2}}{m^{5}}$, giving a positive index.", "C",
      ["$m^{3}$", "$m^{-3}$", "$\\frac{1}{m^3}$", "$\\frac{1}{m^7}$"],
      "$2 - 5 = -3$, so $\\frac{m^2}{m^5} = m^{-3} = \\frac{1}{m^3}$.",
      "Subtract, then convert the negative index.", 2),
    answer("y8-iadv-p9", "Evaluate $\\frac{3^{4}}{3^{2}}$.", "",
      "9", "$4 - 2 = 2$, so $\\frac{3^4}{3^2} = 3^2 = 9$.", "Subtract the indices, then evaluate.",
      [], 2),
    answer("y8-iadv-p10", "Evaluate $\\frac{2^{3}}{2^{5}}$, giving a simple fraction.",
      "", "1/4",
      "$3 - 5 = -2$, so $\\frac{2^3}{2^5} = 2^{-2} = \\frac{1}{4}$.",
      "Subtract the indices, then evaluate the reciprocal power.", ["1/4"], 2),
    // ── Difficulty 3: negative indices in products and quotients ─────────
    choice("y8-iadv-p11", "Simplify $a^{-4} \\times a^{9}$.", "A",
      ["$a^{5}$", "$a^{-5}$", "$a^{-36}$", "$a^{13}$"],
      "$-4 + 9 = 5$, so $a^{-4} \\times a^9 = a^5$.", "Add the exponents.", 3),
    choice("y8-iadv-p12", "Simplify $\\frac{x^{-2}}{x^{-5}}$.", "B",
      ["$x^{-7}$", "$x^{3}$", "$x^{-3}$", "$x^{7}$"],
      "$-2 - (-5) = -2 + 5 = 3$.", "Watch the double negative.", 3),
    choice("y8-iadv-p13", "Simplify $\\frac{p^{-6}}{p^{-1}}$, giving a positive index.", "C",
      ["$p^{7}$", "$p^{5}$", "$\\frac{1}{p^5}$", "$p^{-7}$"],
      "$-6 - (-1) = -5$, so $\\frac{p^{-6}}{p^{-1}} = p^{-5} = \\frac{1}{p^5}$.",
      "Subtract the bottom index from the top, then convert.", 3),
    answer("y8-iadv-p14", "Evaluate $2^{-3} \\times 2^{6}$.", "",
      "8", "$-3 + 6 = 3$, so $2^{-3} \\times 2^6 = 2^3 = 8$.", "Add the indices, then evaluate.",
      [], 3),
    answer("y8-iadv-p15", "Evaluate $5^{2} \\times 5^{-1}$.", "",
      "5", "$2 + (-1) = 1$, so $5^2 \\times 5^{-1} = 5^1 = 5$.", "Add the indices, then evaluate.",
      [], 3),
    choice("y8-iadv-p16", "Simplify $a^{-3} \\times a^{3}$.", "D",
      ["$a^{9}$", "$a^{-9}$", "$a^{6}$", "$1$"],
      "$-3 + 3 = 0$, so $a^{-3} \\times a^3 = a^0 = 1$.", "Add the indices; $a^0 = 1$.", 3),
    // ── Difficulty 4: two laws combined ──────────────────────────────────
    choice("y8-iadv-p17", "Simplify $\\frac{a^{4} \\times a^{3}}{a^{2}}$, then evaluate it at $a=2$.", "A",
      ["$a^{5}$ and $32$", "$a^{9}$ and $512$", "$a^{-1}$ and $\\frac12$", "$a^{24}$ and $2^{24}$"],
      "Combining the numerator gives $a^7$, then division gives $a^{7-2}=a^5$. At $a=2$, $a^5=2^5=32$.",
      "Collect the numerator, divide by subtracting indices, then substitute.", 4),
    choice("y8-iadv-p18", "Simplify $\\frac{x^{6} \\times x^{-2}}{x^{3}}$, then evaluate it at $x=5$.", "B",
      ["$x^{5}$ and $3125$", "$x$ and $5$", "$x^{-1}$ and $\\frac15$", "$x^{11}$ and $5^{11}$"],
      "The total exponent is $6+(-2)-3=1$, so the expression is $x$. At $x=5$, its value is 5.",
      "Add numerator indices, subtract the denominator index, then substitute.", 4),
    choice("y8-iadv-p19", "Simplify $\\frac{m^{-1} \\times m^{5}}{m^{-2}}$, then evaluate it at $m=2$.", "C",
      ["$m^{2}$ and $4$", "$m^{4}$ and $16$", "$m^{6}$ and $64$", "$m^{-6}$ and $\\frac1{64}$"],
      "The exponent is $-1+5-(-2)=6$, so the expression is $m^6$. At $m=2$, its value is 64.",
      "Subtracting a negative denominator index adds it; then substitute.", 4),
    answer("y8-iadv-p20", "For $\\frac{2^{5} \\times 2^{-2}}{2^{1}}$, state the final exponent of 2 and the numerical value.",
      "", "2, 4",
      "The exponent is $5+(-2)-1=2$, so the expression is $2^2=4$.",
      "Combine all three indices before evaluating.", ["2 and 4"], 4),
    answer("y8-iadv-p21", "For $\\frac{3^{4} \\times 3^{-2}}{3^{3}}$, state the final exponent of 3 and give the value as a simple fraction.",
      "", "-1, 1/3",
      "The exponent is $4+(-2)-3=-1$, so the expression is $3^{-1}=\\frac13$.",
      "Combine the indices first; then convert the negative power to a reciprocal.", ["-1 and 1/3"], 4),
    choice("y8-iadv-p22", "Simplify $\\frac{a^{-2} \\times a^{-3}}{a^{-4}}$. Which option gives both the final exponent and the equivalent positive-index fraction?", "D",
      ["$9$ and $a^9$", "$1$ and $a$", "$-9$ and $\\frac1{a^9}$", "$-1$ and $\\frac1a$"],
      "The exponent is $-2+(-3)-(-4)=-1$, so $a^{-1}=\\frac1a$.",
      "Combine the signed indices, then rewrite a negative power as a reciprocal.", 4),
    // ── Difficulty 5: harder multi-step / multi-base ─────────────────────
    answer("y8-iadv-p23", "Simplify $\\frac{a^{6}a^{-9}}{a^{-2}}$ with a positive index, then evaluate at $a=4$.",
      "", "1/a, 1/4",
      "Numerator $a^6 \\times a^{-9} = a^{-3}$, then $\\frac{a^{-3}}{a^{-2}} = a^{-1} = \\frac{1}{a}$. At $a=4$, the value is $\\frac14$.",
      "Collect the numerator, then apply the division law and convert.", ["1/a"], 5),
    choice("y8-iadv-p24", "Simplify $\\frac{x^{-3}x^{8}}{x^{2}x^{-1}}$, then evaluate at $x=2$.", "A",
      ["$x^{4},16$", "$x^{2},4$", "$x^{6},64$", "$x^{-4},1/16$"],
      "Top $x^{-3} \\times x^8 = x^5$; bottom $x^2 \\times x^{-1} = x^1$; then $\\frac{x^5}{x^1} = x^4$. At $x=2$, the value is $2^4=16$.",
      "Collect the top and bottom separately, then divide.", 5),
    answer("y8-iadv-p25", "For $\\frac{2^{6}2^{-4}}{2^{-1}}$, state the final exponent and value.",
      "", "3, 8",
      "Numerator $2^6 \\times 2^{-4} = 2^2$, then $\\frac{2^2}{2^{-1}} = 2^{2-(-1)} = 2^3 = 8$.",
      "Collect the numerator, then subtract the negative index carefully.", [], 5),
    answer("y8-iadv-p26", "For $\\frac{10^{3}10^{-5}}{10^{-4}}$, state the final exponent and value.",
      "", "2, 100",
      "Numerator $10^3 \\times 10^{-5} = 10^{-2}$, then $\\frac{10^{-2}}{10^{-4}} = 10^{2} = 100$.",
      "Collect the numerator, then apply the division law.", [], 5),
    choice("y8-iadv-p27", "Simplify $\\frac{a^{-5}a^{2}}{a^{-6}a}$, then evaluate at $a=3$.", "B",
      ["$a,3$", "$a^{2},9$", "$a^{-2},1/9$", "$a^{4},81$"],
      "Top $a^{-5} \\times a^2 = a^{-3}$; bottom $a^{-6} \\times a^1 = a^{-5}$; then $\\frac{a^{-3}}{a^{-5}} = a^{2}$. At $a=3$, the value is $3^2=9$.",
      "Collect top and bottom separately, then divide.", 5),
    answer("y8-iadv-p28", "Simplify $\\frac{m^{4}m^{-7}m^{2}}{m^{-3}}$, then evaluate at $m=-2$.",
      "", "m^2, 4",
      "Numerator $m^4 \\times m^{-7} \\times m^2 = m^{-1}$, then $\\frac{m^{-1}}{m^{-3}} = m^{-1-(-3)} = m^{2}$. At $m=-2$, the value is $(-2)^2=4$.",
      "Add all numerator indices first, then apply the division law.", ["m^{2}"], 5),
    choice("y8-iadv-p29", "Simplify $\\frac{x^{0}x^{5}}{x^{-2}}$, then evaluate at $x=2$.", "C",
      ["$x^{3},8$", "$x^{5},32$", "$x^{7},128$", "$x^{-7},1/128$"],
      "Top $x^0 \\times x^5 = x^5$ (since $x^0 = 1$), then $\\frac{x^5}{x^{-2}} = x^{5-(-2)} = x^7$. At $x=2$, the value is $2^7=128$.",
      "Remember $x^0 = 1$, then subtract the negative index.", 5),
    answer("y8-iadv-p30", "For $\\frac{5^{-1}5^{4}}{5^{2}}$, state the final exponent and value.",
      "", "1, 5",
      "Numerator $5^{-1} \\times 5^4 = 5^3$, then $\\frac{5^3}{5^2} = 5^1 = 5$.",
      "Collect the numerator, then apply the division law.", [], 5),
  ],
  multiPartPractice: [
    {
      id: "y8-iadv-mp1",
      prompt:
        "Simplify each expression using the index laws. Give every answer with a positive index.",
      latex: "\\text{Use } a^m \\times a^n = a^{m+n} \\text{ and } \\frac{a^m}{a^n} = a^{m-n}.",
      answer: "1/a^3",
      hint: "Work one law at a time: collect numerators, then divide, then convert negative indices.",
      explanation:
        "Part (a): $a^7 \\times a^{-4} = a^{3}$. Part (b): $\\frac{a^{-2}}{a^{-6}} = a^{4}$. Part (c): $\\frac{a^2 \\times a^{-8}}{a^{-3}} = \\frac{a^{-6}}{a^{-3}} = a^{-3} = \\frac{1}{a^3}$.",
      parts: [
        {
          key: "a",
          label: "(a)",
          prompt: "Simplify $a^{7} \\times a^{-4}$.",
          latex: "",
          marks: 1,
          answer: "a^3",
          acceptedAnswers: ["a^{3}"],
          hint: "Add the indices.",
          explanation: "$7 + (-4) = 3$, so $a^{7} \\times a^{-4} = a^{3}$.",
        },
        {
          key: "b",
          label: "(b)",
          prompt: "Simplify $\\frac{a^{-2}}{a^{-6}}$.",
          latex: "",
          marks: 1,
          answer: "a^4",
          acceptedAnswers: ["a^{4}"],
          hint: "Subtract the bottom index from the top, watching the double negative.",
          explanation: "$-2 - (-6) = 4$, so $\\frac{a^{-2}}{a^{-6}} = a^4$.",
        },
        {
          key: "c",
          label: "(c)",
          prompt:
            "Simplify $\\frac{a^{2} \\times a^{-8}}{a^{-3}}$, giving a fraction with a positive index.",
          latex: "",
          marks: 2,
          answer: "1/a^3",
          acceptedAnswers: ["1/a^{3}"],
          hint: "Collect the numerator first, then apply the division law.",
          explanation:
            "Numerator $a^2 \\times a^{-8} = a^{-6}$. Then $\\frac{a^{-6}}{a^{-3}} = a^{-3} = \\frac{1}{a^3}$.",
        },
      ],
    },
  ],
};

// ── Lesson 2: Algebraic Bases ────────────────────────────────────────────────

const algebraicBases: LessonContent = {
  moduleTitle: "Indices B",
  video,
  description:
    "Simplify powers of algebraic products and quotients using $(ab)^n = a^n b^n$ and $\\left(\\frac{a}{b}\\right)^n = \\frac{a^n}{b^n}$, raise a power to a power, and combine these with negative indices.",
  learningIntention:
    "Apply the power-of-a-product, power-of-a-quotient and power-of-a-power laws to simplify algebraic expressions, including with negative indices.",
  successCriteria: [
    "Explain why $(a^m)^n = a^{mn}$ by writing the power as repeated multiplication.",
    "Apply the power-of-a-product law $(ab)^n = a^n b^n$.",
    "Apply the power-of-a-quotient law $\\left(\\frac{a}{b}\\right)^n = \\frac{a^n}{b^n}$.",
    "Simplify expressions such as $(2x^3)^4$ by raising both the coefficient and the variable to the power.",
    "Combine these laws with negative indices to write answers with positive indices.",
    "Simplify quotients of algebraic powers in a single expression.",
  ],
  teaching: {
    paragraphs: [
      "When you raise a power to another power, you are repeating the inside power. $(a^3)^2$ means $a^3 \\times a^3$, which is six factors of $a$, so $(a^3)^2 = a^6$. In general $(a^m)^n = a^{mn}$: you multiply the indices because the block of $m$ factors is repeated $n$ times. This is different from the multiplication law, where the indices are added.",
      "A bracket containing a product behaves the same way for each factor. $(ab)^3$ means $(ab)(ab)(ab)$. Because multiplication can be reordered, this equals $a \\times a \\times a \\times b \\times b \\times b = a^3 b^3$. So the power-of-a-product law is $(ab)^n = a^n b^n$ — the index attaches to every factor inside the bracket, including any number out the front.",
      "For example, $(2x)^3 = 2^3 \\times x^3 = 8x^3$. A very common slip is to forget the coefficient and write $2x^3$. The 2 is a factor inside the bracket, so it must be cubed as well. Always raise the number and the variable.",
      "A quotient inside a bracket works the same way: $\\left(\\frac{a}{b}\\right)^n = \\frac{a^n}{b^n}$, because $\\left(\\frac{a}{b}\\right)^3 = \\frac{a}{b} \\times \\frac{a}{b} \\times \\frac{a}{b} = \\frac{a^3}{b^3}$. The power lands on the top and the bottom separately. So $\\left(\\frac{x}{3}\\right)^2 = \\frac{x^2}{9}$.",
      "When a term inside the bracket already has an index, combine the laws. $(2x^3)^4 = 2^4 \\times (x^3)^4 = 16 \\times x^{12} = 16x^{12}$: cube — here, fourth-power — the coefficient, and multiply the variable's indices using the power-of-a-power law. Take each factor in turn so nothing is missed.",
      "Negative indices fit in with no new rules. $(a^{-2})^3 = a^{-6} = \\frac{1}{a^6}$, and $(2x^{-1})^2 = 2^2 x^{-2} = \\frac{4}{x^2}$. Apply the power to every factor first, multiply the indices, then convert any negative index to a fraction as the final step.",
    ],
    latexBlocks: [
      "(a^m)^n = a^{mn}",
      "(ab)^n = a^n b^n, \\quad \\left(\\frac{a}{b}\\right)^n = \\frac{a^n}{b^n}",
      "(2x^3)^4 = 2^4 (x^3)^4 = 16x^{12}",
    ],
  },
  workedExamples: [
    {
      title: "Power of a power",
      questionLatex: "\\text{Simplify } (a^{4})^{3}.",
      steps: [
        { explanation: "Multiply the indices.", latex: "(a^{4})^{3} = a^{4 \\times 3}" },
        { explanation: "Simplify.", latex: "a^{12}" },
      ],
      finalAnswerLatex: "a^{12}",
    } as WorkedExample,
    {
      title: "Power of a product with a coefficient",
      questionLatex: "\\text{Simplify } (3x^{2})^{3}.",
      steps: [
        { explanation: "Apply the power to every factor inside the bracket.", latex: "(3x^{2})^{3} = 3^{3} \\times (x^{2})^{3}" },
        { explanation: "Evaluate the coefficient and multiply the variable's indices.", latex: "27 \\times x^{6}" },
      ],
      finalAnswerLatex: "27x^{6}",
    } as WorkedExample,
    {
      title: "Power of a quotient",
      questionLatex: "\\text{Simplify } \\left(\\frac{x}{2}\\right)^{4}.",
      steps: [
        { explanation: "Raise the top and the bottom to the power separately.", latex: "\\left(\\frac{x}{2}\\right)^{4} = \\frac{x^{4}}{2^{4}}" },
        { explanation: "Evaluate the denominator.", latex: "\\frac{x^{4}}{16}" },
      ],
      finalAnswerLatex: "\\frac{x^{4}}{16}",
    } as WorkedExample,
    {
      title: "Combine with a negative index",
      questionLatex: "\\text{Simplify } (2a^{-2})^{3} \\text{, giving a fraction with a positive index.}",
      steps: [
        { explanation: "Apply the power to each factor.", latex: "(2a^{-2})^{3} = 2^{3} \\times (a^{-2})^{3}" },
        { explanation: "Evaluate and multiply the indices.", latex: "8 \\times a^{-6}" },
        { explanation: "Convert the negative index to a fraction.", latex: "8a^{-6} = \\frac{8}{a^{6}}" },
      ],
      finalAnswerLatex: "\\frac{8}{a^{6}}",
    } as WorkedExample,
  ],
  guidedPractice: [
    choice(
      "y8-ialg-g1",
      "Simplify $(a^{3})^{5}$.",
      "B",
      ["$a^{8}$", "$a^{15}$", "$a^{2}$", "$a^{35}$"],
      "Multiply the indices: $3 \\times 5 = 15$, so $(a^3)^5 = a^{15}$.",
      "Use the power-of-a-power law: multiply the exponents.",
    ),
    choice(
      "y8-ialg-g2",
      "Simplify $(2x)^{4}$.",
      "C",
      ["$2x^{4}$", "$8x^{4}$", "$16x^{4}$", "$2x^{5}$"],
      "$(2x)^4 = 2^4 x^4 = 16x^4$. The coefficient is also raised to the power.",
      "Raise both the number and the variable to the power.",
    ),
    choice(
      "y8-ialg-g3",
      "Simplify $\\left(\\frac{a}{3}\\right)^{2}$.",
      "A",
      ["$\\frac{a^{2}}{9}$", "$\\frac{a^{2}}{3}$", "$\\frac{2a}{9}$", "$\\frac{a^{2}}{6}$"],
      "$\\left(\\frac{a}{3}\\right)^2 = \\frac{a^2}{3^2} = \\frac{a^2}{9}$.",
      "Raise the top and the bottom to the power separately.",
    ),
    choice(
      "y8-ialg-g4",
      "Simplify $(3x^{2})^{2}$.",
      "D",
      ["$3x^{4}$", "$6x^{4}$", "$9x^{2}$", "$9x^{4}$"],
      "$(3x^2)^2 = 3^2 (x^2)^2 = 9x^4$.",
      "Square the coefficient and multiply the variable's index by 2.",
    ),
  ],
  independentPractice: [
    choice(
      "y8-ialg-i1",
      "Simplify $(m^{6})^{2}$.",
      "A",
      ["$m^{12}$", "$m^{8}$", "$m^{3}$", "$m^{36}$"],
      "Multiply the indices: $6 \\times 2 = 12$.",
      "Use the power-of-a-power law.",
    ),
    choice(
      "y8-ialg-i2",
      "Simplify $(4y^{3})^{2}$.",
      "C",
      ["$4y^{6}$", "$8y^{6}$", "$16y^{6}$", "$16y^{5}$"],
      "$(4y^3)^2 = 4^2 (y^3)^2 = 16y^6$.",
      "Square the coefficient and multiply the variable's index by 2.",
    ),
    choice(
      "y8-ialg-i3",
      "Simplify $\\left(\\frac{x}{5}\\right)^{3}$.",
      "B",
      ["$\\frac{x^{3}}{15}$", "$\\frac{x^{3}}{125}$", "$\\frac{3x}{125}$", "$\\frac{x^{3}}{25}$"],
      "$\\left(\\frac{x}{5}\\right)^3 = \\frac{x^3}{5^3} = \\frac{x^3}{125}$.",
      "Cube the top and the bottom separately.",
    ),
    choice(
      "y8-ialg-i4",
      "Simplify $(a^{-3})^{2}$, giving a positive index.",
      "D",
      ["$a^{-1}$", "$a^{6}$", "$a^{-6}$", "$\\frac{1}{a^6}$"],
      "$(a^{-3})^2 = a^{-6} = \\frac{1}{a^6}$.",
      "Multiply the indices, then convert the negative index.",
    ),
    answer(
      "y8-ialg-i5",
      "Simplify $(2x^{4})^{3}$.",
      "",
      "8x^12",
      "$(2x^4)^3 = 2^3 (x^4)^3 = 8x^{12}$.",
      "Cube the coefficient and multiply the variable's index by 3.",
      ["8x^{12}"],
    ),
  ],
  commonMistakes: [
    {
      mistake: "Forgetting to raise the coefficient: $(2x)^3 = 2x^3$.",
      fix: "The power applies to every factor in the bracket: $(2x)^3 = 2^3 x^3 = 8x^3$.",
    },
    {
      mistake: "Adding indices instead of multiplying for a power of a power: $(a^4)^3 = a^7$.",
      fix: "Power of a power multiplies the indices: $(a^4)^3 = a^{4 \\times 3} = a^{12}$.",
    },
    {
      mistake: "Raising only the numerator of a quotient: $\\left(\\frac{x}{3}\\right)^2 = \\frac{x^2}{3}$.",
      fix: "Both top and bottom take the power: $\\left(\\frac{x}{3}\\right)^2 = \\frac{x^2}{3^2} = \\frac{x^2}{9}$.",
    },
    {
      mistake: "Leaving a negative index after combining laws: $(a^{-2})^3 = a^{-6}$ with no conversion when a positive index is asked for.",
      fix: "Convert as the final step: $(a^{-2})^3 = a^{-6} = \\frac{1}{a^6}$.",
    },
  ],
  masteryQuiz: [
    choice(
      "y8-ialg-m1",
      "Simplify $(a^{5})^{4}$.",
      "A",
      ["$a^{20}$", "$a^{9}$", "$a^{1}$", "$a^{54}$"],
      "Multiply the indices: $5 \\times 4 = 20$.",
      "Use the power-of-a-power law.",
    ),
    choice(
      "y8-ialg-m2",
      "Simplify $(3x)^{3}$.",
      "C",
      ["$3x^{3}$", "$9x^{3}$", "$27x^{3}$", "$27x^{4}$"],
      "$(3x)^3 = 3^3 x^3 = 27x^3$.",
      "Raise both the number and the variable to the power.",
    ),
    choice(
      "y8-ialg-m3",
      "Simplify $\\left(\\frac{a}{4}\\right)^{2}$.",
      "B",
      ["$\\frac{a^{2}}{8}$", "$\\frac{a^{2}}{16}$", "$\\frac{2a}{16}$", "$\\frac{a^{2}}{4}$"],
      "$\\left(\\frac{a}{4}\\right)^2 = \\frac{a^2}{16}$.",
      "Square the top and the bottom separately.",
    ),
    choice(
      "y8-ialg-m4",
      "Simplify $(2m^{3})^{4}$.",
      "D",
      ["$2m^{12}$", "$8m^{12}$", "$16m^{7}$", "$16m^{12}$"],
      "$(2m^3)^4 = 2^4 (m^3)^4 = 16m^{12}$.",
      "Raise the coefficient to the power and multiply the variable's index.",
    ),
    choice(
      "y8-ialg-m5",
      "Simplify $(x^{-4})^{2}$, giving a positive index.",
      "A",
      ["$\\frac{1}{x^8}$", "$x^{8}$", "$x^{-2}$", "$x^{-6}$"],
      "$(x^{-4})^2 = x^{-8} = \\frac{1}{x^8}$.",
      "Multiply the indices, then convert.",
    ),
    answer(
      "y8-ialg-m6",
      "Simplify $(5x^{2})^{2}$.",
      "",
      "25x^4",
      "$(5x^2)^2 = 5^2 (x^2)^2 = 25x^4$.",
      "Square the coefficient and multiply the variable's index by 2.",
      ["25x^{4}"],
    ),
    choice(
      "y8-ialg-m7",
      "Simplify $\\left(\\frac{2}{x}\\right)^{3}$.",
      "C",
      ["$\\frac{2}{x^3}$", "$\\frac{6}{x^3}$", "$\\frac{8}{x^3}$", "$\\frac{8}{x}$"],
      "$\\left(\\frac{2}{x}\\right)^3 = \\frac{2^3}{x^3} = \\frac{8}{x^3}$.",
      "Cube the top and the bottom separately.",
    ),
    choice(
      "y8-ialg-m8",
      "Simplify $(2a^{-3})^{2}$, giving a fraction with a positive index.",
      "B",
      ["$\\frac{2}{a^6}$", "$\\frac{4}{a^6}$", "$4a^{6}$", "$\\frac{4}{a^5}$"],
      "$(2a^{-3})^2 = 2^2 (a^{-3})^2 = 4a^{-6} = \\frac{4}{a^6}$.",
      "Square the coefficient, multiply the indices, then convert.",
    ),
    answer(
      "y8-ialg-m9",
      "Simplify $(4x^{5})^{2}$.",
      "",
      "16x^10",
      "$(4x^5)^2 = 4^2 (x^5)^2 = 16x^{10}$.",
      "Square the coefficient and multiply the variable's index by 2.",
      ["16x^{10}"],
    ),
    answer(
      "y8-ialg-m10",
      "Simplify $\\left(\\frac{3}{a^{2}}\\right)^{2}$.",
      "",
      "9/a^4",
      "$\\left(\\frac{3}{a^2}\\right)^2 = \\frac{3^2}{(a^2)^2} = \\frac{9}{a^4}$.",
      "Square the top and the bottom; remember the power-of-a-power on the bottom.",
      ["9/a^{4}"],
    ),
  ],
  masteryQuizPool: [
    // ── Difficulty 1: power of a power, single variable ──────────────────
    choice("y8-ialg-p1", "Simplify $(a^{2})^{3}$.", "A",
      ["$a^{6}$", "$a^{5}$", "$a^{8}$", "$a^{23}$"],
      "Multiply the indices: $2 \\times 3 = 6$.", "Multiply the exponents.", 1),
    choice("y8-ialg-p2", "Simplify $(x^{4})^{2}$.", "B",
      ["$x^{6}$", "$x^{8}$", "$x^{2}$", "$x^{42}$"],
      "Multiply the indices: $4 \\times 2 = 8$.", "Multiply the exponents.", 1),
    choice("y8-ialg-p3", "Simplify $(m^{3})^{3}$.", "C",
      ["$m^{6}$", "$m^{27}$", "$m^{9}$", "$m^{33}$"],
      "Multiply the indices: $3 \\times 3 = 9$.", "Multiply the exponents.", 1),
    answer("y8-ialg-p4", "Simplify $(y^{5})^{2}$.", "",
      "y^10", "Multiply the indices: $5 \\times 2 = 10$.", "Multiply the exponents.",
      ["y^{10}"], 1),
    choice("y8-ialg-p5", "Simplify $(a^{1})^{6}$.", "D",
      ["$a^{1}$", "$a^{7}$", "$a^{16}$", "$a^{6}$"],
      "Multiply the indices: $1 \\times 6 = 6$.", "Multiply the exponents.", 1),
    // ── Difficulty 2: power of a product with a coefficient ──────────────
    choice("y8-ialg-p6", "Simplify $(2x)^{3}$.", "A",
      ["$8x^{3}$", "$6x^{3}$", "$2x^{3}$", "$8x$"],
      "$(2x)^3 = 2^3 x^3 = 8x^3$.", "Raise both factors to the power.", 2),
    choice("y8-ialg-p7", "Simplify $(5a)^{2}$.", "B",
      ["$10a^{2}$", "$25a^{2}$", "$5a^{2}$", "$25a$"],
      "$(5a)^2 = 5^2 a^2 = 25a^2$.", "Square both factors.", 2),
    choice("y8-ialg-p8", "Simplify $(3m)^{3}$.", "C",
      ["$9m^{3}$", "$3m^{3}$", "$27m^{3}$", "$27m$"],
      "$(3m)^3 = 3^3 m^3 = 27m^3$.", "Cube both factors.", 2),
    answer("y8-ialg-p9", "Simplify $(4x)^{2}$.", "",
      "16x^2", "$(4x)^2 = 4^2 x^2 = 16x^2$.", "Square both factors.",
      ["16x^{2}"], 2),
    choice("y8-ialg-p10", "Simplify $(10y)^{2}$.", "D",
      ["$10y^{2}$", "$20y^{2}$", "$100y$", "$100y^{2}$"],
      "$(10y)^2 = 10^2 y^2 = 100y^2$.", "Square both factors.", 2),
    // ── Difficulty 3: power of a quotient, and coefficient + index ───────
    choice("y8-ialg-p11", "Simplify $\\left(\\frac{a}{2}\\right)^{3}$.", "A",
      ["$\\frac{a^{3}}{8}$", "$\\frac{a^{3}}{6}$", "$\\frac{3a}{8}$", "$\\frac{a^{3}}{2}$"],
      "$\\left(\\frac{a}{2}\\right)^3 = \\frac{a^3}{2^3} = \\frac{a^3}{8}$.",
      "Cube the top and the bottom separately.", 3),
    choice("y8-ialg-p12", "Simplify $\\left(\\frac{x}{4}\\right)^{2}$.", "B",
      ["$\\frac{x^{2}}{8}$", "$\\frac{x^{2}}{16}$", "$\\frac{2x}{16}$", "$\\frac{x^{2}}{4}$"],
      "$\\left(\\frac{x}{4}\\right)^2 = \\frac{x^2}{16}$.",
      "Square the top and the bottom separately.", 3),
    choice("y8-ialg-p13", "Simplify $(2x^{2})^{3}$.", "C",
      ["$2x^{6}$", "$6x^{6}$", "$8x^{6}$", "$8x^{5}$"],
      "$(2x^2)^3 = 2^3 (x^2)^3 = 8x^6$.", "Cube the coefficient and multiply the index.", 3),
    answer("y8-ialg-p14", "Simplify $(3y^{2})^{2}$.", "",
      "9y^4", "$(3y^2)^2 = 3^2 (y^2)^2 = 9y^4$.",
      "Square the coefficient and multiply the index.", ["9y^{4}"], 3),
    choice("y8-ialg-p15", "Simplify $\\left(\\frac{3}{x}\\right)^{2}$.", "D",
      ["$\\frac{3}{x^2}$", "$\\frac{6}{x^2}$", "$\\frac{9}{x}$", "$\\frac{9}{x^2}$"],
      "$\\left(\\frac{3}{x}\\right)^2 = \\frac{9}{x^2}$.", "Square the top and the bottom.", 3),
    choice("y8-ialg-p16", "Simplify $(5x^{3})^{2}$.", "A",
      ["$25x^{6}$", "$10x^{6}$", "$25x^{5}$", "$5x^{6}$"],
      "$(5x^3)^2 = 5^2 (x^3)^2 = 25x^6$.", "Square the coefficient and multiply the index.", 3),
    // ── Difficulty 4: negative indices combined ──────────────────────────
    choice("y8-ialg-p17", "Simplify $(a^{-2})^{4}$ with a positive index, then evaluate at $a=2$.", "A",
      ["$\\frac{1}{a^8}$ and $\\frac1{256}$", "$a^{8}$ and $256$", "$a^{-2}$ and $\\frac14$", "$a^{-6}$ and $\\frac1{64}$"],
      "Multiplying the indices gives $a^{-8}=\\frac1{a^8}$. At $a=2$, this is $\\frac1{2^8}=\\frac1{256}$.", "Apply the power-of-a-power law, convert the negative index, then substitute.", 4),
    choice("y8-ialg-p18", "Simplify $(x^{-1})^{5}$ with a positive index, then evaluate at $x=2$.", "B",
      ["$x^{5}$ and $32$", "$\\frac{1}{x^5}$ and $\\frac1{32}$", "$x^{-4}$ and $\\frac1{16}$", "$x^{4}$ and $16$"],
      "$(x^{-1})^5=x^{-5}=\\frac1{x^5}$, which equals $\\frac1{32}$ when $x=2$.", "Multiply the indices, rewrite as a reciprocal, then substitute.", 4),
    choice("y8-ialg-p19", "Simplify $(2a^{-1})^{2}$ with a positive index, then evaluate at $a=2$.", "C",
      ["$\\frac{2}{a^2}$ and $\\frac12$", "$4a^{2}$ and $16$", "$\\frac{4}{a^2}$ and $1$", "$\\frac{4}{a}$ and $2$"],
      "Squaring both factors gives $4a^{-2}=\\frac4{a^2}$. At $a=2$, the value is $4/4=1$.",
      "Square both the coefficient and variable factor, then substitute.", 4),
    answer("y8-ialg-p20", "Simplify $(3a^{-2})^{2}$ with a positive index, then evaluate at $a=3$.",
      "", "9/a^4, 1/9",
      "$(3a^{-2})^2=9a^{-4}=\\frac9{a^4}$. At $a=3$, this is $9/81=1/9$.",
      "Square each factor, convert the negative index, then substitute.", ["9/a^{4}, 1/9"], 4),
    choice("y8-ialg-p21", "Simplify $(m^{-3})^{2}$ with a positive index, then evaluate at $m=2$.", "D",
      ["$m^{6}$ and $64$", "$m^{-1}$ and $\\frac12$", "$m^{-6}$ and $\\frac1{64}$", "$\\frac{1}{m^6}$ and $\\frac1{64}$"],
      "$(m^{-3})^2=m^{-6}=\\frac1{m^6}$, which is $\\frac1{64}$ at $m=2$.", "Multiply the indices, present a positive-index form, then substitute.", 4),
    answer("y8-ialg-p22", "Simplify $(4x^{-1})^{2}$ with a positive index, then evaluate at $x=4$.",
      "", "16/x^2, 1",
      "$(4x^{-1})^2=16x^{-2}=\\frac{16}{x^2}$. At $x=4$, the value is $16/16=1$.",
      "Square the coefficient and variable factor separately, then substitute.", ["16/x^{2}, 1"], 4),
    // ── Difficulty 5: multi-factor / quotient with indices ───────────────
    choice("y8-ialg-p23", "Simplify $\\left(\\frac{2x^{2}}{3}\\right)^{2}$, then evaluate at $x=3$.", "A",
      ["$\\frac{4x^{4}}9,36$", "$\\frac{4x^{4}}3,108$", "$\\frac{2x^{4}}9,18$", "$\\frac{4x^{2}}9,4$"],
      "$\\left(\\frac{2x^2}{3}\\right)^2 = \\frac{2^2 (x^2)^2}{3^2} = \\frac{4x^4}{9}$. At $x=3$, the value is $\\frac{4(3^4)}9=36$.",
      "Square the top (coefficient and variable) and the bottom.", 5),
    answer("y8-ialg-p24", "Simplify $\\left(\\frac{a^{3}}2\\right)^3$, then evaluate at $a=2$.",
      "", "a^9/8, 64",
      "$\\left(\\frac{a^3}{2}\\right)^3 = \\frac{(a^3)^3}{2^3} = \\frac{a^9}{8}$. At $a=2$, the value is $\\frac{2^9}{8}=64$.",
      "Cube the top using the power-of-a-power law, and cube the bottom.", ["a^{9}/8"], 5),
    choice("y8-ialg-p25", "Simplify $(2x^{3})^{2}x^{4}$, then evaluate at $x=1$.", "B",
      ["$2x^{10},2$", "$4x^{10},4$", "$4x^{24},4$", "$4x^{13},4$"],
      "$(2x^3)^2 = 4x^6$, then $4x^6 \\times x^4 = 4x^{10}$. At $x=1$, the value is $4$.",
      "Expand the bracket first, then use the multiplication law.", 5),
    answer("y8-ialg-p26", "Simplify $(3a^{2})^{2}a^{-1}$, then evaluate at $a=2$.",
      "", "9a^3, 72",
      "$(3a^2)^2 = 9a^4$, then $9a^4 \\times a^{-1} = 9a^3$. At $a=2$, the value is $9(2^3)=72$.",
      "Expand the bracket, then add the indices.", ["9a^{3}"], 5),
    answer("y8-ialg-p27", "Simplify $\\frac{(2x^{2})^{3}}{4x^{2}}$, then evaluate at $x=2$.",
      "", "2x^4, 32",
      "$(2x^2)^3 = 8x^6$, then $\\frac{8x^6}{4x^2} = 2x^4$. At $x=2$, the value is $2(2^4)=32$.",
      "Expand the bracket, then divide coefficients and subtract indices.", ["2x^{4}"], 5),
    choice("y8-ialg-p28", "Simplify $(a^{2}b^{3})^{2}$, then evaluate at $a=1,b=2$.", "C",
      ["$a^{2}b^{3},8$", "$a^{4}b^{5},32$", "$a^{4}b^{6},64$", "$a^{2}b^{6},64$"],
      "$(a^2 b^3)^2 = (a^2)^2 (b^3)^2 = a^4 b^6$. At $a=1$ and $b=2$, the value is $1^4\\times2^6=64$.",
      "Apply the power to each factor and multiply each index.", 5),
    answer("y8-ialg-p29", "Simplify $(2x^{-2})^{3}$ with a positive index, then evaluate at $x=2$.",
      "", "8/x^6, 1/8",
      "$(2x^{-2})^3 = 2^3 x^{-6} = 8x^{-6} = \\frac{8}{x^6}$. At $x=2$, the value is $\\frac{8}{2^6}=\\frac18$.",
      "Cube the coefficient, multiply the index, then convert.", ["8/x^{6}"], 5),
    choice("y8-ialg-p30", "Simplify $\\left(\\frac{x^{3}}x\\right)^2$, then evaluate at $x=3$.", "D",
      ["$x^{8},6561$", "$x^{2},9$", "$x^{6},729$", "$x^{4},81$"],
      "Inside first: $\\frac{x^3}{x} = x^2$, then $(x^2)^2 = x^4$. At $x=3$, the value is $3^4=81$.",
      "Simplify inside the bracket first, then apply the outer power.", 5),
  ],
  multiPartPractice: [
    {
      id: "y8-ialg-mp1",
      prompt:
        "Simplify each expression. Where an index is negative, write the answer as a fraction with a positive index.",
      latex: "\\text{Use } (ab)^n = a^n b^n,\\; \\left(\\tfrac{a}{b}\\right)^n = \\tfrac{a^n}{b^n},\\; (a^m)^n = a^{mn}.",
      answer: "9/x^4",
      hint: "Apply the power to every factor, multiply indices, then convert any negative index.",
      explanation:
        "Part (a): $(2x^3)^2 = 2^2 (x^3)^2 = 4x^6$. Part (b): $\\left(\\frac{a}{5}\\right)^2 = \\frac{a^2}{25}$. Part (c): $(3x^{-2})^2 = 3^2 x^{-4} = 9x^{-4} = \\frac{9}{x^4}$.",
      parts: [
        {
          key: "a",
          label: "(a)",
          prompt: "Simplify $(2x^{3})^{2}$.",
          latex: "",
          marks: 1,
          answer: "4x^6",
          acceptedAnswers: ["4x^{6}"],
          hint: "Square the coefficient and multiply the variable's index.",
          explanation: "$(2x^3)^2 = 2^2 (x^3)^2 = 4x^6$.",
        },
        {
          key: "b",
          label: "(b)",
          prompt: "Simplify $\\left(\\frac{a}{5}\\right)^{2}$.",
          latex: "",
          marks: 1,
          answer: "a^2/25",
          acceptedAnswers: ["a^{2}/25"],
          hint: "Square the top and the bottom separately.",
          explanation: "$\\left(\\frac{a}{5}\\right)^2 = \\frac{a^2}{5^2} = \\frac{a^2}{25}$.",
        },
        {
          key: "c",
          label: "(c)",
          prompt:
            "Simplify $(3x^{-2})^{2}$, giving a fraction with a positive index.",
          latex: "",
          marks: 2,
          answer: "9/x^4",
          acceptedAnswers: ["9/x^{4}"],
          hint: "Square the coefficient, multiply the index, then convert.",
          explanation:
            "$(3x^{-2})^2 = 3^2 x^{-4} = 9x^{-4} = \\frac{9}{x^4}$.",
        },
      ],
    },
  ],
};

// ── Lesson 3: Indicial Equations ─────────────────────────────────────────────

const indicialEquations: LessonContent = {
  moduleTitle: "Indices B",
  video,
  description:
    "Solve simple indicial (exponential) equations by writing both sides with the same base and equating the indices, including equations with a linear expression in the exponent, and verify solutions.",
  learningIntention:
    "Solve simple indicial equations such as $2^x = 32$ and $3^{x+1} = 27$ by equating bases, and check each solution.",
  successCriteria: [
    "Recognise an indicial equation as one where the unknown is in the exponent.",
    "Rewrite a number as a power of a chosen base, e.g. $32 = 2^5$.",
    "Equate the indices once both sides share the same base.",
    "Solve equations with a linear expression such as $x+1$ in the exponent.",
    "Verify a solution by substituting it back into the original equation.",
    "Handle equations where the unknown power equals 1 (so the index is 0).",
  ],
  teaching: {
    paragraphs: [
      "An indicial equation is one where the unknown sits up in the exponent, such as $2^x = 32$. You cannot just divide or subtract to free $x$, because $x$ is controlling how many times the base is multiplied. Instead, the key idea is that a power function like $2^x$ is one-to-one: each input gives a different output. So if two powers of the same base are equal, their indices must be equal.",
      "That gives the equate-bases method. Write both sides as a power of the same base, then set the indices equal. For $2^x = 32$, recognise $32 = 2^5$, so $2^x = 2^5$. Because the bases match, $x = 5$. The whole skill is rewriting the right-hand side as a power of the base on the left.",
      "To rewrite a number as a power, keep dividing by the base. For $32$ with base $2$: $32 \\div 2 = 16 \\div 2 = 8 \\div 2 = 4 \\div 2 = 2 \\div 2 = 1$, which is five divisions, so $32 = 2^5$. It helps to know the small powers by heart: $2^1$ to $2^6$ are $2, 4, 8, 16, 32, 64$; powers of 3 are $3, 9, 27, 81$; powers of 5 are $5, 25, 125$.",
      "When the exponent contains a linear expression, equate the whole expression to the index on the other side and solve. For $3^{x+1} = 27$, write $27 = 3^3$, so $3^{x+1} = 3^3$, giving $x + 1 = 3$, hence $x = 2$. The equate-bases step turns the indicial equation into an ordinary linear equation.",
      "Two special cases are worth remembering. Anything to the power 0 is 1, so $5^x = 1$ means $x = 0$. And a base to the power 1 is itself, so $7^x = 7$ means $x = 1$. Spotting these saves time and avoids errors.",
      "Always verify. Substitute your solution back into the original equation and check both sides match. For $x = 2$ in $3^{x+1} = 27$: $3^{2+1} = 3^3 = 27$. It checks. Verifying catches arithmetic slips and confirms you rewrote the number to the correct power.",
    ],
    latexBlocks: [
      "\\text{If } a^{m} = a^{n} \\text{ then } m = n \\quad (a > 0,\\; a \\neq 1)",
      "2^{x} = 32 = 2^{5} \\;\\Rightarrow\\; x = 5",
      "3^{x+1} = 27 = 3^{3} \\;\\Rightarrow\\; x + 1 = 3 \\;\\Rightarrow\\; x = 2",
    ],
  },
  workedExamples: [
    {
      title: "Equate bases",
      questionLatex: "\\text{Solve } 2^{x} = 64.",
      steps: [
        { explanation: "Write 64 as a power of 2.", latex: "64 = 2^{6}" },
        { explanation: "Equate the indices.", latex: "2^{x} = 2^{6} \\Rightarrow x = 6" },
        { explanation: "Check.", latex: "2^{6} = 64 \\checkmark" },
      ],
      finalAnswerLatex: "x = 6",
    } as WorkedExample,
    {
      title: "Linear expression in the exponent",
      questionLatex: "\\text{Solve } 3^{x+1} = 81.",
      steps: [
        { explanation: "Write 81 as a power of 3.", latex: "81 = 3^{4}" },
        { explanation: "Equate the indices and solve the linear equation.", latex: "x + 1 = 4 \\Rightarrow x = 3" },
        { explanation: "Check.", latex: "3^{3+1} = 3^{4} = 81 \\checkmark" },
      ],
      finalAnswerLatex: "x = 3",
    } as WorkedExample,
    {
      title: "Both sides need rewriting",
      questionLatex: "\\text{Solve } 4^{x} = 8.",
      steps: [
        { explanation: "Write both sides as powers of 2.", latex: "4^{x} = (2^{2})^{x} = 2^{2x}, \\quad 8 = 2^{3}" },
        { explanation: "Equate the indices.", latex: "2x = 3 \\Rightarrow x = \\tfrac{3}{2}" },
        { explanation: "Check.", latex: "4^{3/2} = (\\sqrt{4})^{3} = 2^{3} = 8 \\checkmark" },
      ],
      finalAnswerLatex: "x = \\tfrac{3}{2}",
    } as WorkedExample,
    {
      title: "Special case: power equals 1",
      questionLatex: "\\text{Solve } 5^{x} = 1.",
      steps: [
        { explanation: "Any non-zero base to the power 0 equals 1.", latex: "1 = 5^{0}" },
        { explanation: "Equate the indices.", latex: "5^{x} = 5^{0} \\Rightarrow x = 0" },
      ],
      finalAnswerLatex: "x = 0",
    } as WorkedExample,
  ],
  guidedPractice: [
    answer(
      "y8-ieq-g1",
      "Solve $2^{x} = 16$.",
      "",
      "4",
      "$16 = 2^4$, so $2^x = 2^4$ gives $x = 4$. Check: $2^4 = 16$.",
      "Write 16 as a power of 2, then equate the indices.",
    ),
    answer(
      "y8-ieq-g2",
      "Solve $3^{x} = 27$.",
      "",
      "3",
      "$27 = 3^3$, so $x = 3$. Check: $3^3 = 27$.",
      "Write 27 as a power of 3.",
    ),
    answer(
      "y8-ieq-g3",
      "Solve $2^{x+1} = 8$.",
      "",
      "2",
      "$8 = 2^3$, so $x + 1 = 3$, giving $x = 2$. Check: $2^{2+1} = 2^3 = 8$.",
      "Write 8 as a power of 2, then equate the exponents and solve for $x$.",
    ),
    answer(
      "y8-ieq-g4",
      "Solve $5^{x} = 1$.",
      "",
      "0",
      "$1 = 5^0$, so $x = 0$. Any non-zero base to the power 0 is 1.",
      "Recall that $a^0 = 1$.",
    ),
  ],
  independentPractice: [
    answer(
      "y8-ieq-i1",
      "Solve $2^{x} = 32$.",
      "",
      "5",
      "$32 = 2^5$, so $x = 5$. Check: $2^5 = 32$.",
      "Write 32 as a power of 2.",
    ),
    answer(
      "y8-ieq-i2",
      "Solve $3^{x+1} = 27$.",
      "",
      "2",
      "$27 = 3^3$, so $x + 1 = 3$, giving $x = 2$. Check: $3^{2+1} = 27$.",
      "Equate the indices, then solve the linear equation.",
    ),
    answer(
      "y8-ieq-i3",
      "Solve $5^{x} = 125$.",
      "",
      "3",
      "$125 = 5^3$, so $x = 3$. Check: $5^3 = 125$.",
      "Write 125 as a power of 5.",
    ),
    answer(
      "y8-ieq-i4",
      "Solve $2^{x-1} = 16$.",
      "",
      "5",
      "$16 = 2^4$, so $x - 1 = 4$, giving $x = 5$. Check: $2^{5-1} = 2^4 = 16$.",
      "Equate the indices, then solve $x - 1 = 4$.",
    ),
    answer(
      "y8-ieq-i5",
      "Solve $10^{x} = 1000$.",
      "",
      "3",
      "$1000 = 10^3$, so $x = 3$. Check: $10^3 = 1000$.",
      "Count the zeros: $1000 = 10^3$.",
    ),
  ],
  commonMistakes: [
    {
      mistake: "Trying to divide to solve $2^x = 32$, e.g. writing $x = 32 \\div 2 = 16$.",
      fix: "The unknown is an exponent, so dividing does not free it. Rewrite $32 = 2^5$ and equate indices: $x = 5$.",
    },
    {
      mistake: "Forgetting the $+1$ in the exponent: solving $3^{x+1} = 27$ by writing $x = 3$.",
      fix: "Equate the whole exponent to the index: $x + 1 = 3$, so $x = 2$. Then verify: $3^{2+1} = 27$.",
    },
    {
      mistake: "Rewriting a number to the wrong power, e.g. claiming $64 = 2^5$.",
      fix: "Count the divisions or check by multiplying: $2^5 = 32$, $2^6 = 64$. So $64 = 2^6$.",
    },
    {
      mistake: "Thinking $5^x = 1$ has no solution because 1 is not a power of 5.",
      fix: "Any non-zero base to the power 0 equals 1: $1 = 5^0$, so $x = 0$.",
    },
  ],
  masteryQuiz: [
    answer(
      "y8-ieq-m1",
      "Solve $2^{x} = 8$.",
      "",
      "3",
      "$8 = 2^3$, so $x = 3$. Check: $2^3 = 8$.",
      "Write 8 as a power of 2.",
    ),
    answer(
      "y8-ieq-m2",
      "Solve $3^{x} = 81$.",
      "",
      "4",
      "$81 = 3^4$, so $x = 4$. Check: $3^4 = 81$.",
      "Write 81 as a power of 3.",
    ),
    answer(
      "y8-ieq-m3",
      "Solve $2^{x} = 64$.",
      "",
      "6",
      "$64 = 2^6$, so $x = 6$. Check: $2^6 = 64$.",
      "Write 64 as a power of 2.",
    ),
    answer(
      "y8-ieq-m4",
      "Solve $3^{x+1} = 9$.",
      "",
      "1",
      "$9 = 3^2$, so $x + 1 = 2$, giving $x = 1$. Check: $3^{1+1} = 3^2 = 9$.",
      "Equate the indices, then solve the linear equation.",
    ),
    answer(
      "y8-ieq-m5",
      "Solve $5^{x} = 25$.",
      "",
      "2",
      "$25 = 5^2$, so $x = 2$. Check: $5^2 = 25$.",
      "Write 25 as a power of 5.",
    ),
    answer(
      "y8-ieq-m6",
      "Solve $2^{x-1} = 32$.",
      "",
      "6",
      "$32 = 2^5$, so $x - 1 = 5$, giving $x = 6$. Check: $2^{6-1} = 2^5 = 32$.",
      "Equate the indices, then solve $x - 1 = 5$.",
    ),
    choice(
      "y8-ieq-m7",
      "Which is the correct first step to solve $4^{x} = 64$ by equating bases?",
      "B",
      [
        "Divide both sides by 4 to get $x = 16$.",
        "Write $64$ as a power of $4$: $64 = 4^{3}$.",
        "Write $64 = 4 \\times 16$.",
        "Take the square root of both sides.",
      ],
      "Write 64 as a power of 4: $64 = 4^3$, so $4^x = 4^3$ and $x = 3$.",
      "Express the right-hand side as a power of the base on the left.",
    ),
    answer(
      "y8-ieq-m8",
      "Solve $7^{x} = 1$.",
      "",
      "0",
      "$1 = 7^0$, so $x = 0$. Any non-zero base to the power 0 equals 1.",
      "Recall that $a^0 = 1$.",
    ),
    answer(
      "y8-ieq-m9",
      "Solve $2^{x+3} = 16$.",
      "",
      "1",
      "$16 = 2^4$, so $x + 3 = 4$, giving $x = 1$. Check: $2^{1+3} = 2^4 = 16$.",
      "Equate the indices, then solve $x + 3 = 4$.",
    ),
    answer(
      "y8-ieq-m10",
      "Solve $10^{x} = 100000$.",
      "",
      "5",
      "$100\\,000 = 10^5$, so $x = 5$. Check: $10^5 = 100\\,000$.",
      "Count the zeros to find the power of 10.",
    ),
  ],
  masteryQuizPool: [
    // ── Difficulty 1: 2^x = small power of 2 ─────────────────────────────
    answer("y8-ieq-p1", "Solve $2^{x} = 4$.", "",
      "2", "$4 = 2^2$, so $x = 2$.", "Write 4 as a power of 2.", [], 1),
    answer("y8-ieq-p2", "Solve $2^{x} = 8$.", "",
      "3", "$8 = 2^3$, so $x = 3$.", "Write 8 as a power of 2.", [], 1),
    answer("y8-ieq-p3", "Solve $3^{x} = 9$.", "",
      "2", "$9 = 3^2$, so $x = 2$.", "Write 9 as a power of 3.", [], 1),
    answer("y8-ieq-p4", "Solve $5^{x} = 5$.", "",
      "1", "$5 = 5^1$, so $x = 1$.", "A base to the power 1 is itself.", [], 1),
    answer("y8-ieq-p5", "Solve $10^{x} = 100$.", "",
      "2", "$100 = 10^2$, so $x = 2$.", "Count the zeros.", [], 1),
    // ── Difficulty 2: larger single-base equations ───────────────────────
    answer("y8-ieq-p6", "Solve $2^{x} = 16$.", "",
      "4", "$16 = 2^4$, so $x = 4$.", "Write 16 as a power of 2.", [], 2),
    answer("y8-ieq-p7", "Solve $2^{x} = 32$.", "",
      "5", "$32 = 2^5$, so $x = 5$.", "Write 32 as a power of 2.", [], 2),
    answer("y8-ieq-p8", "Solve $3^{x} = 27$.", "",
      "3", "$27 = 3^3$, so $x = 3$.", "Write 27 as a power of 3.", [], 2),
    answer("y8-ieq-p9", "Solve $5^{x} = 125$.", "",
      "3", "$125 = 5^3$, so $x = 3$.", "Write 125 as a power of 5.", [], 2),
    answer("y8-ieq-p10", "Solve $4^{x} = 16$.", "",
      "2", "$16 = 4^2$, so $x = 2$.", "Write 16 as a power of 4.", [], 2),
    // ── Difficulty 3: equals 1, or larger powers ─────────────────────────
    answer("y8-ieq-p11", "Solve $2^{x} = 64$.", "",
      "6", "$64 = 2^6$, so $x = 6$.", "Write 64 as a power of 2.", [], 3),
    answer("y8-ieq-p12", "Solve $3^{x} = 81$.", "",
      "4", "$81 = 3^4$, so $x = 4$.", "Write 81 as a power of 3.", [], 3),
    answer("y8-ieq-p13", "Solve $6^{x} = 1$.", "",
      "0", "$1 = 6^0$, so $x = 0$.", "Any non-zero base to the power 0 is 1.", [], 3),
    answer("y8-ieq-p14", "Solve $10^{x} = 10000$.", "",
      "4", "$10\\,000 = 10^4$, so $x = 4$.", "Count the zeros.", [], 3),
    answer("y8-ieq-p15", "Solve $2^{x} = 128$.", "",
      "7", "$128 = 2^7$, so $x = 7$.", "Keep doubling: $64 \\times 2 = 128 = 2^7$.", [], 3),
    answer("y8-ieq-p16", "Solve $9^{x} = 1$.", "",
      "0", "$1 = 9^0$, so $x = 0$.", "Recall $a^0 = 1$.", [], 3),
    // ── Difficulty 4: linear expression in the exponent ──────────────────
    answer("y8-ieq-p17", "Solve $2^{x+1}=8$, then verify by giving the value of the left side at your solution.", "",
      "2, 8", "$8=2^3$, so $x+1=3$ and $x=2$. Substitution gives $2^{2+1}=2^3=8$.", "Rewrite 8 as a power of 2, solve the linear equation, then substitute.", ["x=2, 8"], 4),
    answer("y8-ieq-p18", "Solve $3^{x+1}=27$, then verify by giving the value of the left side at your solution.", "",
      "2, 27", "$27=3^3$, so $x+1=3$ and $x=2$. Checking gives $3^{2+1}=27$.", "Match powers of 3, solve, then substitute.", ["x=2, 27"], 4),
    answer("y8-ieq-p19", "Solve $2^{x-1}=16$, then verify by giving the value of the left side at your solution.", "",
      "5, 16", "$16=2^4$, so $x-1=4$ and $x=5$. Checking gives $2^{5-1}=16$.", "Rewrite 16 as a power of 2, solve, then check.", ["x=5, 16"], 4),
    answer("y8-ieq-p20", "Solve $5^{x-1}=25$, then verify by giving the value of the left side at your solution.", "",
      "3, 25", "$25=5^2$, so $x-1=2$ and $x=3$. Checking gives $5^{3-1}=25$.", "Match powers of 5, solve the exponent equation, then check.", ["x=3, 25"], 4),
    answer("y8-ieq-p21", "Solve $3^{x+2}=81$, then verify by giving the value of the left side at your solution.", "",
      "2, 81", "$81=3^4$, so $x+2=4$ and $x=2$. Checking gives $3^{2+2}=81$.", "Rewrite 81 as a power of 3, solve, then check.", ["x=2, 81"], 4),
    answer("y8-ieq-p22", "Solve $2^{x+3}=32$, then verify by giving the value of the left side at your solution.", "",
      "2, 32", "$32=2^5$, so $x+3=5$ and $x=2$. Checking gives $2^{2+3}=32$.", "Rewrite 32 as a power of 2, solve, then check.", ["x=2, 32"], 4),
    // ── Difficulty 5: rewrite both sides / coefficient in exponent ───────
    answer("y8-ieq-p23", "Solve $4^{x}=64$ and verify the left side.", "",
      "x=3, 64", "$64=4^3$, so $x=3$; checking, $4^3=64$.",
      "Write 64 as a power of 4.", [], 5),
    answer("y8-ieq-p24", "Solve $9^{x}=27$ and verify using base 3.", "",
      "x=3/2; 3^3=27", "Writing $3^{2x}=3^3$ gives $x=3/2$; then $9^{3/2}=3^3=27$.",
      "Rewrite both sides with base 3.", ["1.5"], 5),
    answer("y8-ieq-p25", "Solve $4^{x}=8$ and verify using base 2.", "",
      "x=3/2; 2^3=8", "Base 2 gives $2^{2x}=2^3$, so $x=3/2$; substitution gives $2^3=8$.",
      "Rewrite both sides with base 2.", ["1.5"], 5),
    answer("y8-ieq-p26", "Solve $2^{2x}=16$ and verify the exponent and value.", "",
      "x=2; exponent 4, value 16", "$16=2^4$, so $2x=4$ and $x=2$; the exponent is 4 and value 16.", "Equate indices, solve, then substitute.", [], 5),
    answer("y8-ieq-p27", "Solve $3^{2x}=81$ and verify the exponent and value.", "",
      "x=2; exponent 4, value 81", "$81=3^4$, so $x=2$; substitution gives exponent 4 and value 81.", "Equate indices and check.", [], 5),
    answer("y8-ieq-p28", "Solve $8^{x}=32$ and verify using base 2.", "",
      "x=5/3; 2^5=32", "Base 2 gives $2^{3x}=2^5$, so $x=5/3$; substitution gives $2^5=32$.",
      "Rewrite both sides with base 2.", [], 5),
    answer("y8-ieq-p29", "Solve $2^{2x+1}=32$ and verify the exponent and value.", "",
      "x=2; exponent 5, value 32", "$32=2^5$, so $2x+1=5$ and $x=2$; checking gives exponent 5 and value 32.", "Solve the exponent equation, then check.", [], 5),
    answer("y8-ieq-p30", "Solve $25^{x}=125$ and verify using base 5.", "",
      "x=3/2; 5^3=125", "Base 5 gives $5^{2x}=5^3$, so $x=3/2$; substitution gives $5^3=125$.",
      "Rewrite both sides with base 5.", ["1.5"], 5),
  ],
  multiPartPractice: [
    {
      id: "y8-ieq-mp1",
      prompt:
        "Solve each indicial equation by equating bases. Verify each solution by substituting it back.",
      latex: "\\text{If } a^{m} = a^{n} \\text{ then } m = n.",
      answer: "2",
      hint: "Rewrite the right-hand side as a power of the base on the left, then equate the indices.",
      explanation:
        "Part (a): $32 = 2^5$, so $x = 5$. Part (b): $1 = 3^0$, so $x = 0$. Part (c): $81 = 3^4$, so $x + 2 = 4$, giving $x = 2$; check $3^{2+2} = 3^4 = 81$.",
      parts: [
        {
          key: "a",
          label: "(a)",
          prompt: "Solve $2^{x} = 32$.",
          latex: "",
          marks: 1,
          answer: "5",
          acceptedAnswers: [],
          hint: "Write 32 as a power of 2.",
          explanation: "$32 = 2^5$, so $x = 5$.",
        },
        {
          key: "b",
          label: "(b)",
          prompt: "Solve $3^{x} = 1$.",
          latex: "",
          marks: 1,
          answer: "0",
          acceptedAnswers: [],
          hint: "Any non-zero base to the power 0 equals 1.",
          explanation: "$1 = 3^0$, so $x = 0$.",
        },
        {
          key: "c",
          label: "(c)",
          prompt: "Solve $3^{x+2} = 81$ and verify your answer.",
          latex: "",
          marks: 2,
          answer: "2",
          acceptedAnswers: [],
          hint: "Write 81 as a power of 3, then solve the linear equation.",
          explanation:
            "$81 = 3^4$, so $x + 2 = 4$, giving $x = 2$. Check: $3^{2+2} = 3^4 = 81$.",
        },
      ],
    },
  ],
};

// ── Lesson map and export ─────────────────────────────────────────────────────

const lessons: Record<string, LessonContent> = {
  "advanced-index-manipulation": advancedIndexManipulation,
  "algebraic-bases":             algebraicBases,
  "indicial-equations":          indicialEquations,
};

export function year8IndicesBLessonOverride(
  course: CoursePathwaySeed,
  unit: CourseUnitSeed,
  lesson: CourseLessonSeed
): Partial<ExplicitLesson> | null {
  if (course.slug !== "year-8-mathematics") return null;
  if (unit.slug !== "indices-b") return null;
  const content = lessons[lesson.slug];
  if (!content) return null;
  return {
    syllabusArea: "Number and Algebra",
    masteryPassMark: 0.8,
    ...content,
  };
}
